### ISSUE TITLE
Fix deployment of participation dashoard

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1002]

**Comment by pmbinapps** [comment]
https://participation.dev-sanchonet.govtool.byron.network/
https://participation.test-sanchonet.govtool.byron.network/

**Comment by pmbinapps** [comment]
OK:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/ad760154-ec92-4d75-a5dd-ca50cc920103)
