### ISSUE TITLE
Dashboard - After Retire as DRep and Direct Voter - delegation cards suggest that Voting power is delegated to Active DRep

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1010]
Occurred on dev-sancho:

To reproduce:
1. Become DRep
2. Delegate to Yourself
3. Become Direct Voter
4. Retire as Direct Voter
5. Go to Dashboard - Delegation card show that Voting power is delegated to Drep_name - suggesting that there is Valid Active delegation - (it is you in fact - but you are Retired)

Dashboard:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b8481cc3-c74d-4311-ac04-af7c7f7ff669)

This what is shown in DRep explorer:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/93a33e87-6b8d-4c78-aed0-c83e7609c2b8)

Looks like the text or an chip is needed is needed to present this state and the list on Drep explorer delegation should be shown accordingly.

**Comment by pmbinapps** [comment]
@m-i-k-e please take a look on this issue. It could that more descriptive info could be shown there.

**Comment by pmbinapps** [comment]
@bosko-m this issue is related to https://github.com/IntersectMBO/govtool/issues/1026 - which and could be solved together.

**Comment by m-i-k-e** [comment]
@m-i-k-e add Figma screen here

**Comment by pmbinapps** [comment]
Still the same:
![image](https://github.com/IntersectMBO/govtool/assets/82152577/06ad21a7-c4ae-4a62-a70c-50d2a2f5643d)

To solve this issue and improve distinction between Direct Voter and DRep - this issue should be implemented for DRep explorer: https://github.com/IntersectMBO/govtool/issues/1162  and Dashboard should present state like in comment above: https://github.com/intersectMBO/govtool/issues/1010#issuecomment-2139305134

**Comment by pmbinapps** [comment]
OK NOW:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/310c41c1-7c14-47e2-8782-a5bc3b67ccc5)
