### ISSUE TITLE
DRep registration - Registration hang up after providing json file and confirming

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1011]
Registration as Drep fails:

To reproduce:
1. Provide meta data as below:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/97de5be1-2874-44ec-8285-a310ecc12954)

2. Confirm
3. Pass

Metadata link: https://raw.githubusercontent.com/mpawel79/testrepo/master/test.jsonld

4. Proceed - bank screen appears. Compare with:

Jam recording [here](https://jam.dev/c/bd82a61e-9a2f-4c52-9bb5-80e0aba1663b)

**Comment by m-i-k-e** [comment]
This fails with a different error: "Metadata not verified"

https://www.loom.com/share/2a1d643df66b4a1ea315463a18967fc4?sid=aab95f83-c608-4dd8-ba6e-17bedc2ee401

**Comment by m-i-k-e** [comment]
"Blocked" as cannot be tested.

**Comment by m-i-k-e** [comment]
[misterDrep_1000.jsonld.zip](https://github.com/user-attachments/files/15788055/misterDrep_1000.jsonld.zip)
This is the json file for this issue. Zipped because github doesn't like json.

**Comment by MSzalowski** [comment]
Fixed by #1247

**Comment by pmbinapps** [comment]
OK NOW - use of URL without protocol, eg. 'test.com' works fine now. Jam [Recording](https://jam.dev/c/fed66068-69c5-4416-b329-40e74213c105)

**Comment by m-i-k-e** [comment]
Working now. Closing
