### ISSUE TITLE
No DReps found card with extra one result

### ISSUE THREAD

**Issue by vercia** [IntersectMBO/govtool#1019]
## Context & versions
dev

## Steps to reproduce
  1. Go to DRep Directory page when wallet is disconnected
  2. Enter something to input to show no results 

## Actual behavior
The empty card has shown and one result under this.
<img width="1791" alt="Zrzut ekranu 2024-05-14 o 10 25 11" src="https://github.com/IntersectMBO/govtool/assets/18899699/4039f088-360b-421a-91f4-2f77aea6afa0">

## Expected behavior
It should show only empty card if there are no results.

**Comment by pmbinapps** [comment]
Also results are doubled when existing drepid is given:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/e6c9d254-08e0-4143-97c6-ddbd6b08dfb0)
