### ISSUE TITLE
GA - details - no metadata or error info is shown on details view after adding proposal

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1027]
To reproduce:

1. Go to dashboard
2. Add Info Proposal (use inputs like on screenshots below)
3. Confirm (use json [link](https://raw.githubusercontent.com/mpawel79/testrepo/master/Info.jsonld))
4. Wait until transaction is completed
5. Go to GA list
6. Find newly added Proposal - enter to details page compare with screenshots:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/25b071ee-9069-4bf8-9f66-a368adb660c4)

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/e479ff7b-5637-4f7f-beb9-41015f82b17c)

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/0f11e563-19ab-47a2-a399-c64b9bfcf1f3)

**Comment by MSzalowski** [comment]
Seems like it might be the db-sync issue not getting the metadata info. @jankun4 Could you have a look?

**Comment by MSzalowski** [comment]
Answering my previous comment - this data is indeed missing on the db-sync side. However, the validation against the metadata under the url and the hash provided succeeds - that is why we are displaying the metadata.

I wonder whether we should make the 2 step validation:
One - against the metadata and the URL provided to the proposal.
Second one - against the metadata provided directly from the proposal.

**Comment by bosko-m** [comment]
@MSzalowski Does this still count as P0 given your recent comment?

**Comment by MSzalowski** [comment]
We still can vote on the governance action. However, we don't know what the governance action is about. It is something between P0 and P1

**Comment by m-i-k-e** [comment]
P0 to me.

**Comment by bosko-m** [comment]
CC @Ryun1 
This should be a dbsync bug, so we will retest this after the respin is complete.

**Comment by Ryun1** [comment]
@bosko-m 
Probably best to raise this as an issue via the [DB-Sync repository](https://github.com/IntersectMBO/cardano-db-sync), or ask via the working group on discord

**Comment by MSzalowski** [comment]
Raised issue: https://github.com/IntersectMBO/cardano-db-sync/issues/1716

**Comment by bosko-m** [comment]
@MSzalowski While testing this on dev (because staging is not yet up and running fully), we have realized that once you create an Info GA, you cant find it on the list of all GAs. The thing that make it worse is that there arent titles showing on the ones recently created. This needs to be solved before the release as its a show stopper. Lets discuss on Monday.

**Comment by bosko-m** [comment]
@MSzalowski @m-i-k-e Went through it with @Ryun1 , all seems to be working as they appeared after some period of time which is great, but still missing metadata.

**Comment by bosko-m** [comment]
Known issue going to the Beta releaser on 6th June, however, will be fixed in the next few days.
CC @m-i-k-e @Ryun1 @l-br1

**Comment by pmbinapps** [comment]
OK when validating, showing metadata and info about missing, corrupted
https://jam.dev/c/1d4e44fd-6104-41ce-a18b-bd79c0293918
https://raw.githubusercontent.com/pmbinapps/vva/main/tmp/Info.jsonld



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/d9b4e131-d13d-422d-a736-0def465f4843)



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/a2eb820e-2e42-4fd3-ba45-afa3ff3f97b4)

**Comment by m-i-k-e** [comment]
JSONLD file contents:

{
  "@context": {
    "@language": "en-us",
    "CIP100": "https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/README.md#",
    "CIP108": "https://github.com/cardano-foundation/CIPs/blob/master/CIP-0108/README.md#",
    "hashAlgorithm": "CIP100:hashAlgorithm",
    "body": {
      "@id": "CIP108:body",
      "@context": {
        "references": {
          "@id": "CIP108:references",
          "@container": "@set",
          "@context": {
            "GovernanceMetadata": "CIP100:GovernanceMetadataReference",
            "Other": "CIP100:OtherReference",
            "label": "CIP100:reference-label",
            "uri": "CIP100:reference-uri",
            "referenceHash": {
              "@id": "CIP108:referenceHash",
              "@context": {
                "hashDigest": "CIP108:hashDigest",
                "hashAlgorithm": "CIP100:hashAlgorithm"
              }
            }
          }
        },
        "title": "CIP108:title",
        "abstract": "CIP108:abstract",
        "motivation": "CIP108:motivation",
        "rationale": "CIP108:rationale"
      }
    },
    "authors": {
      "@id": "CIP100:authors",
      "@container": "@set",
      "@context": {
        "name": "http://xmlns.com/foaf/0.1/name",
        "witness": {
          "@id": "CIP100:witness",
          "@context": {
            "witnessAlgorithm": "CIP100:witnessAlgorithm",
            "publicKey": "CIP100:publicKey",
            "signature": "CIP100:signature"
          }
        }
      }
    }
  },
  "authors": [],
  "hashAlgorithm": {
    "@value": "blake2b-256"
  },
  "body": {
    "abstract": {
      "@value": "test"
    },
    "motivation": {
      "@value": "test"
    },
    "rationale": {
      "@value": "test"
    },
    "references": [
      {
        "@type": "Other",
        "label": {
          "@value": "Label"
        },
        "uri": {
          "@value": "https://test.com"
        }
      }
    ],
    "title": {
      "@value": "test"
    }
  }
}

**Comment by Ryun1** [comment]
Working on staging with Info action and your metadata @m-i-k-e 

![image](https://github.com/IntersectMBO/govtool/assets/44342099/e4d4acdf-528c-4e80-8e72-cbc3206d9156)

**Comment by Ryun1** [comment]
Working on staging with demos, and a treasury action with @m-i-k-e's metadata
![image](https://github.com/IntersectMBO/govtool/assets/44342099/c40ca775-3380-489c-b8e6-4be0db22ab07)

**Comment by Ryun1** [comment]
and the GAs can be seen via GA explorer
https://staging.govtool.byron.network/connected/governance_actions/28cbfca8afc31df1996ffab4bec23c960121b2a57d30bb5a88ee8265eb5f3a3f#0

**Comment by m-i-k-e** [comment]
Thanks @Ryun1 looks good.

**Comment by m-i-k-e** [comment]
This works for me now. Closing
