### ISSUE TITLE
DRep directory - incorrectly appended filter "Yourself" to DRep directory

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1028]
## Context & versions

1. dev-env
2. Found on tes-env

## Steps to reproduce
1. Go to DRep Directory
2. Click filter

## Actual behavior

Filter `yourself` is visible.
## Expected behavior

There should not be such filter like `yourself`

**Comment by pmbinapps** [comment]
OK NOW:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/28cb9643-353c-4ffb-bcb3-13f4f5de5ba4)
