### ISSUE TITLE
Fix test environment deployment

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#1037]
Test environment is failing:

```
"metadatavalidationhost": "metadata-validation",
    "metadatavalidationport": 3000
```
These new config options are added to backend.

**Comment by spannercode** [comment]
The test environment is manually resolved. The fix is already merged to develop but has not been promoted to test environment yet.

PR here: https://github.com/IntersectMBO/govtool/pull/1041

**Comment by Ryun1** [comment]
This ready to be closed out @spannercode ?
