### ISSUE TITLE
[BUG] Some test IDs still missing

### ISSUE THREAD

**Issue by SandraRodziewicz** [IntersectMBO/govtool#1038]
##Delegation Page:

- signal-no-confidence-card.
- abstain-delegation-card.

##Dashboard:

- Inside the dRep-card, the dRep-id-display-card test ID is conflicting with the sidebar's dRep-id-display-card. Suggest creating distinct test IDs, such as dRep-id-display-card-dashboard for the dashboard.

**Comment by pmbinapps** [comment]
##Delegation Page:

data-testid: abstain-delegation-card
data-testid: abstain-from-every-vote-info-button
data-testid: abstain-from-every-vote-delegate-button

data-testid: signal-no-confidence-on-every-vote-info-button
data-testid: signal-no-confidence-on-every-vote-delegate-button


# Dashboard

Elements _"Inside the dRep-card, the dRep-id-display-card test ID is conflicting with the sidebar's dRep-id-display-card. Suggest creating distinct test IDs, such as dRep-id-display-card-dashboard for the dashboard."_ not occurring anymore. 


Instead are used:


Element: A
 data-testid: logo-button
  ---
  Element: A
 data-testid: dashboard-link
  ---
  Element: A
  data-testid: drep-directory-link
  ---
  Element: A
  data-testid: governance-actions-link
  ---
  Element: A
  data-testid: guides-link
  ---
  Element: A
  data-testid: faqs-link
  ---
  Element: BUTTON
  data-testid: disconnect-button
  ---
  Element: P
  data-testid: voting-power-delegation-status
  ---
  Element: svg
  data-testid: ArrowForwardIosIcon
  ---
  Element: BUTTON
  data-testid: delegate-learn-more-button
  ---
  Element: BUTTON
  data-testid: delegate-to-another-drep-button
  ---
  Element: P
  data-testid: voting-power-delegation-status
  ---
  Element: BUTTON
  data-testid: register-button
  ---
  Element: BUTTON
  data-testid: register-learn-more-button
  ---
  Element: P
  data-testid: voting-power-delegation-status
  ---
  Element: BUTTON
  data-testid: register-as-sole-voter-button
  ---
  Element: BUTTON
  data-testid: learn-more-button
  ---
  Element: P
  data-testid: voting-power-delegation-status
  ---
  Element: BUTTON
  data-testid: view-governance-actions-button
  ---
  Element: BUTTON
  data-testid: learn-more-governance-actions-button
  ---
  Element: P
  data-testid: voting-power-delegation-status
  ---
  Element: BUTTON
  data-testid: propose-governance-actions-button

**Comment by pmbinapps** [comment]
@NabinKawan take a look if those will work for you.

**Comment by NabinKawan** [comment]
Hi @pmbinapps, Could you mention the PR in which it has been implemented so that I can verify it.
