### ISSUE TITLE
[BUG] Missing Test IDs  (Drep Directory)

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1050]
## Description:
- This ticket is a subtask of parent ticket  #937.
#### Delegation Page: (Mention on #1038  )

- signal-no-confidence-card.
- abstain-delegation-card. 

#### DRep registration

- **Incorrect Test ID Path on DRep Form:** The test IDs for email-input and link-input are incorrectly placed. The data-testid should be inside the input tag.
``` 
<div data-testid="email-input" class="MuiInputBase-root MuiInputBase-colorPrimary css-1di96g7">
  <input id=":r16:" name="email" placeholder="john.smith@email.com" type="text" class="MuiInputBase-input css-mevgbx" value="" data-dashlane-rid="92c37e5aa4443fee" data-kwimpalastatus="alive" data-kwimpalaid="1715918960562-0" data-form-type="email">
</div>
```
The data-testid should be moved to the input tag for proper identification and testing.

- Missing test ID for metadata URL (should be testId = metadata-url)

![image](https://github.com/sireto/govtool/assets/49801844/e864e1b1-3297-424f-b707-a2b2514e2b3b)

- missing test-id on metadata-download-button

![image](https://github.com/IntersectMBO/govtool/assets/49801844/5d287588-3ee8-49aa-8c73-192fb1bb9230)

- Missing test Id on DRep Card
    - DRep card -> test id = drep1qzw234c0ly8csamxf8hrhfahvzwpllh2ckuzzvl38d22wwxxquu-drep-card
    - voting power -> test id  = voting-power
    - status -> test id = status
    - Delegated DRep card -> test id = drep14px384j0j20psnezaf95yppvsqh9hnu73yxpv87yugzujn97t9y-delegated-card 
    
    
      ![image](https://github.com/IntersectMBO/govtool/assets/49801844/c0c4044e-a56b-489e-bbd8-6eef42a21aaf)

- Missing voting power test id on drep details 

    ![image](https://github.com/IntersectMBO/govtool/assets/49801844/4563a67a-15bc-4dee-bb6d-a4945b00e0ef)
- Missing test IDs on edit DRep info 
   - add-link-button for the "Add Link" button.
   - name-input for the name input field.
   - email-input for the email input field.
   - bio-input for the bio input field.
   - link-input for the link input field.
   
![image](https://github.com/IntersectMBO/govtool/assets/49801844/de39d250-11e8-4c17-9581-c6d81842718f)

- missing voting power test id on dashboard

   ![image](https://github.com/IntersectMBO/govtool/assets/49801844/1ff4d6e2-5ba1-4004-a908-26b1cad36d23)

**Important:** Please ensure to add proper test IDs for all interactive elements to facilitate testing and automation.

**Comment by pmbinapps** [comment]
OK - found id:

Delegation Page: (Mention on https://github.com/IntersectMBO/govtool/issues/1038 )

signal-no-confidence-card.
abstain-delegation-card.

FOUND 
Element: DIV
data-testid: no-confidence-delegation-card

Element: DIV
 data-testid: abstain-delegation-card

**Comment by pmbinapps** [comment]
OK for - Missing test Id on DRep Card

DRep card -> test id = drep1qzw234c0ly8csamxf8hrhfahvzwpllh2ckuzzvl38d22wwxxquu-drep-card

data-testid: drep1pzuxy8ukuvffjyyrdp8sxkzp3z8r57z5q0jtgxhwu3a22t9ppel-drep-card
jam-console-devtools.js:1 

- voting power -> test id = voting-power:

Element: P
data-testid: drep1qzts73jthmvqjee2m0x7jqm8snn0ycqxcduf9xqec2n3x3u6ge9-voting-power-label

 Element: P
data-testid: drep1qzts73jthmvqjee2m0x7jqm8snn0ycqxcduf9xqec2n3x3u6ge9-voting-power


status -> test id = status

data-testid: drep1qzts73jthmvqjee2m0x7jqm8snn0ycqxcduf9xqec2n3x3u6ge9-st

Delegated DRep card -> test id = drep14px384j0j20psnezaf95yppvsqh9hnu73yxpv87yugzujn97t9y-delegated-card

Element: DIV
data-testid: drep1qzts73jthmvqjee2m0x7jqm8snn0ycqxcduf9xqec2n3x3u6ge9-delegated-card

**Comment by pmbinapps** [comment]
OK NOW for Missing voting power test id on drep details

Element: P
data-testid: voting-power

OK - found :
Missing test IDs on edit DRep info

add-link-button for the "Add Link" button.
Element: BUTTON
jam-console-devtools.js:1 data-testid: add-link-button

name-input for the name input field.
Element: INPUT
 data-testid: drep-name-input

email-input for the email input field.
Element: INPUT
 data-testid: email-input

bio-input for the bio input field.
Element: TEXTAREA
 data-testid: bio-input

link-input for the link input field.
Element: INPUT

**Comment by pmbinapps** [comment]
@kneerose found all mentioned test id - take look and let us know how they work

**Comment by kneerose** [comment]
Hi @pmbinapps ,

It seems like you've made changes to the test IDs for other components:
- name-input is now drep-name-input
- link-input is now link-number-input (with a number that increases when adding links)

While I appreciate the improvements, could you please avoid changing previously assigned test IDs? Our tests are failing because of these modifications.

Thanks for your clarification!

**Comment by pmbinapps** [comment]
@NabinKawan I guess there could be so duplicate, thus that change.
@Sworzen1 please correct if I'm wrong.

**Comment by kneerose** [comment]
Hey @Sworzen1 
- It looks like you've changed the code, replacing drep-name-input with name-input. However, this change also removes the bio-input testid, which causes the test to fail. 
- For reference, your [PR](https://github.com/IntersectMBO/govtool/pull/1105/commits/3ecb8a977cf535c7e9673aff9d5c0aa78aeb4cbd)

![image](https://github.com/IntersectMBO/govtool/assets/49801844/c359b7e1-1865-400d-95ce-62d1e28be71e)

**Comment by pmbinapps** [comment]
OK NOW on dev-sancho with bio-input



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/50dbade8-4611-48d8-baf8-d43ec7a91110)

**Comment by NabinKawan** [comment]
Hi @pmbinapps, Can we close this related issue after merging it into the test branch? We still cannot verify it.

**Comment by kneerose** [comment]
Hello @pmbinapps ,

Some components still have missing test IDs. I have listed all the missing and incorrect test IDs below. Please confirm and update them accordingly.

1. Edit dRep Info Information Storage Steps
      - Currently the submit button has testID `continue-button` which is not correct
      -  I have mentioned the test IDs in the image below
   

![Screenshot from 2024-06-20 13-04-12](https://github.com/IntersectMBO/govtool/assets/49801844/7371502f-3b61-4b9d-a81a-b69356efcd3a)

2. Missing test IDs on inProgress chip 
     - Please add test IDs to all "In Progress" chips that will display while the transaction is in progress.

![Screenshot from 2024-06-20 13-05-40](https://github.com/IntersectMBO/govtool/assets/49801844/930bda65-42b9-437d-9462-a7cddaafa3ed)

3. Learn More Button
     -   Make the test ID for the "Learn More" button unique.
     -   Please ensure it on the connected and disconnected state

![Screenshot from 2024-06-20 13-07-40](https://github.com/IntersectMBO/govtool/assets/49801844/f97a1550-c711-4160-ae44-a6a3ee77f324)

4. Governance Action Provide Context Update
    - Some test IDs are missing or incorrect. Please review and update them.
    - Here instead of `metadata-url-input`  `undefinedinput` is taking

![Screenshot from 2024-06-20 12-55-35](https://github.com/IntersectMBO/govtool/assets/49801844/9f4e9d37-2d60-41f0-baf3-e73d6d14d655)

Thank you for your attention to these details.

**Comment by kneerose** [comment]
@MSzalowski  any update on this ?

**Comment by kneerose** [comment]
The missing test IDs are crucial as they can make some tests flaky, especially the metadata button test for editDRep. Currently, we are locating the button by testId using `page.getByRole("button", { name: `${newDRepName}.jsonld` }).click();`. If `newDRepName` has more characters than expected, it can cause the test to fail to locate the button.

![image](https://github.com/user-attachments/assets/00010bfe-db36-49e9-9d5a-4d8be8ace2c1)


Therefore, it is necessary to add test IDs to fix the flaky test. Here are some flaky tests related to this issue:
1. [Test Report 1](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/82//#testresult/ad2bee4cae1a77f9)
2. [Test Report 2](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/64//#testresult/e407a7dbbae679e9)

**Comment by kneerose** [comment]
@jdyczka  any update on this?
