### ISSUE TITLE
Configure sentry on deployments

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/govtool#1053]
Sentry Project : [govtool-frontend](https://intersect.sentry.io/projects/govtool-frontend/?project=4507101527277568)

This project is set-up in sentry but there are no events from any of the deployed environment.
We must enable capturing events in sentry for detection of issues early on.

### Todos:
Setup sentry DSN on following deployments
- [x] beta
- [x] staging
- [x] test

**Comment by spannercode** [comment]
This can be closed as well.
CC: @bosko-m

**Comment by bosko-m** [comment]
Closing as per the comment above.
