### ISSUE TITLE
GA - To Vote, Voted by me, Details page - proposal metadata are not shown

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1066]
To reproduce on test-sancho: 
1. Add new Proposal filling all fields, eg adding text: test.
2. Go to o Vote, Voted by me, Details page - no provided data are shown just, id and creation dates.

Compare with screenshots, for [GA](https://test-sanchonet.govtool.byron.network/connected/governance_actions/db4dbeb5946e5d49778f457d9c5a460488c40af0b93d8b98111f5be11bf165a6#0):

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/e9d58645-ceb1-4c83-95b1-a52c3cdce76f)

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/400f7985-4411-4238-96f7-5802836c4158)

vs Figma [designs](https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?node-id=7606-129137&t=QJQtwdZGh0jPssab-4):

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/981897bc-e6ff-4c05-8beb-b898b86979a5)

**Comment by MSzalowski** [comment]
Duplicate of #1027 - if it helps you tracking the issue we can keep this. But as soon as DB-sync provides the metadata both of these issues will be fixed.

That issue is not to be fixable under govtool applications (either frontend or backend)

**Comment by pmbinapps** [comment]
This is duplicate of https://github.com/IntersectMBO/govtool/issues/1027 - Closing
