### ISSUE TITLE
[BUG] Missing test ids (Governance Action proposal)

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1070]
## Description
- This ticket is a subtask of parent ticket #937 

### Missing Test Ids

- On create governance action proposal form fields
   -  title-input for the title input field
   -  abstract-input for the abstract input field
   - motivation-input for the motivation input field
   - rationale-input for the rationale input field
   - receiving-address-input for the receiving address field
   - amount-input for the amount input field
   - link-input for the link input field
   - add-link-button for the "Add Link" button

![image](https://github.com/IntersectMBO/govtool/assets/49801844/ec4ed0f2-22d6-41ad-8e8b-bf1a0064bcb5)

- On review fillup proposal form
    -  edit-submission-button for the edit submission button 
    -  governance-action-type-content
    -  governance-action-abstract-content
    -  governance-action-motivation-content
    -  governance-action-rationale-content
    -  governance-action-receiving-address-content
    -  governance-action-amount-content
    -  governance-action-link-content

![Screenshot from 2024-05-22 13-55-03](https://github.com/IntersectMBO/govtool/assets/49801844/4a646292-7ad0-467c-b0a3-d5208faa18ac)

- On information storage steps 
    - metadata-download-button
    - metadata-url
 
![Screenshot from 2024-05-22 14-18-58](https://github.com/IntersectMBO/govtool/assets/49801844/784cf251-fb5b-45a2-b76d-c042c61bd1ff)

**Comment by pmbinapps** [comment]
OK On Edit page:
Test ID found: title-input
Test ID found: abstract-input
Test ID found: motivation-input
Test ID found: rationale-input
Test ID found: receiving-address-input
Test ID found: amount-input
Test ID not found: link-input --> link-1-input  OK
Test ID found: add-link-button

**Comment by pmbinapps** [comment]
NOT OK - on content page, ids have new line char, eg:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/28022946-fd9c-4dcb-81b9-845c3282a61e)

**Comment by pmbinapps** [comment]
OK NOW:

DIV text: A 899448.985635| data-testid: voting-power-chips svg text: [undefined| data-testid: InfoOutlinedIcon
P text: A 899448.985635| data-testid: voting-power-chips-value
DIV text: [Back to dashboard| data-testid: Back-to-dashboard-link svg text: [undefined| data-testid: ArrowBackIosIcon
INPUT text: | data-testid: governance-action-type-input
P text: |To change the Governance Action Type go back to the previous page. I data-testid: to-change-the-governance-action-type-go-back-to-the-previous-page.-error
INPUT text: | data-testid: title-input
TEXTAREA text: || data-testid: abstract-input
P text: [General summary of the Action| data-testid: general-summary-of-the-action-error
TEXTAREA text: || data-testid: motivation-input
P text: |How will this solve a problem| data-testid: how-will-this-solve-a-problem-error
TEXTAREA text: || data-testid: rationale-input
P text: |Put all the content of the GA here| data-testid: put-all-the-content-of-the-ga-here-error
INPUT text: || data-testid: receiving-address-input
INPUT text: || data-testid: amount-input
INPUT text: || data-testid: link-1-input
BUTTON text: |+ Add link| data-testid: add-link-button
BUTTON text: Back| data-testid: back-button
BUTTON text: | Continuel data-testid: continue-button
A text: [Privacy policyl data-testid: privacy-policy-footer-link
A text: |Term of servicel data-testid: term-of-service-footer-link
BUTTON text: |Help| data-testid: help-footer-button
BUTTON text: | Feedback| data-testid: feedback-footer-button



@Sworzen1 id for element below seems to be invalid, ends with .-error

P text: |To change the Governance Action Type go back to the previous page. I 
data-testid: to-change-the-governance-action-type-go-back-to-the-previous-page.-error

**Comment by NabinKawan** [comment]
Hi @pmbinapps, Can we close this related issue after merging it into the test branch? We still cannot verify it.
