### ISSUE TITLE
[Bug] Internal Server error on Governance Actions page

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/govtool#1073]
### Context & versions
Test Stack: https://govtool.cardanoapi.io/governance_actions

### Steps to reproduce
I created a new HardFork governance action proposal.
Govtool broke immediately and started  showing `500 Internal Server Error` on Governance Actions page.

**Note**: The gov action was created by loader and  has invalid url format.

### API Response

```
"When parsing the record MetadataValidationResponse of type VVA.API.Types.MetadataValidationResponse the key valid was not present."
```

**Comment by pmbinapps** [comment]
Retest https://github.com/IntersectMBO/govtool/issues/1027 if this is fixed.
