### ISSUE TITLE
[BUG] State is unclear after Sole Voter Registration

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1075]
## Description:

After registering as a sole voter, the DRep ID and voting power are initially not displayed on the delegated card.
These elements become visible only after refreshing the page or switching tabs and returning to the dashboard.

## Steps to Reproduce:

- Register as a sole voter.
- Observe that the DRep ID and voting power are missing from the initial dashboard view. 

![sole-voter](https://github.com/IntersectMBO/govtool/assets/49801844/cdb46c03-9707-436d-a7a5-e9e651dc034e)

- Either Refresh the page or switch tabs and return to the dashboard.
- Verify that the DRep ID and voting power are now displayed. 

![sole-voter-DRepId](https://github.com/IntersectMBO/govtool/assets/49801844/5bf16ee6-fc0d-4f10-9c6a-d821635b5d06)

## Additional Notes:
- The DRep ID and voting power should be displayed on the dashboard immediately after successful registration as a sole voter or DRep ID should not be visible ?
- It is unclear whether the DRep ID is intended to be displayed on the initial dashboard.
- Confirmation on the expected behavior from Figma designs would be helpful.

**Comment by m-i-k-e** [comment]
The screen should look like this after the registration of a Direct Voter has completed: 
![direct voter](https://github.com/IntersectMBO/govtool/assets/965789/7f42c589-6c4f-4494-a98d-e99766ab4ef8)


https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=8754-62229&t=oA5PJj4nz9Y9JSRs-1

**Comment by m-i-k-e** [comment]
This video asks a simple question: If we know the user is a direct voter, why can't we use that info to make the Delegation card correct (as in the screenshot above)

https://www.loom.com/share/da58a590972e40b8ba8eb0152a487c89?sid=0450f759-9308-4eae-bffe-f820400f2f4c

**Comment by m-i-k-e** [comment]
Probably the biggest problem here is that the Direct Voter will have a difficult time to change roles to "Delegator", as this option has been removed from the dashboard.
