### ISSUE TITLE
[BUG] Missing Link for Tracking Registration Confirmation in DRep Registration Confirmation Modal

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1076]
## Context & versions
- Upon registering as a DRep, the confirmation modal should display a link to track the confirmation of registration as specified in the Figma design. However, this feature is not present in the current implementation.

## Actual behavior

![Screenshot from 2024-05-23 12-38-43](https://github.com/IntersectMBO/govtool/assets/49801844/ddb9a44b-ebf1-4e40-8d8e-3923e550ec13)
- The confirmation modal does not display a link for tracking the confirmation of registration

## Expected behavior

<img width="1440" alt="dRep registration_Confirmation" src="https://github.com/IntersectMBO/govtool/assets/49801844/d7659d66-e12c-4fad-b66b-b8040f4c77c6">

 - The confirmation modal should include a link for tracking the confirmation of your registration, as shown in the provided Figma design.

**Comment by pmbinapps** [comment]
OK NOW:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/6d5c2e8d-025e-42a0-8cfb-c6f8a309d8b0)
