### ISSUE TITLE
[BUG] Abstain and Signal No Confidence Delegate Buttons Load Incorrectly on DRep Directory

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1078]
## Context & versions
- The delegated buttons of  Abstain, and Signal No Confidence are loading incorrectly when clicking on the DRep Delegate.

## Steps to reproduce
- Navigate to the DRep directory page.
- Click on the delegate button of either Abstain, Signal No Confidence or the DRep.
- Observe the loading behaviour of the delegate buttons for Abstain and Signal No Confidence.

## Actual behaviour
- The deletion buttons for Abstain and Signal No Confidence both load, even when only one button was clicked.

![image](https://github.com/sireto/govtool/assets/49801844/73150486-ca1b-4543-ac95-296118244c22)

- Instead of loading the DRep delegate button, Abstain and Signal No Confidence delegate buttons are loading.

![image](https://github.com/IntersectMBO/govtool/assets/49801844/51c8d21b-2216-4660-9bc6-e8a9c8f4a47f)

## Expected behaviour
-  Only the clicked button should load, not multiple buttons.

**Comment by pmbinapps** [comment]
OK now - retested on dev-sancho - Jam recording [here](https://jam.dev/c/af46be27-893e-40c2-8893-1cf47341add3)

Recheck on test-sancho

**Comment by NabinKawan** [comment]
Hi @pmbinapps, Can we close this related issue after merging it into the test branch? We still cannot verify it.

**Comment by kneerose** [comment]
@pmbinapps   
I am closing this issue as it has been resolved.

CC: @bosko-m
