### ISSUE TITLE
[BUG] Multiple Wallet Popups

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1079]
## Context & versions
Multiple Wallet Popups on Clicking Vote button multiple times

## Steps to reproduce
- Navigate to the governance action page
- View Details of any proposal 
- Choose the vote option and click submit vote multiple time

## Actual behaviour

![image](https://github.com/sireto/govtool/assets/49801844/86f4e737-0589-4aa9-9bc0-b223566eb9b7)

## Expected behaviour
 - Should Block Additional Clicks Until the Transaction is Processed

**Comment by pmbinapps** [comment]
Occurs on Continue button when registering as or retiring as Direct Voter and Drep.

https://github.com/IntersectMBO/govtool/assets/82152577/030a36f9-0232-47ab-968b-994c44ee7779

**Comment by NabinKawan** [comment]
Hi @pmbinapps, Can we close this related issue after merging it into the test branch? We still cannot verify it.

**Comment by kneerose** [comment]
@pmbinapps   
I am closing this issue as it has been resolved.

CC: @bosko-m

**Comment by pmbinapps** [comment]
@NabinKawan the issue should be open until is confirmed on stage and closed, if not thing changed regarding this.
