### ISSUE TITLE
Endpoint /drep/info - Incorrect State of Direct Voter in Endpoint Response

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1083]
Summary:
The Swagger endpoint returns an incorrect state for the "isRegisteredAsSoleVoter" field, indicating that the user is still registered as a Direct Voter even though the UI shows that the user has retired.
DREP
https://dev-sanchonet.govtool.byron.network/api/swagger-ui/#/default/get_drep_info__drepId_

Steps to Reproduce:

1. Navigate to the Sanchonet GOV Tool dashboard.
2. Observe the status of the Direct Voter in the dashboard, which correctly shows the user as retired.
4. Use the Swagger UI to query the relevant endpoint for the same user. 
Alternatively:
`curl -X 'GET' \
  'https://test-sanchonet.govtool.byron.network/api/drep/info/08b8621f96e312991083684f035841888e3a785403e4b41aeee47aa5' \
  -H 'accept: application/json;charset=utf-8'`
5. Check the response from the endpoint.
6. Expected Result:
7. The field isRegisteredAsSoleVoter should be set to false in the Swagger response, reflecting the user's retired status as shown in the dashboard UI.
Actual Result:
The field isRegisteredAsSoleVoter is incorrectly set to true in the Swagger response.

Attachments:

Screenshot showing the dashboard indicating the user has retired as a Direct Voter.

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/f6c4d14c-c4c7-453b-b5a8-9e3242bac2ac)

Environment:

Application: Sanchonet GOV Tool
Environment: Test Network (test-sanchonet.govtool.byron.network)
Date/Time: Fri, 24 May 2024 00:37:12 GMT
Browser: [Specify browser used]
Additional Information:
The discrepancy between the dashboard UI and the Swagger endpoint response suggests a possible issue in the backend logic or the API response handling. This needs to be investigated and corrected to ensure consistency in the user's voting status across different interfaces.

**Comment by pmbinapps** [comment]
@bosko-m this could become P0 as states on different Views depends on values returned by this endpoint

**Comment by m-i-k-e** [comment]
The screen shows the correct state in this issue.

**Comment by pmbinapps** [comment]
Tried to reproduce it but it looks fine up to now. Closing...



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/9c106221-193e-4b2d-a722-dfa2836f4a42)
