### ISSUE TITLE
Fix failing tests on CI

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#1088]
The following tests are passing locally but failing on the CI tests.

- [x] 2E. Should register as Sole voter
- [x] 2S. Should retire as a Direct Voter on delegating to another DRep

**Comment by pmbinapps** [comment]
This is fine on test with latest demos wallet.

**Comment by spannercode** [comment]
This could be because of extra workers using the CPU cores on Github action. @NabinKawan is investigating the issue further.

**Comment by NabinKawan** [comment]
This is due to [issue](https://github.com/IntersectMBO/govtool/issues/1106). For now, will handle it by putting some retires.

**Comment by spannercode** [comment]
It is now working on the dev with retries.
Here is the working test report: 
- [2E. Should register as Sole voter](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/31/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/a65f8e1c4fc55e6e/)
- [2S. Should retire as a Direct Voter on delegating to another DRep](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/31/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/85fcea4930d82b88/)

**Comment by NabinKawan** [comment]
[PR](https://github.com/IntersectMBO/govtool/pull/1115) for this.
