### ISSUE TITLE
Showing delegated DRep Id after delegation is slow

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#1089]
User story:
 **2A. Should show delegated DRep Id (on Dashboard, and DRep Directory) after delegation**
 - https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/14/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/b7d744547cc07631/
 
 Description:
 After delegation on Dashboard, DRep Directory, the DRep Id is reflected after a lag. This is causing test to timeout.
 
 Related other stories which fail because of the slow UI response:
 **2F. Should change delegated DRep**
 - https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/13/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/cd55d3b83bf93937/

**Comment by pmbinapps** [comment]
Need to decide what timeout length is acceptable.
[Here](https://jam.dev/c/3a06ed02-31f8-4088-b344-d805f3a371f5) recoding of a Delegation which lasted apx 25 sek.

**Comment by MSzalowski** [comment]
Transaction might be on In Progress even up to 3 minutes.

@Ryun1 could you please verify if that is true?

**Comment by Ryun1** [comment]
> Transaction might be on In Progress even up to 3 minutes.
> 
> @Ryun1 could you please verify if that is true?

Yup

**Comment by spannercode** [comment]
The reason for the timeout on test was the lag to show the DRep Id even after the transaction is completed. The test waits for the transaction to be completed before it expects to see the updates on the page.
<img width="1417" alt="Screenshot 2024-06-10 at 06 32 57" src="https://github.com/IntersectMBO/govtool/assets/45617712/da56416b-3c03-4d91-8547-4a436e50a844">

**Comment by bosko-m** [comment]
@spannercode Should anything be fixed then in the code? Perhaps on the test itself?

**Comment by NabinKawan** [comment]
It is due to a null reference error in the function `getData`.
Error:
```
null (reading 'dRepHash')
    at lKe (index-98ec2c1b.js:398:27075)
    at async u0 (index-98ec2c1b.js:398:28410)
lKe @ index-98ec2c1b.js:398
o4507027845021696.ingest.us.sentry.io/api/4507101527277568/envelope/?sentry_key=69300ede4a476619986b4f6c4f3193d4&sentry_version=7&sentry_client=sentry.javascript.react%2F7.116.0:1 
``` 

**This error prevents the transaction status from being updated.**

Source code from where the error is generated:
![image](https://github.com/IntersectMBO/govtool/assets/43606623/97d8cf3f-c182-4801-a8e1-26fee128926c)

[sentry link](https://intersect.sentry.io/issues/5502857371/?project=4507101527277568&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=3)

@MSzalowski Could you please have a look on this?

**Comment by NabinKawan** [comment]
> @spannercode Should anything be fixed then in the code? Perhaps on the test itself?

@bosko-m It should be fixed in the code.

**Comment by spannercode** [comment]
Linking the PR to address this issue:
- https://github.com/IntersectMBO/govtool/pull/1256

CC: @MSzalowski

**Comment by bosko-m** [comment]
Will be handled after DBSync 5.1.0 issue is resolved.

**Comment by bosko-m** [comment]
@spannercode @MSzalowski Is this resolved?
