### ISSUE TITLE
Do not display direct voter delegation on delegation card.

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1095]
When user is registered as a direct voter (which means that they also delegates their ada to themselves).
**Do not display such delegation on delegation card.**

Card after becoming a Direct voter should look like this:
<img width="543" alt="image" src="https://github.com/IntersectMBO/govtool/assets/24510246/bcbf47ea-0762-4b10-ab27-2e6da0a74262">

**Comment by MSzalowski** [comment]
@m-i-k-e Could you please verify the issue description against the requirements?

**Comment by pmbinapps** [comment]
OK on Dashboard:

![image](https://github.com/IntersectMBO/govtool/assets/82152577/29aa176d-983a-4d65-80ce-294588e512ed)

DRep explores shows this:
![image](https://github.com/IntersectMBO/govtool/assets/82152577/0b17e13d-8633-49fd-9bb7-3285712425e1)
