### ISSUE TITLE
[BUG] Wallet Connection Popup on GovTool Reopen (Connected State)

### ISSUE THREAD

**Issue by NabinKawan** [IntersectMBO/govtool#1106]
**Description**
- Tests 2E and 2S are intermittently failing due to an unexpected popup appearing when attempting to reopen the GovTool after a successful wallet connection.
- The popup itself is difficult to reproduce.
![image](https://github.com/IntersectMBO/govtool/assets/43606623/5e7ee104-6704-4104-9757-f0f92ccb7e07)

**Comment by NabinKawan** [comment]
@MSzalowski, can you please verify this in the codebase?

**Comment by m-i-k-e** [comment]
What browser/wallet version is this?

**Comment by NabinKawan** [comment]
@m-i-k-e, I'm using mock wallet which we have implemented for testing, with the Chromium browser

**Comment by MSzalowski** [comment]
I'll have a look

**Comment by kneerose** [comment]
This issue is no longer reproducible and can now be closed.
CC: @bosko-m
