### ISSUE TITLE
Replace vva occurencies to govtool

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#111]
# Description
As `vva` stage of the application has ended and the application has changed its name to `govtool` we have to replace all the occurencies in code of `vva` to `govtool`.

# Why?
Our repository will be published to the community and open-sourced. We have to avoid the misunderstanding of our community members of what the `vva` is.

# ToDo
1. Replace `vva` to `govtool`
2. Make changes on any integrated services, platforms etc.
3. Make any requried changes on the infrastructure 
4. Check if the application after changes is working

**Comment by Ryun1** [comment]
very old, lets close
