### ISSUE TITLE
Add metadata validation in DRep Directory

### ISSUE THREAD

**Issue by Sworzen1** [IntersectMBO/govtool#1112]
## Context 
Add metadata validation into DRep Directory

## Actual behavior
DRep Directory elements dont validate and display metadata. Data is mocked.

## Expected behavior
DRep Directory elements should validate and display metadata from chain.

**Comment by pmbinapps** [comment]
Validation case:

Scenario - DRep metadata Submitting/Edit 
* OK metadata match json file - registrations goes

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/d9746b9d-d5c8-485e-b806-31ec6f7eb85b)


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/5fa75f85-a5fd-413d-9942-0fc6d9798250)


* OK metadata do not match json file contents - error msg is shown


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b08473ac-bf66-4e20-9a35-54b2c413e7d1)

* NOT OK - altering json file correct structure, different content - change not detected immediately
* TO CHECK LATER

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/f1a9ebdd-db10-476e-8a8f-c979c7a8f584)

**Comment by Ryun1** [comment]
this is done
