### ISSUE TITLE
[BUG]  DRep Directory Page Displays Wallet Disconnect State Despite Active Wallet Connection

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1117]
## Context & versions
- The DRep directory page displays as a wallet disconnect state when accessed via `/drep_directory` , even with a connected wallet.

## Steps to reproduce
- Connect to your wallet
- Navigate to the DRep directory page using the URL `/drep_directory`

## Actual behavior
![image](https://github.com/IntersectMBO/govtool/assets/49801844/491a4bca-2dd6-4175-bbf0-ac9155ff0aa7)

## Expected behavior
- Either redirected to `/connected/drep_directory` Or preview with the information reflecting the connected wallet state.

![image](https://github.com/IntersectMBO/govtool/assets/49801844/17d1eff2-6055-4bd6-93a1-7bbbbe58d7db)

For more details, please refer to the reference report [here](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/31/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/cbb88161b2c1e189/)

**Comment by kneerose** [comment]
@pmbinapps  @Sworzen1 any update on this?

**Comment by MSzalowski** [comment]
@jdyczka Could you please handle this issue?

**Comment by bosko-m** [comment]
Closing as per the comment above.
