### ISSUE TITLE
[BUG] Wallet disconnect: Unexpected redirection to dashboard from governance/dRep pages

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1119]
## Context & versions
- Disconnecting the wallet while on the governance action page or dRep directory page redirects the user to the dashboard.

## Steps to reproduce
- Access the `governance action / dRep directory` page with a connected wallet.
- Disconnect the wallet.
- The application automatically redirects to the dashboard.

## Actual behaviour
- Upon wallet disconnect, the user lands on the dashboard

![image](https://github.com/IntersectMBO/govtool/assets/49801844/5c2aa3db-53bc-47b2-8b0d-6aae5a255ce7)

## Expected behaviour
- Disconnecting the wallet should ideally return the user to the previous page they were on before the disconnect 

![image](https://github.com/IntersectMBO/govtool/assets/49801844/db14591e-4a43-43cf-9b09-785f883f44a6)

![image](https://github.com/IntersectMBO/govtool/assets/49801844/c97ece64-b576-4f15-912a-a61badc88ce5)

- A similar issue is documented in the test report [here](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/31/#behaviors/1523ff4143db0faaf245e2252e8ca520/1caa906a60a0991f/)

**Comment by SandraRodziewicz** [comment]
Checked on different views - disconnecting a wallet and then connecting it again returns to the same page
Ready for staging
