### ISSUE TITLE
"View Governance Actions" Learn More text - Gitbook

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1124]
Text for this Learn More:

![image](https://github.com/IntersectMBO/govtool/assets/965789/3f8aed03-8314-4bdd-956d-47c7c3eaca8c)

**Comment by m-i-k-e** [comment]
Change link to : https://docs.sanchogov.tools/how-to-use-the-govtool/using-govtool/governance-actions/governance-actions-overview

**Comment by m-i-k-e** [comment]
This should go to: https://docs.sanchogov.tools/how-to-use-the-govtool/using-govtool/governance-actions

**Comment by m-i-k-e** [comment]
@MSzalowski has this been done?

**Comment by Ryun1** [comment]
this is done
