### ISSUE TITLE
"Propose Governance Action" Learn More text - Gitbook

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1125]
Text for this:

![image](https://github.com/IntersectMBO/govtool/assets/965789/640283b6-d697-4b59-b0ad-bd266e1c8157)

**Comment by m-i-k-e** [comment]
This links to the wrong point: it should go to:  https://docs.sanchogov.tools/how-to-use-the-govtool/using-govtool/governance-actions/propose-a-governance-action

**Comment by Ryun1** [comment]
this is done
