### ISSUE TITLE
"Info" action tooltip - write

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1128]
the text that shows when a user clicks/taps the 'i'

![image](https://github.com/IntersectMBO/govtool/assets/965789/a35e4e3a-1e47-4a88-9907-3e0930d675a2)

**Comment by m-i-k-e** [comment]
Text For Tooltip: 
"An action that doesn't have any on-chain impact except for being recorded on-chain."

**Comment by GypsyBinar** [comment]
tooltips added https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/branch/1RSRpNPpkQF1MPTkyeGvoG/Voltaire---GOV-TOOL?m=auto&node-id=14263-89664&t=mXLQMG9nUNsfdXOE-1

**Comment by m-i-k-e** [comment]
@MSzalowski Tooltips in Figma here: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=14263-89664&t=WX0PNuKWSUFm65EF-1

**Comment by m-i-k-e** [comment]
Good
