### ISSUE TITLE
Treasury tooltip entry - write

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1129]
The 'i' text here:

![image](https://github.com/IntersectMBO/govtool/assets/965789/11d7523e-ab51-4919-9ae2-3628f1ebb71d)

**Comment by m-i-k-e** [comment]
Text for Tooltip: 
"Treasury withdrawals are sub-categorized into small, medium, or large and are determined by the amount of lovelace to be withdrawn."

**Comment by GypsyBinar** [comment]
tooltips added

**Comment by m-i-k-e** [comment]
@MSzalowski Tooltips in Figma here: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=14263-89664&t=WX0PNuKWSUFm65EF-1

**Comment by m-i-k-e** [comment]
Good. Closing
