### ISSUE TITLE
"Propose a Governance Action" text needs writing

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1132]
If you click "learn more" from this card:
<img width="550" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/71a88ef2-fa17-458d-8381-eb42acaac7b6">

You get this page: https://docs.sanchogov.tools/faqs/what-is-a-governance-action

The above page has virtually zero information, and it need to tell users how to propose a GA, not what a GA is. Needs re-writing.

Note: the above page may also not be fit for purpose, and probably should be fleshed out.

**Comment by m-i-k-e** [comment]
added blank page

**Comment by m-i-k-e** [comment]
Closing as a duplicate of https://github.com/IntersectMBO/govtool/issues/1125

**Comment by m-i-k-e** [comment]
This should link to: https://docs.sanchogov.tools/how-to-use-the-govtool/using-govtool/governance-actions/propose-a-governance-action

**Comment by m-i-k-e** [comment]
Done

**Comment by m-i-k-e** [comment]
This should link to: https://docs.sanchogov.tools/how-to-use-the-govtool/using-govtool/governance-actions/propose-a-governance-action

**Comment by MSzalowski** [comment]
I've added link to the very first comment: https://github.com/IntersectMBO/govtool/issues/1132#issuecomment-2158787090
I've updated that link to this comment: https://github.com/IntersectMBO/govtool/issues/1132#issuecomment-2258204025

**Comment by MSzalowski** [comment]
PR with the fix: https://github.com/IntersectMBO/govtool/pull/1634
