### ISSUE TITLE
Translate Byron's address from Estonian

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1133]
The first line of the privacy policy has some strange language in it: 

> The controller of personal data processed via the govtool.com ("Webiste") is Byron (hereinafter: "Byron") registered Byron Network OÜ; Registrikood: 16423145 Tegevusaadress: Lõõtsa tn 5 // Sepapaja tn 4 Tallinn Harjumaa 11415, electronic contact address:contact@byron.network, website https://byron.network/# . 

The address should be transalted to English.

Also, there are references to the Polish office for data protection. Is this relevant to users outside of Poland?

**Comment by bosko-m** [comment]
@MSzalowski Is Byron team able to provide answers on @m-i-k-e questions? For the use of estonian language, the address itself shouldnt be translated, but the address label should. Also, there is a gap with Poland being explicitly mentioned while the company is registered in Estonia.

**Comment by m-i-k-e** [comment]
I've reassigned this to @MSzalowski because I think he's in the best position to get this fixed.
