### ISSUE TITLE
Overlapping Feedback buttons - remove the old button and reveal the new in-page one

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1135]
## Context & versions
dev.sanchonet

## Steps to reproduce

  1. Go to any page on GovTool
  2. Look at lower right of screen

## Actual behavior
You see the old feedback button and the new one is overlapped by it

## Expected behavior
You should see only the new one, that's integrated into the page.

<img width="297" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/7541dc66-ac8e-4252-be6b-290b83331a8d">

**Comment by MSzalowski** [comment]
Done with [sancho-v1.0.5](https://github.com/IntersectMBO/govtool/releases/tag/sancho-v1.0.5)

**Comment by m-i-k-e** [comment]
Closing
