### ISSUE TITLE
Stress test: Govtool-backend crashes

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/govtool#1148]
## Context & versions
commit: [64ebaf7bd62a4fa2878a4ff05c15ba5085133a2e](https://github.com/IntersectMBO/govtool/commit/64ebaf7bd62a4fa2878a4ff05c15ba5085133a2e)

## Issue Explaination
Govtool backend  cannot handle sudden peak in requests. The container simply crashes with error log when hit with a brust of requests.

## Container log
```
[ec2-user@ip-10-0-1-213 ~]$ docker logs -f 7b8e9ed1ecd1
listening on Host "0.0.0.0":8080
vva-be: file descriptor 1024 out of range for select (0--1024).
Recompile with -threaded to work around this.
```

**Comment by MSzalowski** [comment]
Reopening this issue as:

`Warning: 'ghc-options: -threaded' has no effect for libraries. It should only be used for executables.`

**Comment by bosko-m** [comment]
@spannercode Should we keep or close this one?
