### ISSUE TITLE
[Documentation] Proposal Discussion Forum covered user stories 

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1152]
-  This issue serves as a placeholder for gathering PDF user stories.
-  The UI for the Proposal Discussion Forum is not currently implemented. However, we can begin capturing user stories using Figma to define the functionality.

**Comment by kneerose** [comment]
Documentation [link](https://docs.google.com/document/d/1ZRHzFGG7MseftLA_AwZLBm-HH_kHLn-9yBBJU9aYQ8I/edit?usp=sharing) for the proposal discussion forum User story

**Comment by spannercode** [comment]
The user stories are submitted as PR on `cardano-test-plans` repo by @kneerose here:
- https://github.com/IntersectMBO/cardano-test-plans/pull/49

**Comment by spannercode** [comment]
@ValMBO This is the ticket for the documentation of the user stories. If you could go through the user stories and validate or correct them, that would be great.

CC: @bosko-m

**Comment by bosko-m** [comment]
@spannercode I think that @ValMBO commented in the doc.

**Comment by spannercode** [comment]
@ValMBO Thank you for the review and comments.
@bosko-m Yes, this is addressed.
