### ISSUE TITLE
CTA - Submit as a Governance Action

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1157]
CTA - Submit as a Governance Action is not working

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/7602fd0f-b6e8-4178-b4f5-af24f5985e0c)

**Comment by MSzalowski** [comment]
@ValMBO Logic behind Submitting the Governance Action is handled by Proposal pillar, so if this button is not working it should be fixed on the pillar side

**Comment by bosko-m** [comment]
Verified it works on staging, closing.
