### ISSUE TITLE
Parsing error on becoming a DREp P0

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1160]
## Steps to reproduce

  1. Try to register as a DRep
  2. get to last step (checking metadata)

## Actual behavior
"Parsing error" dialog box

## Expected behavior
Registration completes

## See Loom Video: https://www.loom.com/share/d634800d94e848759d0380ae5ba0c13f?sid=102eb267-27ea-4d8c-9419-ac34d2fe3458

<img width="1333" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/6ec9ae38-5111-432c-80d4-dccc90b4d0e7">

**Comment by Ryun1** [comment]
Interesting error

**Comment by pmbinapps** [comment]
@m-i-k-e nice catch, could you share the link to the json file you are using for this?

**Comment by xoriole** [comment]
@NabinKawan lets add a test for this issue.

**Comment by Sworzen1** [comment]
@m-i-k-e could you provide full error from console ?

**Comment by Ryun1** [comment]
Suspected wallet related error;
- working for me on demos and eternl

**Comment by Ryun1** [comment]
Confirmed behaviour with NuFi wallet

![image](https://github.com/IntersectMBO/govtool/assets/44342099/532046b7-3cbc-4d17-a916-6f24523a6831)

**Comment by m-i-k-e** [comment]
This works in Demos wallet.

<img width="545" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/a7f53b76-079f-4a0f-8719-babf428dc571">

**Comment by m-i-k-e** [comment]
Closing, as this is a wallet issue. @Ryun1 is going to inform NuFi.
