### ISSUE TITLE
Direct Voter listed in DRep Directory (at top)

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1162]
## Context & versions
staging.sanchonet + NuFi wallet

## Steps to reproduce

  1. Become Direct Voter
  2. Look at DRep directory

## Actual behavior
You see a row at the top of screen with your delegation to yourself

## Expected behavior
You should not see this row. This row is for DReps delegating to themselves or others, or Delegators, not Direct Voters

**Comment by pmbinapps** [comment]
Not finding drep in list, covered in separate issue https://github.com/IntersectMBO/govtool/issues/960

**Comment by MSzalowski** [comment]
That is no longer an issue. @pmbinapps Could you please verify it?

**Comment by pmbinapps** [comment]
OK NOW
