### ISSUE TITLE
Old Direct Voter showing in DRep directory as DRep

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1163]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Be a delegator
  2. Look at DRep Directory

## Actual behavior
I see a listing for some DRep called "Direct Voter" This, I believe, was my role previously. In other words, a few minutes before I was a Direct Voter, and I became a Delegator

## Expected behavior
This listing should not be in the Directory

## Loom Video

https://www.loom.com/share/be80b1d6138b43f084bd14dd1cf585ae?sid=9959854e-ee4f-4f33-830b-dcd6a5e18559

<img width="1590" alt="Screenshot 2024-06-04 at 16 26 14" src="https://github.com/IntersectMBO/govtool/assets/965789/fb0e8fa3-2dcd-4fe0-8ed8-48941f6e6199">

**Comment by MSzalowski** [comment]
Now all the retired DReps have the missing metadata. Last DRep registration (of the deregistration) doesn't have such fields.

To be discussed whether we can fetch these and on which exact conditions between DReps and Direct Voters.

CC @jankun4

**Comment by jankun4** [comment]
Cannot reproduce
