### ISSUE TITLE
Missing a pop up message after clicking on Share icon

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1172]
## Context & versions
Chrome 

## Steps to reproduce

  1. Govtool home page
  2. Click on Proposal Discussion Forum
  3. Go to Proposals cards
  4. Click on Share Icon

## Actual behavior
After you click on share icon, there is no pop up message

## Expected behavior
Reuse the copy from GovTool - Here is the link of Figma file: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=9347-311411&t=EVcqxokPKbNGsUpT-1

Comment from Nikola - https://www.figma.com/design/239JKpjintphf2Go5NPipp?node-id=965-103629#828484460

**Comment by bosko-m** [comment]
Verified on staging and Sancho, closing.
