### ISSUE TITLE
Blank section when PDF is open

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1173]
## Context & versions
dev.gov.tools Chrome

## Steps to reproduce

  1. Open PDF and first thing I see is a blank section

## Actual behavior
Blank section on the home page

## Expected behavior
Proposal cards - Dashboard

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/e12b6228-64b7-454b-90af-bb7a665e8801)

**Comment by teske00** [comment]
@ValMBO @vpaunovic This is the environment we created based on our govtool-ui wrapper (https://github.com/IntersectMBO/govtool-ui), for testing the PDF package. We did not do the entire govtool design, but only the "Proposed governance actions" page. Michal is working on an implementation in the current govtool where all pages are visible (https://dev-sanchonet.govtool.byron.network/)

**Comment by ValMBO** [comment]
Fantastic! thanks guys for the explanation - I will leave it open until Michal finish with the integration.

**Comment by MSzalowski** [comment]
It is already done on [dev](https://dev-sanchonet.govtool.byron.network/), [test](https://test-sanchonet.govtool.byron.network/) and [staging](https://staging.govtool.byron.network/)
