### ISSUE TITLE
Table design for Governance Actions

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1177]
Design a table view of the GA homepage. Use standard Material Design stuff, and include pagination.

This has already been started, let's use this issue to converge our ideas so we can find them in the future.

**Comment by m-i-k-e** [comment]
This has been done in wireframe, but is not implemented, nor is the design passed

**Comment by bosko-m** [comment]
This is already covered in another issue thats also part of the community backlog.
