### ISSUE TITLE
GA - Submitting proposal - validation submitted data vs provided URL is not working

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1178]
To reproduce:
1. Start adding new proposal eg Info.
2. Fill all required info
3. Continue to last step with download of Info.json file
4. Provide input Paste the URL here: - tye valid url to not existing file and confirm - verification starts, no error is shown, wallet is called 

Compare with recording.

https://github.com/IntersectMBO/govtool/assets/82152577/ad848c57-fa3b-40fc-9ea7-5d1e4b55578b

**Comment by kneerose** [comment]
Hello @pmbinapps ,

Spot on! Not only is there a missing provided URL and submitted data validation check during GA proposal submission, but there's also the same issue for dRep registration and editing registered dReps.

For reference reports:
- GA proposal submission : [report](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/38/#behaviors/1c853b5eba2ae76bed30628cc87b9764/c1e1c97bc6f4eac5/)
- DRep registration : [report](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/38/#behaviors/f7eea6c55a554c79a959f2fe9524fccc/10bc78c47bc53f27/)
- Edit registered dRep: [report](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/38/#behaviors/f7eea6c55a554c79a959f2fe9524fccc/907600a8cc3c053e/)

**Comment by pmbinapps** [comment]
OK for GA
https://jam.dev/c/631abc60-ccfa-4cf2-9160-3238c2cb3427
OK for DRep
https://jam.dev/c/80c2b85c-71b2-4a31-8a3d-e1d7641c7914

**Comment by m-i-k-e** [comment]
Can't test, as get same error as #1027

**Comment by m-i-k-e** [comment]
This has worked for me now on staging. Closing
