### ISSUE TITLE
[BUG] Metadata anchor validation

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1180]
## Context & versions
- The current system allows users to register dReps, edit existing dReps, and submit (GA) proposals. During these processes, users can provide a metadata anchor link. However, the system does not validate the length of the URL within the link. This allows users to submit entries with URLs exceeding the expected character limit (greater than 128 bytes).

## Steps to reproduce
- Navigate to the dRep registration, edit dRep, or GA proposal submission page.
- Fill out the required information.
- In the metadata anchor field, enter a URL with a character count exceeding 128 bytes.
- Observe that the submit button remains enabled, and no error message is displayed.

## Actual behaviour
- The system permits submission even if the URL in the metadata anchor field exceeds the character limit.

![Screenshot from 2024-06-06 11-38-27](https://github.com/IntersectMBO/govtool/assets/49801844/8d91df58-97db-48f2-8963-a9f8ef449cb7)

## Expected behaviour
- When a user enters a URL exceeding 128 bytes in the metadata anchor field, the system should:
    - Disable the submit button.
    - Display an error message like "Invalid URL: Character limit exceeded."
    
    
### Report references
- GA proposal submission : [report](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/41/#behaviors/1c853b5eba2ae76bed30628cc87b9764/c7621102c931ef13/)
- DRep registration : [report](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/41/#behaviors/f7eea6c55a554c79a959f2fe9524fccc/7903f4efec8eb4f8/)
- Edit registered dRep : [report](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/41/#behaviors/f7eea6c55a554c79a959f2fe9524fccc/3067899eaf5e1bd0/)

**Comment by m-i-k-e** [comment]
In my opinion, this is a P1.

**Comment by pmbinapps** [comment]
@Ryun1 @MSzalowski  please confirm what max length should be use? previously 64 chars max were mentioned in User stories:

_Given that I am on the DRep registration page 

If/when I have entered some information into the input box for metadata url, then it will be checked against the following criteria:
It must be <= 64 bytes in length_

**Comment by Ryun1** [comment]
@pmbinapps 

[128 (bytes)](https://github.com/IntersectMBO/cardano-ledger/blob/master/eras/conway/impl/cddl-files/conway.cddl#L377C1-L377C26)

**Comment by pmbinapps** [comment]
OK NOW



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b68b51f1-daf9-4d32-a7e5-d918b0ba7faa)
