### ISSUE TITLE
[BUG] Persistant "Wallet Connected" Toast Disrupts Testing

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1181]
## Context & versions
- The application displays a "wallet connected" toast message every time it's opened when a wallet is already connected. This toast interferes with automated tests, causing flakiness and hindering test interaction.

## Steps to reproduce
- Navigate to the app while a wallet is connected.
- Observe the "wallet connected" toast notification.

### Impact:
- Automated tests are rendered unreliable due to the persistent toast.
- Test interactions are disrupted by the toast presence.

### Reference test reports
- [ Should search governance actions](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/41/#behaviors/1523ff4143db0faaf245e2252e8ca520/ef8c2d69c7ec10b9/) 
- [Should sort Governance Action Type on governance actions page](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/41/#behaviors/1523ff4143db0faaf245e2252e8ca520/55a331646b0e3e6d/)

above mention, tests are currently blocked due to this toast.

**Comment by pmbinapps** [comment]
A decision is need how this feature should be used to inform user about wallet connection status.

**Comment by MSzalowski** [comment]
Wallet reconnects every time the page is being refreshed. That is to prevent the situation when the wallet looses its connection on refresh (which is possible on such action).

Every time when wallet is being reconnected, the toast is displayed informing the user about the successful connection. I wouldn't call it as a bug, is it any way to bypass the wallet connect toast on your tests using the test ids?

**Comment by bosko-m** [comment]
@kneerose Whats your opinion on this?

**Comment by kneerose** [comment]
@bosko-m   we already handle this.
