### ISSUE TITLE
[BUG] Unintended Access to dRep Registration and Editing Functions

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1183]
## Context & versions
- **Unrestricted Access to Registration:** Registered dReps can access the `/register_drep` page, intended for new dRep registrations.
- **Uncontrolled Access to Editing:** Non-registered users can inappropriately access the `/edit_drep` page, meant for modifying existing dRep profiles.

## Steps to reproduce
**dRep user:**
- Log in as a registered dRep user.
- Navigate to the URL for registering a new dRep ` /register_drep`.

**Non dRep User:**
- Access the system with non-dRep users.
- Navigate to the URL for editing a dRep profile `/edit_drep`.

## Expected behaviour
- **Registered dReps:** Upon accessing `/register_drep`, a registered dRep should be redirected to a relevant page (e.g. dashboard) with a clear message indicating they are already registered.
- **Non-registered Users:** When a non-registered user attempts to access `/edit_drep`, they should be redirected to the registration page (/register_drep) with a message explaining they need to register first.

## Allure Report references
- [6G Should restrict edit dRep for non dRep](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/46/#behaviors/be0c801ac30023c8c33048413e6782a7/9974f00398b7e5c1/)
- [6H Should restrict dRep registration for dRep](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/46/#behaviors/be0c801ac30023c8c33048413e6782a7/1a5ff7f8b35bfd67/)

**Comment by MSzalowski** [comment]
That should already be fixed @pmbinapps could you please retest it making sure that the issue no longer exists?

**Comment by pmbinapps** [comment]
OK NOW
* for not connected user, after reload user stays on dashboard when /edit_drep is used
* for connected as Drep after /edit_drep - Edit drep is used
* for connected as non-Drep /edit_drep shows Dashboard

TBC any behaviour mentioned in Expected results should be implemented.

**Comment by kneerose** [comment]
Hello @pmbinapps ,

The `/edit_drep` navigation is working fine, but the `/register_drep` navigation proceeds even if the user is already registered as a dRep.

### Impact
- An error is thrown during registration

![image](https://github.com/IntersectMBO/govtool/assets/49801844/6872ffc0-1a70-4f0a-b449-be500f87b34b)

**Comment by kneerose** [comment]
### Sentry Issue Details
- URL: [View Issue](https://intersect.sentry.io/issues/5497681367/?project=4507101527277568&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=16)
### Test Report
- URL: [Test Report](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/56/#behaviors/be0c801ac30023c8c33048413e6782a7/59ed5c790604800e)

**Comment by kneerose** [comment]
@pmbinapps  any updates on this?

**Comment by pmbinapps** [comment]
@kneerose assigning to @MSzalowski to clarify how to handle /register_drep when user is already a DRep.

**Comment by kneerose** [comment]
@jdyczka  any update on this?

**Comment by jdyczka** [comment]
@kneerose Yes, the same problem exists for retire_drep, register_direct_voter and retire_direct_voter. 
As far as how to handle this, instead of automatically redirecting the user, I would show a message with Go to dashboard button. The reason is that we have to fetch some data to know if the user can access this url and so for the automatic redirect scenario there is first a flash of the page with title and loader before the redirect happens.

**Comment by kneerose** [comment]
I see this message while navigating to the /register_drep page when the user is already a DRep. It seems that the issue has been fixed. What do you think, @MSzalowski  and @jdyczka ?

![image](https://github.com/user-attachments/assets/064b7947-22c7-4b9e-8916-8c692eb26a30)

CC: @bosko-m

**Comment by bosko-m** [comment]
Closing as per the comment above.
