### ISSUE TITLE
Treasury actions don't accept sanchonet addresses

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1187]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. try and create a treasury action
  2. paste in a sanchonet address in the receiving field
 

## Actual behavior
You get an error below field: "invalid Bech32 address"

## Expected behavior
GovTool accepts sanchonet addresses

## Loom video
https://www.loom.com/share/68116be06f4f4e8eaf1a8569571dc312?sid=b311bc36-5960-49dc-add4-ad031b701ff1

**Comment by pmbinapps** [comment]
@Ryun1 @MSzalowski what format of address should be there?:

Bech32 - like for  DRep ID (Pub DRep Key hash): eg: drep1x0a3rs0m5jz9mkgq6tc9580s23lkg3tufmsrt3xg5x7dx8djhcp - this one is accepted


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/430e1295-6437-418c-8398-3fcb35747efa)

or 
.getChangeAddress(): addr_test1qqcalzn9jwh6sw2dc6hx7j032u2vckwsd2tgpwa5nwkgmv8lrhej449gjdrmkupt8g04u8fgns5e6z2dfn3catkn6v2q3ud7y8

**Comment by Ryun1** [comment]
we could disallow hex encoded addresses,
on the grounds that it is less safe for users than using Bech
as the Bech32 prefix removes any potential for using a random hex encoded address

and you (users) really would not want to be doing a treasury withdrawal to the wrong address

**Comment by MSzalowski** [comment]
Make sense, if we agree on that, the issue could be closed after retests as it already handles the bech32 stake key addresses validation

**Comment by Ryun1** [comment]
> Make sense, if we agree on that

Im happy with this, seems reasonable

**Comment by pmbinapps** [comment]
OK NOW:
- state address accepted Bech32: stake_test1u

- GA Treasury type adding [here](https://jam.dev/c/eaef2af8-7b55-4ea6-9ef6-96cc98c288a3)
![Image](https://github.com/IntersectMBO/govtool/assets/82152577/9225af9f-e330-4966-ae1d-d0435cbedc5f)


- drep bech32 not accepted


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/84e2ae52-5f0b-44b8-a031-b562472c0d25)
