### ISSUE TITLE
[USERSNAP] New Navigation

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1192]
**Sender**: mister.pumpkin@microsoft.com
**Taken at**: https://sanchogov.tools/
**Fields**:
- Name of the idea or new feature: New Navigation
- Please summarize your idea or new feature: A better way to Navigate, and it&#39;s new
- Any additional details: Nope

**Browser**: Firefox 126 (macOS Catalina)
**Screen size**: 2560x1440
**[Open #39 in Usersnap](https://app.usersnap.com/l/feedback/51bed844-ca90-4d2f-8534-2f803d89fdba?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
This was a test from me. Closing.
