### ISSUE TITLE
Vote buttons on Voted for proposal should not be highligted

### ISSUE THREAD

**Issue by l-br1** [IntersectMBO/govtool#12]
_from Mike S._

**To reproduce:**

1. Connect wallet
2. become dRep
3. Go to Governance Actions page
4. Choose a proposal
5. Vote on it, and submit transaction
6. Wait for transaction to complete
7. Navigate back to the proposal detail page

Issue: The proposal doesn’t explicitly tell you how you voted. What it does is highlight one of the voting buttons. This, I assume is a proxy for how I’ve voted. However, it is not clear. Also, pre-selecting a radio button seems confusing to me.

![Image](https://github.com/IntersectMBO/govtool/assets/134690345/d07c5d4d-1ece-428f-af4c-7b9d6d14e29f)

**Proposed solution:**

Make it clear how the user voted on the proposal, and let the user decide which button to select if they want to change their vote.

Other things that this page is missing:

The date the vote was cast.

The voting power that is being applied at the present moment.

The voting power that was in force when the vote was cast.

**Environment**

[https://dev-sanchonet.govtool.byron.network](https://dev-sanchonet.govtool.byron.network/governance_actions) 

Wallet v 1.5.3

-----
### Comments
_Comment from Lorenzo Bruno 23 October 2023 at 12:53_

@Mike Susko we should bring in the pill we have in the summary card. Let’s leave this open and design the update after the beta testing opening.

**Comment by bosko-m** [comment]
Changing to the last known status before migrating to this project.
