### ISSUE TITLE
When submitting a DRep Registration, the transaction does not contain a vote delegation to self

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1211]
## Context & versions

- When registering as a DRep from any role (Direct Voter, No Role, Delegator)
- The transaction never contains a vote delegation to self

## Actual behavior

when i change from; Direct Voter -> DRep, all GovTool does is submit a DRep Update certificate
when I go from; retired DRep -> Direct Voter, GovTool does a DRep registration AND a Vote Delegation
when I go from; retired DRep -> DRep, GovTool does a DRep registration

when I go from; no role -> DRep, GovTool does a DRep registration AND is missing the delegation

## Expected behavior

- When moving from No Role -> DRep, the transaction SHOULD also contain a Vote Delegation to self.
- When moving from the Retired state, NO delegation is fine as it is expect that the user is still delegated to self

## Sketch of intended behaviour 

![image](https://github.com/IntersectMBO/govtool/assets/44342099/a339a60e-b770-44ff-8b19-b7588b046149)

**Comment by MSzalowski** [comment]
That is an awesome explanation of the flow, we'll do that

**Comment by pmbinapps** [comment]
Recheck when fixed:
Dashboard, DRep metadata validation: after Retirement, and when a user is a Direct Voter - DRep metadata are shown as missing #1254
