### ISSUE TITLE
Resolve CSP issue blocking Sentry requests in Traefik configuration

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#1218]
**User Story:** As a frontend developer, I want to fix the Content Security Policy (CSP) issue that is blocking Sentry requests in the Traefik configuration so that error tracking and monitoring using Sentry can function correctly.

**Summary:** The frontend service is encountering a CSP-related problem, where requests to send data to Sentry are being blocked by client-side security mechanisms, as indicated by the error message. This issue is stemming from the configuration of Traefik, a popular reverse proxy and load balancer, which is preventing these requests from reaching the Sentry platform. Resolving this issue is crucial to ensure that error logging and monitoring through Sentry can operate effectively and provide necessary insights for troubleshooting.

**Acceptance Criteria:**
1. Analyze the current CSP settings in Traefik to identify the specific rule or configuration that is blocking requests to Sentry.
2. Adjust the CSP configuration in Traefik to allow requests to the Sentry endpoint, specifically permitting POST requests to the Sentry API.
3. Test the updated configuration to confirm that Sentry requests are no longer blocked and that error data can be successfully transmitted to the Sentry platform.
4. Ensure that the CSP changes do not compromise the security of the frontend service and adhere to best practices for content security policies.
5. Document the modifications made to the Traefik configuration for future reference and maintainability.

**Comment by MSzalowski** [comment]
Reopening this issue as sentry is still being blocked

**Comment by bosko-m** [comment]
@MSzalowski @placek Is this still relevant?
