### ISSUE TITLE
GA - Treasury - unable to add Proposal with this type when bech32 receiving address is used

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1231]
Occurred being DRep and adding GA Treasury type with data like below:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b9ca7f56-4274-4741-8443-f6338d171e09)

json: https://raw.githubusercontent.com/pmbinapps/vva/main/tmp/Treasury.jsonld

After long time GA is still not visible

Jam recording [here](https://jam.dev/c/817c73af-42d6-494d-a0e4-04c14c73a515)

Screen recording: 

https://github.com/IntersectMBO/govtool/assets/82152577/965e554a-ca85-4451-ad52-d6fd2eb6bb86

**Comment by MSzalowski** [comment]
We can valdiate only against the bech32, which the address you provide - is. That means that forms doesn't catch this as a wrong address, but the transaction with such address cannot be submitted on chain. That bug is P1, maybe even P2 as it reflects the normal network behaviour

**Comment by MSzalowski** [comment]
Please have a look at this comment: https://github.com/IntersectMBO/govtool/issues/1187#issuecomment-2155010119

**Comment by pmbinapps** [comment]
OK NOW
