### ISSUE TITLE
[BUG] Missing testids on setup username 

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1232]
## Description:
Several components lack proper test IDs, impeding effective testing and automation

### Missing testIds
- setup-username-modal for setup username modal
- username-input for the username input field
- proceed-button for proceed with this username button

![Screenshot from 2024-06-11 10-45-25](https://github.com/IntersectMBO/govtool/assets/49801844/72c9b203-e21a-45a3-a457-e111f705d36c)

- no-change-button for No, Change button

![Screenshot from 2024-06-11 10-49-40](https://github.com/IntersectMBO/govtool/assets/49801844/fce7553d-032d-488a-ac42-8ad112b2d92d)

- close-button for close button

![Screenshot from 2024-06-11 10-50-54](https://github.com/IntersectMBO/govtool/assets/49801844/171a08ce-ef6c-4a02-b595-368450135b9d)

**Comment by teske00** [comment]
@NabinKawan  Test id's have been added to the modal for username, the package has been updated at[ [www](https://dev-sanchonet.govtool.byron.network/)](https://dev-sanchonet.govtool.byron.network/)

**Comment by kneerose** [comment]
Hello @teske00 

I've reviewed your recent updates regarding the missing test IDs, but some issues persist. Below is a detailed list of the required corrections:

**1. Username input**
```
<div class="MuiFormControl-root MuiFormControl-fullWidth MuiTextField-root css-1j5gcdd-MuiFormControl-root-MuiTextField-root" data-testid="username-input">
  <label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-sizeMedium MuiInputLabel-outlined MuiFormLabel-colorPrimary Mui-required MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-sizeMedium MuiInputLabel-outlined css-v59q3t-MuiFormLabel-root-MuiInputLabel-root" data-shrink="false" for=":ru7:" id=":ru7:-label">
    Username<span aria-hidden="true" class="MuiFormLabel-asterisk MuiInputLabel-asterisk css-wgai2y-MuiFormLabel-asterisk"> *</span>
  </label>
  <div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl css-4r00uj-MuiInputBase-root-MuiOutlinedInput-root">
    <input aria-invalid="false" id=":ru7:" required="" type="text" class="MuiInputBase-input MuiOutlinedInput-input css-1t8l2tu-MuiInputBase-input-MuiOutlinedInput-input" value="" data-dashlane-rid="76e9f078a1fb5e73" data-form-type="other">
    <fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-1d3z3hw-MuiOutlinedInput-notchedOutline">
      <legend class="css-yjsfm1"><span>Username *</span></legend>
    </fieldset>
  </div>
</div>

``` 
- The `data-testid` should be inside `<input>` tag instead of the `<div>` tag

**2. Proceed with this username**

![image](https://github.com/IntersectMBO/govtool/assets/49801844/67a9e827-7e03-4ca0-b99e-3f7ebc65ef5e)

- The "Proceed with this username" button is missing a testid. The test ID should be `data-testid="proceed-button"`.


**Note:**  Please ensure to add proper test IDs if you introduce any new components in the future. Additionally, please make these adjustments to ensure appropriate test IDs are in place.

**Comment by teske00** [comment]
@kneerose We have added a test id to the PDF package version 0.2.2 which is deployed on the govtool dev environment

**Comment by kneerose** [comment]
@teske00 , I've reviewed your recent updates regarding the missing test IDs. I noticed that you added an error message on invalid usernames. It looks great! However, please remember to add a testId to it.

![image](https://github.com/IntersectMBO/govtool/assets/49801844/a2c090ba-df29-4793-a228-fecc2f71500f)

### NOTE
- Please make sure to add proper test IDs if you introduce any new components in the future.

**Comment by teske00** [comment]
cc @vpaunovic

**Comment by teske00** [comment]
@kneerose It is deployed on dev, it can be tested

**Comment by kneerose** [comment]
I see the data-testid="username-error-text" attribute on the error message. As it is fixed, I am closing the issue.
