### ISSUE TITLE
[BUG] Missing testIds on Proposal Discussion 

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1233]
## Description:
Several components lack proper test IDs, impeding effective testing and automation

### Missing test ids 
- propose-a-governance-action-button for Propose a Governance Action
- search-input for search input field
- filter-button for filter button
- sort-button for sort button
- show-all-button for show all button
- proposal-${proposal_id}-card for individual proposal card
- proposal-${proposal_id}-share-button for individual proposal share button
- proposal-${proposal_id}-view-details for individual proposal  view details button
- proposal-${proposal_id}-comment-count for individual proposal total comments count 
- proposal-${proposal_id}-edit-button for the created proposal edit button
- proposal-${proposal_id}-title for individual proposal title

![Screenshot from 2024-06-11 11-52-14](https://github.com/IntersectMBO/govtool/assets/49801844/f1eb212f-4eb0-426e-938d-1633ff709762)

- info-radio for filtering by info type
- treasury-radio for filtering by treasury type
- reset-filters for reset filters button

![Screenshot from 2024-06-11 12-09-33](https://github.com/IntersectMBO/govtool/assets/49801844/583027cc-3494-49e0-b143-309de38838e4)

**Comment by bosko-m** [comment]
@vpaunovic @teske00  Is this in progress then?

**Comment by vpaunovic** [comment]
@bosko-m this is already done. Just, it is not yet in NPM package. Its in our repo on main branch. When we update our NPM package, and @MSzalowski update our PDF NPM package with that new version, it will be available there in current govtool.

**Comment by kneerose** [comment]
Hello @vpaunovic 
- I've reviewed your recent updates regarding the missing test IDs, but some issues persist. Below is a detailed list of the required corrections:

**1. Search Input**

```
<div class="MuiFormControl-root MuiFormControl-fullWidth MuiTextField-root css-3lfscr-MuiFormControl-root-MuiTextField-root" data-testid="search-input">
    <div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl MuiInputBase-adornedStart css-1q02obe-MuiInputBase-root-MuiOutlinedInput-root" data-dashlane-rid="77bdcd041ad7f2b3">
        <div class="MuiInputAdornment-root MuiInputAdornment-positionStart MuiInputAdornment-outlined MuiInputAdornment-sizeMedium css-ittuaa-MuiInputAdornment-root">
            <span class="notranslate">​</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#212A3D" viewBox="0 0 24 24" color="#212A3D">
                <path fill-rule="evenodd" d="M10 4a6 6 0 1 0 0 12 6 6 0 0 0 0-12m-8 6a8 8 0 1 1 14.32 4.906l5.387 5.387a1 1 0 0 1-1.414 1.414l-5.387-5.387A8 8 0 0 1 2 10" clip-rule="evenodd"></path>
            </svg>
        </div>
        <input aria-invalid="false" id="outlined-basic" placeholder="Search..." type="text" class="MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart css-1o9s3wi-MuiInputBase-input-MuiOutlinedInput-input" value="" data-dashlane-rid="4a893a91328c158d" data-form-type="other">
        <fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-1d3z3hw-MuiOutlinedInput-notchedOutline">
            <legend class="css-ihdtdm"><span class="notranslate">​</span></legend>
        </fieldset>
    </div>
</div>
``` 
The `data-testid` should be inside `<input>` tag instead of  the `<div>` tag

**2. Proposal card**
- Currently, the test ID for the proposal card is proposal-${proposal_id}. To get all proposal cards listed on the proposal discussion, using `data-testid="proposal-${proposalId}-card"` would be better as mentioned earlier in the ticket.

**3. Proposal Status**
- I see you have added the status of each proposal card as active or submitted for a vote. However, there is no test ID for the status element. It would be helpful to add `data-testid="proposal-${proposal_id}-status"`.

![image](https://github.com/IntersectMBO/govtool/assets/49801844/b44854bd-9292-4a93-89f3-ab3edc32e190)



**Note:** Please ensure to add proper test IDs if you introduce any new components in the future. Additionally, please make these adjustments to ensure appropriate test IDs are in place.

**Comment by kneerose** [comment]
@vpaunovic  I have created a separate ticket for all missing test IDs of the PDF [here](https://github.com/IntersectMBO/govtool/issues/1568). Therefore, I am closing this issue.

CC : @bosko-m
