### ISSUE TITLE
[BUG] Missing test ids on Create a governance action 

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1237]
## Description:
- Several components across various pages lack proper test IDs, impeding effective testing and automation.
- some of the test IDs are mentioned in (issue #1070)

### Missing test IDs

- show-all-button for show all
- draft-${draft_id}-card for each draft card
- draft-${draft_id}-start-editing for each draft start editing button

 ![Screenshot from 2024-06-11 13-27-30](https://github.com/IntersectMBO/govtool/assets/49801844/d94eda7c-acde-402c-a8ab-1b1665d912a3) 
 
 
- save-draft-button for save draft
![image](https://github.com/IntersectMBO/govtool/assets/49801844/79ab0fe9-84a4-4294-8f0d-f69b6cfb7f3a)

**Important**: Please ensure to add proper test IDs as defined on previous proposal submission flow

**Comment by bosko-m** [comment]
@vpaunovic @teske00  Is this in progress then?

**Comment by vpaunovic** [comment]
@bosko-m this is already done. Just, it is not yet in NPM package. Its in our repo on main branch. When we update our NPM package, and @MSzalowski update our PDF NPM package with that new version, it will be available there in current govtool.

**Comment by pmbinapps** [comment]
See only these ones on dev-sancho now:







![Image](https://github.com/IntersectMBO/govtool/assets/82152577/6d131678-b38b-4285-a13c-3144cca2da55)

A text: ||  data-testid: logo-button
VM658:26 A text: |Dashboard|  data-testid: dashboard-link
VM658:26 A text: |DRep Directory|  data-testid: drep-directory-link
VM658:26 A text: |Governance Actions|  data-testid: governance-actions-link
VM658:26 A text: |Proposal Discussion|  data-testid: proposal-discussion-link
VM658:26 A text: |Guides|  data-testid: guides-link
VM658:26 A text: |FAQs|  data-testid: faqs-link
VM658:26 IMG text: ||  data-testid: copy-button
VM658:26 P text: |drep1pzuxy8ukuvffjyyrdp8sxkzp3z8r57z5q0jtgxhwu3a22t9ppel|  data-testid: dRep-id-display
VM658:26 BUTTON text: |Disconnect|  data-testid: disconnect-button
VM658:26 A text: |Privacy policy|  data-testid: privacy-policy-footer-link
VM658:26 A text: |Term of service|  data-testid: term-of-service-footer-link
VM658:26 BUTTON text: |Help|  data-testid: help-footer-button
VM658:26 BUTTON text: |Feedback|  data-testid: feedback-footer-button
VM658:26 DIV text: |Wallet connected|  data-testid: alert-success
VM658:26 svg text: |undefined|  data-testid: SuccessOutlinedIcon
VM658:26 svg text: |undefined|  data-testid: CloseIcon

**Comment by vpaunovic** [comment]
@MSzalowski This should be assigned to you, right? Because everything in on GovTool

CC: @teske00 @bosko-m @ValMBO @m-i-k-e

**Comment by NabinKawan** [comment]
@vpaunovic Hi, Could you provide the version for PDF npm package?

**Comment by kneerose** [comment]
Hello @vpaunovic ,

I noticed that the proposal form, review page, and edit proposal forms still have missing test IDs. I mentioned this in issue (issue #1070 ), but it appears the changes have not yet been made. Here are the references for the missing test IDs
 
![Screenshot from 2024-06-19 15-20-30](https://github.com/IntersectMBO/govtool/assets/49801844/d57a6bed-ae66-4c7a-896e-ea599d21e9ec)
![Screenshot from 2024-06-19 15-22-19](https://github.com/IntersectMBO/govtool/assets/49801844/69db91d1-e72c-4ff7-914d-01c0a96497cb)
![Screenshot from 2024-06-19 15-24-21](https://github.com/IntersectMBO/govtool/assets/49801844/850c61b9-b1af-4bdd-975c-c9f6b8317b20)
![Screenshot from 2024-06-19 15-56-15](https://github.com/IntersectMBO/govtool/assets/49801844/7993c21a-ee05-43cb-93fe-68ef6b9acc08)
![Screenshot from 2024-06-19 15-56-41](https://github.com/IntersectMBO/govtool/assets/49801844/b6b30892-aba6-48b8-8ceb-cfec59aad8cd)
![Screenshot from 2024-06-19 16-11-33](https://github.com/IntersectMBO/govtool/assets/49801844/62ec4820-619e-47c9-bfff-1e59a920f81f)

**Comment by kneerose** [comment]
Hello @vpaunovic 
- I've reviewed your recent updates regarding the missing test IDs. The test IDs I mentioned above are still missing. Additionally, please look into the issue detailed [here](https://github.com/IntersectMBO/govtool/issues/1099) regarding the create proposal form validation. It currently accepts spaces as input, which needs to be addressed.

**Note:** Please ensure to add proper test IDs if you introduce any new components in the future. Additionally, please make these adjustments to ensure appropriate test IDs are in place.

**Comment by teske00** [comment]
@kneerose We have added a test id to the PDF package version 0.2.2 which is deployed on the govtool dev environment

**Comment by bosko-m** [comment]
@kneerose This is included in the latest package prepared yesterday so it should be verifiable soon.

**Comment by kneerose** [comment]
Hello @bosko-m 
- I've reviewed your recent updates regarding the missing test IDs in PDF version 0.2.2, but still some issues persist. Below is a detailed list of the required corrections:

**1. Title Input**

```
<div class="MuiFormControl-root MuiFormControl-fullWidth MuiTextField-root css-wb57ya-MuiFormControl-root-MuiTextField-root" data-testid="title-input">
    <label class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined MuiFormLabel-colorPrimary MuiFormLabel-filled Mui-required MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiInputLabel-sizeMedium MuiInputLabel-outlined css-1peu7hn-MuiFormLabel-root-MuiInputLabel-root" data-shrink="true" for=":r5pl:" id=":r5pl:-label">Title<span aria-hidden="true" class="MuiFormLabel-asterisk MuiInputLabel-asterisk css-wgai2y-MuiFormLabel-asterisk"> *</span></label>
    <div class="MuiInputBase-root MuiOutlinedInput-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl css-4r00uj-MuiInputBase-root-MuiOutlinedInput-root">
        <input aria-invalid="false" id=":r5pl:" required="" type="text" class="MuiInputBase-input MuiOutlinedInput-input css-1t8l2tu-MuiInputBase-input-MuiOutlinedInput-input" value=" " data-dashlane-rid="29d126c88d925c7b" data-form-type="other">
        <fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-1d3z3hw-MuiOutlinedInput-notchedOutline">
            <legend class="css-14lo706"><span>Title *</span></legend>
        </fieldset>
    </div>
</div>
```

- The `data-testid` attribute should be inside the `<input>` tag instead of the `<div>` tag.
- Similar issue exists for `abstract-input`, `motivation-input`, `rationale-input`, and `link-input` in both proposal creation and edit proposal sections.
- Please ensure to add the testId  to the `<input>` tag for input field

**2. Draft saved modal**

-  The test ID is not properly added. The button testid is set as `delete-proposal-yes-button`, but it is not a delete proposal yes button. Please add a proper test ID.
![image](https://github.com/IntersectMBO/govtool/assets/49801844/c6c30c98-1b34-4854-b3d8-33cdac6a9959)

#### Note 
- Ensure that proper test IDs are added if you introduce any new components in the future. Please make these adjustments to ensure appropriate test IDs are in place.

**Comment by teske00** [comment]
The package has not yet been imported into govtool, we will report here when it is. We have version 0.2.3

**Comment by bosko-m** [comment]
@teske00 Was this part of the last weeks release?

**Comment by vpaunovic** [comment]
@kneerose It can be tested on dev.

 CC: @bosko-m

**Comment by kneerose** [comment]
@vpaunovic  I recently noticed that the test ID for the governance action type dropdown select is placed incorrectly. The test ID should be added to the element where the actual select action is performed.

![image](https://github.com/IntersectMBO/govtool/assets/49801844/4cd3d27c-6056-4589-af67-76fccd285ef6)

**Comment by vpaunovic** [comment]
@kneerose You see it, on screenshot, it is right on Input component inside that div? That is the input, main component, that is div. We thought that you said that every testId needs to be on main component, not on divs wrapping etc.

**Comment by vpaunovic** [comment]
@kneerose I placed it now to be on that div that you have hovered on the screenshot. Does this needs to be with every dropdown, so I can check them and do them..?

**Comment by kneerose** [comment]
@vpaunovic  No, it is applicable only for these types of dropdowns. Fine for other dropdowns.

**Comment by kneerose** [comment]
@vpaunovic  can you look at this [comment](https://github.com/IntersectMBO/govtool/issues/1237#issuecomment-2202684443)?  I haven't seen any changes for No. 2 yet.

**Comment by vpaunovic** [comment]
@kneerose It will be in the new PDF package version that we will publish today and inform the guys from Byron so then can bump the PDF version in Govtool and you can test it.

**Comment by kneerose** [comment]
@vpaunovic , can you provide the version of the PDF package after it's published? So that I can test it locally.

**Comment by kneerose** [comment]
@vpaunovic I've located the missing test IDs mentioned above which are now visible in the test environments.
CC: @bosko-m

**Comment by bosko-m** [comment]
Thank you all, closing
