### ISSUE TITLE
[Bug] Incorrect labelling of governance action metadata field (About -> Abstract)

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1243]
## Context & versions

- CIP-108 defines a set of fields what should be attached to governance actions
- incorrect fields are shown in the governance action details

## Steps to reproduce

Go to governance action details page

## Actual behavior

- GovTool shows `About`

## Expected behavior

- GovTool should show `Abstract`

![image](https://github.com/IntersectMBO/govtool/assets/44342099/aa2e59bb-289b-4df7-b745-aaf34e41df05)

[here](https://staging.govtool.byron.network/connected/governance_actions/139aed2eada6b5ad5b9a29f52b696b8b1b8e2c55f6bc577f43f7bd04c0a764b3#0)

**Comment by pmbinapps** [comment]
OK NOW


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/1cc1e6eb-c0ae-4cc3-8027-2961c32eec52)



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/2a178f14-79d3-48c4-bdc4-3355d9f64404)
