### ISSUE TITLE
[Bug] CIP-108 metadata - markdown text styling not shown

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1244]
## Context & versions

- CIP-108 allows for metadata fields to contain basic markdown syntax, see [here](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0108#markdown-text-styling)
- Currently GovTool does not render this correctly

## Steps to reproduce

- Submit a governance action with markdown text styling supplied in a metadata field

## Actual behavior

- Markdown text styling is not rendered

## Expected behavior

- Markdown text styling is rendered

see [here](https://staging.govtool.byron.network/connected/governance_actions/139aed2eada6b5ad5b9a29f52b696b8b1b8e2c55f6bc577f43f7bd04c0a764b3#0)

![image](https://github.com/IntersectMBO/govtool/assets/44342099/26b504ff-b7bf-43d9-8195-14217513d271)

**Comment by pmbinapps** [comment]
@Sworzen1 just made try on dev, and I can not see any rendering of Markdown eg. on:  https://dev-sanchonet.govtool.byron.network/connected/governance_actions/055202ee88529fdbc5bd85ef80a6cb38265ac744eee22926b375ab72a9dd182d#0

Could you take if this is working?



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/6a170cc8-9ecb-419f-81d1-4c4afc46da55)

**Comment by Sworzen1** [comment]
I'm merge it now

**Comment by pmbinapps** [comment]
OK - markdown supported:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/906b9bf7-8e43-4e5e-ac4c-adc4bb079bea)

**Comment by pmbinapps** [comment]
OK NOW 
https://test-sanchonet.govtool.byron.network/connected/governance_actions/e77b011c7b834b3e87eb91ab5257158a75448765fd981036f66319edce93b953#0



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/2c13927a-205b-4f11-b791-065133930571)
