### ISSUE TITLE
When there is an error on DRep validation, the button to "Go to Edit Screen" goes to wrong screen

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1248]
## Context & versions
staging sanchonet Demos wallet

## Steps to reproduce

  1. Try and register as a DRep
  2. For some reason (this can be simulated) the external data does not match
  3. You see the error saying the External Data does not Match
  4. Click the "Go to Data Edit Screen"

## Actual behavior
The user is taken to this screen: 
<img width="606" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/47982552-f210-41be-aabf-180fe2320d77">

## Expected behavior
user should go to this screen:
<img width="615" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/a3ba3327-3a34-4655-825d-f14c13e88cc0">

See loom video at about 2:25 for this error.

https://www.loom.com/share/696c474dec6b4077a2ddb00c78296973?sid=810926d5-7e2f-4688-8aa5-58b4cd706825

**Comment by Sworzen1** [comment]
it should work, try again
