### ISSUE TITLE
View details takes me to explorer on GA

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1252]
## Context & versions
staging .sanchonet

## Steps to reproduce

  1. Be a direct voter
  2. Go to a treasury action
  3. Vote Yes on it
  4. Return to Ga homepage
  5. Click on "View Details" on the action that you voted on (says "in progress")

## Actual behavior
Link takes you to sanchonet explorer

## Expected behavior
User should be taken to details page of this particular GA

Loom: 
https://www.loom.com/share/8577f69262d840e4b1bebd3559659fed?sid=235d8e40-b461-4899-867c-cf1119de17d4

**Comment by m-i-k-e** [comment]
Note: this only happens in the "in progress" state.

**Comment by pmbinapps** [comment]
OK NOW - Jam [recording](https://jam.dev/c/c7b30751-4c28-4006-9831-8b3c3a7618d3)
