### ISSUE TITLE
Dashboard, DRep explorer, DRep details - DRep name appears beyond label

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1253]
To reproduce:
1. Register DRep with 80 chars long no space name
2. Go to Dashboard
3. Go to DRep explorer 
4. Go to DRep details

Results is as on image blow:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/81f17114-c3cb-40a2-a264-b820eae0b642)

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/ed134524-0d18-4d1a-a710-89d4a5eb01c7)

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/d7789fb5-45b0-4355-a9bd-363516131672)

**Comment by pmbinapps** [comment]
OK NOW - Jam [record](https://jam.dev/c/5a3ba223-8fbe-4440-87af-2d13433a3944)

**Comment by m-i-k-e** [comment]
If you put in a really long name - 80 characters, then you will generate a really long URL, and in this case, this failed because the url was over 128 characters long.

https://www.loom.com/share/9b3eeffcc06246ae95a6ce5236dcc4ba?sid=87cd9079-d02c-491f-9bc1-2a3691ff2023

![Uploading image.png…]()

**Comment by m-i-k-e** [comment]
@MSzalowski
