### ISSUE TITLE
Dashboard, DRep metadata validation: after Retirement, and when a user is a Direct Voter - DRep metadata are shown as missing

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1254]
To reproduce:

I scenario:
1. Register as Drep
2. Retire

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/897b2ea2-2688-4f70-ac1c-1495fc1cb733)

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/ff57c428-2fa9-403d-8701-a263ae208faa)

Compare with Jam [Recording](https://jam.dev/c/ff6f55f5-8244-44fc-b30a-b6d0d43e2ff5)

II Scenario:
Use two users
1. 1st one registers as Direct Voter
2. 2nd user browse DReps - when the first user card is show in title is show Data missing:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/2bbc48ba-1d73-42d3-87fb-6177d494f41c)

**Comment by MSzalowski** [comment]
I am looking on it

**Comment by pmbinapps** [comment]
OK on Dashboard 

NOT OK in details page reached with direct link. - still Data missing error:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/636a2010-11de-4e96-9195-5d9690b639b5)

**Comment by MSzalowski** [comment]
I would leave this as a known issue and pass it to staging, wdyt @m-i-k-e ?

**Comment by bosko-m** [comment]
@MSzalowski Is this related to CIP-119?

**Comment by MSzalowski** [comment]
It is related to CIP-119, we don't have the metadata validation standardized for the DReps yet
