### ISSUE TITLE
Dashboard shows delegation in two places, should be one, after becoming a DRep

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1257]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Register as a DRep, after being a delegator
  2. Look at Dashboard

## Actual behavior
Both the delegation cards and the DRep card show that I'm delegated to the same Drep - which is myself

## Expected behavior
The delegation card should not show any delegation information if I'm delegated to myself as a DRep. It should show delegation information if I'm delegated to a different DRep

<img width="1020" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/dc6d9640-8e93-419a-a905-bed23fabd9e8">

**Comment by m-i-k-e** [comment]
Made a Loom video for this: 

https://www.loom.com/share/6930e1319d4c4f24abf736f9a2d6b7f0?sid=838fb3c0-ef4c-482d-9a76-02403b8dba26

**Comment by m-i-k-e** [comment]
Loom video: 

https://www.loom.com/share/6930e1319d4c4f24abf736f9a2d6b7f0?sid=65da1894-b943-4232-9c77-7a1dfe1d91d6

**Comment by pmbinapps** [comment]
NOT OK after still delegation to previous DRep is shown. It changes after a time

1. Steps to reproduce
2. Register as a DRep, after being a delegator
3. Look at Dashboard -  Jam [recording](https://jam.dev/c/e7129129-1746-4c01-9441-206e8866e2a3)


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/eafe8934-007e-431a-aaae-ba440a367f64)

 After a while it changes to be OK


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/6cb20ae5-7ccc-4fe4-a6da-c6162c6abda9)

**Comment by MSzalowski** [comment]
That would be fixed by https://github.com/IntersectMBO/govtool/issues/1235. So far, I would treat this as a known issue and pass it to staging, is that ok @m-i-k-e

**Comment by m-i-k-e** [comment]
This looks good.

**Comment by bosko-m** [comment]
Can we close this one @m-i-k-e ?
