### ISSUE TITLE
After retiring as DRep, Dashboard incorrect

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1260]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Register as a DRep (your delegation comes to your DRep automatically)
  2. Retire as a DRep
  3. Wait for transaction to complete
  4. Look at Delegation panel on Dashboard

## Actual behavior
Says that I'm 'delegated to "Missing" DRep' - this is the DRep ID that has been retired

## Expected behavior
DRep panel should go back to it's default state

This is the loom video for this: 

https://www.loom.com/share/74a735fa3ec94dc298818a8fff23da95?sid=5243feea-ac0d-41d2-9ac3-299db4249545

**Comment by bosko-m** [comment]
@m-i-k-e @MSzalowski Lets clarify the timeline on this one tomorrow on the bug triage session. This shouldnt be considered a showstopper.

**Comment by MSzalowski** [comment]
We have already fix for that that I've done reviewing and can confirm that the fix is working

**Comment by bosko-m** [comment]
@MSzalowski Dev, Test, Staging?

**Comment by MSzalowski** [comment]
Dev, Test

**Comment by pmbinapps** [comment]
OK NOW:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/82615fcd-a7a6-4456-9361-137b8f954d03)

**Comment by m-i-k-e** [comment]
@bosko-m Has this been done? Can it be closed?

**Comment by bosko-m** [comment]
Tested on Preview, yes.
