### ISSUE TITLE
Set up a username

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1275]
## Context & versions
https://dev.gov.tools/proposal_discussion

## Steps to reproduce

  1. Click to propose a governance action
  2. Then a pop up message appears asking for a username
  3. Click Proceed with username

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/644aef44-e230-444d-b7ab-fe7fa347badb)

## Expected behavior

- The Popup is not accurate in width 
- Also there is no label under the field.  
- Crosscheck if distance from edges is correct
- Let's add a proper Subtext

**Comment by teske00** [comment]
@ValMBO The modal's width is scaled depending on the screen size according to the MUI standard. As for the input that does not have a label, this is the core MUI label. And in MUI there is no variant of the input with a label as in the design. What text should we add to the modal to clarify that actions require a username?

**Comment by m-i-k-e** [comment]
@ValMBO The text "Hey, setup your username" needs to be improved.
