### ISSUE TITLE
Footer not fixed to bottom of page

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1278]
## Context & versions
https://dev.gov.tools/proposal_discussion

## Steps to reproduce

  1. Click on search bar
  2. Add a word
  3. Nothing was identified
  4. Footer was not at bottom
  

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/2281007f-a796-4353-8e55-3ea37ea32a2a)

## Expected behavior
Footer remains at bottom of page.

**Comment by m-i-k-e** [comment]
I've changed this to a P0, as it doesn't function.

**Comment by vpaunovic** [comment]
@m-i-k-e It is old Npm package of pdf. Our package is still not updated to new version. We think we will do it today or tomorrow - as we already said today on daily.

**Comment by m-i-k-e** [comment]
@vpaunovic I am going through the bugs with @ValMBO. Can you please update the issue when it's pushed?
