### ISSUE TITLE
User not notified when their draft is saved

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1279]
## Context & versions
https://dev.gov.tools/proposal_discussion

## Steps to reproduce

  1. Click on save draft
  2. Nothing happens

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/9599d8c3-4d52-48fd-aca4-005977ebdadb)

## Expected behavior
User is notified that their draft is being saved, and can either safely leave the flow or return to it at a later time.

**Comment by m-i-k-e** [comment]
Please solve this flow so as not to lose the user.

**Comment by m-i-k-e** [comment]
I've changed the Priority to P0 because the user is stuck and they don't know if their draft is saved or not.
