### ISSUE TITLE
Colours vary from Gov Tool

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1280]
## Context & versions
https://dev.gov.tools/proposal_discussion

## Steps to reproduce

  1. Click on use an existing draft

## Actual behavior
Design of buttons, background, cards, etc vary quite a lot in colour from GovTool.

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/0d4784c3-2c16-4f51-9ea2-61072dca0b7a)

## Expected behavior
Design elements match GovTool.

**Comment by m-i-k-e** [comment]
CTAs like these should match the color of similar ones in GovTool: 

PDF: https://www.figma.com/design/239JKpjintphf2Go5NPipp/Proposal-discussion-Forum?node-id=966-123223&t=yGnYRc9NEBABmtB5-1

GovTool: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=8271-80546&t=pV7sEwa70lcq8C6W-1

**Comment by m-i-k-e** [comment]
The design of the entire page is awfully pink. Should match gov tool's colour palette as well.
