### ISSUE TITLE
Missing references in governance action metadata passes the validation

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1282]
## Context & versions

sancho-v1.0.5-alpha

## Steps to reproduce
1. Prepare the governance action without the `references`
2. Submit such a governance action with a valid hash

## Actual behavior

Validation passes
## Expected behavior

Validation should fail

**Comment by pmbinapps** [comment]
OK : GA Info proposal with removed "references" key in json file is passing NOT validation

GA Proposal: https://dev-sanchonet.govtool.byron.network/connected/proposal_pillar/proposal_discussion/302
Used Json file: https://raw.githubusercontent.com/pmbinapps/vva/main/tmp/data_info.jsonld

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/9dcfb01f-f7fc-4105-b888-7673957af0ba)


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/10fa1725-ecb7-4429-8e40-c1ce7ec01407)
