### ISSUE TITLE
The word "GUIDES" across pages

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1298]
## Context & versions
https://dev.gov.tools/proposal_discussion

## Steps to reproduce

1. Click on save draft

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/d115f7ac-d51a-4f8c-a35c-19477995d876)

## Expected behavior

The word GUIDES on the top left, should not be there.

**Comment by vpaunovic** [comment]
@ValMBO I think this is old or? We do not have that, it is fixed, right @teske00 ?
