### ISSUE TITLE
DRep explorer - being DRep I can not find myself on list

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1303]
To reproduce:
1. Become DRep
2. Try to find yourself

https://jam.dev/c/2735a030-4be2-4f92-996d-86b555140444

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/f82c1fee-b55c-42c0-ad01-a703567b263f)

**Comment by Sworzen1** [comment]
You cant see DRep, you are delegeting to.

**Comment by MSzalowski** [comment]
@m-i-k-e Should we display such DRep on a DRep list? As @Sworzen1 said this DRep has a delegation to themselves as described [here](https://github.com/IntersectMBO/govtool/issues/1211) and the delegation to themselves is not displayed (delegation is still part of the drep list data). Of course we can handle all the edge cases, but I would strongly not recommend this without the CIP-119 support as the complexity around Direct Voters and DReps is now extremely high and highly likely to have a bugs

**Comment by bosko-m** [comment]
@MSzalowski Are you suggesting we should address this with CIP-119?

**Comment by m-i-k-e** [comment]
@MSzalowski To answer your question: " Should we display such DRep on a DRep list?": Yes. There are designs in Figma for the DRep that you are delegating to, and also if you are your 'own' DRep.
