### ISSUE TITLE
[BUG] White screen appear on dashboard after first wallet connect

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1305]
## Context & versions
- A white screen appears on the dashboard after connecting to the wallet first time.

## Steps to reproduce
- Clear local storage on the browser console
- Connect injected wallets
- Wait for 5 seconds and Observe the dashboard

## Actual behaviour
![image](https://github.com/IntersectMBO/govtool/assets/49801844/fd293341-20b5-467e-b9c6-4f59e4d93f09)

## Expected behaviour
![image](https://github.com/IntersectMBO/govtool/assets/49801844/c3273d2e-217c-4ca1-bc65-87340933db6f)

**Comment by pmbinapps** [comment]
OK for demos and eternl wallets

**Comment by MSzalowski** [comment]
As @pmbinapps reported there is still an issue when `change vote` button displays - the crash happens randomly

**Comment by kneerose** [comment]
I am closing this issue as it is no longer reproducible.
