### ISSUE TITLE
DRep explorer - As not connected user - click 'Connect to Delegate' after connection opens dashboard instead DRep explorer and Delegation

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1312]
To reproduce:

1. Go to test-sancho
2. Go to DRep explorer
3. Find a DRep with 'Connect to delegate' button 
4. Click it - Dashboard is opened instead of DRep explorer and initiating delegation

https://jam.dev/c/6a724885-5e77-4248-8702-ff3df9293d64

**Comment by jdyczka** [comment]
Solved here #1611
