### ISSUE TITLE
List elements are cut due to overflow hidden on a `.slick-list`

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1314]
## Context & versions

dev sancho

## Steps to reproduce
1. Go to Proposal Discussion
2. Check the righ side of the list

## Actual behavior

The list is cut (no shadow visible) right after the `.slick-list` container.

![slick-overflow-hidden](https://github.com/IntersectMBO/govtool/assets/24510246/594d553f-64d8-4e3a-ac73-690144073af0)

## Expected behavior

Shadow is displayed correctly.

**Comment by Ryun1** [comment]
@teske00 this done?

**Comment by teske00** [comment]
@Ryun1 Yes, it's an old issue. It's done
