### ISSUE TITLE
[USERSNAP] Test Issue from beta

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1318]
**Sender**: michal.szalowski@binarapps.com
**Taken at**: https://sanchogov.tools/dashboard
**Fields**:
- Add a comment: Test Issue from beta

**Browser**: Chrome 126 (Linux)
**Screen size**: 3077x1620
**[Open #54 in Usersnap](https://app.usersnap.com/l/feedback/ba122cac-c528-4bc0-832c-53b1ccf3f24b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by MSzalowski** [comment]
Closing as this was the usersnap beta connection test
