### ISSUE TITLE
Group the same sentry issues (eg.: wallet)

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1326]
### Why

To provide better view of the same errors that differs only by some body.

### What

Provide tag for grouping the sentry events

### How

-

**Comment by pmbinapps** [comment]
TBC:Unable to find tag wallet in current govtool.sentry:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/eea77947-7610-4853-b291-359e05209ad6)

**Comment by pmbinapps** [comment]
Wallet-action tag appeared with recent issues:



![Image](https://github.com/user-attachments/assets/0b53aedf-a17c-4b43-9724-86b1d51a7975)
