### ISSUE TITLE
What should happened when user doesnt have registered and unregistered stake keys

### ISSUE THREAD

**Issue by Sworzen1** [IntersectMBO/govtool#1329]
## Steps to reproduce
1. Create empty wallet on Eternl
2. Try to connect to GovTool

## Actual behavior
Redirect to choose stake key panel and display empty list.

## Expected behavior
What should happened ?

**Comment by Ryun1** [comment]
I think this is an eternl bug

eternl wallet doesnt show any stake keys via CIP95 endpoints, can be checked via https://ryun1.github.io/cip95-cardano-wallet-connector/

**Comment by Sworzen1** [comment]
ok, I would like to know how GovTool should behave in this case.

**Comment by Ryun1** [comment]
What do you think GovTool should do? 😆

**Comment by Sworzen1** [comment]
now we display empty choose stake key panel :D. Its ok ?
![Uploading Zrzut ekranu 2024-06-18 o 20.26.08.png…]()

**Comment by Sworzen1** [comment]
IMO, we can display modal, which inform a user, that he cannot proceed because he does not have the keys.

**Comment by Ryun1** [comment]
To be honest, I think this is a wallet error 
this behaviour is unexpected 
I will message Eternl

**Comment by Sworzen1** [comment]
thank you
