### ISSUE TITLE
Invalid api-key error log on sentry 

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/govtool#1335]
## Context & versions
deployment: https://govtool.cardanoapi.io/ 

## Steps to reproduce
Each page load on https://govtool.cardanoapi.io/ triggers a  sentry bug report with `missing api-key` message

## Expected behavior
Google Tag Manager api-key should be properly set on test stack deployment

### ToDo
 - [x] Update test stack deployment script to make sue of api-key available in GitHub secrets.
 - [ ] Re-deploy the test-stack directly from dev

**Comment by Ryun1** [comment]
I believe this has stopped happening
