### ISSUE TITLE
Make it easy to share governance action IDs

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/govtool#134]
### Why

Currently governance actions in GovTool are truncated and people using the app cannot see the full governance action ID or copy it. This makes it difficult to share, or search for a specific governance action. This is especially true cross platform e.g. for users wanting to search for a governance action on the CLI.

### What

Where the governance action is displayed in truncated form, it should at least be copy-able, if not extendable and copy-able.

**Comment by Ryun1** [comment]
very old, lets close
