### ISSUE TITLE
[BUG] Missing Navbar and Proposal Discussion navigation link on Disconnected State

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1341]
## Context & versions
- When the application is in a disconnected state, the "Proposal Discussion" page should be accessible via the navbar, similar to how the "DRep Directory" page is.
- The "Proposal Discussion" page should include a navbar in the disconnected state, just like the "DRep Directory" page.

## Actual behaviour
- The "Proposal Discussion" page is not available on the navbar in the disconnected state.

![Screenshot from 2024-06-19 16-35-28](https://github.com/IntersectMBO/govtool/assets/49801844/36310958-b03a-44a8-9300-459e9eaec8e6)

- The "Proposal Discussion" page does not include a navbar when in the disconnected state.

![Screenshot from 2024-06-19 16-35-48](https://github.com/IntersectMBO/govtool/assets/49801844/03413238-3e06-4515-82bf-4d8e6457668f)

## Expected behaviour
- The "Proposal Discussion" page should be available on the navbar in the disconnected state.
- The "Proposal Discussion" page should include a navbar in the disconnected state, similar to the "DRep Directory" page.
![image](https://github.com/IntersectMBO/govtool/assets/49801844/0477ae4a-eb45-4f12-8ddc-c52366b6f1be)

**Comment by MSzalowski** [comment]
@m-i-k-e Should we display proposal discussion page on the disconnected state?

**Comment by kneerose** [comment]
I can see the navbar on the proposal discussion page in the disconnected state, and the `proposal` link on the navbar. Therefore, I am closing this ticket.
