### ISSUE TITLE
Guides and FAQ

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1346]
## Context & versions
Chrome - https://dev-sanchonet.govtool.byron.network/

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/998d46e7-0e3d-440b-8a06-948354151d7c)

## Expected behavior
Guides and FAQ should be moved from the top to the footer and pinned them

**Comment by vpaunovic** [comment]
@ValMBOThis is not a pdf, this is

**Comment by MSzalowski** [comment]
As @vpaunovic said this is GovTool header and footer, and in GovTool header design we have such links - [ref](https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?node-id=8063-51057&t=e4KIWY2C9e2aPxET-4)

@m-i-k-e Should we remove them?

**Comment by l-br1** [comment]
so 'dashboard' I think it's a mistake in the new design coming from the design system. Dashboard should only be visible when your wallet is connected, in the previous version we had 'home' on the landing page and then dashboard once logged in.

Now that we are adding Proposals list we should add Guides and FAQs to the footer before login (they can stay where they are post wallet connect) 

We need to document this in proposal discussion and govtool figma

**Comment by bosko-m** [comment]
@l-br1 Who can change these in figma?
