### ISSUE TITLE
Add "Connect to delegate"

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1348]
## Context & versions

https://dev-sanchonet.govtool.byron.network/

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/2584cc50-1c58-408c-89bd-38afdfda4a96)

## Expected behavior
Change "View DRep Directory" for **"Connect to delegate"**

**Comment by vpaunovic** [comment]
@ValMBO This is also on GovTool side not PDF

**Comment by teske00** [comment]
@MSzalowski

**Comment by MSzalowski** [comment]
And in GovTool side it is designed to display `View DRep Directory` - [source](https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?node-id=8063-50883&t=e4KIWY2C9e2aPxET-4)

@m-i-k-e Should we change that?

**Comment by bosko-m** [comment]
@l-br1 Think that this should have the same principle as with any other card, so if you dont have your wallet connected, you should have `Connect to Delegate` instead of `View DRep Directory`, do you agree? If so, please update the figma file.
