### ISSUE TITLE
Change "Proposal Discussion"

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1349]
## Context & versions

https://dev-sanchonet.govtool.byron.network/connected/proposal_pillar/proposal_discussion

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/049bf960-ea66-4feb-b323-40a5cbe16d46)

## Expected behavior

Change "Proposal Discussion" for "Proposals"

**Comment by vpaunovic** [comment]
@ValMBO This is on GovTool side, not PDF 

cc @teske00

**Comment by teske00** [comment]
Yes, this is at the govtool level cc @MSzalowski

**Comment by pmbinapps** [comment]
OK:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/6b58fb00-a161-4230-a812-880314cd87ad)
