### ISSUE TITLE
Governance actions need a title

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/govtool#135]
### Why

Currently when looking at the Governance Actions page, all of the governance actions look indistinguishable from one another. This makes it almost impossible for DReps to find a governance action of interest.

### What

Governance actions should have a title which comes from their metadata. This title should be displayed on the Governance Actions page so that people can distinguish between them and search for them.

**Comment by Ryun1** [comment]
very old, lets close
