### ISSUE TITLE
Adjust the contrast on "Active Status"

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1350]
## Context & versions

https://dev-sanchonet.govtool.byron.network/connected/proposal_pillar/proposal_discussion

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/41a89be7-7cea-4fe9-985a-f73370f594ab)

## Expected behavior
Adjust the contrast on "Active Status"

**Comment by vpaunovic** [comment]
@ValMBO This will be in new pdf npm package when we bump the version :)

**Comment by bosko-m** [comment]
Verified on Sancho, closing.
