### ISSUE TITLE
thumbs up/down

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1352]
## Context & versions

https://dev-sanchonet.govtool.byron.network/proposal_pillar/proposal_discussion/291

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/62ead635-6ebd-403a-aec9-b8bb73e620be)

## Expected behavior

Add an info icon prompting the user to connect their wallet if they want to add thumbs up/down without connecting their wallet.

**Comment by bosko-m** [comment]
Verified on Sancho, closing.
