### ISSUE TITLE
Max length of comments box

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1353]
## Context & versions

https://dev-sanchonet.govtool.byron.network/proposal_pillar/proposal_discussion/291

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/0e4757e9-2891-47a1-a334-f0fa658b321a)

## Expected behavior

Add a max length of comments box

**Comment by vpaunovic** [comment]
@ValMBO This is already done but when we do other things then it will be in new PDF npm package version
