### ISSUE TITLE
User get stack

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1355]
## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/fcc7d761-a3f0-4976-b935-d4f94e181c8b)

**Comment by vpaunovic** [comment]
@ValMBO What is context of this issue, it says just the user gets stuck :)

**Comment by teske00** [comment]
@vpaunovic @ValMBO @MSzalowski The problem here is when we are on the PDF page and we disconnect the wallet, I think. Maybe @MSzalowski  should check because it seems that there is no handling of this page in the case of a disconnected wallet

**Comment by pmbinapps** [comment]
OK: When click Disconnect - landing page is shown and a reload of page occurs allowing to Connect again

Jam recording [here](https://jam.dev/c/a0afeb7e-bc8e-49c2-a777-747e95166904)
