### ISSUE TITLE
Gov Tool Freezes on initial submission of proposal

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1357]
## Context & versions
sanchonet staging demos wallet

## Steps to reproduce
<!--
  1. Click "Propose Governace Action" from card on homepage
  2. You will see modal asking to enter a name
  3. Enter a name

## Actual behavior
Govtool freezes

## Expected behavior
Next step in creating proposal

**Comment by MSzalowski** [comment]
I'll do the investigation around this topic, but it would be nice to have more details of the scenario or any other dependencies

**Comment by pmbinapps** [comment]
Could not reproduce up to know..

**Comment by pmbinapps** [comment]
@m-i-k-e could you attach link to json file you used. We could retry with exact data you used.

**Comment by bosko-m** [comment]
Closing as not reproducible.
