### ISSUE TITLE
Add the username

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1361]
## Context & versions

https://dev-sanchonet.govtool.byron.network/dashboard

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/4a0e5527-dc25-4e7a-96c2-2f5c4506fb23)

## Expected behavior

Add the username on the bottom left, just above the Wallet connection

**Comment by vpaunovic** [comment]
@ValMBO @teske00 How we will do this because it is not on PDF side, its GovTool sidebar?

**Comment by MSzalowski** [comment]
It is govtool sidebar, we can provide to the app context username property where we could set and display in the connected wallet card

**Comment by bosko-m** [comment]
@ValMBO This sounds fine to me, what do you think?

**Comment by bosko-m** [comment]
Removing the milestone and adding to Community backlog.
