### ISSUE TITLE
Text styling -  Proposals

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1364]
## Context & versions

https://dev-sanchonet.govtool.byron.network/connected/proposal_pillar/proposal_discussion

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/14f4dd2a-5ee8-45da-b5c1-79cb72fd2f92)

## Expected behavior

Add the option for text styling when filling out the text field. This should allow users to customize their text with various formatting options, such as bold, italics, underlining, bullet points, and numbered lists, to enhance the clarity and presentation of their input.

**Comment by vpaunovic** [comment]
@teske00 With this included, then this is not regular textfield or textarea, its rich text, its more complex there right?

cc @ValMBO

**Comment by ValMBO** [comment]
@vpaunovic This is a P2 and a nice-to-have feature. Don’t worry if it’s too complex; we can add it to the backlog for consideration after the release.

**Comment by vpaunovic** [comment]
@teske00 can proove me wrong, but i think we already did this and it will be available in new bersion

**Comment by ValMBO** [comment]
Fantastic!

**Comment by teske00** [comment]
Yes, we added react-markdown (https://www.npmjs.com/package/react-markdown/v/8.0.6) as it was in govtool
