### ISSUE TITLE
Navigating to PDF asks for sign in

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1375]
## Context & versions
staging + demos 1.8.1

## Steps to reproduce

  1. Connect to Govtool with an account that has not previously used PDF
  2. Click "Proposal Discussion" on the menu
# Loom
https://www.loom.com/share/6d18c62fedb24f0ba3113dedc19c14f5?sid=c68db8a7-9482-417d-8cc0-a3838e5cd9ce

## Actual behavior
I am asked to sign with my wallet

## Expected behavior
No wallet interaction, as I've already connected my wallet

**Comment by bosko-m** [comment]
As previously agreed, upon visiting PDF for the first time user will be asked to verify identity by signing the transaction which is different from connecting with the wallet.
Usage of username platform wide will be discussed further.
Closing.
