### ISSUE TITLE
No info on clicking 'i' on PDF

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1377]
## Steps to reproduce

  1. Be on PDF home page
  2. click the 'i' next to date

## Actual behavior
Nothing happens

## Expected behavior
see an info popup

**Comment by vpaunovic** [comment]
@m-i-k-e This will also be in the next npm version of pdf package. Already fixed it in meantime.

CC: @ValMBO @teske00

**Comment by bosko-m** [comment]
Verified on Sancho, closing.
