### ISSUE TITLE
Cancelling wallet signing on pdf leaves user uninformed

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1378]
## Context & versions
staging sanchonet

## Steps to reproduce

  1. Have wallet connected but not yet created a username on PDF
  2. Go to PDF page. If asked to sign, cancel
  3. Click on a proposal
  4. Wallet pops up, cancel signing
  5. Click on comments or anything

## Actual behavior
User cannot participate and is given no idea of why, and does not know their state re: GovTool

## Expected behavior
User state is handled with the user in mind, and proper UX is created so as to inform users how to recover from errors.

This is breaking some usability heuristics: 

- (1) Visibility of System Status
- (3) User control and Freedom
- (9) Recognise, Diagnose and recover from Errors

Heruistics attached for reference

![usability heuristics](https://github.com/IntersectMBO/govtool/assets/965789/0794aa69-9123-4c77-ab11-a1ffa2330899)

**Comment by bosko-m** [comment]
Closing as obsolete due to new screen being introduced to connect the wallet upon first visit to PDF page.
