### ISSUE TITLE
Pdf asking me to submit someone else's proposal

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1379]
## Context & versions
staging sanchonet

## Steps to reproduce

  1. have connected wallet (to govtool)
  2. go to pdf page
  3. do not sign in with wallet (cancel)
  4. Click on a proposal written by a different user than myself

## Actual behavior
PDF asks me at the top of the screen if I want to submit this proposal

## Expected behavior
I should not be asked as this is not my proposal

**Comment by m-i-k-e** [comment]
Definitely a P0

**Comment by vpaunovic** [comment]
@m-i-k-e We will publish fix in next npm version od pdf package. We fixed this in meantime :)
