### ISSUE TITLE
Author of proposal should be labelled on PDF home page

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1380]
## Context & versions
staging . sancho

## Steps to reproduce
  1. Go to PDF homepage with wallet and already have a username
  2. Look at list and try and determine author

## Actual behavior
I can't tell who the author is, as it's not labelled. I took the name there to be the name of a commenter (as it had a weird format)

## Expected behavior
I can clearly tell who the author is

**Comment by vpaunovic** [comment]
@m-i-k-e It says it on top of that card, the username of the user who made the proposal. (image example: VukasinTest is the user)

CC: @ValMBO @teske00 

<img width="256" alt="image" src="https://github.com/IntersectMBO/govtool/assets/98397262/22896c5b-def4-4110-ad23-5bd9c16c2fff">

**Comment by bosko-m** [comment]
Im closing this with acceptance of @vpaunovic comment above.
