### ISSUE TITLE
User is not shown their vote in poll

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1385]
## Context & versions
staging.sanch0

## Steps to reproduce

  1. Go to a proposal
  2. Vote on the "Yes or No" poll
  3. Look at the poll element
 
<img width="1015" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/6ea1f2ef-6fcd-4b09-a9dd-09c3f3834108">

## Actual behavior
User cannot tell how they voted

## Expected behavior
User should see how they voted.

**Comment by vpaunovic** [comment]
@m-i-k-e You voted for Yes, it is bolded with Primary color, right?

**Comment by bosko-m** [comment]
I agree with @vpaunovic comment, closing.
