### ISSUE TITLE
[BUG] Clearing Name Field on Edit dRep Form Causes It to Reappear and Adds Extra Link Input

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1389]
## Context & versions
- When a user clears the name field on the edit dRep form, the name reappears, and two link input fields become visible after clicking the "Add a link" button at First.

## Steps to reproduce
- Register as a Drep
- Navigate to edit dRep page
- Click the "Add a link" button.
- Clear the name field

## Expected Behavior:

- The name field should remain clear.
- Only one link input field should be visible after clicking "Add a link."

## Actual Behavior:

- The name field reappears after being cleared.
- Two link input fields become visible after clicking "Add a link" for the first time.

## Video Demonstration:
https://github.com/IntersectMBO/govtool/assets/49801844/3f27e647-9b85-4687-bc06-b7311f8976c2

**Comment by pmbinapps** [comment]
OK NOW:

https://jam.dev/c/58b382e3-5627-4c5f-9d6f-89510a7f3f39
