### ISSUE TITLE
It should be more obvious to DReps how they get to vote 

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/govtool#139]
### Why

Currently when on the dashboard DReps see a widget in the sidebar that says "Governance Actions", and it's not obvious to people who are voting on the outcome of governance actions that navigating to the Governance Actions Page will navigate them towards a situation where they can vote. 

### What

Change the text in the sidebar to "Governance Actions and Voting"

**Comment by Ryun1** [comment]
very old, lets close
