### ISSUE TITLE
Redirect to Propose page

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1413]
## Context & versions

https://dev-sanchonet.govtool.byron.network/dashboard

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/ae1911c5-50a5-46a2-b34b-fb1d01aae934)

## Expected behavior

When user click on "PROPOSE" it should be redirected to the Propose page

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/c307d95c-3a35-47e2-9836-aec6706aaf8a)

**Comment by teske00** [comment]
@ValMBO This is a little complicated to implement at the moment, it is possible, but when we want to create a proposal, we have the first step with information about GA when we do not have a DRAFT or if we have a draft, we have a list of drafts that we can build on. Does this perhaps present a problem that in case we have drafts, we skip a step with them like this?

**Comment by teske00** [comment]
@ValMBO What is the status of this task, with the addition of the wallet verification screen, it is not possible to redirect here, because the verification screen will have priority

**Comment by bosko-m** [comment]
@teske00 @ValMBO Here are my observations:

1. **Propose** button points to the wrong route - `/proposal_pillar/proposal_discussion`
2. If you try the same from proposal discussion page it points to this one - `/connected/proposal_pillar/proposal_discussion`
3. In the case you already verified yourself (by visiting all proposals page) you should be able to jump to the correct link
4. In the case you didnt verify yourself, can we present the verification screen and then redirect to creating the proposal page like in 2 above upon successful verification?

**Comment by teske00** [comment]
@bosko-m @akruk93 @jdyczka After this latest version is imported into govtool, you need to set up a redirect by clicking this button to "/proposal_discussion/propose"

![image (21)](https://github.com/IntersectMBO/govtool/assets/63746943/a41c4059-cac5-4b95-b33e-5dbdcf95d71b)

**Comment by vpaunovic** [comment]
@kneerose It can be tested on dev with new version of pdf now.

 CC: @bosko-m

**Comment by kneerose** [comment]
@vpaunovic 

I have tested this on the dev environment. When my wallet has more than 50K ADA, I can navigate the proposal creation step without issues. However, if my wallet balance is below 50K ADA, clicking the "Propose" button on the dashboard triggers an "insufficient balance" popup. Please look into this issue: [Issue #1428](https://github.com/IntersectMBO/govtool/issues/1428).

CC: @bosko-m

**Comment by teske00** [comment]
In fact, the check should be removed, we do not submit that proposal to the chain, but only create it in our database
