### ISSUE TITLE
Supporting text

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1414]
## Context & versions
https://dev-sanchonet.govtool.byron.network/proposal_pillar/proposal_discussion/303

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/ac23b680-3658-45c6-9ba4-d0a627bcb9ff)

## Expected behavior

Delete the text "Supporting text"

**Comment by bosko-m** [comment]
Verified on staging and Sancho, closing.
