### ISSUE TITLE
Sort icon

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1416]
## Context & versions

https://dev-sanchonet.govtool.byron.network/proposal_pillar/proposal_discussion/301

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/637bc93a-5702-43b6-a2fc-f8b87bb0d84d)

## Expected behavior

The sorted icon should order by the most recent proposal.

**Comment by teske00** [comment]
@ValMBO Currently, it is the default sorting, and when the icon is clicked, it is sorted from the oldest, and when we click again, from the newest. Was it expected to be that way?
