### ISSUE TITLE
Auth of data

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1421]
## Context & versions

https://dev-sanchonet.govtool.byron.network/proposal_pillar/proposal_discussion/304

## Actual behavior

Authorisation data is requested before doing any action on PDF

## Expected behavior
Data authorization should be requested only once, and it should cover submitting/editing proposals, adding comments, and creating polls.
Therefore if a user have already submitted a proposal shouldn't be requested to auth the data AGAIN if he wants to add a comment.

**Comment by teske00** [comment]
@ValMBO  I wanted to ask about this, the situation regarding the editing and deletion of the proposal. That would mean that we have to show these options to everyone at every moment, which I don't know how good it is.

![image](https://github.com/IntersectMBO/govtool/assets/63746943/717c21c6-0865-4b3b-aa8a-b8f9db65d368)

**Comment by teske00** [comment]
Because it can be a situation, you click edit proposal, the user logs in and nothing happens, but everything disappears because that proposal is not from that user.

**Comment by teske00** [comment]
And at the same time it must always be visible. Perhaps we should analyze in more detail what is the best thing to do here. Because I had moments when I wanted to edit a proposal, and in order to log in, I had to do some action, for example to post a comment, and only then can I see the edit for my proposal

**Comment by ValMBO** [comment]
Okay, but I believe the main issue is that the Edit and Delete options should only be visible to authors of proposals. Is there a way to address this?

**Comment by teske00** [comment]
The only way we know someone is the author is if the user is logged in. It's a dependency that I don't know how we can solve here. That's why I had the idea that there should be a button that directly says log me in, rather than triggering everything through actions.

**Comment by ValMBO** [comment]
Ohh I understand, okey so let me ask Lorenzo.

**Comment by teske00** [comment]
@ValMBO @bosko-m I think this task is no longer valid because we solved these problems by adding an additional screen for wallet verification

**Comment by bosko-m** [comment]
True @teske00 , closing.
