### ISSUE TITLE
[BUG] Inconsistent Proposal Creation: Dashboard Requires Minimum Balance, Proposal Discussion Page Does Not

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1428]
## Context & versions
- Attempting to create a proposal from the dashboard results in an error due to insufficient balance, while proposing from the discussion page allows creation with a zero balance.

## Steps to reproduce
- Connect a compatible wallet with less than 50000 Ada.
- Attempt to propose a governance action from the dashboard.
- Observe the error message indicating insufficient balance.

## Actual behaviour
- When trying to propose from the dashboard, an error is encountered due to insufficient balance, as shown in the provided screenshot.

![image](https://github.com/IntersectMBO/govtool/assets/49801844/5b5a4013-ef2e-4897-bd3d-dc5c16894039)

## Expected behaviour
- Creating a proposal from the dashboard should not require a sufficient wallet balance since it doesn't involve an immediate transaction

### Questions
- Shouldn't it redirect me to this page when attempting to propose a governance action from the dashboard?

![image](https://github.com/IntersectMBO/govtool/assets/49801844/a7a65315-b6f6-44f0-97e6-6b42fde26b2e)

**Comment by kneerose** [comment]
I have tested this on both the test and dev environments, and it no longer reproduces.
This issue can be closed now.
CC: @bosko-m

**Comment by bosko-m** [comment]
Closing with the comment above.
