### ISSUE TITLE
Add a new log in section

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1430]
![Image](https://github.com/IntersectMBO/govtool/assets/158469375/a0905390-2c08-44fc-9beb-81f031679886)

Let;s change the second sentence for this: 

"Please verify your identity using your wallet."

And then on the blue button: " Verify your identity"

**Comment by teske00** [comment]
@ValMBO @l-br1  What do you think, should we leave this background to be like govtool, because the header on govtool is not white, or should we set the PDF to be white?

![image](https://github.com/IntersectMBO/govtool/assets/63746943/477fdbe2-7e92-459b-a31a-7a8aeb2e0149)
