### ISSUE TITLE
[GovTool + PDF] Handle disconnected state of proposals

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1431]
## Steps to reproduce
1. On home page
2. Proposal card have a button labeled: `Connect to propose` - should be `View proposals`

1. On proposals page
2. User disconnects the wallet
3. User is redirected to home

## Actual behavior

1. Proposal card on home have button `Connect to propose`
2. When user disconnects the wallet on proposals list, they are being redirected to home page

## Expected behavior

1. Proposal card on home should have button `View Proposals`
2. When user disconnects the wallet on proposals list, they should stay on proposals page

**Comment by teske00** [comment]
@ValMBO @l-br1 I will also leave a comment here that we have everything we need on the ticket. 

How does this affect the PDF, should all the actions that we have triggered the login so far be removed and disabled when the wallet is not connected? This is now important for us to know how to act when the PDF is visited without a wallet

**Comment by MSzalowski** [comment]
Maybe they don't need to be removed, you could just make them executable only when `walletAPI.isEnabled()` returns true. If it is false we can allow user to display only the list of proposals without the possibility of submitting them on-chain

**Comment by bosko-m** [comment]
@teske00 Before introducing signData, what was the action that happened after you click "Propose GA" button?

**Comment by MSzalowski** [comment]
I Marked the issue as blocked until [this comment](https://github.com/IntersectMBO/govtool/issues/1431#issuecomment-2188839315) is resolved

**Comment by ValMBO** [comment]
If the wallet is not connected, all main actions like "add a comment" or "propose GA" should be disabled. Instead of deleting these actions, we should simply disable them. @l-br1 do you agree?

**Comment by ValMBO** [comment]
Hi guys, we had this discussion with Lorenzo and Bosco, and seems like there are 2 things here:

1. @MSzalowski : There is a misunderstanding. We should keep the "Connect to Propose" as it is now and then "Learn more" will be change to "view Poposals" (Ticket 1347)

<img width="863" alt="image" src="https://github.com/IntersectMBO/govtool/assets/158469375/7b61a72c-aa03-456d-8d65-e67d9bf3c000">

2. @teske00 - If the wallet is not connected, User should be able to see all the proposals, all main actions like "add a comment" or "propose GA" should be disabled. However we should keep the option of connect your wallet in all those main actions.

**Comment by ValMBO** [comment]
@teske00 this is the example in Figma. Wallet is not connected, "Add a comment" is disabled and user are able to  connect their wallet by clicking the blue button 

<img width="526" alt="image" src="https://github.com/IntersectMBO/govtool/assets/158469375/f638c092-24f6-4533-b907-354bbd4de383">

**Comment by teske00** [comment]
@ValMBO @MSzalowski I think that currently the opening of the wallet selection modal can only be triggered via govtool, not via PDF. The "Connect wallet" button is always visible in the govtool header, so I don't think there's any need to add it here?

**Comment by ValMBO** [comment]
Yes, this is the design from Figma, if the CTA is on the top, then is fine.

**Comment by MSzalowski** [comment]
> @ValMBO @MSzalowski I think that currently the opening of the wallet selection modal can only be triggered via govtool, not via PDF. The "Connect wallet" button is always visible in the govtool header, so I don't think there's any need to add it here?

That is right and I think that we should follow this approach in the PDF pillar as well for the consistency with the rest of the system. Rest of the points are clear meaning that I am removing the `blocked` label willing to prepare the solution on GovTool side. Thank you @ValMBO, @bosko-m  and @teske00

**Comment by MSzalowski** [comment]
Based on the discussion on call (26th jun 2024) - I also added a `Proposal` nav item on top of the home page

**Comment by pmbinapps** [comment]
**Expected behavior**

NOT OK Proposal card on home should have button View Proposals - still two buttons
![Image](https://github.com/IntersectMBO/govtool/assets/82152577/1fca94f2-9bc2-4e81-b4d4-595157b9ccf7)

OK When user disconnects the wallet on proposals list, they should stay on proposals page - Jam [recording](https://jam.dev/c/b4bc28c4-aa71-4988-b834-742e8370fff9)

Note: there is other 404 error on recording trancked [here](https://github.com/IntersectMBO/govtool/issues/1436)

**Comment by bosko-m** [comment]
@pmbinapps In regards to above mentioned NOT OK part, it is done according to the agreement as stated here - https://github.com/IntersectMBO/govtool/issues/1431#issuecomment-2189200591

**Comment by pmbinapps** [comment]
Thanks @bosko-m for noticing this:

OK NOW - according to  [commet](https://github.com/IntersectMBO/govtool/issues/1431#issuecomment-2189200591) "If the wallet is not connected, User should be able to see all the proposals, all main actions like "add a comment" or "propose GA" should be disabled. **However we should keep the option of connect your wallet** in all those main actions."
