### ISSUE TITLE
Landing page - click in Proposals card on Connect to Propose redirects to Dashboard

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1442]
To reproduce:

1. Go to landing page
2. Find card Proposal 
3. Click Connect to Propose - Dashboard is opened

Jam recording [here](https://jam.dev/c/351749b1-ef32-4525-b8a0-427e43aebf28)

**Comment by bosko-m** [comment]
Same thing happens likely on all cards @pmbinapps

**Comment by jdyczka** [comment]
Looks like both _Become a DRep_ and _Become a Direct Voter_ cards have the same problem
