### ISSUE TITLE
There is no error notification about entering an existing username on the PDF

### ISSUE THREAD

**Issue by teske00** [IntersectMBO/govtool#1446]
## Context & versions

  1. I have verified the wallet
  2. I get a username entry modal
  3. I am entering the existing username
  4. Nothing happens

We need to have some notification that the entered username is taken.

Should we add a modal with text as a response on the frontend? @bosko-m  @ValMBO 

cc @vpaunovic

**Comment by Ryun1** [comment]
i think this is fixed
