### ISSUE TITLE
[BUG] Proposal Draft is Publicly Accessible

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1447]
## Context & versions
- When creating a proposal draft, there's a share button on the unfinished draft card. and also the draft becomes publicly visible. Other users can view, and comment on it, and even I can submit the draft for governance action.

## Steps to reproduce
- Save the proposal as a draft.
- Observe the draft card.
- Copy the draft URL and paste it into an incognito browser.

## Actual behaviour
![image](https://github.com/IntersectMBO/govtool/assets/49801844/0012fb38-0acc-4665-92d7-19779ce01654)
![image](https://github.com/IntersectMBO/govtool/assets/49801844/05323ff8-f804-4152-962e-5df5409b649e)

#### Questions 
- What is the purpose of creating a draft if it is publicly accessible?

**Comment by vpaunovic** [comment]
We will remove the share icon from the proposal card and handle that with public access to proposal details for draft ones.

CC: @teske00

**Comment by vpaunovic** [comment]
This is resolved in PDF-UI v.0.2.4. I think that version is on dev sanchonet also.

CC: @teske00 @bosko-m

**Comment by bosko-m** [comment]
@vpaunovic If I understood correctly, with this fix the following will be true:

1. No share icon on drafted proposals
2. No public access on drafted proposals

Is that correct?

**Comment by vpaunovic** [comment]
@bosko-m Yes

**Comment by vpaunovic** [comment]
@bosko-m @kneerose It can be tested on the latest Sancho-dev

**Comment by kneerose** [comment]
@vpaunovic, I see the share button has been removed, and I could not find the draft on the proposal. It seems the issue is resolved.

CC: @bosko-m

**Comment by bosko-m** [comment]
@kneerose @vpaunovic Intersect should be closing issues like this after being tested on staging. Testing on dev gives early insight into resolution, testing on test gives insight on whether it works well when integrated with the rest, whether it breaks something and testing on staging is where we give the final sign off to be released into SanchoNet at this point.
