### ISSUE TITLE
[BUG] Created New Draft On Edit Existing Draft

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1450]
## Context & versions
- When editing the existing proposal draft and saving it back to the draft a new draft is created instead of updating the edit draft. 

## Steps to reproduce
- Create a proposal draft.
- Click the "Start Editing" button.
- Update some information and save it as a draft.
- Navigate back to the "Create New Proposal".
- Observe the list of proposal drafts.

## Actual behaviour
- After updating the existing draft, a new proposal draft is created, and the existing draft remains unchanged without the modifications.

## Expected behaviour
- Instead of creating a new draft, the edited draft should be updated with the modifications.

**Comment by teske00** [comment]
@kneerose This can be tested on the dev environment

**Comment by kneerose** [comment]
I have tested this on both the test and dev environments on Sanchonet, and it does not reproduce anymore.

CC: @bosko-m

**Comment by bosko-m** [comment]
Great, thanks @kneerose . So it should go with the next release.
