### ISSUE TITLE
[BUG] Draft Remains in List After Submitting as Proposal

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1451]
## Context & versions
- The proposal draft remains in the draft list after being submitted as a proposal.

## Steps to reproduce
- Create a proposal draft.
- Click the "Start Editing" button.
- Submit it to the proposal.
- Navigate back to the "Create New Proposal".
- Observe the list of proposal drafts.

## Actual behaviour
- After submitting the existing draft as a proposal, the draft remains in the unfinished draft list.

## Expected behaviour
- The draft should be removed from the list after being submitted as a proposal.

**Comment by ValMBO** [comment]
@spannercode  agreed with the expected behaviour described. CC @bosko-m

**Comment by teske00** [comment]
@ValMBO @bosko-m This is the final decision and we can start working on this?

**Comment by bosko-m** [comment]
I agree too. Yes, you can start working on it @teske00

**Comment by teske00** [comment]
@kneerose This can be tested on the dev environment

**Comment by kneerose** [comment]
I have tested this on both the test and dev environments on Sanchonet, and it does not reproduce anymore.

CC: @bosko-m

**Comment by bosko-m** [comment]
Great, thanks @kneerose . It should go then out with the next release.
