### ISSUE TITLE
PDF - on Proposal - click on button Back to Proposal Discussion is not working

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1462]
To reproduce:

1. Go to PDF - Proposals
2. Click 'Back to Proposal Discussion' - nothing happes

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/1f21b531-aab8-4d04-bb05-8c0e7b2418b0)

**Comment by teske00** [comment]
@pmbinapps This can be tested on the dev environment

**Comment by pmbinapps** [comment]
OK NOW - https://jam.dev/c/d41d8b7d-6e8a-439e-baef-a79b755293a9
