### ISSUE TITLE
Backend test is failing

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/govtool#1468]
## Context & versions
deployment: https://govtool.cardanoapi.io

## Test run
Last failing:
https://github.com/IntersectMBO/govtool/actions/runs/9791874634
Last passing:
https://github.com/IntersectMBO/govtool/actions/runs/9774786986

### Test result

```
================================================================== short test summary info ===================================================================
FAILED test_cases/test_proposal.py::test_list_proposal - AssertionError: proposal.metadataStatus should be of type <class 'str'> got <class 'NoneType'>
FAILED test_cases/test_proposal.py::test_get_proposal - AssertionError: proposal.metadataStatus should be of type <class 'str'> got <class 'NoneType'>
```

**Note**
It is weird that the same test was passing a day ago on the same deployment. 
There might be some issue with the backend caching.

**Comment by bosko-m** [comment]
@mesudip Can I get your latest result on this?

**Comment by MSzalowski** [comment]
Metadata status has been removed from that endpoint. That property is now accessible only via metadata validation service

**Comment by bosko-m** [comment]
@mesudip Should we close this one?
