### ISSUE TITLE
Refactor backend for DB-Sync `sancho-5-1-0`

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1474]
### Why

- #1473 will bump GovTool to use DbSync `sancho-5-0-0`
  - This version of DbSync has significant schema changes from the current `sancho-4-3-0`
  - This means GovTool's backend will have to be updated so it is able to continue to read from DBSync's postgres DB 

### What

- See DBSync [change log](https://github.com/IntersectMBO/cardano-db-sync/releases/tag/sancho-5.0.0)
- GovTool's backend will have to be updated so it is able to continue to read from DBSync's postgres DB 

### How

- Update the queries used by the backend to read from PostGres
- At face value it looks like
  - tables storing DRep off-chain metadata are affected

**Comment by MSzalowski** [comment]
@Ryun1 [`db-sync sancho-5.0.0`](https://github.com/IntersectMBO/cardano-db-sync/releases/tag/sancho-5.0.0) provides support for `CIP-119`. We can bump this without using newly provided table `off_chain_vote_drep_data`, but I would strongly recommend using this. Which would mean additional changes to the designs, DRep registration flow, and DRep directory (except backend changes with handling new table data) - that would allow us to get rid of the metadata service usage on backend ([comment regarding this topic](https://github.com/IntersectMBO/govtool/pull/1540#issuecomment-2227967343)).

And removing the backend dependency of metadata-validation service would potentially fix the issues with timeouts that we have reported [here](https://github.com/IntersectMBO/govtool/issues/1417) and [here](https://github.com/IntersectMBO/govtool/issues/1422).

**Comment by MSzalowski** [comment]
I am moving this issue to QA as all the needed changes are already done (by #1552) and are prepared to be released on test env.

Also, I'll keep this issue open, as I'll handle support for CIP-119 under this issue once it is accepted.

**Comment by Ryun1** [comment]
this is done
