### ISSUE TITLE
[BUG] Missing TestIDs on Submit Proposal as a Governance Action

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1477]
## Context & versions
- Several components lack proper test IDs, impeding effective testing and automation

### Missing Test IDs
- continue-button for continue button
- cancel-button for cancel button

![Screenshot from 2024-07-05 12-04-02](https://github.com/IntersectMBO/govtool/assets/49801844/d6548c90-7c28-4a5f-bf9e-770de1cbe2ed)

- metadata-download-button for metadata json download button
- metadata-url for metadata URL input field
- submit-button for submit button
- cancel-button for cancel button

![Screenshot from 2024-07-05 12-03-37](https://github.com/IntersectMBO/govtool/assets/49801844/4e40d3c2-9641-4c50-aa3a-bedb3e6f5024)

**Note:** Please make sure to add proper test IDs if you introduce any new components in the future. Additionally, please make these adjustments to ensure appropriate test IDs are in place.

**Comment by teske00** [comment]
@kneerose We had already added the test ids but under different names

**Comment by kneerose** [comment]
@teske00, I have located the missing test IDs on the test environment. I am closing this ticket as the issue is now resolved.
CC: @bosko-m
