### ISSUE TITLE
[USERSNAP] pm bb test idea

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1500]
**Sender**: pawel.mergist@binarapps.com
**Taken at**: https://test-sanchonet.govtool.byron.network/dashboard
**Fields**:
- Name of the idea or new feature: pm bb test idea
- Please summarize your idea or new feature: test
- Any additional details: test

**Browser**: Chrome 125 (macOS Catalina)
**Screen size**: 1440x900
**[Open #43 in Usersnap](https://app.usersnap.com/l/feedback/3b2891ca-fe87-4791-9787-595ce560be66?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
are usersnap tickets meant to contain the email of the submitter? 🤔
