### ISSUE TITLE
Testing for hardfork phases and network

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#1530]
### Why

We want to have smooth transition of the hard fork phases on the govtool and ensure that nothing breaks

### What

- Testing for the hardfork phases based on the protocol version
- Testing the network compatibility

### How

For this, we need to the following information from the backend (or wallet (does not seem possible atm))
- Network tip
- protocol version
- Network name/id

With information, we need to update the tests to enable conditional checks on the tests. This involves which gov actions are currently valid for the current protocol version and whether or not the govtool has addressed that sufficiently.
This also involves setup stage of test confirming the wallet is inline with the network the backend is configured for.

### Dependency
- [x] Backend API provides protocol version, network tip information
- [x] Govtool frontend is updated to check for wallet network and backend network
- [x] Govtool frontend is updated to react according to the protocol version. Eg. enabling/disabling certain gov actions.
- [x] References to hard coded SanchoNet should be removed with network name obtained from backend or the wallet.

**Comment by MSzalowski** [comment]
Network name under GET /network/metrics:
https://github.com/IntersectMBO/govtool/issues/1644

**Comment by MSzalowski** [comment]
[Milestone](https://github.com/IntersectMBO/govtool/milestone/67) created by @Ryun1 that covers some of the points listed in **Dependency** secion.

**Comment by Ryun1** [comment]
this sorted @spannercode ?

**Comment by spannercode** [comment]
@Ryun1 yes, it can be closed now.
