### ISSUE TITLE
[BUG] Slide Unfinished Drafts Infinitely

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1536]
## Context & versions
- Although I have only one draft I can slide it to infinite time.

## Steps to reproduce
https://www.loom.com/share/d512245bc772445db74ac8a13719b0cf

**Comment by vpaunovic** [comment]
@kneerose It can be tested on dev with new version of pdf now.

 CC: @bosko-m

**Comment by kneerose** [comment]
@vpaunovic , Thanks 
 I am closing this ticket as the issue is no longer reproducible.
