### ISSUE TITLE
Chore: Bump Node to version `node-8.11.0-pre`

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#1537]
**Update Cardano Node to version node-8.11.0-pre for governance functionalities**

As a GovTool DevOps,

I want to update the Cardano Node to version node-8.11.0-pre

so that the application runs on SanchoNet network that can support full governance functionalities to be tested before release to mainnet.

**Acceptance Criteria:**

- [ ] The Cardano Node is updated to version node-8.11.0-pre, including all new Conway/Governance functionalities.
- [ ] The configuration for the Node has to be updated.
- [ ] The update is successfully tested in a staging environment before deploying on the beta.
- [ ] No major bugs or downtime occur on the mainnet post-update.

**Additional Information:**

1. The current version node-8.11.0-pre will be rebadged as node-8.11.0-pre after final testing.
2. The Preview network will be forked once Node node-8.11.0-pre is ready.

**Comment by Ryun1** [comment]
We should now target Cardano Node 9.0.0, as this is the version SanchoNet is running on
