### ISSUE TITLE
Chore: Bump DB-Sync to version `sancho-5-1-0`

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#1538]
**Update Cardano DBSync Service Instances to sancho-5.1.0**

As a GovTool DevOps,

I want to update the Cardano DBSync service instances to the latest compatible version

so that the GovTool application remains in sync with the latest node version and supports governance functionalities on Preview network.

**Acceptance Criteria:**

- [x] The Cardano DBSync service instances are updated to the latest compatible version with Node 9.0.0.
- [ ] The update is successfully tested in a staging environment before deploying to the beta.
- [ ] No major issues or downtime occur on the beta post-update.

**Additional Information:**

1. The update should align with the Node 9.0.0 upgrade to maintain compatibility.
2. Testing in SanchoNet and PreProd environments should confirm the stability of the update.

**Comment by MSzalowski** [comment]
Blocked by https://github.com/IntersectMBO/govtool/issues/1583, which is already under testing in development, so it shouldn't be blocked too long.
