### ISSUE TITLE
Create a new information storage download&submit page

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#154]
### Why

To allow DRep to provide their data.

### What

⚠️ Check the latest designs on figma ⚠️ 
<img width="681" alt="image" src="https://github.com/IntersectMBO/govtool/assets/24510246/866c793c-f1d4-4a04-bd6f-d8708db9078b">

* Download button that allows to download .jsonld file
* Link to the guide for saving the DRep info file
* Input with the info file URL

**Comment by Ryun1** [comment]
very old, lets close
