### ISSUE TITLE
DRep explorer - DRep-Yourself-Retired is shown when Filter is set to Active only

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#1551]
To reproduce on test-sancho:

1. Become a Drep
2. Retire
3. Go to DRep explorer
4. Set Filter to Active - on first place your DRep card is shown with Yourself - Retired state, below are there rest of Retired Dreps

API endpoint: /drep/info returns that the current - your DRep is retired

Used DRep: drep1pzuxy8ukuvffjyyrdp8sxkzp3z8r57z5q0jtgxhwu3a22t9ppel
```
curl -X 'GET' \
  'https://test-sanchonet.govtool.byron.network/api/drep/info/33fb11c1fba4845dd900d2f05a1df0547f64457c4ee035c4c8a1bcd3' \
  -H 'accept: application/json;charset=utf-8'

{
  "isRegisteredAsDRep": false,
  "wasRegisteredAsDRep": false,
  "isRegisteredAsSoleVoter": false,
  "wasRegisteredAsSoleVoter": false,
  "deposit": null,
  "url": null,
  "dataHash": null,
  "votingPower": null,
  "dRepRegisterTxHash": null,
  "dRepRetireTxHash": null,
  "soleVoterRegisterTxHash": null,
  "soleVoterRetireTxHash": null
}
```

Compare with screenshot below and jam [recording](https://jam.dev/c/e724b30c-c2f3-4cd2-bc02-dd6ffbf60213)

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/48113786-3582-4910-b495-63eaa8683670)

**Comment by bosko-m** [comment]
@pmbinapps Is the 4th step in the description set correctly? Title says active only, 4th bullet point says retired only

**Comment by pmbinapps** [comment]
@bosko-m right, it should be 'Active' in 4th step as on screenshot. Thank you for spotting!
