### ISSUE TITLE
[BUG] Proposal Creation form validation

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1564]
## Context & versions
- The Governance Action Proposal creation form currently supports empty values.
- Also it treats spaces as filled characters and allows the addition of random addresses and negative amounts. 
Please review the relevant tickets and discussions regarding treasury address validation.
- https://github.com/IntersectMBO/govtool/issues/1187
- https://github.com/IntersectMBO/govtool/issues/1231

For form validation, please refer to [this link](https://govtool.cardanoapi.io/create_governance_action).
- The form currently supports empty values, but it should not. See reference ticket (#1099).

**Comment by kneerose** [comment]
@vpaunovic, I can see the form validation on the development environment, but there are still some inconsistencies:

1. An empty title is accepted, and whitespace is taken as a valid title.
   - Actual Behavior:
   
   ![image](https://github.com/user-attachments/assets/0ad5df99-c896-49e7-ae7f-a3e613ac5614)
   
   - Expected Behavior:
   
   ![image](https://github.com/user-attachments/assets/efe3d95a-1256-4962-b8dc-304001a0564b)

2. Instead of blocking the input that exceeds 80 characters, can you show an error message?
   - Actual Behavior:
   
   ![image](https://github.com/user-attachments/assets/a5230c73-b9ce-4a45-9828-f41dde994bc5)
   
   - Expected Behavior:
   
   ![image](https://github.com/user-attachments/assets/0adc9a3d-06f7-4780-9c90-b8bd9abef9c5)

Also, don't forget to add the test ID for those error messages.

**Comment by kneerose** [comment]
@vpaunovic   
I can confirm that the form validation and test IDs for the error message are in place.

This issue can be closed now. CC: @bosko-m

**Comment by bosko-m** [comment]
Closing as per the comment above.
