### ISSUE TITLE
[BUG] The 'Edit Proposal' and 'Review Your Submission' contents do not match.

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1566]
## Context & versions
- When I try to edit a draft with updated data and click 'Continue,' I am navigated to the Review your submission page. If I then navigate back by clicking 'Show All,' later return to edit the same draft, and click 'Continue'  again without making any changes, the governance action type content disappears, and an extra amount is added.

## Steps to reproduce
https://www.loom.com/share/ff977c9592a0484795841a5ffed6497e?sid=26ed761a-dab1-4a9d-b6b6-8fac3f207cf0

**Comment by kneerose** [comment]
@vpaunovic I see the issue is not reproduciable on the dev environment but not yet on the test environment. The ticket will be closed once the changes are available in the test environment.
CC: @bosko-m

**Comment by bosko-m** [comment]
Please dont close it after it passes the testing on test environment @kneerose . Intersect should give in this case final sign off after testing it on staging.

**Comment by kneerose** [comment]
@bosko-m, sure thanks.
