### ISSUE TITLE
[BUG] Remaining Missing Test IDs on PDF

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1568]
## Context & versions
- Some Several components still lack proper test IDs, impeding effective testing and automation

### Missing test IDs
1. Proposal Card
  - Governance action type -> data-testid=governance-action-type
  - Proposed on date -> data-testid = proposed-date
  - It will be better to change the proposal card testId like proposal-${governanceActionType}-card as the previous test ID conflict with filtering
  
![Screenshot from 2024-07-12 13-10-12](https://github.com/user-attachments/assets/e3528751-53c5-4ed2-b92c-68b296f256e9)

2. Proposal Details
  - Governance action type-content -> data-testid=governance-action-type-content
  - Title content -> data-testid= title-content
  - Abstract Content -> data-testid=abstract-content
  - Motivation Content -> data-testid=motivation-content
  - Rationale Content -> data-testid=rationale-content
  - Link text content -> data-testid=link-${index}-text-content
  
  
![image](https://github.com/user-attachments/assets/d3731df9-1062-448c-abe3-5c97146ccd08)

 - Click to copy link -> data-testid=copy-link
 
![image](https://github.com/user-attachments/assets/2f25fec9-d945-440c-a21f-2f6a0f2afdc9)

  - Verify identity button -> data-testid=verify-identity-button

![image](https://github.com/user-attachments/assets/14cf08e7-8de9-489f-9e3e-454c34e6e406)

 - Close button of user modal -> data-testid=close-user-modal

![Screenshot from 2024-07-12 15-41-04](https://github.com/user-attachments/assets/3b01b78b-f67e-4415-a477-4631d432855e)

**Comment by kneerose** [comment]
Hello @teske00, 
I have noticed that the test IDs for filters have different naming conventions. For example, "Info" and "Treasury" start with a capital letter, whereas "submitted for vote" and "active proposal" starts with a lowercase letter. Please standardize the naming conventions of the test IDs for all filters.

![image](https://github.com/user-attachments/assets/063826c5-9386-4ce9-a9f5-bd8ce55156a7)
![Screenshot from 2024-07-22 13-46-41](https://github.com/user-attachments/assets/a907d23f-713a-40e9-a442-8ecb7092483d)

**Comment by kneerose** [comment]
@teske00, furthermore the status should be inside the proposal card. I cannot test which status belongs to which proposal card

![image](https://github.com/user-attachments/assets/9807558c-3a9e-430a-b02d-eefb919bc54f)

**Comment by teske00** [comment]
@kneerose The component is structured like this, the only thing we can do now so as not to break the entire logic is to set the name of the status in the data-testId of the status, for example 'data-testid': `proposal-${proposal?.id}-{status_name }-status`. Also, for the proposal card, in addition to proposal-{status_name}-card, add proposal_id in the name, so that it becomes proposal_{proposal_id}-{status_name}-card. In this way, it is possible to connect which status belongs to which card. Is it ok to do it like this?

**Comment by kneerose** [comment]
@teske00, I don't think this approach is ideal. We are retrieving a list of proposal locators `proposal-${govactionType}-card` and checking the status inside each proposal card. If the component is structured this way, could you change the data-test-id of the proposal card to be the parent element of the status and the current `<div>` tag which is using the data-test-id of the card. ie. `proposal-${govactionType}-card`. If it is possible.

**Comment by teske00** [comment]
@kneerose As far as I understand you, you mean to put the card and status in a div to which we will add the test id "proposal-${govactionType}-card", and remove it from the current div (card). And what do you think if we change the testId for draft cards to follow that structure, and not to be draft-${proposal?.id}-card, how is it now?

**Comment by teske00** [comment]
@kneerose And is it perhaps necessary to add the proposal id to the testID in addition to the name of the status?

**Comment by teske00** [comment]
@kneerose Is this the desired structure, the card component with test id wraps the card content and status. I didn't change the other testIDs, I just moved the current testIDs that were in the wrapper components. Is this enough?

![image](https://github.com/user-attachments/assets/42f7eb15-ead0-4f78-bc11-8735c37d7d98)

**Comment by kneerose** [comment]
@teske00, yes this is the desired structure

**Comment by teske00** [comment]
@kneerose The old testId names can remain as they are now, we just need to do this?

**Comment by kneerose** [comment]
@teske00 yes, only thing you have to do is change the position of the card test ID.

**Comment by kneerose** [comment]
@teske00 
I''ve located the missing test IDs mentioned above. The test IDs are now available in the test environment.

This issue can be closed now. CC: @bosko-m

**Comment by bosko-m** [comment]
Closing as per the comment above.
