### ISSUE TITLE
PDF backend API axios instance

### ISSUE THREAD

**Issue by teske00** [IntersectMBO/govtool#1575]
@MSzalowski @bosko-m @ValMBO @vpaunovic We need to pass to the PDF-UI the baseURL of the backend we use in the PDF-UI, currently we only have a dev environment (https://dev.api.pdf.gov.tools/). We have implemented locally that from govtool this endpoint is passed as a prop to the package. How does this solution look to you, if this is OK, this logic can already be implemented on govtool.
<img width="265" alt="image" src="https://github.com/user-attachments/assets/fa90dd59-63c3-44f9-aed7-090e13e053a1">

**Comment by teske00** [comment]
@bosko-m Can you get information from the Bloxico team about which environments they have created for the PDF backend and what their URLs are?

**Comment by MSzalowski** [comment]
We can provide another argument into the frontend docker file that would include the pdf API URL, and it needs to be provided on CI level as it also needs to be parsed into csp declarations to be working.

I'll provide appropriate PR with the ENV placeholder and tag you once its done @bosko-m

**Comment by MSzalowski** [comment]
Pull request that covers that issue: https://github.com/IntersectMBO/govtool/pull/1593
