### ISSUE TITLE
Support proposing and submitting all governance action types

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1580]
### Why

These action types are currently not supported.

### What

Currently GovTool + proposal discussion only support treasury withdrawals and info actions, this is a subset of what will be allowed on-chain.

- Motion of no-confidence
- Update committee and/or threshold and/or terms
- New Constitution or Guardrails Script
- Hard-Fork Initiation
- Protocol Parameter Changes

### How

add support

**Comment by bosko-m** [comment]
@Ryun1 Added these to the description:
- Motion of no-confidence
- Update committee and/or threshold and/or terms
- New Constitution or Guardrails Script
- Hard-Fork Initiation
- Protocol Parameter Changes

**Comment by bosko-m** [comment]
Also worth mentioning here #1597 #1598 #1599 #1600 #1601 #1602

**Comment by m-i-k-e** [comment]
If you make a list: Github gives you the name of the issue. Might be useful.
- Also worth mentioning here 
- https://github.com/IntersectMBO/govtool/issues/1597 
- https://github.com/IntersectMBO/govtool/issues/1598 
- https://github.com/IntersectMBO/govtool/issues/1599 
- https://github.com/IntersectMBO/govtool/issues/1600 
- https://github.com/IntersectMBO/govtool/issues/1601 
- https://github.com/IntersectMBO/govtool/issues/1602
