### ISSUE TITLE
Rendering Update committee/threshold Discovery Governance Actions

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1598]
Display GA that updates CC members parameters onchain
-----

For this GA can we display the CC member instead of the key? (the info that is on the CC Portal), so that the user can understand what are keys referring to

Add the scope and parameters of the "Update committee/threshold" here to help with screen and flow design.

What is this action all about?
What are it's parameters?
What inputs need to be entered by users?
What outputs need to be served to users?
What are the technical implications?
Anything else?

**Comment by Ryun1** [comment]
On-chain details to be read
Three components to the action, at least one is needed.

- **Existing members to be removed**, represented by a set of verification key hashes ([see example](https://cardanoscan.io/ccmember/cc_cold1z00saqaaue2pdkk7tv0e0el3zhxpl7ve259dj6y9q7plu5qwvxfy9))
- New members (they may already be in the committee) and their term limit, represented by a map of keyhashes to expiration epoch
- A voting threshold represented by a fraction

Other details that might want to be shown
- What the current CC looks like / what the current fraction looks like
  - who is and isnt being removed
