### ISSUE TITLE
Rendering New Constitution and/or Guardrails Script Governance Action

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1599]
Display info about this GA. This is the GA that will used to update the constitution (render URL and hash of new constitution)

HMW we show users the proposed constitution content and differences with the old?

-----
Add the scope and parameters of the "New Constitution or Guardrails Script" here to help with screen and flow design.

What is this action all about?
What are it's parameters?
What inputs need to be entered by users?
What outputs need to be served to users?
What are the technical implications?
Anything else?

**Comment by Ryun1** [comment]
Showing a diff view comparing the proposed constitution to the existing constitution is the most sensible route

[github diff example](https://github.com/IntersectMBO/interim-constitution/commit/75155526ce850118898bd5eacf460f5d68ceb083#diff-05e8bc0d1c3d577e2f896c2b0e8e2974da692191c184146bbab617d754a2c58bL96)

**Comment by m-i-k-e** [comment]
Ready to build from design: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=16152-118912&t=rHaGCSxj5xvFYc0r-1
