### ISSUE TITLE
Double Refresh on Transaction Progress Finalization

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#16]
investigate and confirm this still happens

Suspected issue:

- There is a miss match between when the transaction success endpoint says a transaction has been seen and when the data within that Tx has been added to DB-Sync
- So the BE will see transaction X, but the DRep endpoint wont see the new DRep registration from within transaction X for another amount of time
- This means the in progress status will go from the UI (this relies on the in progress endpoint), but the Registered DRep UI wont be shown until the DRep List endpoint sees the new DRep

**Comment by bosko-m** [comment]
Moving it to the last known status before the migration to this project.
