### ISSUE TITLE
Rendering Hard-Fork Initiation Governance Actions

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1600]
### What?

- GovTool should show voters the on-chain details for Hard-Fork Initiation Governance Actions
- Showing users the proposed new protocol version.

### Why?

- This is important information that will help inform the voters
- Hardfork initiations are available in the bootstrapping phase

### How?

- @m-i-k-e and team design how this could be rendered
- GovTool BE API adjusted to provide this information
- GovTool FE adjusted to render this new information

---

### User Story

**Title:** Render all relevant all on-chain details of hard-fork initiations.

**User Story:** As a DRep, I want to be able to see all the relevant on-chain information for protocol parameter changes, including what parameters are being changed from what current value to the new proposed value.

**Acceptance Criteria:**

- Given that I am a DRep.
- When I view a hard-fork initiation in GovTool.
- Then I should see all relevant on-chain details, including:
  - The proposed next major and minor protocol version
  - Their current protocol major and minor versions.

**Comment by Ryun1** [comment]
### What is this action all about?

- Triggers a non-backwards compatible upgrade of the network; requires a prior software upgrade (upgrading node software versions) 
- Voted on by DReps, CC and SPOs
- Available within the bootstrapping phase (will be used to exit the bootstrapping phase)

### What are the on-chain details? (specific to treasury withdrawals)

- governance action ID of the previous hardfork initiation to be enacted (this isn't super important, but shows users how hard-forks can be chained together)
- the next major and minor protocol versions

For example;

The hard-fork governance action for Chang #2 could look like

- prev governance action ID = `fc0386f81025d66fc448d4f0aa3ca6c1eeae95fe88e3b10244bacc126bbeb007#0`
- next protocol version (major.minor) = `10.0`

### What is other contextual information that might be nice?

- the current protocol version

**Comment by Ryun1** [comment]
Next step;
- wireframes by Friday

cc @bosko-m

**Comment by m-i-k-e** [comment]
Wireframe to discuss:
![hard fork](https://github.com/user-attachments/assets/965a02ba-4192-46f9-8326-a2e241c6c005)

**Comment by Ryun1** [comment]
@m-i-k-e 
oo! this looks nice

I would rename `Parameter` label on the tab to `details` or something similar
to avoid confusion with protocol parameters

**Comment by m-i-k-e** [comment]
Good call!
![hard fork](https://github.com/user-attachments/assets/cf7a3250-e336-4966-9315-72ab0e001f9f)

**Comment by m-i-k-e** [comment]
@MSzalowski This is now ready to develop in Figma: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=14751-92651&t=hLlpXMOe0RpGkeDc-1
