### ISSUE TITLE
Rendering Treasury Withdrawal Governance Actions

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1602]
Add missing onchain details (some of them are already supported in govtool including treasury action submission)
----
Add the scope and parameters of the "Treasury Withdrawals" here to help with screen and flow design.

What is this action all about?
What are it's parameters?
What inputs need to be entered by users?
What outputs need to be served to users?
What are the technical implications?
Anything else?

**Comment by Ryun1** [comment]
### What is this action all about?

- Allows withdrawal of Ada funds from the Cardano treasury to one or many reward accounts (reward/stake addresses)
- Voted on by DReps and the CC
- Not available within bootstrapping phase

### What are the onchain details?

- A array of reward/stake addresses and how much ada to be transferred to each
  - note that reward/stake addresses are not the same as payment addresses
- The script hash of the gaurdrails script applied (this is unlikely to change between actions so may not be 100% required to always be shown)

**Comment by m-i-k-e** [comment]
@Ryun1 says we can withdraw up to 10 different addresses

**Comment by m-i-k-e** [comment]
Wireframe for rendering

![Image](https://github.com/user-attachments/assets/47ed3dfc-d103-469e-b7bb-adddb028bbac)

**Comment by m-i-k-e** [comment]
Wireframe for input:
![Image](https://github.com/user-attachments/assets/7473b30f-2673-4a19-bc85-c71a2288dfc3)

**Comment by m-i-k-e** [comment]
Input: https://www.figma.com/design/239JKpjintphf2Go5NPipp/Proposal-discussion-Forum?m=auto&node-id=3320-42001&t=zK8ygEe7KRfnxjI1-1


Rendering:
https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=8762-61513&t=XVj7lGRTjf8hJXMJ-1
