### ISSUE TITLE
Use single certificate for delegation + registration

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/govtool#1608]
### Why

- To make delegation transaction a little smaller 
- Stake registration certificate (0) is **deprecated in conway era**

### What

When Stake Address is not registered, We are currently creating transaction with 2 certificates (registration, delegation). But this can be done in single certificate in conway era. Furthermore, the used certificate-type (0) is deprecated. 

#### Example (cert list in decoded-tx) (Current implementation)
```json5
[
    [
        0, // stake-registration cert ; Deprecated in Conway Era
        [
            0, "992D25F1234F161763F5FAAEEA857BAF06DE242547BDE90895019CDE"
        ]
    ],
    [
        9, // vote_deleg_cert
        [
            0, "992D25F1234F161763F5FAAEEA857BAF06DE242547BDE90895019CDE"
        ],
        [
            0, "001021A9B538F693F5293B9AD77E9FD2FEBE5ECD66CF8BB2844B4A8D"
        ]
    ]
]
```

#### Suggested change (certs in decoded tx)
```json5
[
    [
        12, // vote_reg_deleg_cert
        [
            0, "992D25F1234F161763F5FAAEEA857BAF06DE242547BDE90895019CDE"
        ],
        [
            0, "001021A9B538F693F5293B9AD77E9FD2FEBE5ECD66CF8BB2844B4A8D"
        ],
        2000000 // deposit amount
    ]
]
```
**NB** Refer to corresponding certificate builder in `cardano-serialization-lib` to create the `registration_delegation_cert`

**Comment by Ryun1** [comment]
@mesudip 

I agree with the motivation and rationale here - great catch!
But unfortunately hardware wallets have not supported these "combination" certificates (see [CIP-21 Certificates](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0021#certificates))
So by using them we could break the user flow for HWWs

> Stake registration certificate (0) is deprecated in conway era

*[depreciated in the era **after** conway](https://github.com/IntersectMBO/cardano-ledger/blob/master/eras/conway/impl/cddl-files/conway.cddl#L295C44-L295C82)
Maybe we should just move to use the new Conway [reg_cert](https://github.com/IntersectMBO/cardano-ledger/blob/master/eras/conway/impl/cddl-files/conway.cddl#L307)?

**Comment by Ryun1** [comment]
we can close for now
