### ISSUE TITLE
Support ipfs in GovTool

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1616]
## Context & versions

GovTool 1.0.8

## Steps to reproduce

1. Pass ipfs link to validate endpoint

## Actual behavior

URL_NOT_FOUND error

## Expected behavior

IPFS should be supported
We also need to use new config `ipfs_gateway`

**Comment by bosko-m** [comment]
Once the related DBSync issue is implemented, ipfs support can be added to GovTool.
https://github.com/IntersectMBO/cardano-db-sync/issues/1792

**Comment by Ryun1** [comment]
Supported in DBSync [13.6.0.0-pre](https://github.com/IntersectMBO/cardano-db-sync/blob/889f96917f7c5909362f36955a4c5bf1d34f7b65/CHANGELOG.md#13600)

**Comment by bosko-m** [comment]
@MSzalowski Slightly edited, to add:

We also need to use new config `ipfs_gateway`

CC @Ryun1

**Comment by bosko-m** [comment]
@MSzalowski What needs to be done? Infrastructure provided or existing one reconfigured?

**Comment by bosko-m** [comment]
We should probably use paid ipfs gateway service.
