### ISSUE TITLE
Cannot build backend docker image

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/govtool#1621]
The CHANGELOG file has been  removed on backend, but its still referenced on the cabal project. This is causing the build to fail.

https://github.com/IntersectMBO/govtool/blob/8522c3d62cbe354956c6458c3a46ef8a7abe9428/govtool/backend/vva-be.cabal#L22-L23

Shouldn't we retain the changelog file?

**Comment by MSzalowski** [comment]
Awesome catch!
