### ISSUE TITLE
Replace `SanchoNet` in copy with `Voltaire`

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1637]
### Intro

The time has come.
We have had fun, but it is time for GovTool to graduate past SanchoNet

### What?

- Update copy throughout to remove and replace every publicly facing reference "SanchoNet" reference with "Voltaire".
- It may also make sense to change wording within code.

(first of a few issues on this)

**Comment by Ryun1** [comment]
Do we have new icons prepared for this @m-i-k-e ?

**Comment by MSzalowski** [comment]
I made the draft with the changes, and I am waiting for the necessary icons to complete the replacing

**Comment by Ryun1** [comment]
@m-i-k-e can you help with the icons?

**Comment by m-i-k-e** [comment]
@Ryun1 I've had a talk with Lorenzo, and we are reverting to "Voltaire" in place of Sancho. I've asked @kgrzonka  to sort out all the rebranding stuff (there isn't a lot) in Figma. She will probably get to it tomorrow. There is an issue for this #1640 

I will take care of GitBook myself.

**Comment by MSzalowski** [comment]
I've made [the PR](https://github.com/IntersectMBO/govtool/pull/1684) that replaces Sancho with Voltaire. You can have a look on the changes on dev

**Comment by m-i-k-e** [comment]
@MSzalowski I've sent you the correct logo, replace it, and I think we're done.
