### ISSUE TITLE
Cannot submit Governance Action

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1641]
## Context & versions

sanchogov.tools (staging)

## Steps to reproduce

1. Try to submit Governance Action

## Actual behavior

1. Insufficient balance error occurs

## Expected behavior

1. GA should submit (if only meets the balance criteria)

**Comment by Ryun1** [comment]
Is your wallet on the correct network?

**Comment by Ryun1** [comment]
Working for me within an Info action on staging environment using demos wallet

![image](https://github.com/user-attachments/assets/04d7f6ed-c38b-41ac-8b38-3f83f3e19c59)

**Comment by MSzalowski** [comment]
I don't have that issue either - I've reported that based on a slack thread

**Comment by MSzalowski** [comment]
> Although metadata doesnt seem to get picked up: https://staging.govtool.byron.network/connected/governance_actions/ab9d706d480845946e571f0c37d8d5d046ed3ddf8360f644d5422a3cb6de77b4#0

I'll reorganise the services responsibility under [this](https://github.com/IntersectMBO/govtool/issues/1623) issue - to have that fixed. I am aware of the issues around the metadatas

**Comment by MSzalowski** [comment]
Error log for treasury action:
```
instrument.ts:129 (400)
failed:
c55c2c133d9adb1c15424ad8fb7cd8048a2a3c506ab8a327a9652ca6b77e7cda
The provided constitution guardrails hash doesn't match the expected on defined in the constitution. Some governance actions such as treasury withdrawals or protocol parameters updates must correctly refer to the constitution guardrails hash digest. The latter can be 'null'. The field 'data.providedHash' indicates the hash provided in the proposal, and the field 'data.expectedHash' the one specified in the constitution
Data: {"providedHash":null,"expectedHash":"edcd84c10e36ae810dc50847477083069db796219b39ccde790484e0"}
```

**Comment by Ryun1** [comment]
This is the same as
https://github.com/IntersectMBO/govtool/issues/1565

**Comment by bosko-m** [comment]
Closing as per the previous comment.
