### ISSUE TITLE
Usersnap is not working on preview

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1642]
## Context & versions

preview.gov.tools

## Steps to reproduce

1. Press feedback button

## Actual behavior

Nothing happens

## Expected behavior

Feedback modal should open

**Comment by MSzalowski** [comment]
To verify whether the usersnap API key is missing or it is on the usersnap console level.

**Comment by MSzalowski** [comment]
API_KEYS were not set. I've forwarded that to DevOps to provide the appropriate key & redeploy the app.
https://github.com/IntersectMBO/govtool/pull/1647 - this pr makes these arguments mandatory

**Comment by bosko-m** [comment]
Works on Preview now.
