### ISSUE TITLE
GTM ID is missing on the preview

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1643]
## Context & versions

preview.gov.tools

## Steps to reproduce

Check console.

## Actual behavior

 GTM ID missing log appears.
 
## Expected behavior

GTM ID should be set and correctly handle events

**Comment by MSzalowski** [comment]
API_KEYS were not set. I've forwarded that to DevOps to provide the appropriate key & redeploy the app.
https://github.com/IntersectMBO/govtool/pull/1647 - this pr makes these arguments mandatory

**Comment by bosko-m** [comment]
Working on Preview.
