### ISSUE TITLE
No metadata taken from off_chain_vote_gov_action_data

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1650]
## Context & versions

Backend v1.0.11

## Steps to reproduce

1. Execute list proposals endpoint from swagger or locally on backend connected to sanchonet network. 

## Actual behavior

list-proposals.sql seems to be correct, metadata for that table exists (for some records at least) but the final SQL doesn't return any.

## Expected behavior

Metadata (if exists) should be returned.

**Comment by Ryun1** [comment]
Metadata produced via GovTool adds in "@value"
I wonder if these are breaking the DBSync validation

**Comment by MSzalowski** [comment]
That is another topic - somehow it is produced by the compact method of jsonld. We are not passing them manually, but maybe either doc or context we have wrong - I'll have a look.

But regarding this issue - on my local db-sync I have 2 records with the valid off_chain metadata:
```
cexplorer=# select id, title from off_chain_vote_gov_action_data where title is not null;
 id |              title              
----+---------------------------------
  1 | Buy Ryan a island
  2 | Hardfork to Protocol version 10
(2 rows)

```

But they are not listed via final query. I guess that either joins are wrong or records are not linked between tables (they don't have matching ids).

**Comment by Ryun1** [comment]
The `Buy Ryan a island` is probably from [this example](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0108/examples/treasury-withdrawal.body.jsonld) in CIP108.

**Comment by MSzalowski** [comment]
> Metadata produced via GovTool adds in "@value"
> I wonder if these are breaking the DBSync validation

That is added automatically within the compact function of digitalbazaar jsonld library

**Comment by MSzalowski** [comment]
Reference

> Metadata produced via GovTool adds in "@value" I wonder if these are breaking the DBSync validation

I've created issue for that problem [here](https://github.com/IntersectMBO/govtool/issues/1687)

**Comment by MSzalowski** [comment]
After further investigation - that is not an issue. GAs were not returned due to being expired as well as the `@value` issue described by Ryan which is also fixed.
