### ISSUE TITLE
[BUG] Blank screen on proposal when disconnected.

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1652]
## Context & versions
- Proposals are not accessible when disconnected. A blank screen is displayed when disconnected but works fine when the wallet is connected.

## Actual behaviour
![image](https://github.com/user-attachments/assets/76818cbd-0699-48bc-a6d7-56c685e067d3)

![image](https://github.com/user-attachments/assets/f412a3a5-151d-4286-b990-830e225b6c42)

![image](https://github.com/user-attachments/assets/29ef9ffa-08d1-4cca-b22f-3fab8a98302b)

**Comment by jdyczka** [comment]
The request url is not correct, it's the url for the app. It seems to me like maybe the api is called before the `pdfApiUrl` passed to pdf-ui is set on `axiosInstance`?
CC @teske00

**Comment by jdyczka** [comment]
If you navigate to any other route and then back to Proposals, the it starts working ok

**Comment by teske00** [comment]
@jdyczka is right, here comes the problem she described, we can conclude that by the requestURL when it takes the frontend URL, because there is no other forwarded. I don't know what the situation is, is there any other solution for passing this variable, we also have an env variable NEXT_PUBLIC_PROPOSAL_DISCUSSION_API_URL to which the value for the backend URL can be passed, which value is taken if it exists, but I don't know if it can be used on the current govtool cc @vpaunovic

**Comment by jdyczka** [comment]
I think it could stay the way it is right now with small tweaks. How about for example returning `null` from `GlobalWrapper` until the api url is set?

**Comment by vpaunovic** [comment]
@jdyczka Can it be done in this way. So, on Govtool side, can you make conditional rendering of Proposal Discussion Forum, so until there is not pdfApiUrl - show loader, when there is pdfApiUrl - render the Proposal Discussion Forum. In that case - Proposal Discussion Forum will be renderer when pdfApiUrl is there and should not be the case when it is rendered and do not have URL.

CC: @teske00

**Comment by jdyczka** [comment]
@vpaunovic It would have to be done on your side. The value of pdfApiUrl on our side is there from the beginning. It's just not set on the `axiosInstance` that lives inside pdf-ui and the `axiosInstance` is not exported.

**Comment by vpaunovic** [comment]
@jdyczka We will check what can be done on our side and we will inform you and @MSzalowski .

**Comment by bosko-m** [comment]
Verified on Staging, closing.
