### ISSUE TITLE
[BUG] Varying Documentation Navigation for "Delegate Your Voting Power" Card

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1654]
### Context & Versions
- When disconnected, the "Learn more" button under the "Delegate Your Voting Power" card navigates to `https://docs.sanchogov.tools/faqs/ways-to-use-your-voting-power`.
- When connected, the same button navigates to `https://docs.sanchogov.tools/how-to-use-the-govtool/using-govtool/delegating`.

### Steps to Reproduce
1. Click the "Learn more" button on the "Delegate Your Voting Power" card while disconnected.
2. Click the "Learn more" button on the "Delegate Your Voting Power" card while in a connected state.

### Actual Behaviour
- The button navigates to different documentation pages depending on the connection state.

### Expected Behaviour
- The button should navigate to the same documentation page regardless of the connection state.

**Comment by bosko-m** [comment]
This is now resolved and on Beta, closing.
