### ISSUE TITLE
Errors and missing text on DRep detail page for Missing Data

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1655]
## Context & versions
staging.govtool.byron.network

## Steps to reproduce

  1. Connect wallet
  2. Go to DRep directory
  3. Choose a Drep with "Data Missing"
  4. View DRep detail page

## Actual behavior
You see a page like this: 
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/af9aa1ee-1712-4b17-841d-d3cd1f8cc3fb">

## Expected behavior
Page should look like this: 
<img width="637" alt="image" src="https://github.com/user-attachments/assets/5a84291b-8675-4e6a-add2-05b3709c282b">

## What's wrong: 
Supporting text below "Data Missing" is missing
There should be no link to 'external data'

## See Figma page:
https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=9004-94366&t=xZOX8GTBbyFP9x2h-1

**Comment by jdyczka** [comment]
Supporting text seems to be there, [example drep](https://staging.govtool.byron.network/connected/drep_directory/drep1p6vcpyuj4jal40f4zcr7ty4v9xdu0ex3whnsemmvajm6sgysutl)

**Comment by bosko-m** [comment]
Verified on Sancho and Preview, closing.
