### ISSUE TITLE
[NOT-A-BUG] Missing User Deletion Functionality

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1668]
## Context & versions
- If the username our test tries to add is already occupied, then the test cases dependent on the authentication state (where the username is set) will be skipped. 
- Currently, we generate usernames using Faker. Although the test has not failed yet, there is a possibility that a previously set username could match a new one. If this happens, all other tests dependent on the set username will be skipped, leading to potential timeouts on this page.

![image](https://github.com/user-attachments/assets/78f63921-b59b-48e5-b25d-9ea68b770a3d)

- To prevent this issue, it would be better to delete the set username after the test is completed during the teardown phase.

**Comment by spannercode** [comment]
After discussion at the daily, it is clear that the username is permanent and there is no deletion made possible or intended. It is accepted as such. 

Therefore, @kneerose we'll need to workaround this issue while testing by generating unique usernames for tests. For eg. using timestamps or uuids along with Faker.

For now, lets close the issue as not-a-bug but a design choice.

CC: @bosko-m @ValMBO
