### ISSUE TITLE
[BUG] Blank Screen Error When Accessing `edit_dRep` Page with Invalid dRep Registration

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1675]
## Context & versions
- I have registered my dRep with an invalid anchor dataHash and URL. When I try to access the edit_dRep page for the registered dRep with the invalid hash, a blank screen appears with the following error in the console:

![image](https://github.com/user-attachments/assets/a79fafa5-816e-412f-aabc-0912b1bcd07b)

![image](https://github.com/user-attachments/assets/605b75fd-d446-4763-9e8a-2c987c4ebb1e)

## Steps to reproduce
- Register a dRep with an invalid anchor URL and data hash.
- Navigate to view your dRep details.
- Click on the edit_dRep button and observe the error.

**Comment by kneerose** [comment]
@jdyczka I have tested it on the development, test environment, and the issue is no longer reproducible.
CC: @bosko-m

**Comment by bosko-m** [comment]
Closed as per the comment above.
