### ISSUE TITLE
The CI/CD workflows has to be cleaned up and fixed

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#168]
Investigate why storybook and lighthouse actions fails on every workflow execution and fix them.

**Comment by spannercode** [comment]
@bosko-m I think this issue can be closed:

Here are the GH actions link for storybook and lighthouse tests:
https://github.com/IntersectMBO/govtool/actions/workflows/test_storybook.yml
https://github.com/IntersectMBO/govtool/actions/workflows/lighthouse.yml

Regarding Lighthouse, while the github action is passing, it does not mean that there are no issues. 

The results are published here:
https://lighthouse-govtool.cardanoapi.io/app/projects/govtool/dashboard

And there are related issues:
- https://github.com/IntersectMBO/govtool/issues/1086
- https://github.com/IntersectMBO/govtool/issues/1409
- https://github.com/IntersectMBO/govtool/issues/2025

**Comment by bosko-m** [comment]
Closing as per the comment above.
