### ISSUE TITLE
[BUG] Replies to Comments on Proposals Not Immediately Visible Without Expansion

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1680]
## Context & versions
- When I reply to any comment on a proposal, the comment should be immediately visible without requiring the user to expand and view the reply.
- For reference, you can look at how YouTube handles replies: when you reply to a comment on YouTube, the reply is immediately visible, even though it may need to be expanded later.

## Steps to Reproduce
1. Navigate to any proposal.
2. Reply to an existing comment, or if no comments are available, add a comment and then reply to it.
3. Observe that you need to expand the comment thread to view the reply.

## Report reference
https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/100/#behaviors/dc8de5361d62fd689c0edc9aba05a8b4/25af2d0660ca2a4f/

**Comment by kneerose** [comment]
@teske00  any update on this ?

**Comment by teske00** [comment]
@kneerose Need to check with @MSzalowski if the latest version (0.3.4) of the PDF package is implemented in govtool
