### ISSUE TITLE
[Bug] Preview GovTool points to SanchoNet blockexplorer

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1682]
## Context & versions

- https://preview.gov.tools/

## Steps to reproduce

- Send any transaction on `preview.gov.tools`

## Actual behavior

- Click Show Transaction or any similar button, and youre taken to https://sancho.cexplorer.io

## Expected behavior

- Click Show Transaction or any similar button, and youre taken to https://preview.cexplorer.io

**Comment by Ryun1** [comment]
Thanks for the spot @nilscodes

**Comment by MSzalowski** [comment]
Fixed by #1684

**Comment by MSzalowski** [comment]
The fix I introduced depends on the network to which Voltaire GovTool is connected. Which means, that having GovTool connected to sancho - links to sancho.cexplorer.io but on preview it links to the preview.cexplorer.io

**Comment by Ryun1** [comment]
Perfect!
