### ISSUE TITLE
Control Govtool Functionality Based on Hardfork and Protocol Version

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1688]
### **Objective:**
- Implement a mechanism to restrict the use of govtool features until the specified hardfork has occurred. This will ensure that govtool transactions are only permitted when the protocol version exceeds 8 or after the hardfork is executed.

### **Implementation Details:**
- **UI:** Display on the govtool interface with the message: "Govtool features will be available after the hardfork," to inform users about the availability.
- **Transaction Restriction:** Configure the system to permit govtool transactions only when the protocol parameter version exceeds 8 or the hardfork has been completed.

**Comment by kneerose** [comment]
@m-i-k-e  is this a correct way forward?

**Comment by MSzalowski** [comment]
We should also have that in the acceptance criteria

**Comment by Ryun1** [comment]
I think we can close this one, as the ideas have been captured within
https://github.com/IntersectMBO/govtool/milestone/68
across a few tickets
