### ISSUE TITLE
Wallet related sentry issues

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#1699]
## Context & versions
Currently sentry reports all failure associated wallet interactions eg. wallet not enabled, not connected, user cancelled etc. Looking at the stacktrace on the error report, it is not always intuitive which is the cause of the issue. The newly added wallet tags, however, does give a better idea about the reason.

The proposition on this ticket is **to review and decide which error cases** related to the wallet interaction we would like to be reported on Sentry and **plan for the implementation of the changes**.

## Steps to reproduce
  1. Visit https://sanchogov.tools/
  2. Try to connect a wallet connected to the mainnet
  3. An error message is shown as expected.
  4. Visit sentry, select environment to be `beta`. You'll see an error report.

While the user experience is as expected for the user, there is not much value to have a sentry report for this.

## Screenshots
<img width="1437" alt="Screenshot 2024-08-08 at 09 49 56" src="https://github.com/user-attachments/assets/b76aa7de-2962-4b52-9978-c96490098db9">

<img width="1220" alt="Screenshot 2024-08-08 at 09 49 33" src="https://github.com/user-attachments/assets/63f1c698-d0de-4421-91ba-c5f48a7ce2ec">

## Actual behavior
Sentry reports are sent on every error cases related to the wallet interaction including the ones which are desired.

## Expected behavior
No sentry reports are sent for expected error cases.

**Comment by MSzalowski** [comment]
I agree, we shouldn't sent sentry events on every wallet scenario
