### ISSUE TITLE
Wallet connection lost in redelegation

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#17]
To reproduce:

As a user with a connected wallet that has already delegated their voting power to “Abstain”
Go to dashboard
Click “Change Drep”

Go through with the re-delegation, approve transaction, and sign, and you consistently get the “Opps” message. In other words, it fails.

If you refresh the browser, it works, otherwise it doesn’t.

Please see this video: https://www.loom.com/share/cd1a51e6bccb49b9966f00f8f7859358?sid=e4f40247-f7bf-498d-b3ed-2f61ec717566 

A related video: https://www.loom.com/share/b8c341a20b114410ba40a2ce8ff10c11?sid=6e9c94f5-f413-4454-a618-2a9b9d9f25a9

**Comment by bosko-m** [comment]
Moving this to the last known status before the migration to this project.
