### ISSUE TITLE
[Bootstrap] Remove ability to propose a treasury withdrawal

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1701]
### Why

Under bootstrapping phase treasury withdrawal actions cannot be submitted to chain, we should prevent users from proposing and then submitting these actions, as otherwise they will fail at submit time.

### What

We should prevent users from proposing treasury withdrawals.

Remove the option from the drop down
![image](https://github.com/user-attachments/assets/3199ce41-37c7-4dae-87f7-2eac2b4a9d95)

### How

- Should there be some technical way that GovTool read if it is in bootstrapping and then turn this off via PDF?
- Or do we use a feature flag on this?
- What is best?

---

### User Story

**Title**: Restrict Proposal Creation During Bootstrapping Phase

**User Story**: As an ada holder, I want to be restricted from creating proposals during the bootstrapping phase that cannot be submitted to the network, ensuring I only create valid proposals.

**Acceptance Criteria**

- Given that I am an ADA holder.
- When I attempt to create a new governance action proposal during the bootstrapping phase.
- Then I should only be able to select and create types of proposals that are allowed to be submitted to the connected network.

**Comment by Ryun1** [comment]
TODO @Ryun1 
- write a user story for this

**Comment by teske00** [comment]
@Ryun1 I will check, but I think we can disable this at any time on the PDF backend side by publishing/unpublishing the treasury GA type. In this way, we enable/disable the listing or creation of treasury GA. As we use strapi baceknd framework, with it we get a frontend dashboard where we can create a user who will have access to control the availability of GA types. Does this sound like an acceptable proposal for controlling the availability of GA types?

**Comment by Ryun1** [comment]
What do you think @MSzalowski ?

**Comment by teske00** [comment]
@MSzalowski We can enable/disable this anytime, I tested locally, just say when and for which environment. I can also create a user for you with access to our backend and permission for this.

**Comment by MSzalowski** [comment]
Let's do that!

**Comment by teske00** [comment]
@MSzalowski It's done on the preview environment, does it need to be done on another one? (https://preview.gov.tools/)

**Comment by bosko-m** [comment]
Only on preview for the moment.

**Comment by teske00** [comment]
Hi @Ryun1 , do you know how based on [this](https://z0656605b-zf5929b48-gtw.z937eb260.rustrocks.fr/epoch/params) response we can set a condition whether treasury GA is available or not? Which key and which value is important for us, so that we can automate this part

**Comment by Ryun1** [comment]
@teske00 

### Governance action availability across protocol versions

| Governance Action | `protocol_major` < 9 (before hardfork) | `protocol_major` = 9 (bootstrapping phase) | `protocol_major` > 9 (full governance) |
| --- | --- | --- | --- |
| 1. Motion of no-confidence | No | No | Yes |
| 2. Update committee and/or threshold and/or terms | No | No | Yes |
| 3. New Constitution or Guardrails Script | No | No | Yes |
| 4. Hard-Fork Initiation | No | Yes | Yes |
| 5. Protocol Parameter Changes | No | Yes | Yes |
| 6. Treasury Withdrawals | No | No | Yes |
| 7. Info | No | Yes | Yes |

**Comment by teske00** [comment]
Great, thanks Ryan!
