### ISSUE TITLE
[Bootstrap] Warn users that they are in bootstrapping phase via banner

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1702]
### Why

- The bootstrapping phase places some restrictions on what users can do within GovTool
- On the home page, we should warn users if the GovTool they on is connected to a network within bootstrapping phase

### What

- Place a dismissible banner on the main page which warns users IF this instance of GovTool is on a network which is in bootstrapping.
- The banner should offer a link to `docs.gov.tools` which describes the impact of bootstrapping on GovTool. 

### How

- @m-i-k-e design a beautiful banner, share the info of that here on this ticket
- We can then pass this beautiful banner to developer team

---

### User Story

**Title**: Warning for Bootstrapping Network in GovTool

**User Story**: As an ADA holder, I want to be warned that the network GovTool is connected to is in the bootstrapping phase, so I am aware that some features are disabled.

**Acceptance Criteria**

- Given that I am an ADA holder.
- When I access GovTool connected to a bootstrapping network.
- Then I should receive a warning notification indicating that the network is in the bootstrapping phase and that some features are disabled.
- And the warning banner should be dismissible.
- And the banner should include a link to docs.gov.tools explaining the impact of bootstrapping on GovTool functionalities.

**Comment by m-i-k-e** [comment]
This has to support both logged in and disconnected users - note to self

**Comment by m-i-k-e** [comment]
@MSzalowski You can make this now: Please note: 

- the banners are not dismissible.
- There is always a network banner unless it's MainNet, then, no banner.

Designs are in the Voltaire master Figma file here: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=7834-145819&t=hLlpXMOe0RpGkeDc-1
