### ISSUE TITLE
Showing SPO and CC vote totals

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1704]
### What?

- On GovTool's governance action details page GovTool should show vote totals for DReps, SPOs and CC.
- For simplicity, for now, lets render the same thing for all types of governance action
  - See [information](https://github.com/cardano-foundation/CIPs/blob/master/CIP-1694/README.md#requirements) on which governance actor type votes on which type of governance action. 

### Why?

- SPOs and CC vote on governance actions, these votes can inform the DReps on their votes
- SPO and CC vote totals are just useful information for everyone

### How?

- @m-i-k-e and team design how this could be rendered
- GovTool BE API adjusted to provide this information
- GovTool FE adjusted to render this new information using the designs

---

### User Story

**Title:** Display Vote Totals for DReps, SPOs, and CC on Governance Action Details Page

**User Story:** As a user of GovTool, I want to see the vote totals for DReps, SPOs, and CC on the governance action details page so that I can be informed about the voting landscape for any given governance action.

**Acceptance Criteria:**

- Given that I am a user of GovTool.
- When I navigate to the governance action details page.
- Then I should see vote totals for DReps, SPOs, and CC clearly displayed.
- And this information should be presented consistently across all types of governance actions.

**Comment by m-i-k-e** [comment]
This shows DReps, SPos and CC members.
Please discuss!
![hard fork](https://github.com/user-attachments/assets/854263e7-883b-4460-8405-332f73384d65)

**Comment by Ryun1** [comment]
LGTM!

**Comment by MSzalowski** [comment]
@m-i-k-e Is this design ready to be implemented?

**Comment by m-i-k-e** [comment]
It's not in Figma, and Kasia was going to make it today. But it will not change from this, just needs a mobile version.

**Comment by m-i-k-e** [comment]
Ok @MSzalowski Kasia will be working on these tomorrow (14 Aug). We will update the issue when they are ready for dev.

**Comment by m-i-k-e** [comment]
@MSzalowski This is done in Figma and ready to go: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=14751-92651&t=hLlpXMOe0RpGkeDc-1

**Comment by bosko-m** [comment]
Block is displayed, however there is an issue with counts for CC and SPOs. #1838
