### ISSUE TITLE
[USERSNAP] There's an issue in the drep creation flow. I created the associated 974DRep.jsonld file on github: https://github.com/romainPellerin/cardano-voltaire-drep/blob/main/974DRep.jsonld and received the error below (see screenshot).

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1707]
**Sender**: romain.pellerin@iohk.io
**Taken at**: https://preview.gov.tools/register_drep
**Fields**:
- Add a comment: There&#39;s an issue in the drep creation flow. I created the associated 974DRep.jsonld file on github: https://github.com/romainPellerin/cardano-voltaire-drep/blob/main/974DRep.jsonld and received the error below (see screenshot).

**Browser**: Chrome 127 (macOS Catalina)
**Screen size**: 1728x1117
**[Open #98 in Usersnap](https://app.usersnap.com/l/feedback/50c0f987-c959-47bc-bf9b-3efca78cc9ad?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
Should be using a link to the raw file;
- https://raw.githubusercontent.com/romainPellerin/cardano-voltaire-drep/main/974DRep.jsonld

rather than just a link to the repo
