### ISSUE TITLE
Give banner to inform users of which network the instance of GovTool is connected to

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1708]
### What?

- GovTool instances are connected to different networks
- Different networks have different characteristics so it is important for users to know this

### Why?

- We need to inform users which network the instance of GovTool is on, so they can set their wallets to the correct network.

### How?

- @m-i-k-e and team design how a informative banner could be used for this
- GovTool FE adjusted to render this new information using the designs

---

### User Story

**Title:** Display Network Information on GovTool

**User Story:** As a user of GovTool, I want to know which network the instance of GovTool is connected to, so I can set my wallet to the correct network.

**Acceptance Criteria:**

- Given that I am a user of GovTool.
- When I access GovTool.
- Then I should see an informative banner that clearly indicates the network the instance of GovTool is connected to.

**Comment by Ryun1** [comment]
First mockup from Mike

![sancho banner](https://github.com/user-attachments/assets/d1554861-5a45-4f55-8df4-de62a13d9bfe)

**Comment by l-br1** [comment]
you could use the same component we are using for the member area 
![Screenshot 2024-08-09 at 10 33 27](https://github.com/user-attachments/assets/03843ea1-6960-44b3-b4b2-8551f9a6686c)

**Comment by m-i-k-e** [comment]
Yeah, that will work. Thanks!

**Comment by m-i-k-e** [comment]
Question: @Ryun1 @l-br1:

The user story says:

> Given that I am a user of GovTool.
When I access GovTool.
Then I should see an informative banner that clearly indicates the network the instance of GovTool is connected to

This implies that the network should always be shown. I agree that this is better than 'sometimes' showing it.

This would make the banner permanent, however. I think we could look at different ways of displaying this next week.

**Comment by Ryun1** [comment]
> This would make the banner permanent, however. I think we could look at different ways of displaying this if that's the case.

Why dont we just show the banner on testnets? and then it is removed on mainnet?
this is how some dApps on Cardano do it

**Comment by m-i-k-e** [comment]
That was my idea at first.

**Comment by m-i-k-e** [comment]
So there are two banners: One for the network - the network banner shows when you're not on Mainnet. It always shows.

The other banner is the bootstrapping banner, which can show on any network (but SanchoNet).

Sometimes there is a need for both to show.

Examples:
![Banners completed](https://github.com/user-attachments/assets/05be63dc-60b9-46f1-a63f-005b57acb8be)

**Comment by m-i-k-e** [comment]
This has been passed to @kgrzonka  for final artwork.

**Comment by Ryun1** [comment]
Looking great @m-i-k-e 🤝
