### ISSUE TITLE
[USERSNAP] I'm not showing up in the list of DReps. 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1709]
**Taken at**: https://preview.gov.tools/dashboard
**Fields**:
- Add a comment: I&#39;m not showing up in the list of DReps. 

**Browser**: Chrome 123 (macOS Catalina)
**Screen size**: 1512x982
**[Open #99 in Usersnap](https://app.usersnap.com/l/feedback/d46d710b-ffd9-46ca-9367-432619a230b0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
This bug has been fixed
