### ISSUE TITLE
Enhance deployment script for conditional generation of BasicAuth configuration files

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#171]
### Background:

1. There is a script that generates configuration files before deploying an application.
2. Among these configuration files, two are specifically for configuring Basic Authentication (BasicAuth) for the application.
3. On some environments (like `beta`), these BasicAuth files should not be generated based on certain conditions.
4. **There's a false assumption in the current script that these files do not exist prior to generation.**
5. The process works as expected in Continuous Deployment (CD) workflows on GitHub Actions, where it's run in isolated containers.
6. However, when the script is run locally multiple times in a row, it fails due to the above assumption.

### Problem Statement:
The script does not account for existing BasicAuth configuration files when run locally multiple times, leading to failures in environments where these files should be conditionally generated or not generated at all.

### Goal:
To modify the script to accurately handle the presence of BasicAuth configuration files, ensuring it works correctly both in isolated CI/CD environments and when run locally multiple times.

### User Story:
As a developer, I want the deployment script to intelligently manage the generation of BasicAuth configuration files, so that it can be executed reliably both in automated CD workflows and during local development. This includes:

- Checking for the existence of BasicAuth configuration files before attempting to generate them.
- Applying the necessary conditions to determine whether these files should be generated for the current environment.
- Ensuring that the script's behavior is consistent across both isolated CI/CD environments and local development setups, preventing failures due to previously made assumptions about the state of the filesystem.

### Acceptance Criteria:

- [ ] The script checks for existing BasicAuth configuration files before generating new ones.
- [ ] The script correctly applies conditions to decide if BasicAuth configuration files should be generated, based on the target environment.
- [ ] The script performs as expected in both CI/CD environments (like GitHub Actions) and when run locally, even if executed multiple times in succession.
- [x] Documentation is updated to reflect the new checks and conditions applied by the script.

**Comment by bosko-m** [comment]
@MSzalowski Is this still relevant?

**Comment by MSzalowski** [comment]
Not blocked anymore
