### ISSUE TITLE
[USERSNAP] abstract is misspelt as on the review you submission screen "Abstrtact" this is for both info and treasury proposals

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1710]
**Taken at**: https://preview.gov.tools/proposal_discussion
**Fields**:
- Add a comment: abstract is misspelt as on the review you submission screen &#34;Abstrtact&#34; this is for both info and treasury proposals

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1536x864
**[Open #100 in Usersnap](https://app.usersnap.com/l/feedback/6860487a-0e92-48c4-8ce0-38dd774ff393?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
this has been fixed
