### ISSUE TITLE
[USERSNAP] Don't know if its just these current Governance actions but they are all displaying as "Data Formatted Incorrectly" Chrome browser, Windows 11

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1711]
**Sender**: matt@adamail.me
**Taken at**: https://preview.gov.tools/connected/governance_actions
**Fields**:
- Add a comment: Don&#39;t know if its just these current Governance actions but they are all displaying as &#34;Data Formatted Incorrectly&#34; Chrome browser, Windows 11

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1536x864
**[Open #101 in Usersnap](https://app.usersnap.com/l/feedback/6c1b14f1-8561-487e-86c0-d3da958cffdd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
known issue
