### ISSUE TITLE
[USERSNAP] unsure if governance proposal submitted, maybe needs error message? 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1712]
**Taken at**: https://preview.gov.tools/connected/governance_actions
**Fields**:
- Add a comment: unsure if governance proposal submitted, maybe needs error message? 

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1536x864
**[Open #102 in Usersnap](https://app.usersnap.com/l/feedback/7d39b322-30ee-409f-addb-2a014d57bd31?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
this is related to known issue submitting treasury actions
