### ISSUE TITLE
[Discovery] - How do deal with multiple version of guides (or not) for Sancho and un-Sancho

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1715]
This is a discussion on the implications of having two versions of guides. 

Do we need two versions, or can one version do with modifications?

**Comment by m-i-k-e** [comment]
Note: there are currently two versions of the guides: One is un-sanchoed - docs.gov.tools and docs.sanchogov.tools

**Comment by Ryun1** [comment]
I feel strongly that we just have one set of guides
Within these guides, we should explain the differences between networks/deployments of GovTool

**Comment by m-i-k-e** [comment]
@Ryun1 I agree, but we have two different apps. Whatever we do, it would be a good thing to have a list of the differences so we can see what we're looking at. Will do next week.

**Comment by bosko-m** [comment]
We will be using one source of truth.
