### ISSUE TITLE
[USERSNAP] Receive address on Treasury proposal form change

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1719]
**Taken at**: https://preview.gov.tools/proposal_discussion
**Fields**:
- Name of the idea or new feature: Receive address on Treasury proposal form change
- Please summarize your idea or new feature: Change the text to say either stake address or reward address, I assume they are the same as this was the only address accepted from the wallet. If i am wrong in that an explanation of where a reward address can be found in bech32 in the guide

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1536x864
**[Open #47 in Usersnap](https://app.usersnap.com/l/feedback/6b01162f-eb15-4ded-a52c-5945b2b8eb9d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
this has been improved now
![image](https://github.com/user-attachments/assets/9cddf42e-d6a3-46ce-b18e-b4ccfdc23683)
![image](https://github.com/user-attachments/assets/c0c10b59-1b58-40e6-86d6-ec0201cfd263)
