### ISSUE TITLE
[USERSNAP] Website is not showing the correct amount of funds in my wallet.  I am using Eternl wallet.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1721]
**Taken at**: https://preview.gov.tools/dashboard
**Fields**:
- Add a comment: Website is not showing the correct amount of funds in my wallet.  I am using Eternl wallet.

**Browser**: Chrome 123 (macOS Catalina)
**Screen size**: 1512x982
**[Open #103 in Usersnap](https://app.usersnap.com/l/feedback/7bd0df24-acd9-4e02-afb0-02b16c6edd9c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
this should be fixed now
