### ISSUE TITLE
🐛 Incorrect deposit amount reported via error message at proposal -> governance action time

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1729]
**Sender**: None
**Taken at**: https://sanchogov.tools/proposal_discussion/16
**Fields**:
- Add a comment: I have nearly tAda 100k in my SanchoNet Demos wallet. When I attempt to submit an info governance action I am told that I need at least 50k tAda to submit the action, and so the action cannot be submitted. 

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1368x912
**[View screen recording](https://resources.usersnap.com/company/127c73ca-bcdd-4a4a-89e5-a1faa2d0e4ca/screen_recording/c0d63875-c155-4be0-9ee7-e5ea977f2d0c_screen_recording_71ccf342-7ee7-44cb-9004-aa1a4afc60d0.webm?etag=c26ad41a748f1ce5f219eb23b11b9a91)**
**[Open #104 in Usersnap](https://app.usersnap.com/l/feedback/c2e0861b-0d84-4491-86e4-5357695337af?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
error message reporting incorrect value for proposal deposit size (is currently 100K on Sancho)
![image](https://github.com/user-attachments/assets/9cfa7eda-1b88-4431-9468-289560a98e48)

**Comment by Ryun1** [comment]
Not sure why this goes wrong, perhaps it is pulling incorrect params from `getItemFromLocalStorage(PROTOCOL_PARAMS_KEY);`

https://github.com/IntersectMBO/govtool/blob/develop/govtool/frontend/src/hooks/forms/useCreateGovernanceActionForm.ts#L243

**Comment by MSzalowski** [comment]
And @Ryun1 gov action deposit on [Sancho Beta](https://sanchogov.tools/) is 100k - that can be checked on the:
Dev Console > Application > Local storage > protocol_params (pic rel)

![Zrzut ekranu z 2024-08-13 14-36-53](https://github.com/user-attachments/assets/f234a9e9-9491-4f15-b27b-314c38d0292e)

**Comment by teske00** [comment]
@MSzalowski @Ryun1 Yes, it is an error on the modal in the PDF. We didn't know this state existed in localstorage, we will implement a dynamic value change in the modal depending on the state in localstorage

**Comment by teske00** [comment]
@MSzalowski We have updated the PDF package to version 0.3.5, it is ready for import

**Comment by Ryun1** [comment]
This is fixed
