### ISSUE TITLE
Agree the format of on-chain governance action data coming from DB-Sync

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/govtool#173]
As a developer working on the display of governance actions in GovTool, I want to know the format of governance action data that I should expect coming from DB-Sync, so that I don't have to make guesses, and so that I can minimise breaking changes. 

#########

Given that I am examining the output relating to governance actions in DB-Sync

When there are changes to this output

Then:
- JSON key names remain consistent (i.e. the same values are referenced by the same keys)
- The changes are predictable 
- The changes where announced ahead of time

############

Given that I am examining the output relating to governance actions in DB-Sync

When I  compare different types of governance action

Then the only difference in key names and the structure of the JSON output are differences that need to exist, due to different variables being contained in different governance action types (e.g. Treasury Withdrawal governance actions have a withdrawal amount and address, whereas an Info governance action will not).

###########

Definition of done: There is an agreed structure for the output of governance action data from DB-Sync between the GovTool team and DB-Sync team, a plan of how to minimise the changes in the future, and a method of notifying us of changes in the future.

**Comment by Ryun1** [comment]
very old, lets close
