### ISSUE TITLE
[USERSNAP] hello Lorenzo, does this work?

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1743]
**Taken at**: https://preview.gov.tools/connected/governance_actions
**Fields**:
- Add a comment: hello Lorenzo, does this work?

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1368x912
**[Open #107 in Usersnap](https://app.usersnap.com/l/feedback/d4127a65-9515-4ec8-a42b-6b89cca17182?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Thomas-Upfield** [comment]
It seems it does work. 😂
