### ISSUE TITLE
[USERSNAP] Drep smart contract flaggging

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1744]
**Taken at**: https://sanchogov.tools/
**Fields**:
- Name of the idea or new feature: Drep smart contract flaggging
- Please summarize your idea or new feature: A DRep BOB will specialize on voting on topic X but wants to follow DRep Alice on topic Y Z X and will through a smart contract follow the vote of Alice. How can we flag and show this to delegators to BOB?

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1920x1080
**[Open #50 in Usersnap](https://app.usersnap.com/l/feedback/8d5434f6-3aa2-415c-ac13-37200e2c6066?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
This will have to be done manually via the DRep metadata
