### ISSUE TITLE
[USERSNAP] (ex. github) to  (e.g. github)

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1748]
**Taken at**: https://preview.gov.tools/register_drep
**Fields**:
- Name of the idea or new feature: (ex. github) to  (e.g. github)
- Please summarize your idea or new feature: (ex. github) to  (e.g. github)

**Browser**: Chrome 127 (macOS Catalina)
**Screen size**: 1362x802
**[Open #54 in Usersnap](https://app.usersnap.com/l/feedback/c0a07ad9-ddaa-4e12-b292-ec5ee0b9d931?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
Fixed by https://github.com/IntersectMBO/govtool/pull/2026
