### ISSUE TITLE
[USERSNAP] DTW: Localization 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1751]
**Taken at**: https://sanchogov.tools/dashboard
**Fields**:
- Name of the idea or new feature: DTW: Localization 
- Please summarize your idea or new feature: Allow DReps to create multiple metadata profiles in different languages so that DReps can target delegation from people in languages other than and in addition to English. 
- Any additional details: DRep Tooling Workshop feedback

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1368x912
**[Open #55 in Usersnap](https://app.usersnap.com/l/feedback/d95a4d4f-f456-4146-8dda-895be5b6026b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
duplicate to https://github.com/IntersectMBO/govtool/issues/1745
