### ISSUE TITLE
[USERSNAP] DTW: Delegate to multiple DReps

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1752]
**Taken at**: https://sanchogov.tools/dashboard
**Fields**:
- Name of the idea or new feature: DTW: Delegate to multiple DReps
- Please summarize your idea or new feature: Allow people to delegate their voting power to multiple DReps.
- Any additional details: DRep Tooling Workshop feedback.

It is unclear what the problem is that the participant wanted to solve here. Is it that delegation and redelegation is too difficult and that is why they want to spread their DReps? Is it that they want to spread their exposure?

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1368x912
**[Open #56 in Usersnap](https://app.usersnap.com/l/feedback/d92569ed-f1ce-47a3-8af4-b6f93035c611?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
duplicate https://github.com/IntersectMBO/govtool/issues/1754
