### ISSUE TITLE
[USERSNAP] DTW: filter DReps based on location

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1753]
**Taken at**: https://sanchogov.tools/dashboard
**Fields**:
- Name of the idea or new feature: DTW: filter DReps based on location
- Please summarize your idea or new feature: Delegating Ada Holders can find DReps based on their location
- Any additional details: DRep tooling workshop feedback

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1368x912
**[Open #57 in Usersnap](https://app.usersnap.com/l/feedback/92139d94-ea10-4326-ad3e-97914c3ce678?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
This would need for a change in the underlying DRep registration metadata standard
If these changes were made, GovTool could certainly incorporate this
