### ISSUE TITLE
[USERSNAP] Links to the other governance tools within GovTool

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1756]
**Taken at**: https://sanchogov.tools/dashboard
**Fields**:
- Name of the idea or new feature: Links to the other governance tools within GovTool
- Please summarize your idea or new feature: It would be nice to have the links to DRep campaign platform and CC Portal on the drawer of GovTool to easily navigate between supporting platforms

**Browser**: Chrome 127 (macOS Catalina)
**Screen size**: 1447x738
**[Open #59 in Usersnap](https://app.usersnap.com/l/feedback/00011367-4c4a-437c-94a2-c1cefe45042f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
good idea

**Comment by m-i-k-e** [comment]
This is done in Figma here: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/branch/ymWVgwiQocFfcf4AZBz7lT/Voltaire---GOV-TOOL?m=auto&node-id=7834-151129&t=EmU8suJhxi52BkQ2-1 and is covered by issue #1995

**Comment by m-i-k-e** [comment]
Closing as this is the same as #1995
