### ISSUE TITLE
[USERSNAP] Community Flagging of Impersonators 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1764]
**Taken at**: https://sanchogov.tools/dashboard
**Fields**:
- Name of the idea or new feature: Community Flagging of Impersonators 
- Please summarize your idea or new feature: Some way for the community to flag DRep profiles that impersonate others. This will allow people to vote for the real deal. 
- Any additional details: DRep Tooling Workshop suggestion.

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1368x912
**[Open #62 in Usersnap](https://app.usersnap.com/l/feedback/d99c67e5-16d9-4861-ba1d-314fed7697ce?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by jdyczka** [comment]
duplicate #1746
