### ISSUE TITLE
[USERSNAP] DTW: searchable tags 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1766]
**Taken at**: https://sanchogov.tools/dashboard
**Fields**:
- Name of the idea or new feature: DTW: searchable tags 
- Please summarize your idea or new feature: DReps should have searchable tags that can allow them to signal their political affiliation or location or other things about them
- Any additional details: DRep Tooling Workshop suggestion

**Browser**: Chrome 127 (Windows 10)
**Screen size**: 1368x912
**[Open #64 in Usersnap](https://app.usersnap.com/l/feedback/22b85c81-82fb-4dc1-b654-fac3f0c585de?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
duplicate https://github.com/IntersectMBO/govtool/issues/1747
