### ISSUE TITLE
🐛 Blocked on Verify your Identity

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1780]
### Area

Proposal Pillar

### Domain

sanchogov.tools

### Context

I attempted to test the Proposal Discussion Forum, but I got stuck at the "Verifying Your Identity" step. I signed in with my wallet multiple times, but nothing happened.

### Steps to reproduce

1. Connect your wallet
2. Click on "verify your identity"
3. Signed my wallet

### Actual behavior

![Image](https://github.com/user-attachments/assets/268fd58d-9ac3-4928-bfa9-4152b5d1dde9)

### Expected behavior

After signing my wallet I should be redirected to the dashboard

**Comment by vpaunovic** [comment]
We checked on Preview. It is handled, and working now. It can be closed.

@bosko-m @ValMBO
