### ISSUE TITLE
💡

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1783]
### Area

Proposal Pillar

### Is there new design needed?

No

### What?

Change the copy for "Links to additional content or social media contacts (up to 7 entries)"

![Image](https://github.com/user-attachments/assets/8dff2971-866a-4e2c-8f04-d4d4b5e0b4c0)

### Why?

-

### How?

-

**Comment by Ryun1** [comment]
duplicate issue:

https://github.com/IntersectMBO/govtool/issues/1787
https://github.com/IntersectMBO/govtool/issues/1786
https://github.com/IntersectMBO/govtool/issues/1784
https://github.com/IntersectMBO/govtool/issues/1785
