### ISSUE TITLE
💡TYPO on  (maiximum of 7 entries)

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1784]
### Area

Proposal Pillar

### Is there new design needed?

No

### What?

Change the copy to "Links to additional content or social media contacts (up to 7 entries)"

![Image](https://github.com/user-attachments/assets/7aaa640f-7b2a-4316-b0c1-da4b61b833f9)

### Why?

-

### How?

-

**Comment by Ryun1** [comment]
duplicate issue:

https://github.com/IntersectMBO/govtool/issues/1787
https://github.com/IntersectMBO/govtool/issues/1786
https://github.com/IntersectMBO/govtool/issues/1785
https://github.com/IntersectMBO/govtool/issues/1783
