### ISSUE TITLE
💡 Delete "Subtext to describe something if needed" on the second page

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1788]
### Area

Proposal Pillar

### Is there new design needed?

No

### What?

 Delete "Subtext to describe something if needed" on the second page

![Image](https://github.com/user-attachments/assets/649bb400-7452-45ed-b3a6-47436e54acdb)

### Why?

na

### How?

na

**Comment by Ryun1** [comment]
duplicate:
- https://github.com/IntersectMBO/govtool/issues/1741
