### ISSUE TITLE
💡 Change the copy of adding a poll

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1789]
### Area

Proposal Pillar

### Is there new design needed?

No

### What?

Change the copy  "The poll will be pinned to the top of your comments list, and you can close it whenever you like. Opening a new poll will automatically close the previous one, which will then appear as a comment in the comments feed."

![Image](https://github.com/user-attachments/assets/7f98366c-c5bd-4810-b1b7-24c212e9b058)

### Why?

na

### How?

na

**Comment by Ryun1** [comment]
duplicate with;
- https://github.com/IntersectMBO/govtool/issues/1792
- https://github.com/IntersectMBO/govtool/issues/1790
- https://github.com/IntersectMBO/govtool/issues/1791
