### ISSUE TITLE
💡 Change the copy "adding a poll"

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1790]
### Area

Proposal Pillar

### Is there new design needed?

No

### What?

Change the copy on adding a poll  "**The poll will be pinned to the top of your comments list, and you can close it whenever you like. Opening a new poll will automatically close the previous one, which will then appear as a comment in the comments feed.**"

![Image](https://github.com/user-attachments/assets/7615f1fa-735b-4f99-85d1-e31d94870749)

### Why?

na

### How?

na

**Comment by Ryun1** [comment]
duplicate with;
- https://github.com/IntersectMBO/govtool/issues/1792
- https://github.com/IntersectMBO/govtool/issues/1789
- https://github.com/IntersectMBO/govtool/issues/1791
