### ISSUE TITLE
💡 change the copy on Adding a poll

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1791]
### Area

Proposal Pillar

### Is there new design needed?

No

### What?

Change the copy "The poll will be pinned to the top of your comments list, and you can close it whenever you like. Opening a new poll will automatically close the previous one, which will then appear as a comment in the comments feed."

![Image](https://github.com/user-attachments/assets/7bfcb183-4ebc-4bf4-90be-7d22bdbbe99d)

### Why?

na

### How?

na

**Comment by Ryun1** [comment]
duplicate with;

https://github.com/IntersectMBO/govtool/issues/1792
https://github.com/IntersectMBO/govtool/issues/1789
https://github.com/IntersectMBO/govtool/issues/1790
