### ISSUE TITLE
GovTool doesn't recognise wallet account changing

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#18]
To reproduce:

Have demos wallet connected, with an account that has a stake key, has delegated voting power to a different (from connected wallet) dRep, and is registered as a dRep, also there are some GAs that have been voted on.

Change wallet account to one without stake key

Issue: The interface still shows that I’m connected to the old, stake-key enabled account.

Continuing:

Click “Review and Vote” on the GA panel

Issue: Old wallet’s voting patterns are still showing

Continuing:

Select “Voted”

Pick a GA that’s voted on

Change the vote on that GA

Sign and confirm the transaction in wallet

Get Error message “Please try again later'

Issues: 

User should not be able to see GAs from other wallet

Should not be able to vote on other GAs

Error message is not correct, and tells user nothing.

See this video: 

https://www.loom.com/share/82120f4ec7e349bba8e04068a13fca33?sid=caa6f3e0-e3e1-4d96-9f21-87fc5411649a

**Comment by m-i-k-e** [comment]
I think that this has been fixed. @m-i-k-e you can retest it!
