### ISSUE TITLE
🐛 Mainnet instance does not allow mainnet wallets connect

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1807]
### Area

Wrapper

### Domain

Custom setup

### Which wallet were you using?

demos 1.8.2

### Context

When connecting a mainnet wallet, you get an error

### Steps to reproduce

Try to connect a mainnet wallet to `gov.tools`

### Actual behavior

error message 
![image](https://github.com/user-attachments/assets/6c9941dd-a317-4308-9262-ff70514299d6)

### Expected behavior

It only lets mainnet wallets connect

**Comment by MSzalowski** [comment]
@mpavlovicbb What is the `VITE_NETWORK_FLAG` value set on mainnet?

**Comment by mpavlovicbb** [comment]
Empty string.

**Comment by mpavlovicbb** [comment]
The setup changed based on Miha's instructions.
