### ISSUE TITLE
Fix configuration issue for SanchoNet Cardano DB Sync in Docker environment

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#181]
### User Story

As a DevOps engineer responsible for the Cardano blockchain infrastructure on GovTool, I need to ensure that the SanchoNet Cardano DB Sync operates correctly within a Docker environment. Currently (ghcr.io/intersectmbo/cardano-db-sync:sancho-4-0-0), the DBSync component logs an error related to the inability to parse the conway-genesis.json file, indicating a missing key in the poolVotingThresholds. This problem seems to arise from the Docker image's incorporated configuration files for the sanchonet network, which worked without issues in the previous version (ghcr.io/intersectmbo/cardano-db-sync:sancho-3-0-0).

### Acceptance Criteria:

- [x] **Identify the Root Cause:** Investigate the cause of the error message indicating the missing motionNoConfidence key when parsing conway-genesis.json in the Docker environment. This involves comparing the configuration files included in the current Docker image against those from the previous version and the correct configurations available at the official documentation site.

      This part is partly done and results are passed to the DBSync team.

- [x] **Adjust Deployment Configuration Locally:** Update the deployment configuration to ensure that the correct and updated configuration files for DBSync are used, regardless of the difficulties presented by the current Docker image's built-in configurations. This may include providing a custom volume with the necessary files and adjusting scripts to accommodate these changes.

- [ ] **Adjust Deployment Configuration In CD:** Update the deployment configuration to ensure that the CI/CD workflows aligns with the local version of the deployment process and performs deploys accordingly to the adjustments in the DBSync execution schema.

- [ ] **Test and Validate:** Ensure that with the adjusted configurations, the Cardano DB Sync successfully parses the conway-genesis.json file and communicates correctly with the Cardano Node. This involves running integration tests to verify the interaction between the DBSync and the Node.

- [ ] **Monitor for Upstream Fixes:** Keep track of the issue reported on GitHub (https://github.com/IntersectMBO/cardano-db-sync/issues/1629) for a permanent fix to this problem. Once the upstream issue is resolved, evaluate and plan the removal of any temporary fixes or workarounds implemented as part of this user story.

- [ ] **Documentation:** Update internal documentation to reflect the changes made to the deployment configuration and any temporary measures taken. Include notes on the issue for future reference and possible rollback instructions if the upstream fix requires changes to the deployment setup.

### Notes:

- The resolution of this user story is critical for maintaining the integrity and smooth operation of the Cardano blockchain infrastructure within our organization.
- The DevOps team must ensure that any changes made are backward compatible and do not disrupt existing operations or data synchronization processes.
- Collaboration with the Cardano DB Sync development team may be necessary to gain insights into the issue and potential fixes.

**Comment by bosko-m** [comment]
@MSzalowski Is this still relevant?

**Comment by MSzalowski** [comment]
Not blocked anymore
