### ISSUE TITLE
🐛 Use stake key for proposal forum identity

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1810]
### Area

Proposal Pillar

### Domain

sanchogov.tools

### Which wallet were you using?

demos 1.8.2

### Context

When authenticating users for proposal discussion forum they sign data with their payment key.

This implies to me that we are using payment keys to identify users, this is probably not ideal
Some wallets generate multiple payment keys per wallet account, this could lead us proposal forum to misidentifying the users

It would be a better idea to use stake keys as a proxy for identity as multi-stake key wallets are not prevalent within the ecosystem
furthermore at wallet connection time govtool forces users with multi-stake key wallet to choose the stake key, meaning each connection to govtool is with one stake key at a time

### Steps to reproduce

Connect to proposal discussion forum

### Actual behavior

Signing with payment key

![image](https://github.com/user-attachments/assets/2255a2c2-f22d-4e9d-a27d-737417b24d5c)

### Expected behavior

Signing with stake key

**Comment by vpaunovic** [comment]
Its done. Ready to go to QA after it is implemented on GovTool.

@bosko-m @Ryun1 @ValMBO

**Comment by Ryun1** [comment]
LGTM

also
to make things easier, we should move to have the PDF UI and PDF BE in one repo, in the near future
