### ISSUE TITLE
[USERSNAP] test from dev

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1831]
**Taken at**: https://dev-sanchonet.govtool.byron.network/dashboard
**Fields**:
- Add a comment: test from dev

**Browser**: Chrome 126 (macOS Catalina)
**Screen size**: 1440x900
**[Open #109 in Usersnap](https://app.usersnap.com/l/feedback/2e126df8-f112-4eee-ae93-eca4c7f156ef?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
😲
