### ISSUE TITLE
🐛 Cannot submit treasury proposal as governance action

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1845]
### Area

Proposal Pillar

### Domain

sanchogov.tools

### Which wallet were you using?

demos 1.8.2

### Context

It fails trying to build the transaction with the treasury withdrawal inside of it
Giving CSL error `Use add_with_plutus_witness instead.`

![image](https://github.com/user-attachments/assets/007a05a6-3aad-4872-b1ad-baaaa6bd8417)

### Steps to reproduce

- Create a proposal, and then try and submit as a GA

### Actual behavior

Cant progress past storing metadata

### Expected behavior

Wallet popups up to sign the transaction

**Comment by vpaunovic** [comment]
@MSzalowski Can you maybe look at this? I think that probably this is on GovTool side

**Comment by MSzalowski** [comment]
Will do today! :saluting_face:

**Comment by spannercode** [comment]
This is still an issue. CC: @bosko-m 
![Image](https://github.com/user-attachments/assets/1029eb07-2ad2-4a71-8eeb-17181b1548e3)

**Comment by MSzalowski** [comment]
Tag: Proposal Pillar is because it affects the submission in proposal pillar, but the logic is on the wrapper level. Just to clarify

**Comment by spannercode** [comment]
I'm able to still reproduce this issue on sanchogov.tools and preview.gov.tools. Is it pending deployment?

**Comment by MSzalowski** [comment]
Deployment is done. Regarding the wrapper and transaction creation - that should not be an issue, however we still need an update of pdf package to make it working.

Will be fixed with #2378
