### ISSUE TITLE
💡 Tweak CIP119 support to match final designs

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1850]
### Area

Voting Pillar

### Is there new design needed?

Yes

### What?

- @MSzalowski and team have added CIP119 support ahead of designs being finalised
- Once designs finalised, then the team can tweak the existing implementation to match the designs

### Why?

- We must match the great designs!

### How?

shh

### (Optional) User Story with acceptance criteria

N/A
/

**Comment by m-i-k-e** [comment]
These designs are on a Figma branch, awaiting Kasia's work on mobile screens. They are currently here for preview: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/branch/ggPAEAFM3AkOWCWBQ0B0fK/Voltaire---GOV-TOOL?m=auto&node-id=14978-94364&t=WKpk6kk3gudFi9qd-1

**Comment by m-i-k-e** [comment]
When the mobile designs are done, we will merge them to the master Figma file and rationalise the changes in other templates.

**Comment by m-i-k-e** [comment]
Can't be tested now, as DReps registered don't show up: https://www.loom.com/share/350b396abca240478331bc77a99c878f?sid=5eea440f-0639-4fd1-bc69-d5f013b0df8e
