### ISSUE TITLE
Change logo to Cardano GovTool

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#1851]
### Area

Wrapper

### Is there new design needed?

Yes

### What?

Change the logo from Voltaire to Cardano GovTool

### Why?

To better reflect the narrative around the tooling

### How?

https://www.figma.com/design/8MJHuaTfHGLnuicZuXquA6?node-id=4610-171#928323909

![Image](https://github.com/user-attachments/assets/446fe482-6a66-4fae-8d6a-b5bbaec9be6f)

**Comment by m-i-k-e** [comment]
Use this logo: 
![Cardano GT logo](https://github.com/user-attachments/assets/fbd5d114-4476-4ea4-b48b-8ac6ee6f95d8)

**Comment by bosko-m** [comment]
Verified on Sancho.
