### ISSUE TITLE
Change copy to Cardano GovTool

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#1852]
### Area

Other

### Is there new design needed?

Yes

### What?

Change copy from Voltaire GovTool to Cardano GovTool

### Why?

To better reflect the narrative of the voting.

### How?

Throughout the website, replace all occurrences of Voltaire GovTool to Cardano GovTool.

**Comment by m-i-k-e** [comment]
All references to Sanchonet changed to "Cardano" on the master Figma file

**Comment by bosko-m** [comment]
Verified on Sancho.
