### ISSUE TITLE
Change the GitBook docs to reflect the change from Voltaire GovTool to Cardano GovTool

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#1854]
### Area

Other

### Is there new design needed?

Yes

### What?

Change the GitBook docs to reflect the change from Voltaire GovTool to Cardano GovTool

### Why?

To reflect the naming change from Voltaire to Cardano GovTool.

### How?

Change each occurrence of Voltaire GovTool to

**Comment by Ryun1** [comment]
@m-i-k-e have a look, https://docs.gov.tools/
Let me know feedback on the structure, the content needs work
