### ISSUE TITLE
🐛  /api/drep/info/{drepId} - Missing off chain DRep metadata

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#1856]
### Area

-

### Domain

sanchogov.tools

### Which wallet were you using?

Not wallet related

### Context

Fetch DRep info of any DRep that has been registered with CIP-119 compliant metadata.

### Steps to reproduce

1. Register as a DRep providing all the metadata
2. Wait until transaction finishes
3. Check DRep details and provided under /api/drep/info response

### Actual behavior

None of the CIP-119 metadata is provided

### Expected behavior

[off_chain_vote_drep_data](https://github.com/IntersectMBO/cardano-db-sync/blob/kderme/13.4.0.0/doc/schema.md#off_chain_vote_drep_data) should be populated with data and provided under /ap/drep/info response

(at this moment not sure whether it is db-sync related issue or wrong CIP-119 metadata generation by GovTool itself)

**Comment by vpaunovic** [comment]
@Ryun1 @bosko-m This should not be related to Proposal Pillar I think :)

**Comment by MSzalowski** [comment]
That is definitely not a proposal pillar, I must have added that mistakenly

**Comment by vpaunovic** [comment]
@MSzalowski Github actions bot added it somehow

**Comment by Ryun1** [comment]
> @MSzalowski Github actions bot added it somehow

Damn who wrote that crappy bot?! haha

**Comment by MSzalowski** [comment]
It could be me setting that pillar, bot is great :saluting_face:

**Comment by bosko-m** [comment]
@MSzalowski @Ryun1 Moving to a milestone post bootstrap release.

**Comment by jdyczka** [comment]
@bosko-m For some DReps I'm getting this error from dbsync 
```
Error Offchain Voting Anchor: JSON decode error from when fetching metadata from Just https://metadata-govtool.cardanoapi.io/data/Hulda resulted in : \"Error in $['@context']: key \\\"@language\\\" not found\"
```
CIP-100 states that it SHOULD be required, not MUST

> The @context field SHOULD specify a @language property, which is an ISO 639-1 language string, to define a default language for the whole document 

Previously we haven't been adding the `@language` field, so for dbSync to successfully validate DReps created by GovTool, either dbSync would have to accept metadata with no `@language` key or users would have to re-generate the metadata
