### ISSUE TITLE
[USERSNAP] mainnet feedback

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1864]
**Taken at**: https://gov.tools/
**Fields**:
- Add a comment: mainnet feedback

**Browser**: Chrome 128 (macOS Catalina)
**Screen size**: 2560x1440
**[Open #110 in Usersnap](https://app.usersnap.com/l/feedback/da24e0d5-e448-45c6-9e5a-9f569c44b474?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
This was a test from me, I was showing that Usersnap works from the mainnet instance
