### ISSUE TITLE
🐛 Missing test ids on Governance Action details page

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1875]
### Area

Voting Pillar

### Domain

dev-sanchogov.tools

### Context

Test IDs are missing on the new components of the governance action details page. The missing test IDs are as follows:
dRep
- dRepYesVotes
- dRepNoVotes
- dRepAbstainVotes

SPOs
- poolYesVotes
- poolNoVotes
- poolAbstainVotes

CC
- ccYesVotes
- ccAbstainVotes
- ccNoVotes

### Steps to reproduce

1. Register as a dRep.
2. Navigate to  Governance Actions
3. View any govaction
4. Observe test id of dReps,SPOs and CC votes
5. Click show votes and Observe test ids of dRep votes

### Actual behavior

![image](https://github.com/user-attachments/assets/e7e854b0-471e-49d0-b76c-7861f6e50560)

![image](https://github.com/user-attachments/assets/7516a962-f73f-40ac-8b09-0112721fee67)

![image](https://github.com/user-attachments/assets/3089ab57-7151-4f0f-a795-ed0327e1a9d4)

![image](https://github.com/user-attachments/assets/c0ad4b8d-2b54-4d6d-8552-c3feaaabe8f1)

![image](https://github.com/user-attachments/assets/5223bd65-23c9-45be-b817-c25be641d231)

![image](https://github.com/user-attachments/assets/ee4768a6-4687-4a0a-864c-0a6a741d5a04)

### Expected behavior

The page should include appropriate Test IDs for all display text.

### Allure Report
- [4K. Should display correct vote counts on governance details page for disconnect state](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/139/#behaviors/1523ff4143db0faaf245e2252e8ca520/e8a05461d8e13c87/)
- [ 4G. Should display correct vote counts on governance details page for DRep](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/101/#behaviors/1523ff4143db0faaf245e2252e8ca520/72b9602618d80cf1/)

**Note**: Please ensure that appropriate Test IDs are added whenever a new component is introduced.

**Comment by kneerose** [comment]
@jdyczka @MSzalowski  , any updates on this? I couldn't find any test IDs for the components mentioned above.

**Comment by kneerose** [comment]
I''ve located the missing test IDs mentioned above. The test IDs are now available in the dev environment.
This issue can be closed now. CC: @bosko-m

**Comment by bosko-m** [comment]
Closing as per the comment above.
