### ISSUE TITLE
🐛 DReps unable to vote on Info actions in bootstrapping

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1876]
### Area

Voting Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

demos 1.8.2

### Context

- On a bootstrapping network, DReps should be able to vote on Info actions
- Currently on Preview they cannot
- See DRep https://preview.gov.tools/connected/drep_directory/drep19
- See me try to vote

https://github.com/user-attachments/assets/411d04c4-d88f-472e-96dc-531904922ca7

### Steps to reproduce

1. register as DRep on bootstrapped network
2. try to vote on an Info action

### Actual behavior

The vote option is not shown to DReps/direct voters on Info actions in bootstrapping

### Expected behavior

The vote option should be shown to DReps/direct voters on Info actions in bootstrapping

**Comment by bosko-m** [comment]
@Ryun1 Whats the experience on Sancho?

**Comment by Ryun1** [comment]
@bosko-m 

> @Ryun1 Whats the experience on Sancho?

SanchoNet is not in bootstrapping so not the same
and SanchoNet instance dead
