### ISSUE TITLE
🐛 Get caught and can only view one governance action

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1890]
### Area

Voting Pillar

### Domain

preview.gov.tools

### Context

Once you view one governance action, every time I try to view another it takes me back to the first

In video I get stuck viewing the one hardfork

https://github.com/user-attachments/assets/1b0f91e9-bfd0-457f-9f94-af0f987ecfa2

### Steps to reproduce

1. view a governance action
2. go back
3. try to view another governace action

### Actual behavior

Can only view that one GA

### Expected behavior

I can view all the GAs

**Comment by Ryun1** [comment]
Only seems to happen when wallet connected

**Comment by MSzalowski** [comment]
Navigation (state.proposal) needs to be cleared up and refreshed - Will you be able to handle that?

**Comment by Ryun1** [comment]
> Navigation (state.proposal) needs to be cleared up and refreshed - Will you be able to handle that?

fixed!
