### ISSUE TITLE
🐛 DRep metdata validation

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1894]
### Area

Voting Pillar

### Domain

gov.tools

### Context

- Data Not Verifiable error for nearly all DRep registrations
- Seems like the hash check is not working properly
- Even when the metadata files look good and should be valid

### Steps to reproduce

1. look at DRep directory and look at detailed view of DReps

### Actual behavior

- nearly all DReps with correct metadata get the Data Not Verifiable error 

### Expected behavior

- DRep metadata is rendered without error

**Comment by Ryun1** [comment]
might help to bump the DBSync version to the latest

**Comment by MSzalowski** [comment]
I've tested on Sancho with sorting by Registration date:

https://github.com/user-attachments/assets/7fa90380-35d3-4101-bb58-5d7527f947d9

After checking the logs in the metadata validation service, for cases where the validation failed - I could not find any error either.

I would have to have access to a specific case to be able to properly verify this issue.

**Comment by MSzalowski** [comment]
@Ryun1 Could you please provide a link for the specific DRep for which the error occurs?

**Comment by gitmachtl** [comment]
> @Ryun1 Could you please provide a link for the specific DRep for which the error occurs?

you can test mine on preview if you like, also on mainnet: 
`drep1mkmnzmtlflcadyyy7g6ju3sn9ppcrut5wn73x00mfwmw642g5qy`

dbsync via koios says valid=true
