### ISSUE TITLE
🐛  Governance Action Vote Option Not Displayed Correctly for Registered dRep

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1896]
### Area

Voting Pillar

### Domain

dev-sanchogov.tools

### Context

I encountered an issue while attempting to vote on a governance action using a registered dRep. The vote option does not initially appear. However, when I navigate to any info action and reload the page, the vote option is displayed. Additionally, the vote option disappears if I navigate back to the dashboard, reload the page, and then navigate to any governance action again.

### Steps to reproduce

1. Connect to the wallet.
2. Register as a dRep.
3. Navigate to any governance action.
4. Observe the governance action details.
5. Navigate to an info action and reload the page.
6. Navigate back to the dashboard, reload the page.
7. Navigate to any governance action and observe the vote option.

https://www.loom.com/share/3544aac5002b41b9b67fdc78abcaf9da?sid=8a7aca58-9bb7-4612-91b3-f1dd78182b32

### Actual behavior

The vote option is not displayed initially but appears after reloading the page on an info action. It disappears again when navigating back to the dashboard and then to any governance action.
Initial State 

![image](https://github.com/user-attachments/assets/337bfde0-035a-424a-bcb8-f36527301d64)

After Reloading on Info Proposal Details Page and Returning to the Previous Governance Action Details Page:

![image](https://github.com/user-attachments/assets/1ff72ad3-3a85-4760-9b3e-17c1fb741f15)

After Navigate back to dashboard and Returning to the Previous Governance Action Details Page: 

![image](https://github.com/user-attachments/assets/42e41b93-f150-4b1c-b59e-9cffc752f76a)

### Expected behavior

The vote option should be displayed consistently for registered dReps without requiring a page reload or navigation workaround.

**Comment by MSzalowski** [comment]
I found that problem while resolving another issue and provided fix for that within https://github.com/IntersectMBO/govtool/pull/1899 as the fix was rather trivial.

I'll link that issue with provided Pull request to validate that working once merged.


@kneerose Thank you for spotting this 💪
