### ISSUE TITLE
🐛 Govtool Mobile Responsiveness Issues

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1897]
### Area

Other

### Domain

dev-sanchogov.tools
sanchogov.tools

### Context

- The Govtool application is not displaying correctly on mobile devices. Although wallet injection is not available on mobile, users should still be able to view the list of dReps, governance actions, and proposals clearly. However, there are issues with mobile responsiveness. 

### Steps to reproduce

- Ensure that the wallet is disconnected.
- On a mobile device:
1. Navigate to the governance actions page.
2. Horizontally slide the page; it is slideable.
3. Navigate back to the dashboard.
4. Observe the page.

### Actual behavior

**1. Visiting the governance actions page. This looks OK at first. Try horizontal scrolling in the places where there is horzontal scroll. For eg. on the text Governance Actions**
![image](https://github.com/user-attachments/assets/fa92b9fb-b35e-4863-9c3a-df0c63467d84)

**2. This is the state after horizontal scrolling. There is white space area on the scroll section**
![image](https://github.com/user-attachments/assets/a41ba05f-1c43-4691-a021-27658da8f4a9)

**3. Now, clicking on the home GovTool icon on the Governance Actions page redirects the user to the landing page. This page seems to have responsiveness issues. Note that this page loads well if you refresh the page.**
![image](https://github.com/user-attachments/assets/b88e77a2-d353-4833-8046-042cf7e4d35a)

### Expected behavior

It should be fully responsive, ensuring that all elements are visible and correctly aligned.

### Failure test reports 
1. https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/133/#behaviors/1402987606cbaebad9beb98f5734b5ef/ca29fab91378d928/
2. https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/133/#behaviors/1402987606cbaebad9beb98f5734b5ef/5ed062c20605b699/
3.  https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/133/#behaviors/1402987606cbaebad9beb98f5734b5ef/3d663142af2baf70/

**Comment by kneerose** [comment]
@jdyczka  any update on this ?

**Comment by jdyczka** [comment]
Not yet, I wouldn't say it's a priority right now, cc @bosko-m

**Comment by bosko-m** [comment]
@kneerose @spannercode Is this still the case? Loads nicely when trying on mobile and resizing on desktop

**Comment by kneerose** [comment]
CC: @bosko-m  There are still some responsiveness issues

1. **DRep Details**:  
   - Overflow issue on the DRep details card in the disconnected state. It works fine in the connected state.  
   
   ![image](https://github.com/user-attachments/assets/c4dedf84-409e-409a-93a1-bdf633a11587)

2. **DRep Filter Option**:  
   - The DRep status filter dropdown is extending beyond the screen. 
   
   ![image](https://github.com/user-attachments/assets/c14fd3ee-561f-49c9-8bcd-b46f7ec7462e) 
   

3. **Connect to Delegate Button**:  
   - The "Connect to Delegate" button overflows from the DRep card.  
   
    ![image](https://github.com/user-attachments/assets/4098ff2d-fc57-489e-825a-be573a8c1844)
   ![image](https://github.com/user-attachments/assets/7a5c63f9-9210-4393-9576-d8441dfa79bc)


4. **Logo Button Navigation**:  #1987
   - Clicking the logo button does not navigate to the dashboard.  
   
   ![image](https://github.com/user-attachments/assets/3821ffef-06b5-40e1-83e3-3db54d1e8d9a)
  ![image](https://github.com/user-attachments/assets/e2da4c18-33e6-4f83-985f-97526f1e613e)

5. **Governance Action Filter Option**:  
   - The Governance Action filter dropdown extends beyond the screen.  
  
  ![image](https://github.com/user-attachments/assets/e47a361f-dcf9-4db5-962d-b0a37e901b71)
