### ISSUE TITLE
App user can see by default only accepted by CC GA

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#19]
As any user of the app

When I view the governance actions page, the default setting for the filter that tells me if the governance action has been accepted by the Constitutional Committee or not is set to show me those governance actions which have already been accepted

So that I do not waste my time looking at governance actions that will not pass.

Given that I am viewing the governance actions page for the first time since opening the app

When I look at the governance actions

Then the only governance actions I can see are the ones that have been accepted by the Constitutional Committee.

**Comment by m-i-k-e** [comment]
@Ryun1 @l-br1 It's possible that users of GovTool might also be interested in all governance actions, including those that have disapproved by the CC.

**Comment by l-br1** [comment]
yes, this one is an old ticket from Tom. We need to understand how to handle cc votes

**Comment by Ryun1** [comment]
lets close this one, now CC votes are shown
