### ISSUE TITLE
[USERSNAP] I registered for Drep and it is now Active, but when I search for my Drep ID it doesn't show up, neither in Etrnl wallet nor in 1694io. What should I do?

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1908]
**Taken at**: https://sanchogov.tools/dashboard
**Fields**:
- Add a comment: I registered for Drep and it is now Active, but when I search for my Drep ID it doesn&#39;t show up, neither in Etrnl wallet nor in 1694io. What should I do?

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 1923x953
**[Open #113 in Usersnap](https://app.usersnap.com/l/feedback/7e34c8d2-0a54-40c7-915c-17dd214f632c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
On the wrong network :(
