### ISSUE TITLE
🐛 White Screen Appears When Viewing Governance Action Vote Details

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1910]
### Area

Voting Pillar

### Domain

dev-sanchogov.tools

### Context

When attempting to view my vote details on an info proposal, I encountered a white screen instead of accessing the page.

### Steps to reproduce

1. Connect your wallet.
2. Register as a dRep.
3. Vote on any info action.
4. Click on the "Voted on by Me" tab.
5. Click on "View Details" of the voted governance action card.

### Actual behavior

A white screen appears with the following console error:

![image](https://github.com/user-attachments/assets/64c65d41-82ef-4b63-a7df-4a2dc87c5ccd)

### Expected behavior

 Should be able to preview the details of the governance action voted on

**Comment by bosko-m** [comment]
Verified on Preview, closing.
