### ISSUE TITLE
💡 Show authors for governance action details

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1912]
### Area

Voting Pillar

### Is there new design needed?

Yes

### What?

- DRep metadata created outside of GovTool can attach authors to the metadata
- Within this people can signoff on authoring their metadata
- It would be nice for GovTool to check these provided signatures
- Govtool can then show users who the authors are and what keys represent them
- A check IF the DRep key being registered is also an author would be nice

### Why?

- nice to use the full extent of CIP100

### How?

- add to designs
- add to tech

### (Optional) User Story with acceptance criteria

N/A

**Comment by bosko-m** [comment]
Covered in #2016 .
