### ISSUE TITLE
💡 ADA -> Ada in copy

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1916]
### Area

Other

### Is there new design needed?

No

### What?

- Replace instances of ADA with Ada

### Why?

- ADA is a ticker Ada is currency [see context](https://github.com/Ryun1/CIPs/tree/cip-constitution-tech/CIP-0120#capitalisation-of-key-terms)

### How?

cntrl + shift + f

### (Optional) User Story with acceptance criteria

N/A

**Comment by jdyczka** [comment]
These are the occurrences and how I think they should be changed. @Ryun1 could you confirm they are ok?

- a few more `ADA holders \ ADA Holders` -> `Ada holders`
- `... which is equal to the balance of ADA in their connected wallet` -> `ada`
- `You do not currently have enough ADA in your wallet to continue.` -> `ada`
- `You will receive a refund of {{deposit}} ADA when the transaction  completes` ->  `ada`
- `Your deposit of {{deposit}} ADA will be refunded` ->  `ada`
- `... your Voting Power will consist of your own ADA balance ...` -> `Ada balance`

**Comment by Ryun1** [comment]
> These are the occurrences and how I think they should be changed. @Ryun1 could you confirm they are ok?

these look great, thanks for taking the time to investigate
