### ISSUE TITLE
🐛 Mainnet Ada holder voting power incorrect

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1923]
### Area

Wrapper

### Domain

gov.tools

### Context

- On mainnnet instance
- Ada holder voting power seems to be showing total amount of ADA in and out of the wallet
- Using [this wallet](https://cexplorer.io/address/addr1q86dnpkva4mm859c8ur7tjxn57zgsu6vg8pdetkdve3fsacnq7twy06u2ev5759vutpjgzfryx0ud8hzedhzerava35qwh3x34) 
- the balance is around 50 ADA, but GovTool is showing over 2000 ADA
- stake credential: `e1130796e23f5c56594f50ace2c3240923219fc69ee2cb6e2c8facec68`
![image](https://github.com/user-attachments/assets/a3b200cc-975a-4b51-be14-92bfc56fbff6)

### Steps to reproduce

1. connect a minnet wallet to govtool

### Actual behavior

- Incorrect voting power is shown

### Expected behavior

- Correct voting power is shown

**Comment by Ryun1** [comment]
Probably this one is the issue
- https://github.com/IntersectMBO/govtool/blob/develop/govtool/backend/sql/get-stake-key-voting-power.sql#L4

**Comment by jdyczka** [comment]
@Ryun1 
I had a look, and it seems like `utxo_view` selects only unspent transaction outputs https://github.com/IntersectMBO/govtool/blob/develop/.github/dbsync-schema.sql#L988

**Comment by Ryun1** [comment]
- Current mainnet voting power much closer to being correct - new ticket for final discrepencies
- @jdyczka we can add back in this feature

**Comment by Ryun1** [comment]
Carry on discussion here:
- https://github.com/IntersectMBO/govtool/issues/2000
