### ISSUE TITLE
🐛  Gov action with metadata fails to load

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#1924]
### Area

Voting Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

Eternal Beta

### Context

Parameter changes gov action fails to load on preview environment

### Steps to reproduce

1. Visit the following URL: 
- https://preview.gov.tools/connected/governance_actions/27997e2a0b3eca5676cfa59e15f1578e2e929411e813369df6e08a9e857c6031#0
- https://preview.gov.tools/governance_actions/27997e2a0b3eca5676cfa59e15f1578e2e929411e813369df6e08a9e857c6031#0

Alternatively,
1. Visit https://preview.gov.tools/connected/governance_actions
2. Select any parameter update gov actions with proper metadata.

### Actual behavior

The governance action does not load. The console logs the following errors:
```
index-6bfbe0a8.js:446 Uncaught TypeError: k.split is not a function
    at Ez (index-6bfbe0a8.js:446:9020)
    at Pb0 (index-6bfbe0a8.js:38:17959)
    at qK2 (index-6bfbe0a8.js:40:44733)
    at XK2 (index-6bfbe0a8.js:40:40369)
    at nPe (index-6bfbe0a8.js:40:40292)
    at H20 (index-6bfbe0a8.js:40:40140)
    at t70 (index-6bfbe0a8.js:40:36415)
    at iV2 (index-6bfbe0a8.js:40:37229)
    at TR (index-6bfbe0a8.js:38:3322)
    at index-6bfbe0a8.js:40:34714
```
This happens on both `connected` and `disconnected` wallet states.

### Expected behavior

The page loads correctly displaying the governance action details page.

**Comment by spannercode** [comment]
Also occurs on non-parameter update gov actions, as reported here:
- https://github.com/IntersectMBO/govtool/issues/1927

**Comment by bosko-m** [comment]
Verified on Sancho as reported in #1927 too. Every chosen GA is being opened and displayed properly.
