### ISSUE TITLE
🐛 Incorrect date of voting

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#1925]
### Area

Voting Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

Eternal Beta

### Context

The date shown when the DRep voted on a gov action proposal is shown as the proposal submission time. It should reflect the correct date when the user has voted.

### Steps to reproduce

1. As a DRep, find a gov action proposal to vote. For eg.
https://preview.gov.tools/connected/governance_actions/699b989055cb4ea7501e9028df24a48fa256969ef7d82be757b7d7f635d5730b#0
2. Vote on the proposal and wait until the transaction is complete.
3. View the proposal to see your vote. On the right side of the details page, find the text indicating when you voted on the proposal.

### Actual behavior

The date of voting is shown as the proposal submission date.
![Screenshot 2024-09-04 at 07 55 25](https://github.com/user-attachments/assets/379bb0bd-540e-4313-b517-6e5dc0b735fe)

### Expected behavior

The voting date should reflect the actual voting date.

**Comment by bosko-m** [comment]
Verified on Preview, closing.
