### ISSUE TITLE
🐛 White Screen when opening a specific governance action 

### ISSUE THREAD

**Issue by thenic95** [IntersectMBO/govtool#1927]
### Area

Proposal Pillar

### Domain

sanchogov.tools

### Context

When I try top open the URL for my governance action I get a white screen

https://sanchogov.tools/connected/governance_actions/84fe1da5d14450537db36c28ffe2a1a4878f501fc26c998bba54e396711205bc#0

### Steps to reproduce

1. Open the URL https://sanchogov.tools/connected/governance_actions/84fe1da5d14450537db36c28ffe2a1a4878f501fc26c998bba54e396711205bc#0
2. White Screen

### Actual behavior

Instead of showing the governance action site I see a white screen

### Expected behavior

Ideally, I should be able to view the governance action details.

**Comment by spannercode** [comment]
This issue is same as 
- https://github.com/IntersectMBO/govtool/issues/1924

**Comment by spannercode** [comment]
Also occurs on non-parameter update gov actions, as reported here:
- https://github.com/IntersectMBO/govtool/issues/1927

**Comment by jdyczka** [comment]
It should be fixed with #1932

**Comment by bosko-m** [comment]
Verified on Sancho as reported with #1924 . Every chosen GA is being opened and displayed properly.
