### ISSUE TITLE
🐛 Sort issues on Drep directory

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1935]
### Area

Delegation Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

Demos 1.8.2

### Context

Trying to sort the Drep List, and also understand how it is sorted

### Steps to reproduce

Go to DRep list
Try and sort it by "Registration Date" with the oldest first ( or newest )

### Actual behavior

The sort works, but it does not sort backwards, nor is the sort order indicated on the page.

### Expected behavior

Users can see:

1. What the default sort order is when the page loads
2. What the current sort order is without having to click anywhere
3. They can sort each category ascending or descending.

**Comment by bosko-m** [comment]
Closing as opposing to #2013.
