### ISSUE TITLE
[USERSNAP] Unable to use GovTool w/ Lace -- issue seems to be coming from GovTool

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1939]
**Taken at**: https://gov.tools/
**Fields**:
- Add a comment: Unable to use GovTool w/ Lace -- issue seems to be coming from GovTool

**Browser**: Chrome 128 (macOS Catalina)
**Screen size**: 5120x1440
**[Open #114 in Usersnap](https://app.usersnap.com/l/feedback/450c3507-dd07-4139-8ba9-65667c5656d6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
Issue is likely on the Lace side,
as this has not been reported by using any other wallet and I am able to replicate via test dApp

It seems that signing vote delegation certificates fails in Lace across networks
