### ISSUE TITLE
🐛 Discrepancy in DRep Vote Counts for Info Governance Actions Between dRep Registered and Disconnected States

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1941]
### Area

Voting Pillar

### Domain

preview.gov.tools

### Context

When viewing votes on Info governance actions, the system displays inaccurate vote counts. Specifically, the votes submitted by dReps appear as 0 ADA for registered dRep on show votes popup modal, regardless of actual votes submitted by dReps. But it shows actual vote count on disconnected state.

### Steps to reproduce

1. Connect to a wallet with a registered dRep.
2. Navigate to any Info governance action.
3. Click on "Show Votes."
4. Observe the votes submitted by dReps.
5. Disconnect the wallet.
6. Observe the votes submitted by dReps.

### Actual behavior

The votes submitted by dReps are shown as 0 ADA for registered dRep on Show votes popup modal, even though there are actual votes submitted by dReps.

For example, on the Info governance action at the following link: [Info Governance Action](https://preview.gov.tools/governance_actions/5e0e59a1e40fbdef987d0fdb47fd08a6f00ba6a1661b26ebae7bd827ec400e50#0)

In the disconnected state:

![image](https://github.com/user-attachments/assets/ed498b87-d7de-4ab8-ae79-e77c3059c45b)

On the connected state with dRep registered and after clicking on "Show Votes": 

![image](https://github.com/user-attachments/assets/071158ab-7367-49e3-b8f3-e2484d6ac60f)

### Expected behavior

The vote counts for any governance action should be consistent whether in the dRep connected state or the disconnected state.

### Allure Report 
https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/98/#behaviors/1523ff4143db0faaf245e2252e8ca520/2d5432de94f0255a/

**Comment by Ryun1** [comment]
Temp fix:
- add other vote totals to the modal

Long term fix:
- @m-i-k-e to refactor design for this page
