### ISSUE TITLE
🐛 Issue while accessing gov.tools

### ISSUE THREAD

**Issue by FaizanShaikh-3033** [IntersectMBO/govtool#1942]
### Area

Other area
 
### Domain

gov.tools

### Which wallet were you using?

Eternal 1.12.9  &  Lace 1.14.0

### Context

When accessing the gov.tools , it's asking for username and Password.
![gov-tool](https://github.com/user-attachments/assets/83fe5a72-66b9-465c-b15d-6d9549eb31c0)

### Steps to reproduce

1. Go on gov.tools

### Actual behavior

A signin Alert is coming

### Expected behavior

Webpage should be displayed showing information about DRep, Registration, Review vote on governance Action.

**Comment by Ryun1** [comment]
@FaizanShaikh-3033 that is intentional
We havent launched GovTool to the public yet :)
