### ISSUE TITLE
💡 Bump DBSync versions to 13.5.0.2

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#1945]
### Area

Other

### Is there new design needed?

No

### What?

Bump all DBSync versions to 13.5.0.2 to align good with the 9.1.1 node hotfix

### Why?

To make sure that the app stays healthy after the hot fix has been applied to the node

### How?

Upgrade version
[https://github.com/IntersectMBO/cardano-db-sync/releases/tag/13.5.0.2](https://github.com/IntersectMBO/cardano-db-sync/releases/tag/13.5.0.2)

**Comment by Ryun1** [comment]
We will bump SanchoNet instances first, check the `utxo_view` table to make sure it looks good
