### ISSUE TITLE
🐛  Unable to Vote on Non-Info Governance Actions on Sanchonet

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1947]
### Area

Voting Pillar

### Domain

dev-sanchogov.tools

### Which wallet were you using?

Demos 1.8.2

### Context

I am encountering an issue where, as a registered dRep, I am unable to vote on any governance actions other than Info actions on Sanchonet.

### Steps to reproduce

1. Connect your registered dRep wallet.
2. Navigate to a governance action other than an Info action.
3. Observe the details page for the governance action.

### Actual behavior

As a registered dRep, I am unable to vote on governance actions other than Info actions on Sanchonet.

![image](https://github.com/user-attachments/assets/0669e8e1-9334-4b7e-a842-36bc13ea75ec)

![image](https://github.com/user-attachments/assets/4525f57a-4f60-4b9c-bc34-29cff58aa7c9)

### Expected behavior

I should be able to vote on all types of governance actions, including treasury and other actions, on Sanchonet.

### Allure Report
- [4G. Should display correct vote counts on governance details page for DRep](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/139/#behaviors/1523ff4143db0faaf245e2252e8ca520/2a1226f75e67a6be)
- [5A. Should show relevant details about governance action as DRep](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/139/#behaviors/9ac8de95e77713861f808e6170fefbb2/2aa1f2d9beaa9765/)
- [5C. Should show required field in proposal voting on registered as DRep](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/139/#behaviors/9ac8de95e77713861f808e6170fefbb2/e20ee0e0c9cdba30/)
- [5D_1. Should accept valid data in provide context](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/139/#behaviors/9ac8de95e77713861f808e6170fefbb2/5992f3e78d9cfdf2/)
- [5D_2. Should reject invalid data in provide context](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/139/#behaviors/9ac8de95e77713861f808e6170fefbb2/c0c7a0544a25ffc3/)
- [5E. Should re-vote with new data on a already voted governance action](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/139/#behaviors/9ac8de95e77713861f808e6170fefbb2/f86ea5f4418b06d0/)
- [5F. Should show notification of casted vote after vote](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/139/#behaviors/9ac8de95e77713861f808e6170fefbb2/f2f499e7e74b1fc7/)
- [5I. Should view the vote details,when viewing governance action already voted by the DRep](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/139/#behaviors/9ac8de95e77713861f808e6170fefbb2/c5a79ff902e447c0/)

**Comment by jdyczka** [comment]
@kneerose possibly #2008  was a duplicate?

**Comment by kneerose** [comment]
@jdyczka  Yes, it is related to #2008. I can now see the vote option for registered dReps on Non-Info Governance Actions in full governance mode (protocol major version 10).
This issue can be closed. CC: @bosko-m

**Comment by bosko-m** [comment]
Closing as per the comment above.
