### ISSUE TITLE
Properly calculate DRep voting power

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/govtool#195]
As a DRep

I want my voting power to be properly calculated

So that I know how much I have

##########

Given that I have submitted a governance action and paid a deposit (which has not yet been returned to me), and I am also a DRep (for which I also paid a deposit)

When I look at my voting power then:

my voting power = ADA in my wallet + GA deposit amount + ADA delegated to me

DRep deposits do not count towards voting power.

#########

all deposits except GA deposit DO NOT count towards voting power

**Comment by pmbinapps** [comment]
Need needs to be investigated more, seems like Voting power is still shown wrongly:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/15c4bb8c-5e4f-444d-8f81-7e48d148e47f)
