### ISSUE TITLE
🐛 Incorrect representation for script-based DReps

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1951]
### Area

Delegation Pillar

### Domain

gov.tools

### Context

- GovTool assumes all DReps read from chain are key-based, this is incorrect
- Script-based DReps can be created via other tooling and then GovTool can read these from chain and show via the DRep directory
- Script based DReps can be represented with a different bech32 encoding `drep_script`
- Script-based DReps must be represented correctly at vote delegation time
  - this will have to change
  - https://github.com/IntersectMBO/govtool/blob/develop/govtool/frontend/src/context/wallet.tsx#L688C11-L688C75 
- this probably requires a change in BE API to flag Scripbased DReps as such

### Steps to reproduce

1. look up a script DRep: https://gov.tools/drep_directory/drep1uk4nwfsm843kqr2kv4jg0yms46srr633pzc2d0vvaav25ncwj8g
2. see metadata

### Actual behavior

- DRep ID shown incorrectly in directory
- Delegation is to the wrong DRep as keyHash is used instead of scriptHash

### Expected behavior

- DRep ID shown correct in directory with `drep_sctipt1....`
- Delegation is to the correct DRep as using scriptHash here: https://github.com/IntersectMBO/govtool/blob/develop/govtool/frontend/src/context/wallet.tsx#L688C11-L688C75

**Comment by Ryun1** [comment]
Incorrect prefix is reported from the DB-Sync level
- https://github.com/IntersectMBO/cardano-db-sync/issues/1848

**Comment by Ryun1** [comment]
a start
https://github.com/IntersectMBO/govtool/pull/1956

**Comment by Ryun1** [comment]
duplicate to https://github.com/IntersectMBO/govtool/issues/921

**Comment by bosko-m** [comment]
After the conversation with @Ryun1 today, we are putting P0 on this one.
@MSzalowski @jdyczka
