### ISSUE TITLE
🐛 DRep can't delegate to themselves after delegating elsewhere

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1957]
### Area

Delegation Pillar

### Domain

gov.tools

### Which wallet were you using?

Demos 1.8.2

### Context

Drep self-delegation

### Steps to reproduce

1. Become a DRep
2. Delegate to someone else
3. Try and delegate back to yourself

### Actual behavior

There is no button on the DRep list or detail page to delegate to yourself

### Expected behavior

There should be a button to delegate to yourself.

**Comment by m-i-k-e** [comment]
@bosko-m here is a bug

**Comment by Ryun1** [comment]
Lets investigate a little more, Mike to add video :)

**Comment by Ryun1** [comment]
Related to https://github.com/IntersectMBO/govtool/issues/1982

**Comment by m-i-k-e** [comment]
Ok, this was because the DRep was inactive. Closing Thanks @jdyczka
