### ISSUE TITLE
🐛 DRep details not showing voting power for ADA held in DRep's wallet

### ISSUE THREAD

**Issue by tonybsf** [IntersectMBO/govtool#1960]
### Area

Delegation Pillar

### Domain

gov.tools

### Context

After registering as a DRep using govtools I went back to the DRep directory.  It shows voting power of ₳ 0 when I have 18,066.48493 in my wallet. 

Wallet:  addr1q9a25c0hdv2ayud5qlcu5vnwxnggxd4mf4ku0t3sea882f53rzraaguvd6q4l59quc4uhwayk36vgflj2htzwltfqgns2yty0d

DRep ID: drep10sac7436zwwrvec4quflqp802wzgl3a8uzq5rx83xvwe223cvnu

### Steps to reproduce

1. Connect Wallet 2. Register as a DRep 3. Go to DRep directory.    

### Actual behavior

Voting power says ₳ 0. 

### Expected behavior

Should show ₳ 18,066.48493

**Comment by bosko-m** [comment]
@tonybsf Can you confirm if this is still the case for you?

**Comment by bosko-m** [comment]
CC @spannercode @Ryun1

**Comment by spannercode** [comment]
The current voting power looks close to the current stake controlled value (but not exact).
https://gov.tools/connected/drep_directory/drep10sac7436zwwrvec4quflqp802wzgl3a8uzq5rx83xvwe223cvnu

CC: @bosko-m

**Comment by bosko-m** [comment]
Would be curious to understand wheres the difference coming from, what are we missing

**Comment by MSzalowski** [comment]
Voting power is calculated at the end of the epoch. So right after registration, we don't know what the voting power is

**Comment by Ryun1** [comment]
> Voting power is calculated at the end of the epoch. So right after registration, we don't know what the voting power is

yup we have to wait for the first epoch boundary AFTER registration, before GovTool shows DRep voting power

> Would be curious to understand wheres the difference coming from, what are we missing

as of right now
- [GovTool](https://gov.tools/drep_directory/drep10sac7436zwwrvec4quflqp802wzgl3a8uzq5rx83xvwe223cvnu) reports a voting power of: ₳ 18948.905741
- [Cardanoscan](https://cardanoscan.io/dRep/drep1yf7rhr6k8gfecdn8z5r38uqyaafcfr785lsgzsvc7ye3m9g3z20kj) a voting power of: ₳ 1,045,950.090512
- [AdaStat](https://adastat.net/dreps/drep1yf7rhr6k8gfecdn8z5r38uqyaafcfr785lsgzsvc7ye3m9g3z20kj) reports total voting power of: ₳1.05m

It looks like there was a new delegation of over 1m ada, within the last twelve hours and GovTool hasnt recognised that yet.
But before that delegation, it does look like power of ₳ 18948.905741 matches the voting power of the stake key associated with the DRep's payment address [₳ 18,948.905741](https://cardanoscan.io/stakeKey/stake1uxg33p775wxxaq2l6zswv27thwjtgaxyyle9t438045syfck697mf?tab=voteDelegations).

**Comment by bosko-m** [comment]
So I assume we should check whats happening at the end of an epoch.
Is there a way to "catch" that assumed delegation @Ryun1 ?

**Comment by MSzalowski** [comment]
@spannercode Could you please share the stake key where you noticed differences between expected voting power and presented voting power?

**Comment by spannercode** [comment]
@MSzalowski Here is a stake key link on [cardanoscan](https://preview.cardanoscan.io/address/00036d08c0cf543f3d3035693563896b7c0e6a35ad56f22371e921ef1ee356224fb5a313bbe98353e4ccd02f396baaafafbf85393bdbf680ad)

There is a DRep registered on the same wallet address. Here the Ada delegated amount does not look correct.
<img width="1439" alt="Screenshot 2024-11-07 at 12 13 12" src="https://github.com/user-attachments/assets/01e678cb-21e0-4b59-af0e-333218c5490e">

Here is the cardanoscan link to compare (which looks incorrect as well):
https://preview.cardanoscan.io/drep/drep1y23y32wq2047y59509qyvjutk7dmqdgv09kkvegrh8r6elczx5rwf?tab=delegators

**Comment by MSzalowski** [comment]
Thank you, I'll have a look on that

**Comment by MSzalowski** [comment]
We are using [drep_distr](https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/schema.md#drep_distr) table to directly take the voting power proper for the current epoch and it shows 843... ADA (as on your attached screen). And that was our only source of truth.

We could instead calculate that voting power manually (as I guess cexplorer does) using the utxo_view but that might lead to some mistakes in calculation.

I'll provide some examples of calculations based on utxo_view (no schema documentation on db-sync docs)
