### ISSUE TITLE
[USERSNAP] GovTools will not allow me to connect my Eternl wallet to the platform. I am a already registered dRep and I have two wallets on my Eternl interface (unsure if either of these factors may cause an error in the connect function). 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1962]
**Taken at**: https://gov.tools/drep_directory
**Fields**:
- Add a comment: GovTools will not allow me to connect my Eternl wallet to the platform. I am a already registered dRep and I have two wallets on my Eternl interface (unsure if either of these factors may cause an error in the connect function). 

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 1630x1150
**[Open #115 in Usersnap](https://app.usersnap.com/l/feedback/da706e22-7bab-4298-9ee7-f8be50d3b6a3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
The error shown via usersnap indicates that eternl is returning this error, most likely the user does not have an eternl account enabled to connect to dapps
