### ISSUE TITLE
🐛 Duplicate Test IDs for DRep Links and Identity Reference Field Errors

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1965]
### Area

Delegation Pillar

### Domain

preview.gov.tools

### Context

Test IDs for all fields should be unique to ensure accurate testing and identification. Currently, the test IDs for the error messages related to description, URL of links, and identity fields are duplicated (e.g., `invalid-url-error` and `max-80-characters-error`). This issue also includes the overlap where the description error message shares a test ID with one of the name error messages i.e `max-80-characters-error`. Therefore, distinct test IDs are required for each error message to avoid confusion and ensure proper testing.

### Steps to reproduce

1. Connect to the wallet.
2. Navigate to the `/register_dRep` page.
3. Observe the test IDs for the error messages related to description andURL, of identity and links reference 

### Actual behavior

Test IDs for the error messages of description, and URL, of identity and links reference are duplicated, which may lead to confusion during testing.

![Screenshot from 2024-09-06 13-13-24](https://github.com/user-attachments/assets/fc6258b9-f376-457f-a713-fcc3c9869dba)

![Screenshot from 2024-09-06 13-13-29](https://github.com/user-attachments/assets/24114af4-a7de-4373-bcc1-8d9a66ecf8b4)

![Screenshot from 2024-09-06 13-13-36](https://github.com/user-attachments/assets/5203a1b4-5726-4740-abd3-03ad91c41d85)

![Screenshot from 2024-09-06 13-13-44](https://github.com/user-attachments/assets/59bc0792-ee63-4ec6-904e-fa1be45ceae2)

### Expected behavior

Each error message should have a unique test ID to ensure clear and accurate testing.

**Comment by spannercode** [comment]
@jdyczka Here is the ticket for missing test-ids.

**Comment by jdyczka** [comment]
@spannercode Right now test ids for inputs are generated automatically based on the error message. So in theory this can also affect other places where there are different fields, but with the same error message. The same applies to the hint below the input. 
Maybe it would make more sense to generate test ids based on the test id of the input field? If done globally that would ensure uniqueness, however, it might also require a bunch of changes on your side.
Let me know if you would prefer me to go with the global approach, or just handle the case of link and identity references.
