### ISSUE TITLE
🐛 Automatically hide Treasury GA type depending on protocol_major

### ISSUE THREAD

**Issue by teske00** [IntersectMBO/govtool#1967]
### Area

Proposal Pillar

### Domain

gov.tools

### Context

Treasury GA type auto-hide does not work on the PROD environment 

### Steps to reproduce

1. Go to the Proposals page

### Actual behavior

1. Go to the Proposals page
2. Treasury GA type is visible

### Expected behavior

1. Go to the Proposals page
2. Treasury GA type is not visible

**Comment by Ryun1** [comment]
@teske00 how can we allow for @spannercode + team to be able to inject the protocol version to be able to fully test

**Comment by teske00** [comment]
@Ryun1 Currently, it is set to use the govtool API base URL on the backend through the env through which we get the protocol version, so everything depends on that. The only thing is that it is possible to implement a new endpoint for testing purposes, which will override the protocol obtained from the govtool API, it would be good if this is used only in the QA environment, so that this change does not affect the real protocol. Is this okay? cc @vpaunovic

**Comment by spannercode** [comment]
Having a separate endpoint for testing purpose is a no-go. We would like to test the real behavior as much as possible.
The main problem for us to test this is not being able to intercept the network request and change the protocol major version  not reflecting the changes on the PDF side. This is different from the rest of the govtool.

**Comment by teske00** [comment]
@spannercodeI don't know how it can be implemented in our case, because the difference is that govtool sends and receives requests from the frontend, from the client side, while our processing is done on the backend and the frontend has no influence on it. @vpaunovic

**Comment by bosko-m** [comment]
@teske00 @spannercode Is this still relevant as we are going into the full governance phase in the near future?

**Comment by bosko-m** [comment]
This test can be skipped.
