### ISSUE TITLE
[USERSNAP] Links terms and conditions and Help, are leading to page not found. 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1968]
**Taken at**: https://gov.tools/?fbclid=IwY2xjawFHxRhleHRuA2FlbQIxMQABHeQzDbF5LfhV7HXlX_ojXuMbK0kMBLtXy6dWrd13d3iwSEgge9koxe3PsQ_aem_6kO9yAVRP8oFcsx0dWCo7Q
**Fields**:
- Add a comment: Links terms and conditions and Help, are leading to page not found. 

**Browser**: Chrome 128 (Android 14)
**Screen size**: 407x904
**[Open #116 in Usersnap](https://app.usersnap.com/l/feedback/27f0b730-6c6f-4334-aea7-ad8d7f3499a6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
fixed by https://github.com/IntersectMBO/govtool/pull/1972
