### ISSUE TITLE
[USERSNAP] Editing a submitted proposal

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1969]
**Taken at**: https://gov.tools/proposal_discussion
**Fields**:
- Name of the idea or new feature: Editing a submitted proposal
- Please summarize your idea or new feature: I was looking for a way to edit a proposal that I made.  I&#39;m using the same wallet but different browser and I don&#39;t see an edit option

**Browser**: Chrome 123 (macOS Catalina)
**Screen size**: 1382x754
**[Open #71 in Usersnap](https://app.usersnap.com/l/feedback/f87688ce-c3a0-4cc3-8a49-ccd6777f56e4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
This is a feature
