### ISSUE TITLE
[USERSNAP] When I try to search by DRep's name isn't working as you see in the attached image .png, it only works when searching by DRep's ID.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1970]
**Taken at**: https://gov.tools/drep_directory
**Fields**:
- Add a comment: When I try to search by DRep&#39;s name isn&#39;t working as you see in the attached image .png, it only works when searching by DRep&#39;s ID.

**Browser**: Chrome 128 (Linux)
**Screen size**: 1366x768
**[Open #117 in Usersnap](https://app.usersnap.com/l/feedback/9b6df19e-78fa-466e-b398-bc0f2fc8aadd?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
duplicate issue https://github.com/IntersectMBO/govtool/issues/1950
