### ISSUE TITLE
[USERSNAP] Sort Governance Actions by who can vote for them

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1971]
**Taken at**: https://gov.tools/connected/governance_actions
**Fields**:
- Name of the idea or new feature: Sort Governance Actions by who can vote for them
- Please summarize your idea or new feature: Sort Governance Actions by who can vote for them. For example SPOs will only vote on certain actions, while I know they can&#39;t vote here on gov tools, they will use this as a resource to read and copy the governance action IDs. So it would be great if SPOs can come here are quickly if there are items they need to vote on.

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 1280x720
**[Open #72 in Usersnap](https://app.usersnap.com/l/feedback/f08d7a6f-3d09-49d6-8413-e653df4c75a1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
This sounds like a good idea. It's a bit of an edge case, and I wonder if we couldn't provide a CLI tool or something simpler rather than try and build it into GovTool.

**Comment by bosko-m** [comment]
Dreps can vote on everything.
SPOs and CC members do not vote through the GovTool.
