### ISSUE TITLE
[USERSNAP] Please add pictures to DReps

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1973]
**Taken at**: https://gov.tools/drep_directory
**Fields**:
- Name of the idea or new feature: Please add pictures to DReps
- Please summarize your idea or new feature: I might be a good idea to add pictures to DReps on the gov.tool website. Could also be their Twitter profile pic.

It will give people a mucher better overview, numbers and letters only look a bit dry :/

Thanks

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 1920x1080
**[Open #73 in Usersnap](https://app.usersnap.com/l/feedback/454efbe3-d5cd-49dd-9775-4f3b56a1181f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
duplicate to https://github.com/IntersectMBO/govtool/issues/1762
