### ISSUE TITLE
[USERSNAP] Search on the dRep Directory page doesn't work.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1975]
**Taken at**: https://gov.tools/dashboard
**Fields**:
- Add a comment: Search on the dRep Directory page doesn&#39;t work.

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 2560x1440
**[Open #119 in Usersnap](https://app.usersnap.com/l/feedback/38368c8c-490b-4a05-aef0-88cf1bad975b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
duplicate https://github.com/IntersectMBO/govtool/issues/1893
