### ISSUE TITLE
[USERSNAP] Become a Direct Voter leads to a screen that says "Becoming a Direct Voter will require a refundable deposit equal to your voting power." In the docs it reads "your Voting Power - which equals ADA the balance in your wallet". This sounds like...

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1976]
**Taken at**: https://gov.tools/dashboard
**Fields**:
- Add a comment: Become a Direct Voter leads to a screen that says &#34;Becoming a Direct Voter will require a refundable deposit equal to your voting power.&#34;

In the docs it reads &#34;your Voting Power - which equals ADA the balance in your wallet&#34;.

This sounds like you have to deposit all of your ADA. Can&#39;t be right.

Moreover, I think there is an actual bug here, too. I only have a couple thousand ADA in my wallet currently yet my voting power, as it says on the home page, is 1507470.671888 ADA.

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 2560x1440
**[Open #120 in Usersnap](https://app.usersnap.com/l/feedback/2a9be2dc-9e8b-49f9-bf02-204b93676639?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
good spot ill take this

**Comment by Ryun1** [comment]
duplicate https://github.com/IntersectMBO/govtool/issues/1999
