### ISSUE TITLE
🐛 Delegated dRep on dRep List Can Be Delegated Again

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1982]
### Area

Delegation Pillar

### Domain

preview.gov.tools

### Context

When you delegate voting power to an active dRep, the delegated dRep appears on both the "Delegated dRep" Card and the dRep List. This causes confusion because it allows users to inadvertently delegate their voting power to a dRep that is already delegated, potentially leading to issues in the delegation system.

### Steps to reproduce

1. Connect your wallet.
2. Navigate to the dRep directory.
3. Delegate voting power to any active dRep listed.
4. Observe that the delegated dRep appears on both the "Delegated dRep" Card and the dRep List.
5. Note that you can still delegate the dRep listed on the dRep List, even though it is already a delegate.

### Actual behavior

- It is possible to delegate the dRep again, despite it already being delegated.

![image](https://github.com/user-attachments/assets/03a9112c-7a89-4aad-a423-f435b9d46de9)

### Expected behavior
- Delegate button should be disable or hidden
- It should not be possible to delegate the same dRep that has already been delegated to.

**Comment by jdyczka** [comment]
@kneerose Just to clarify, the Delegate button will be visible while transaction is in progress, but clicking it does not result in a duplicate transaction (a modal is displayed instead). The button should disappear when transaction goes through.
