### ISSUE TITLE
🐛 Proposal Card Layout Issues: Excessive Spacing Between Elements

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#1985]
### Area

Proposal Pillar

### Domain

gov.tools

### Context

The proposal card UI is not rendered correctly, resulting in excessive space between the "Gov Action Type" and "Proposed On" sections. This spacing issue negatively impacts the design and readability of the proposal cards.

### Steps to reproduce

1. Navigate to the proposals section.
2. Observe the layout of the proposal cards.

### Actual behavior

The proposal cards have excessive spacing between the "Gov Action Type" and "Proposed On" sections, leading to a visually unappealing design.

![image](https://github.com/user-attachments/assets/fbf331ce-30e7-4215-9ff0-5cb645fbb29d)

### Expected behavior

The spacing between "Gov Action Type" and "Proposed On" should be consistent with the design standards, providing a more polished and cohesive appearance.

![image](https://github.com/user-attachments/assets/fb6ea9de-5d52-407b-b622-8a58fc56f75a)

**Comment by teske00** [comment]
@kneerose @Ryun1 The reason for this is that we previously had a ticket for all cards to be the same height, and here in the row there is a card with a large Abstract text (scroll right, you will see the card). Is it an acceptable solution to limit the number of lines for the Abstract text in the card? cc @vpaunovic

**Comment by m-i-k-e** [comment]
Please truncate these and we want only three lines and a "..." elipsis character.

**Comment by kneerose** [comment]
The ellipsis (`...`) character now appears on the proposal card when the abstract exceeds three lines, and the excessive spacing between elements has been resolved. 
The issue can be closed. CC: @bosko-m

**Comment by bosko-m** [comment]
Closing as per the comment above.
