### ISSUE TITLE
Create link to CC Portal

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#1995]
There needs to be a link to https://constitution.gov.tools from GovTool.

@l-br1 question: All cards in GovTool lead to functions within GovTool, so should we create this as a card or in the left nav menu with an external link icon?

**Comment by l-br1** [comment]
@m-i-k-e CC portal could go live tomorrow. If we can it would be great to have this card ready to go live along side that :)

**Comment by m-i-k-e** [comment]
Ok, I'll see what I can do. Would you be OK with a link in the left menu instead of a card? The cards are all multi-functional parts of GovTool i.e. they change with the state of the user. If we use a card for this, it will just be a link outwards.

**Comment by l-br1** [comment]
this would be an external resource, you could put it in the menu but it needs to be clear and explicit is not a part of govtool and it's an external link (even more we would still need a card on the landing page I think)

**Comment by l-br1** [comment]
<img width="638" alt="Screenshot 2024-09-16 at 12 56 08" src="https://github.com/user-attachments/assets/3f9830ce-c923-49c8-a51a-a4d4a172c2e5">
copy: 

_Check the Constitutional Committee Portal

See Interim Cardano Constitution and Constitutional committee votes rationales_

We need to add another graphic and the external link icon

**Comment by kgrzonka** [comment]
@l-br1 
https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/branch/ymWVgwiQocFfcf4AZBz7lT/Voltaire---GOV-TOOL?m=auto&node-id=7834-151129&t=phfYeYrU017wxzRW-1

should I add this tile in all HomePage rwd screens in Figma ?

**Comment by l-br1** [comment]
I think being in the wallet connect one is enough. Perhaps we do need to add it as a card also on the dashboard? WDYT?

**Comment by kgrzonka** [comment]
also on the dashboard? hmm I don't know if taking people out of our app in dashboard is a good idea...

**Comment by kgrzonka** [comment]
@l-br1 but I need some details-what exactly do we gain by redirecting the user to this page? how does it help. sorry I need some context here

**Comment by m-i-k-e** [comment]
@kgrzonka has made a good solution for any number of links here: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/branch/ymWVgwiQocFfcf4AZBz7lT/Voltaire---GOV-TOOL?m=auto&node-id=7834-151129&t=EmU8suJhxi52BkQ2-1

**Comment by m-i-k-e** [comment]
This is now here in the main file: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=7834-151129&t=xQhnTuOflmR24nmt-1

However, there is no mobile version. I'm chasing the designer for it.

**Comment by bosko-m** [comment]
@m-i-k-e All good with the mobile version or is still pending?

**Comment by jdyczka** [comment]
@bosko-m Should I also add the other two links that are on figma? If so, I need copy for description and url to the parameter checking tool

![image](https://github.com/user-attachments/assets/128a9533-e2d9-4062-8cf9-2125f0dc1b6d)
