### ISSUE TITLE
[USERSNAP] Improve Search

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1996]
**Taken at**: https://gov.tools/drep_directory
**Fields**:
- Name of the idea or new feature: Improve Search
- Please summarize your idea or new feature: Remembering the Drep ID is completely impossible. Please can we search via the username. For example my name is set as zkdid but you cannot search any of the Dreps from their name. That would make sense because sadly right now from my mobile phone and I’m not able to even find my Drep ID from this website. 

Thanks 🙏 

**Browser**: Safari 17 (iOS)
**Screen size**: 428x926
**[Open #75 in Usersnap](https://app.usersnap.com/l/feedback/6296b05e-e8c8-4bcc-9f61-2fde319843f3?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
duplicate https://github.com/IntersectMBO/govtool/issues/1893
