### ISSUE TITLE
[USERSNAP] Gov tools on mobile

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1997]
**Taken at**: https://gov.tools/drep_directory
**Fields**:
- Name of the idea or new feature: Gov tools on mobile
- Please summarize your idea or new feature: Please find a way so we can use this website from our mobile phones. Most of us will likely be more glued to our phones then we will our computers. Would love to be able to connect to this website without needing to use a browser. Thanks for your time and all your hard work. 🙏

**Browser**: Safari 17 (iOS)
**Screen size**: 428x926
**[Open #76 in Usersnap](https://app.usersnap.com/l/feedback/ae202fa1-9bb1-46e4-be88-e75bbe0894ae?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
GovTool does work reasonable well on mobile, with the Vespr wallet
