### ISSUE TITLE
[USERSNAP] The text about the deposit is wrong. The deposit is *not* equal to the voting power (that would make no sense), but a fixed amount, currently 500 ADA.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#1999]
**Taken at**: https://gov.tools/register_direct_voter
**Fields**:
- Add a comment: The text about the deposit is wrong. The deposit is *not* equal to the voting power (that would make no sense), but a fixed amount, currently 500 ADA.

**Browser**: Chrome 128 (Linux)
**Screen size**: 1920x1080
**[Open #122 in Usersnap](https://app.usersnap.com/l/feedback/875da3f4-c032-42f7-bc53-ab1a3e992ff9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
raised [here](https://github.com/IntersectMBO/govtool/issues/1976) also
will continue discussion there
