### ISSUE TITLE
As dRep - on proposal after Voted - Back and Reload the vote decision button is not updated [BT-ensure prio low]

### ISSUE THREAD

**Issue by l-br1** [IntersectMBO/govtool#2]
To reproduce:

As dRep on a proposal, choose decision and Vote 

Click back on browser

Reload - the decision buttons YES, NO, ABSTAIN are not updated as the would after entering from Voted on section

https://github.com/IntersectMBO/govtool/assets/134690345/7a82555c-6df8-43e7-954e-cd23b858a32a

**Comment by pmbinapps** [comment]
Works fine now:
https://jam.dev/c/edcb0c3f-f785-465b-95d2-75b0e65890e4
