### ISSUE TITLE
🐛 Ada holder voting power does not take into account unclaimed rewards OR gov action deposits paid

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#2000]
### Area

Delegation Pillar

### Domain

gov.tools

### Context

- Ada holder voting power is equal to;
  - total of lovelace UTxOs controlled by the stake account
  - total of unclaimed lovelace from the reward account (from staking rewards or treasury withdrawals)
  - total lovelace locked for governance action deposit
- see example stake credential (mine)
  - [e1130796e23f5c56594f50ace2c3240923219fc69ee2cb6e2c8facec68](https://cardanoscan.io/stakeKey/stake1uyfs09hz8aw9vk202zkw9seypy3jr87xnm3vkm3v37kwc6q6dfjar)

### Steps to reproduce

1. check voting power for `e1130796e23f5c56594f50ace2c3240923219fc69ee2cb6e2c8facec68`

### Actual behavior

resulting value it: wallet balance - unclaimed rewards

### Expected behavior

resulting value it: wallet balance + unclaimed rewards

**Comment by bosko-m** [comment]
Im putting a P0 on this @Ryun1 .
