### ISSUE TITLE
💡 Merge the widgets for “DRep” and “Direct Voter” on the dashboard

### ISSUE THREAD

**Issue by HeptaSean** [IntersectMBO/govtool#2001]
### Area

Not sure

### Is there new design needed?

Yes

### What?

There should be only one widget that shows the status of registration as a dRep or as a “direct voter” (which is *also* a dRep, but either without metadata or with metadata with `doNotList` set to `true`). The widget should offer state changes that make sense in the respective situations.

### Why?

The current presentation (in this case from Preview network) is confusing. The wording in the “Direct Voter” widget implies that I cannot use my voting power, but I very much can since I'm registered as a (“real”) dRep.
![screenshot-2024-09-10-14:59:25](https://github.com/user-attachments/assets/a91c3518-e6ab-4722-a92c-f8bc57ac5a98)

Using the “re-register” button would implicitly create a new registration for the same dRep ID *without* metadata, so turn me from a “dRep” to a “direct voter”.

### How?

The widget shows one of the following states with its possible actions:
1. not registered:
   - register without metadata (to become a “direct voter” or campaign outside of gov.tools and similar tools)
   - register with metadata (to become a dRep with public information about them, can be found in gov.tools and similar tools if they choose to be listed)
2. registered without metadata (“direct voter”):
   - update registration to a registration with metadata (same rationale as above)
   - retire (to stop participating in governance and get back the deposit)
3. registered with metadata:
   - update metadata (to change information)
   - update registration to a registration without metadata (same rationale as above)
   - retire (same rationale as above)
4. retired from epoch XXX:
   - re-register without metadata (same rationale as above)
   - re-register with metadata (same rationale as above)

**Comment by m-i-k-e** [comment]
Yes, this is confusing. We tried to wedge more functionality into a very simple interface, and made it confusing. There are issues for a dashboard redesign that will fix this. https://github.com/IntersectMBO/govtool/issues/763

**Comment by m-i-k-e** [comment]
Your comments are very helpful and should feed into the redesign of the dashboard. We can use them to generate the proper set of user stories to test the designs against.

**Comment by HeptaSean** [comment]
Sounds exactly like what I wanted, just embedded in a larger redesign of the dashboard. Did not find your earlier issue (and I can't open the Miro board, probably just accessible to team?).

Redesign could also be an opportunity to reassess the “direct voter” wording. A “direct voter” could be either a dRep without metadata or a dRep with metadata, but with `doNotList: true` in it, or both. And both don't really prevent anyone from delegating to them nevertheless. And both still cost exactly the same deposit as for a “real” dRep.

That's why I gave more prominence to the with/without metadata distinction above (and only added “direct voter” in parentheses). “Metadata” is a rather technical term, I know. Could also call it “public information” or something like that. But that is also the important distinction for the UX flow of gov.tools, if the page where the user gives the metadata is presented or not. If they have or want to have delegations from others or just from their own wallets and accounts doesn't matter that much.

We had some discussion on that in the #wg-governance-tools channel in the Intersect Discord. Don't know who would have to decide, but I would personally tend to not call any state “direct voter” at all.

**Comment by m-i-k-e** [comment]
@HeptaSean A while back we did some initial user testing around voting. We found that most of the people that we asked wanted to vote but not become a DRep. The role of Direct Voter came 'directly' from the voters themselves. We had to somehow carve out this role without breaking the UX, as it was not anticipated in the CIP originally.

**Comment by bosko-m** [comment]
Closed with #2005
