### ISSUE TITLE
[USERSNAP] Multi-sig

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2003]
**Taken at**: https://gov.tools/
**Fields**:
- Name of the idea or new feature: Multi-sig
- Please summarize your idea or new feature: Support for multi-sig wallets.
- Any additional details: Integrate with platforms like Summon to allow DReps multi-sig login to the dashboard.

**Browser**: Chrome 119 (Linux)
**Screen size**: 1920x1080
**[Open #78 in Usersnap](https://app.usersnap.com/l/feedback/c2b226c6-674d-4afb-846a-5ea21b8e0fad?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
> Name of the idea or new feature: Multi-sig

GovTool could do this if there was a new wallet interface written to allow for this (CIP95 does not support)
