### ISSUE TITLE
[USERSNAP] The Find a DRep search function does not work on the page: https://gov.tools/connected/drep_directory I can't find any DREp by name

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2006]
**Taken at**: https://gov.tools/connected/drep_directory
**Fields**:
- Add a comment: The Find a DRep search function does not work on the page:
https://gov.tools/connected/drep_directory
I can&#39;t find any DREp by name

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 1928x965
**[Open #123 in Usersnap](https://app.usersnap.com/l/feedback/864fa879-3b24-43cc-aade-1daaae521276?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
duplicate https://github.com/IntersectMBO/govtool/issues/1893
