### ISSUE TITLE
[USERSNAP] The search bar in the DRep directory does not work.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2007]
**Taken at**: https://gov.tools/connected/drep_directory
**Fields**:
- Add a comment: The search bar in the DRep directory does not work.

**Browser**: Chrome 128 (macOS Catalina)
**Screen size**: 2560x1440
**[Open #124 in Usersnap](https://app.usersnap.com/l/feedback/95a4f03e-f3eb-454d-a093-bf19a0592aa2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
duplicate https://github.com/IntersectMBO/govtool/issues/1893
