### ISSUE TITLE
🐛 Voting on non-Info gov actions not enabled on protocol major version 10

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#2008]
### Area

Voting Pillar

### Domain

sanchogov.tools

### Which wallet were you using?

N/A

### Context

Voting on non-info action (eg. Hard fork) is not enabled on current Sanchonet which is on full governance mode (protocol major version 10)

<img width="1417" alt="Screenshot 2024-09-11 at 05 19 03" src="https://github.com/user-attachments/assets/fd00ffc2-0841-48dd-b315-147fbab9cbc2">

### Steps to reproduce

1. Connect any wallet as a DRep
2. Select any non-info governance action
3. On the governance action details page, check if voting is enabled or not. Compare by checking any info gov action.

### Actual behavior

It is currently not possible to vote on non-info governance actions.

### Expected behavior

It should be possible to vote on non-info governance actions.

**Comment by spannercode** [comment]
The issue also fixed and deployed on sanchonet deployments. So, this issue can be closed.
CC: @bosko-m

**Comment by bosko-m** [comment]
Closing as per the comment above.
