### ISSUE TITLE
🐛 Ada amount is missing on self delegated voting power of DRep

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#2036]
### Area

Voting Pillar

### Domain

gov.tools

### Which wallet were you using?

Eternal Beta

### Context

The self delegated Ada amount is missing value placement. Here is a screenshot:
<img width="1418" alt="Screenshot 2024-09-12 at 19 56 00" src="https://github.com/user-attachments/assets/c2544b88-379e-446c-8b5f-75cab3193ce5">

Note the following text above the DRep Name:
```
You have delegated <strong>₳ {{ada}}</strong> to yourself:
```

### Steps to reproduce

1. Assuming you're a DRep and you have delegated your stake to yourself
2. Check your DRep page

### Actual behavior

```
You have delegated <strong>₳ {{ada}}</strong> to yourself:
```

### Expected behavior

`<strong>₳ {{ada}}</strong>` should have been evaluated and rendered than as string value.

**Comment by Ryun1** [comment]
Push for a hot fix today!

**Comment by spannercode** [comment]
The fix for this issue is already deployed on all environments. So, this issue can be closed.
CC: @bosko-m

**Comment by bosko-m** [comment]
Closing as per the comment above.
