### ISSUE TITLE
💡 Enhance Gitbook - add other governance tools

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#2037]
### Area

Other

### Is there new design needed?

No

### What?

- would be great to add links / summary of other governance tools via the gitbook

### Why?

- so people can see the other options for governance tooling

### How?

I will do it

### (Optional) User Story with acceptance criteria

n/a

**Comment by bosko-m** [comment]
@Ryun1 Is this really in progress?

**Comment by bosko-m** [comment]
With CC Portal being added to the docs, what other tools did you have in mind @Ryun1 ?

**Comment by Ryun1** [comment]
done! at least V1 is done
