### ISSUE TITLE
💡 Reorganise GovTool repositories

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#2038]
### Area

Other

### Is there new design needed?

Yes

### What?

- We have a lot of GovTool repositories
- It is a mess to navigate and confusing from the outside looking in 
- We should have a repo for
  - wrapper (current govtool)
  - proposal pillar (backend and frontend)
  - voting pillar (backend frontend)
  - delegation pillar (backend frontend)
  - documentation

### Why?

this makes more sense

### How?

- Ryan to coordinate with We Deliver team on combining into proposal pillar repo
- Other repos will be audited and checked, with basic docs ensured in each repo

### (Optional) User Story with acceptance criteria

N/A

**Comment by Ryun1** [comment]
Updating docs
https://github.com/IntersectMBO/govtool-voting-pillar/pull/8

**Comment by Ryun1** [comment]
https://github.com/IntersectMBO/govtool-delegation-pillar/pull/5

**Comment by Ryun1** [comment]
https://github.com/IntersectMBO/govtool-proposal-pillar/pull/5

**Comment by bosko-m** [comment]
Is this done @Ryun1 ?

**Comment by Ryun1** [comment]
yurpp @bosko-m
