### ISSUE TITLE
[USERSNAP] Can't connect to second Yoroi wallet.  Always connects to the first one.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2045]
**Taken at**: https://gov.tools/dashboard
**Fields**:
- Add a comment: Can&#39;t connect to second Yoroi wallet.  Always connects to the first one.

**Browser**: Chrome 127 (Linux)
**Screen size**: 2560x1600
**[Open #126 in Usersnap](https://app.usersnap.com/l/feedback/dc9352e6-8a9a-4f30-a976-dbc5fbb7ea2f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
Not enough details here to determin the issue,
potentially because the user has both Yoroi and Yoroi nightly installed - this will cause issues (with any DApp) and one should be disabled via extensions menu
