### ISSUE TITLE
[USERSNAP] Lace wallet connect complaiins of wrong networkdespite being mainnet alredty

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2046]
**Taken at**: https://sanchogov.tools/dashboard
**Fields**:
- Add a comment: Lace wallet connect complaiins of wrong networkdespite being mainnet alredty

**Browser**: Chrome 128 (ChromeOS)
**Screen size**: 1536x864
**[Open #127 in Usersnap](https://app.usersnap.com/l/feedback/f6c43589-1d44-41bd-a199-067d5731139d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
User is connected to SanchoNet instance,
Hopwfully confusion will be fixed via https://github.com/orgs/IntersectMBO/projects/30/views/30?pane=issue&itemId=79285368
