### ISSUE TITLE
[USERSNAP] Connect Multiple Wallets (Yoroi)

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2051]
**Taken at**: https://gov.tools/dashboard
**Fields**:
- Name of the idea or new feature: Connect Multiple Wallets (Yoroi)
- Please summarize your idea or new feature: I have multiple independent wallets in Yoroi.  I&#39;m having a hard time selecting my second wallet.  I disconnect my wallet but when I try to connect again it goes to the same wallet without giving me a choice.

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 1920x1080
**[Open #80 in Usersnap](https://app.usersnap.com/l/feedback/84ce7c7f-da8f-4936-ac6b-4da99d6b5986?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
This is the second time I have seen this one.
I had assumed this was to do with having Yoroi and Yoroi nightly both installed at the same time
I will test out GovTool with Yoroi and see if I can replicate any of this.

**Comment by Ryun1** [comment]
I have been struggling to replicate this issue
