### ISSUE TITLE
[USERSNAP] Tresor wallet. v.8.2.1 Tresor hidden wallet will not sign the delegation transaction

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2052]
**Taken at**: https://gov.tools/dashboard
**Fields**:
- Add a comment: Tresor wallet.
v.8.2.1

Tresor hidden wallet will not sign the delegation transaction

**Browser**: Chrome 128 (Linux)
**Screen size**: 1718x792
**[Open #128 in Usersnap](https://app.usersnap.com/l/feedback/76cfce12-7237-402c-b084-6f07acf75a36?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
I believe this user means their Trezor hardware wallet
Most likely cause of error is not using the latest Tezor firmware
Unfortunately there is not enough details to be able to assist beyond this
