### ISSUE TITLE
🐛 Proposal discussion comments limited to `256` characters

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#2054]
### Area

Proposal Pillar

### Domain

gov.tools

### Context

- Proposal discussion comments are limited to `256` chars
- This is probably not enough to be able to give written out replies
- Lets up to `2500` characters

### Steps to reproduce

1. Go to proposal discussion
2. Go to a proposal
3. Try to comment

### Actual behavior

- comments limited to 256 chars

### Expected behavior

- comments are limited to a reasonable length to allow longer form comments

**Comment by bosko-m** [comment]
@teske00 Did this end up in the latest [1.0.20 release](https://github.com/IntersectMBO/govtool/releases/tag/v1.0.20)?

**Comment by teske00** [comment]
@bosko-m Yes this is on PROD right now

**Comment by bosko-m** [comment]
Closing as per the comment above.
