### ISSUE TITLE
[USERSNAP] Only search by drep id?

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2056]
**Taken at**: https://gov.tools/drep_directory/
**Fields**:
- Name of the idea or new feature: Only search by drep id?
- Please summarize your idea or new feature: When I&#39;m using this website I&#39;m normally want to determine the drep ID of a specific person or group by searching the name. It is quite useless to search by a technical ID of someone I already know.
- Any additional details: https://gov.tools/drep_directory/ 

**Browser**: Firefox 130 (Windows 10)
**Screen size**: 1920x1080
**[Open #81 in Usersnap](https://app.usersnap.com/l/feedback/38bd2901-6304-4355-9d09-7004aec141c0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
This is being worked on #1893
