### ISSUE TITLE
[USERSNAP] Trying to vote 'no' on the missing data governance action, Yoroi Dapp connector just hangs.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2057]
**Taken at**: https://gov.tools/connected/governance_actions/15f82a365bdee483a4b03873a40d3829cc88c048ff3703e11bd01dd9e035c916#0
**Fields**:
- Add a comment: Trying to vote &#39;no&#39; on the missing data governance action, Yoroi Dapp connector just hangs.

**Browser**: Chrome 127 (Linux)
**Screen size**: 1920x1080
**[Open #129 in Usersnap](https://app.usersnap.com/l/feedback/88b90ff2-abe5-437e-8333-5e302aeca667?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
replaced by https://github.com/IntersectMBO/govtool/issues/2068
