### ISSUE TITLE
[USERSNAP] Language Selector

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2058]
**Taken at**: https://gov.tools/governance_actions/59fd353253eb177e2104e8f23ea4c63e3d32ef95c7865d03e90d3884424dc1db#0
**Fields**:
- Name of the idea or new feature: Language Selector
- Please summarize your idea or new feature: Is important for our global community to have the posibility to select a prefer language (e.g. Spanish, English, Japanese, German)
- Any additional details: In the attached file, the Governance Action (Info) is in Japanese.

**Browser**: Chrome 128 (Linux)
**Screen size**: 1366x768
**[Open #82 in Usersnap](https://app.usersnap.com/l/feedback/03f949bf-9d6b-4835-b356-bd6f76fd86d7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
This will be implemented when there are translated versions of GovTool
