### ISSUE TITLE
🐛 The Fee for casting a Vote On-Chain has increased by over fivefold to be 1 ADA

### ISSUE THREAD

**Issue by intertreeJK** [IntersectMBO/govtool#2059]
### Area

Voting Pillar

### Domain

gov.tools

### Which wallet were you using?

Eternal Wallet v1.12.15

### Context

I cast a new Vote On-Chain and this time was charged 1 ADA to submit the Voting Transcation, when last time it was only 0.180285 ADA. 

This is over a fivefold increase in Voting Costs in less than 1 month since gov.tools launched.

This concerns me, as I would much rather be able to Submit five Votes with the same amount of ADA than only one. As it was previously.

Please work to reduce the Fee associated with Voting to reflect its previous setting. 

### Steps to reproduce

Connect Wallet, Cast a Vote on a Proposal.

### Actual behavior

1 ADA Fee when previously only -0.180285 ADA.

### Expected behavior

A smaller Fee of around -0.180285 ADA value.

**Comment by intertreeJK** [comment]
I believe I know what causes this. 

Interaction with gov.tools places back 1 ADA Value UTXOs into your Wallet when it is finished with setting up your Transactions for you.

This then leads to a future problem of it having to pick up 2 separate 1 ADA value UTXOs  to cover Transaction Fees the next time you interact with it.

As the lowest amount of ADA that can be sent back to you is ~1 ADA at this time, it literally CAN'T give you your change of 1 ADA when it uses that second UTXO value it picks up to cover Protocol Fees.

So, it just consumes the whole 1 ADA UTXO by sending it to the Treasury as a Fee.

The solution will involve gov.tools NO LONGER PLACING 1 ADA VALUE UTXOs into User's Wallets after it builds a Transaction for them.

I have actually raised this 1 ADA return UTXO issue in various chat channels multiple times now.

I hope gov.tools will stop the behaviour in future.

**Comment by Ryun1** [comment]
Caused by poor UTxO management https://github.com/IntersectMBO/govtool/pull/2063 should improve
