### ISSUE TITLE
[USERSNAP] Please add commas to delimit thousands

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2060]
**Taken at**: https://gov.tools/connected/governance_actions/59fd353253eb177e2104e8f23ea4c63e3d32ef95c7865d03e90d3884424dc1db#0
**Fields**:
- Name of the idea or new feature: Please add commas to delimit thousands
- Please summarize your idea or new feature: Currently, DREP vote counts are difficult to read. They show as many digits and it is touch to compare. They are seen as:

DReps yes ₳ 81570879.833413

abstain ₳ 97276671.736064

no ₳ 7386787.499895

Why not show them as: 81,570,879.833413 ? 

**Browser**: Chrome 128 (Windows 10)
**Screen size**: 1926x964
**[Open #83 in Usersnap](https://app.usersnap.com/l/feedback/103d02ad-fce0-4381-aef0-07d8d0a02722?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by phillewis** [comment]
Different cultures use different characters to delimit numbers. It should use the user's browser locale to use the appropriate character.

**Comment by m-i-k-e** [comment]
This has been a persistent simple oversight. We have asked for it to be fixed. That is, add commas.

**Comment by bosko-m** [comment]
Duplicate of #2305 .
