### ISSUE TITLE
💡 Change Constitutional Committee Vote Totals to be Constitutional / Unconstitutional

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#2062]
### Area

Voting Pillar

### Is there new design needed?

No

### What?

- Change constitutional committee vote totals to be `constitutional` for `yes` and `unconstitutional` for `no`

### Why?

- This better reflects why they are voting

### How?

- edit the frontend display

### (Optional) User Story with acceptance criteria

N/A

**Comment by SoldierFace** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive
