### ISSUE TITLE
💡 Governance Action Details - Supporting Links don't use CIP-100 Reference Labels

### ISSUE THREAD

**Issue by phillewis** [IntersectMBO/govtool#2070]
### Area

Voting Pillar

### Is there new design needed?

No

### What?

Governance action details are displayed using a CIP-108 compliant document. This extends CIP-100 for providing references. Each reference has a label and uri. A governance action's details page uses the uri for both the link and the display text. It should use the label for the display text.

### Why?

The label is intended to give users additional context about the link. 

### How?

Simple change.

### (Optional) User Story with acceptance criteria

As a DRep I want to have additional information about the "Supporting links" in a governance action so I can be better informed about their purpose.

### Reference screenshot

![Image](https://github.com/user-attachments/assets/527ec8d8-9d77-4355-9c40-3ae8cb06b62e)

**Comment by bosko-m** [comment]
@MSzalowski Use this as a reference

![Image](https://github.com/user-attachments/assets/24dea6a4-33ed-4819-ab22-818e172d47f2)

**Comment by bosko-m** [comment]
@phillewis Edited description to add screenshot. 👍

**Comment by bosko-m** [comment]
Verified on Preview.
