### ISSUE TITLE
[USERSNAP] Search tool to find drep by name

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2071]
**Taken at**: https://gov.tools/drep_directory
**Fields**:
- Name of the idea or new feature: Search tool to find drep by name
- Please summarize your idea or new feature: When I search using the current search tool, when I put in the name of the drep I can see already, no results return! So my idea is to have a search tool that actually searches and returns a result. Go check for yourselves.
- Any additional details: Bizzare how you didn&#39;t have this most basic of functions available or useable.

**Browser**: Chrome 128 (macOS Catalina)
**Screen size**: 1938x1158
**[Open #84 in Usersnap](https://app.usersnap.com/l/feedback/92eeb3d8-6e59-4c72-be3e-992d236318d7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
This is a known issue, and there is a ticket for it: #1893
