### ISSUE TITLE
[USERSNAP] voting still not working - pop up window appears that says the hash computed by the dapp does not match the hash computed by Yoroi.  The action never completes.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2079]
**Taken at**: https://gov.tools/connected/governance_actions/15f82a365bdee483a4b03873a40d3829cc88c048ff3703e11bd01dd9e035c916#0
**Fields**:
- Add a comment: voting still not working - pop up window appears that says the hash computed by the dapp does not match the hash computed by Yoroi.  The action never completes.

**Browser**: Chrome 127 (Linux)
**Screen size**: 1920x1080
**[Open #133 in Usersnap](https://app.usersnap.com/l/feedback/3b9ceb82-a629-4319-a026-598e0df02eb9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by Ryun1** [comment]
Yoroi team have pushed the fix
