### ISSUE TITLE
Gov.tools generated JSON - metadata errors

### ISSUE THREAD

**Issue by kostaspanagias** [IntersectMBO/govtool#2082]
I have found two metadata errors when registering as a DRep through gov.tools. The errors are shown when checking your DRep profile on Adastat.net Cardano Explorer.

![adastat](https://github.com/user-attachments/assets/a70c9b75-28de-4db7-8f54-31a9323e077c)

I have reached to them via intersect working group DReps and they confirmed that the issue is not on their side; at least the first one (screenshot below):

![wg_dreps](https://github.com/user-attachments/assets/8d90d842-0abe-4914-88af-e6156d53f8e2)

### Metadata error shown in adastat: 
`Error Offchain Voting Anchor: JSON decode error from when fetching metadata from Just https://raw.githubusercontent.com/kostaspanagias/drep/refs/heads/main/Kostas%20Panagias.jsonld resulted in : "Error in $['@context']: key \"@language\" not found,`

### Feedback I found about the error:
According to CIP-0100 the *@language* property should be included under the *@context*. However, the automatically generated JSON from gov.tools **does not include this property (tested twice)**.

#### CIP-0100
Link: https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/README.md
Image: 
![cip100](https://github.com/user-attachments/assets/ace8b088-7195-47b6-ad42-e0993b79007e)

#### gov.tools output:
Link (my DRep json): https://raw.githubusercontent.com/kostaspanagias/drep/refs/heads/main/Kostas%20Panagias.jsonld

Image:
![json](https://github.com/user-attachments/assets/b584f675-bbfe-4019-b232-af22680e575c)

---

### Metadata Error Shown in adastat: 
`CIP-100:Error in $.body.references[0]: reference type should be one of [\"Other\",\"GovernanceMetadata\"] but it's Link`

### Feedback I found about the error:
I couldn't actually map the error shown in my JSON files. Unfortunately, I don't have any further feedback on this one.

**Comment by bosko-m** [comment]
CC @spannercode

**Comment by spannercode** [comment]
Since the language support is not yet there on GovTool, we can default to English for now.
To make the metadata compliant, as mentioned on the CIP 100, `@language` field can be added to `@context` with default value of `en`. The rest of the metadata can remain the same.

```json
{
  "@context": {
    "@language": "en",
    "CIP100": "https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/README.md#",
    "CIP119": "https://github.com/cardano-foundation/CIPs/blob/master/CIP-0119/README.md#",
    ...
  }
  ...
}
```
CC: @bosko-m @jdyczka

**Comment by jdyczka** [comment]
Regarding the first issue, CIP-100 states that `@language` SHOULD be included, not MUST BE included, so it's a bit of a grey area.

**Comment by jdyczka** [comment]
Regarding the second issue, CIP-119 defines additional types for reference: `Link` and `Identity`

**Comment by jdyczka** [comment]
And about the issue with drep name not being shown in Adastat, if I understand correctly they use data from dbSync, which will not include any metadata if it's not validated correctly. So the above mentioned issues are the reason why it's not showing.

**Comment by jdyczka** [comment]
This issue is connected to #1856

**Comment by jdyczka** [comment]
@spannercode wisely suggested to add the `@language` property in any case, so as not to create new DReps that, as for now, will result with a dbSync error.

That however, still doesn't fix errors for already created DReps. And since on GovTool their metadata will be displayed correctly, those users might not be aware of the problems on other tooling. So maybe we should also display some kind of a prompt instructing the user to regenerate the jsonld file through editing the DRep? cc @m-i-k-e

**Comment by m-i-k-e** [comment]
It seems to me that this is a terminology issue with the CIP. 'Should' can also mean 'must'. That's how it's been interpreted it seems. I think we 'should' add the language property, but also that adastat should allow for registrations that don't have it, and assume they're English.

I'm not a fan of asking people to re-register at this point. Do we know how many DReps are affected?

**Comment by dmitrystas** [comment]
> but also that adastat should allow for registrations that don't have it

I just wanted to point out this is not AdaStat warning, but DB-Sync one. I.e. all the tools (explorers and other) that use DB-Sync are affected by the issue

**Comment by bosko-m** [comment]
> So maybe we should also display some kind of a prompt instructing the user to regenerate the jsonld file through editing the DRep?

@m-i-k-e Any comment on @jdyczka simple copy suggestions?
