### ISSUE TITLE
[USERSNAP] Bug my wallet of 194 ada is showing up with 372359 voting power. Correct delegation. 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2084]
**Taken at**: https://gov.tools/dashboard
**Fields**:
- Add a comment: Bug my wallet of 194 ada is showing up with 372359 voting power. Correct delegation. 

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 2560x1440
**[Open #135 in Usersnap](https://app.usersnap.com/l/feedback/f39d5b69-1a53-4064-b80f-e81c9c1983ef?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
I don't know if we can investigate this without seeing the user's wallet balance, stake keys etc. @Ryun1?
