### ISSUE TITLE
🐛  Stuck dRep Directory on Loading

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#2090]
### Area

Other

### Domain

dev-sanchogov.tools

### Context

When trying to navigate to the dRep directory using the URL `connected/dRep_directory` while the wallet is disconnected, and `dRep_directory` when the wallet is connected, the dRep directory page gets stuck on loading.

### Steps to reproduce

1. Navigate to `/connected/dRep_directory` on a disconnected wallet.
2. Navigate to `/dRep_directory` on a connected wallet.
3. Observe the page behavior.

### Actual behavior

The dRep directory page remains stuck on loading indefinitely.

![image](https://github.com/user-attachments/assets/78ce8a49-8702-407a-aa16-3d2608522ecd)

### Expected behavior

The dRep directory page should render the list of dReps successfully without getting stuck.

### Allure report
- [2I. Should check validity of DRep Id](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/151/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/3e8640a66f5b81e1/)
- [2J. Should search by DRep id](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/151/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/938cb2d1b07e00a/)
- [2K_1. Should filter DReps](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/151/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/fff3f560b25c670f/)
- [2K_2. Should sort DReps](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/151/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/ebb5123239583926/)
- [2K_3. Should sort DReps randomly](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/151/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/eca10325dd7f2ca6/)
- [2M. Should access dRep directory page on disconnected state](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/151/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/9154a0623ec07242/)
- [2O. Should load more DReps on show more](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/151/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/ac8159d50ab99d39/)
- [2Q. Should include DRep status and voting power on the DRep card](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/151/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/2982668149cf5418/)

**Comment by MSzalowski** [comment]
Wrapper related, due to its routing configuration.
