### ISSUE TITLE
[USERSNAP] I can't verify my identity

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2091]
**Taken at**: https://gov.tools/proposal_discussion
**Fields**:
- Add a comment: I can&#39;t verify my identity

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 1536x864
**[Open #136 in Usersnap](https://app.usersnap.com/l/feedback/c8acccee-3da3-4151-876b-955620839134?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
This doesnt have enough details. Any screenshot attached or existing in Usersnap @l-br1 @kickloop ?

**Comment by bosko-m** [comment]
Closed as it doenst have sufficient information and is too vague.
