### ISSUE TITLE
[USERSNAP] Hi, I see Gov Tools reporting that I have delegated 26,000 to myself as a Drep. However, I have not delegated that amount. I have delegated only around 1400 ADA to myself. 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2095]
**Taken at**: https://gov.tools/connected/drep_directory/drep14l69ewnmc5h6uftda9ghs3mw49hdu7w93e9alhzxckp0v5pczql
**Fields**:
- Add a comment: Hi, I see Gov Tools reporting that I have delegated 26,000 to myself as a Drep. However, I have not delegated that amount. I have delegated only around 1400 ADA to myself. 

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 1921x965
**[Open #137 in Usersnap](https://app.usersnap.com/l/feedback/7f4f73bf-20c2-4939-8772-66d5f50332c6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
@Ryun1 This seems interesting, Im thinking you might know something about it, feels familiar.

**Comment by bosko-m** [comment]
Fixed with #2000.
