### ISSUE TITLE
[USERSNAP] dates are wrong. epoch boundary, and therefore expiry  is Sunday 6th October.  

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2125]
**Taken at**: https://gov.tools/governance_actions
**Fields**:
- Add a comment: dates are wrong. epoch boundary, and therefore expiry  is Sunday 6th October.  

![SCREENSHOT](https://resources.usersnap.com/company/127c73ca-bcdd-4a4a-89e5-a1faa2d0e4ca/datapoint_screenshot/e63a6e1f-0df2-4606-b36a-c16e5d34c8f6-annotated_a0214524-6e25-402e-8e78-028d45f03198.png?etag=07192e776a40bf4dd3a93fea745bc1be)
*[Download original image](https://resources.usersnap.com/company/127c73ca-bcdd-4a4a-89e5-a1faa2d0e4ca/datapoint_screenshot/e63a6e1f-0df2-4606-b36a-c16e5d34c8f6-annotated_a0214524-6e25-402e-8e78-028d45f03198.png?etag=07192e776a40bf4dd3a93fea745bc1be)*

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 1368x912
**Browser size**: 1824x1047
**[Open #139 in Usersnap](https://app.usersnap.com/l/feedback/32e0236f-d7d5-42da-b7af-4bb0288205bc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
@Ryun1 can you please check this?

**Comment by Ryun1** [comment]
DBSync gives expiry epoch number, GovTool converts this to a datetime
This datetime conversion seems to be incorrect

**Comment by MSzalowski** [comment]
@Ryun1 Do you know if there is any better way of counting the epoch boundaries than counting the epoch.end_time - epoch.start_time?

These results in different boundaries per epoch (which is reasonable).

The problem is, that we don't have records for the future epochs to get the boundaries, or I am missing something

**Comment by MSzalowski** [comment]
Additional context:

2 last existing epochs in db-sync:
cexplorer=# select * from epoch where no = '481';
 id  |    out_sum    |   fees   | tx_count | blk_count | no  |     start_time      |      end_time       
-----+---------------+----------+----------+-----------+-----+---------------------+---------------------
 533 | 7831829434041 | 40378681 |      208 |      1705 | 481 | 2024-10-08 00:30:11 | 2024-10-08 11:02:39
(1 row)

cexplorer=# select * from epoch where no = '480';
 id  |    out_sum    |   fees   | tx_count | blk_count | no  |     start_time      |      end_time       
-----+---------------+----------+----------+-----------+-----+---------------------+---------------------
 532 | 3529665779274 | 19439915 |       95 |      4043 | 480 | 2024-10-07 00:30:11 | 2024-10-08 00:29:31
(1 row)

And for example for that proposal:
cexplorer=# select * from gov_action_proposal ORDER BY id DESC LIMIT 1;
 id  | tx_id | index | prev_gov_action_proposal |   deposit    | return_address | expiration | voting_anchor_id |    type    |      description      | param_proposal | ratified_epoch | enacted_epoch | dropped_epoch | expired_epoch 
-----+-------+-------+--------------------------+--------------+----------------+------------+------------------+------------+-----------------------+----------------+----------------+---------------+---------------+---------------
 482 | 30931 |     0 |                          | 100000000000 |           6798 |        492 |             4453 | InfoAction | {"tag": "InfoAction"} |                |                |               |               |              
(1 row)

We have the expiry epoch no - 492

Which is not existing in the epoch table

**Comment by Ryun1** [comment]
Okay, its not pretty, but what about 

latest_epoch = `SELECT * FROM epoch ORDER BY no DESC LIMIT 1`
current_ga = `SELECT * FROM gov_action_proposal ORDER BY id DESC LIMIT 1;`

ga_epoch_delta = (current_ga.expiration - latest_epoch.no)

ga_expiry_date = current_time + (ga_epoch_delta.no * epoch_length_in_days)

where

epoch_length_in_days = 5 (mainnet) | 1 (preview) | 1 (sanchoNet)

**Comment by bosko-m** [comment]
@MSzalowski I would say still not right for the mainnet.
https://gov.tools/connected/governance_actions
Seems that:
1. Correct epoch is calculated based on a submission date
2. Wrong date is set for expiration date ([this action](https://gov.tools/connected/governance_actions/7fd6429add8f2611ad8d48c0cc49101463093aec285faea402e8cfde78ea58d7#0) has 19th November as expiration date and 521 as epoch while in fact epoch boundary of 521 is 15th November and for 522 is 20th November. Same goes for this action, expiration date is set to exactly 4 days after the epoch boundary of stated epoch)
Should expiration date be set to the epoch boundary? According to [the CIP-1694 lifecycle](https://github.com/cardano-foundation/CIPs/tree/master/CIP-1694#lifecycle) : 

All submitted governance actions will therefore either:
1. be ratified, then enacted
2. or expire after a number of epochs

@Ryun1 @MSzalowski Whats your opinion?
