### ISSUE TITLE
[USERSNAP] Unable to register

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2132]
**Taken at**: https://gov.tools/dashboard
**Fields**:
- Add a comment: Unable to register

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 1920x1080
**[Open #141 in Usersnap](https://app.usersnap.com/l/feedback/b7810931-389d-43e9-9c92-87248953b61b?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
This doesnt have enough details. Any more info/screenshot in usersnap @l-br1 @kickloop ?

**Comment by bosko-m** [comment]
Closed as it doenst have sufficient information and is too vague.
