### ISSUE TITLE
[USERSNAP] Archive of governance actions and final result of an expired action

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2139]
**Taken at**: https://gov.tools/connected/governance_actions
**Fields**:
- Name of the idea or new feature: Archive of governance actions and final result of an expired action
- Please summarize your idea or new feature: Hi, I voted as a DRep on the first governance action (name hard fork Hosky). It has expired in the meantime. I do not see it in the Cardano Gov Tool any more. It would be nice to have an 1. archive for the actions that were put to vote and 
2. it would be nice to have an official archive of which actions were approved / not approved and what was the final result of the vote

**Browser**: Chrome 129 (Windows 10)
**Screen size**: 1920x962
**[Open #87 in Usersnap](https://app.usersnap.com/l/feedback/dd108f9e-35a9-401f-85c5-383997bc113d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
This is going to be covered with Governance Action outcome - https://docs.intersectmbo.org/intersect-community-grants/closed-grants/govtool-governance-action-outcome
