### ISSUE TITLE
DRep directory cards

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#215]
Create DRep directory cards

# Home view (wallet not connected)
<img width="894" alt="image" src="https://github.com/IntersectMBO/govtool/assets/24510246/fe1ba4ca-3b28-485f-851f-80da176432b3">

[Link to figma](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7834-151129&mode=design&t=8yNcFlPNERNFVazh-4)

# Dashboard view (wallet is connected)
<img width="414" alt="image" src="https://github.com/IntersectMBO/govtool/assets/24510246/9cc9a193-9ad8-4bf9-8ff7-72d5e17aada2">

[Link to figma](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7868-31034&mode=design&t=8yNcFlPNERNFVazh-4)

**Comment by pmbinapps** [comment]
OK ON DASHBOARD


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/e818cca0-9617-4e60-9ab1-563f77f6ddd1)
