### ISSUE TITLE
[USERSNAP] Tried voting on 7fd6429, after signing the transaction the website hung with the loading circle, now it won't let me re-submit the vote and it's showing I have not voted.  No transaction shows on the wallet.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2150]
**Taken at**: https://gov.tools/connected/governance_actions/7fd6429add8f2611ad8d48c0cc49101463093aec285faea402e8cfde78ea58d7#0
**Fields**:
- Add a comment: Tried voting on 7fd6429, after signing the transaction the website hung with the loading circle, now it won&#39;t let me re-submit the vote and it&#39;s showing I have not voted.  No transaction shows on the wallet.

**Browser**: Chrome 129 (Linux)
**Screen size**: 2560x1600
**[Open #144 in Usersnap](https://app.usersnap.com/l/feedback/5956f8c5-bc72-498d-aa1b-2bb280751eb1?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
@spannercode Can we try to reproduce this one? Perhaps intentionally killing the network connection after transaction fails to see if we can reproduce this. We can test it on preview.

**Comment by spannercode** [comment]
> Tried voting on 7fd6429, after signing the transaction the website hung with the loading circle, now it won't let me re-submit the vote and it's showing I have not voted.

There is a loading circle on the vote button while vote transaction is being casted. When it is completed, the user is redirected to voted on by me tab which has a reported bug (https://github.com/IntersectMBO/govtool/issues/2379). 

When the transaction is still in progress, the re-submission of the vote is not available, which is expected.

> No transaction shows on the wallet.

This is strange. Depending on the wallet used, there should at least be a pending transaction on the wallet if the signing was successful.

@bosko-m 
I have tested on prod(gov.tools) by re-voting on the plomin info action, and it was successful.

**Comment by bosko-m** [comment]
Awesome feedback @spannercode .
Unfortunately we dont have any contact info so will keep an eye on this.
