### ISSUE TITLE
[USERSNAP] Previous report of unsuccessful vote (UI hangs with loading symbol) was using Yoroi wallet.  Was able to vote using Lace wallet.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2154]
**Taken at**: https://gov.tools/connected/governance_actions/7fd6429add8f2611ad8d48c0cc49101463093aec285faea402e8cfde78ea58d7#0
**Fields**:
- Add a comment: Previous report of unsuccessful vote (UI hangs with loading symbol) was using Yoroi wallet.  Was able to vote using Lace wallet.

**Browser**: Chrome 129 (Linux)
**Screen size**: 2560x1600
**[Open #145 in Usersnap](https://app.usersnap.com/l/feedback/c365df3d-049d-4c03-9c85-510a07e34fa2?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
Wallet issue.
