### ISSUE TITLE
[USERSNAP] Why is it that the expiration date of the Ikigai project keeps changing almost every day? I think the expiration date should be said and done, you shouldn't be able to change it as you please. It just becomes a joke. 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2157]
**Taken at**: https://gov.tools/governance_actions
**Fields**:
- Add a comment: Why is it that the expiration date of the Ikigai project keeps changing almost every day? I think the expiration date should be said and done, you shouldn&#39;t be able to change it as you please. It just becomes a joke. 

**Browser**: Chrome 128 (macOS Catalina)
**Screen size**: 1858x857
**[Open #147 in Usersnap](https://app.usersnap.com/l/feedback/3e52f147-4f53-45ba-b3b5-0256db446a25?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
What is the Ikigai project?

**Comment by bosko-m** [comment]
@m-i-k-e It was the title of the Governance Action, but is resolved now.
