### ISSUE TITLE
[USERSNAP] The truncation of the action ID is really annoying, especially when it's not necessary to fit the content in the window width. For my workflow, I need to grab the transaction ID and action index separately, so copying the entire thing to the ...

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2177]
**Taken at**: https://gov.tools/connected/governance_actions/7fd6429add8f2611ad8d48c0cc49101463093aec285faea402e8cfde78ea58d7#0
**Fields**:
- Add a comment: The truncation of the action ID is really annoying, especially when it&#39;s not necessary to fit the content in the window width. For my workflow, I need to grab the transaction ID and action index separately, so copying the entire thing to the clipboard isn&#39;t really the best solution. Can you please have it display the entire gov action ID when there is room to do so?

![SCREENSHOT](https://resources.usersnap.com/company/127c73ca-bcdd-4a4a-89e5-a1faa2d0e4ca/datapoint_screenshot/61006abf-c14c-4fe2-8405-81165d5e5e7b-annotated_a4301cf6-54cd-424c-be24-f250fa3eb40f.png?etag=3880649d5887ab14d3848dc60be755d2)
*[Download original image](https://resources.usersnap.com/company/127c73ca-bcdd-4a4a-89e5-a1faa2d0e4ca/datapoint_screenshot/61006abf-c14c-4fe2-8405-81165d5e5e7b-annotated_a4301cf6-54cd-424c-be24-f250fa3eb40f.png?etag=3880649d5887ab14d3848dc60be755d2)*

**Browser**: Chrome 129 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1440x718
**[Open #148 in Usersnap](https://app.usersnap.com/l/feedback/ddf51cba-b189-4668-ab0c-380336ae1942?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
I agree, it doesn't need to be truncated here. What is the "action index"?

**Comment by m-i-k-e** [comment]
I discussed this in depth with a user, possibly the same as posted this comment.

Here is a transcript: 

By 'action index' I mean the index portion of the gov action ID (the bit that comes after the #)

2841a581076167a0662f1b4f1a38bcc8eff386f9ce45c33ae33b1fe8289de210#0
Like here?Why is that important? Does it mean something?

Governance actions are identified by two pieces of information - the transaction ID they were published in and the index of the governance action within the transaction (transactions can publish more than one). In most tools, these are treated as separate fields and are not parsed in the single-string format GovTool renders them as, for example, cardano-cli:
`cardano-cli conway governance vote create \
  --yes \
  --governance-action-tx-id 2841a581076167a0662f1b4f1a38bcc8eff386f9ce45c33ae33b1fe8289de210 \
  --governance-action-index 0 \
  ...`


So, the index is the position of the GA, and say for example there are two GAs on one transaction, they would have the same base id (in your exmaple 2841a581076167a0662f1b4f1a38bcc8eff386f9ce45c33ae33b1fe8289de210), but the first would be index 0 and the second would be index 1?

Yes

**Comment by m-i-k-e** [comment]
So I've put a comment in Figma to change the main GA screen so it doesn't truncate the entire number. This should solve the problem.

**Comment by MSzalowski** [comment]
![Image](https://github.com/user-attachments/assets/68fcfa60-f1ec-400a-8259-c01d2ebc0c09)
Changed within one of the recent version updates.

**Comment by m-i-k-e** [comment]
Truncation is now happening again on Preview. Maybe some change wasn't merged?

<img width="1168" alt="Image" src="https://github.com/user-attachments/assets/dfc1068c-3164-49c8-8783-395fae533eee" />

**Comment by kneerose** [comment]
@MSzalowski 
![Image](https://github.com/user-attachments/assets/18e01590-ebee-4ef8-98cd-b3c63060acb0)

Truncation is still on the gov.tools

CC: @bosko-m

**Comment by sireto-sandip** [comment]
Action ID is included in the copy of both live and outcomes governance action pages. So, closing as completed.
