### ISSUE TITLE
Active delegation to DRep info section

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#218]
[Link to figma](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7824-119169&mode=design&t=KTLDNrZe8vSXCxAr-4)

<img width="1218" alt="image" src="https://github.com/IntersectMBO/govtool/assets/24510246/74d3d81a-ccf8-4bc5-aaad-aff739216267">

As a user, I want to be able to see my active delegation.
* It should contain information on the amount of delegated ADA.
* It should include the same card component as on the list

**Comment by pmbinapps** [comment]
OK - in progress state

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/6945eb30-6737-49f5-8fc3-3115b969a2a0)

OK: - delegation


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/2a143f18-ad12-42d2-a4e2-4f432df9f949)




![Image](https://github.com/IntersectMBO/govtool/assets/82152577/cab00e17-a0f7-4378-adbd-71f523c2ef79)
