### ISSUE TITLE
[USERSNAP] The Drep directory only shows a very few Drep options at once - the search function does not work and to be honest - albeit I applaud your effort - makes the whole Drep process impossible to find. How can I find a list of all Dreps? How can I...

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2181]
**Taken at**: https://gov.tools/drep_directory
**Fields**:
- Add a comment: The Drep directory only shows a very few Drep options at once - the search function does not work and to be honest - albeit I applaud your effort - makes the whole Drep process impossible to find. How can I find a list of all Dreps? How can I seach either by name or geography . Good luck with it and keep up the good work

**Browser**: Firefox 131 (Windows 10)
**Screen size**: 1382x864
**[Open #149 in Usersnap](https://app.usersnap.com/l/feedback/f108cb96-8d16-49d2-b8c6-4e04a332bd29?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
I don't understand what options the user wants to see.

He says the search function does not work, but does not give specifics as to what he was searching for.

DReps should be searchable by name, but we don't do 'geography'.

**Comment by jdyczka** [comment]
I suppose by `options` they could have just meant the current page size. I think they wanted to have a full list of DReps and then use Ctrl + f to find a specific DRep as a workaround for GovTool search that works only for id/view. But we fetch 10 DReps at a time so it becomes cumbersome to obtain a full list.

**Comment by m-i-k-e** [comment]
@jdyczka This page (and the GA list page) are in the process of being redesigned. What I think the user meant is that there are not a lot of 'filters', but I could be wrong. Also, the search needs to search everything.

**Comment by m-i-k-e** [comment]
We have also redesigned the search experience.

**Comment by bosko-m** [comment]
Will be solved in version [1.0.23](https://github.com/IntersectMBO/govtool/releases/tag/v1.0.23) which is soon to be available.
