### ISSUE TITLE
💡 CIP 129 support on GovTool (?)

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#2183]
### Area

Other

### Is there new design needed?

Yes

### What?

Currently, CIP 129 governance identifiers are not supported on GovTool. The following tools currently supports the CIP (not sure if it is up-to-date).

<img width="259" alt="Screenshot 2024-10-18 at 15 21 02" src="https://github.com/user-attachments/assets/d3b5307d-4ebc-4993-b607-711827aa0e3b">

### Why?

So that GovTool remains compatible with the rest of the ecosystem tooling.

### How?

Refer to the implementation plan of the CIP
https://github.com/StricaHQ/CIPs/blob/gov-identifiers/CIP-0129/README.md#implementation-plan

### (Optional) User Story with acceptance criteria

As a user of GovTool wallet connected or not,
When I use CIP129 governance identifiers for DRep and Governance actions on search or URLs
Then I see the appropriate governance details.

**Comment by MSzalowski** [comment]
@m-i-k-e Should we display both governance action identifiers (default, and CIP-129) or just CIP-129?

**Comment by MSzalowski** [comment]
[Pull request](https://github.com/IntersectMBO/govtool/pull/2341) is ready and will be merged once [this question](https://github.com/IntersectMBO/govtool/issues/2183#issuecomment-2460064898) is answered

**Comment by Ryun1** [comment]
@MSzalowski 

yes, both should be shown to users
