### ISSUE TITLE
DRep directory - DRep details page

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#219]
[Link to figma](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7664-26646&mode=design&t=KTLDNrZe8vSXCxAr-4)

<img width="1060" alt="image" src="https://github.com/IntersectMBO/govtool/assets/24510246/e9d1fd08-3dc1-4c15-a746-dc1ec2e32f2c">

1. After pressing View details on DRep directory page on selected DRep
2. Navigate to DRep Details page
3. On such page
a) Display DRep name
b) Display DRep ID
c) Status
d) Voting Power
e) Email
f) More information links
g) About section
4. On DRep Details page also, I want to be able to delegate my voting power to that DRep

**Comment by pmbinapps** [comment]
OK with mocked vs current design.


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/120868f5-ccc1-44bb-a4d4-dba4b47fdc83)

OK Delegation on chosen DRep


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/0cfae500-0b32-447e-8289-994922a6926f)
