### ISSUE TITLE
🐛 GA title clipped and strange fonts

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2190]
### Area

Voting Pillar

### Domain

sanchogov.tools

### Which wallet were you using?

Eternl v1.12.16.0

### Context

GAs should have all the necessary information clearly visible and should respect overall UI for consistency and good user experience.

### Steps to reproduce

1. Go to sanchogov.tools
2. Connect the wallet
3. Go to this specific GA - https://sanchogov.tools/connected/governance_actions/5b06976ce88d1cc4a7a5cc2478e418c1bb18cd5538527d963a931593f021f533#0

### Actual behavior

1. Name of the GA is clipped
<img width="685" alt="Screenshot 2024-10-22 at 09 55 46" src="https://github.com/user-attachments/assets/4f7e8764-3ac1-4fd2-b196-8578ccffbc4a">

2. **Reasoning** tab has some fonts that do not respect the font used in the application
<img width="685" alt="Screenshot 2024-10-22 at 09 55 57" src="https://github.com/user-attachments/assets/4b9c7149-aaac-4a86-bbcb-321b4e90f148">

### Expected behavior

1. Name of the GA should be fully visible, at least while hovering
2. Font used in reasoning should be the same ones as used in the appllication

**Comment by Ryun1** [comment]
Metadata: https://github.com/IntersectMBO/governance-actions
