### ISSUE TITLE
Review and Update Dependencies

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2192]
### Area

Other

### Is there new design needed?

No

### What?

To maintain the stability and performance of the project, a review of all dependencies will be conducted. This task ensures that libraries are up-to-date and aligned with the latest standards. Apply any necessary updates as part of our regular maintenance.

### Why?

To maintain the stability and performance of the project

### How?

By using Dependabot GitHub app - https://github.com/IntersectMBO/govtool/security/dependabot

**Comment by bosko-m** [comment]
FYI @spannercode

**Comment by bosko-m** [comment]
@spannercode This was completed elsewhere right?

**Comment by spannercode** [comment]
The dependencies on the test side with high severity were addressed on this PR https://github.com/IntersectMBO/govtool/pull/2197. However, there are dependencies that needs to be updated on the govtool pillars side. I think it can be assigned to Byron team.

**Comment by bosko-m** [comment]
Understood, thanks @spannercode .
Adding it to @MSzalowski but not for this week.

**Comment by MSzalowski** [comment]
Draft pf the PR is ready. I still need to provide some adjustments to storybook configuration making it working with newest vite.
