### ISSUE TITLE
🐛 DRep error conditions page in docs is blank

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2203]
### Area

Delegation Pillar

### Domain

gov.tools

### Context

Page is currently empty and it should have enough content to explain differences and specifics on DRep error messages related to metadata.

### Steps to reproduce

1. Go to page - https://docs.gov.tools/about/what-is-cardano-govtool/govtool-functions/dreps/drep-error-conditions

### Actual behavior

Page is empty

### Expected behavior

Page should have sufficient info on each of the messages (which includes, but not limited to):

- Data not verifiable - have metadata, hash different from the one on chain
- Data formatted incorrectly - found metadata, has is correct, metadata is not CIP-119 compliant
- Data Missing - not able to fetch  metadata

**Comment by m-i-k-e** [comment]
Done: https://docs.gov.tools/about/what-is-cardano-govtool/govtool-functions/dreps/drep-error-conditions

**Comment by m-i-k-e** [comment]
Closing
