### ISSUE TITLE
DRep directory - DReps list filters

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#221]
* Should include chips component (as predefined filters)
<img width="710" alt="image" src="https://github.com/IntersectMBO/govtool/assets/24510246/2860329d-744c-4918-a79a-37b16050d123">

[Link to figma](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7614-249851&mode=design&t=8yNcFlPNERNFVazh-4)

**Comment by pmbinapps** [comment]
OK: Filtering
OK: Search 
OK: Sort - default descending



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/922f3173-ebc3-49c6-b2ef-002df5ca960a)

Jam recording [here](https://jam.dev/c/5489548b-f705-49af-8494-7c68faf8d284)
