### ISSUE TITLE
DRep directory - DRep delegation

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#222]
Move the currently implemented logic of delegation to DRep to the DRep directory page.

<img width="946" alt="Zrzut ekranu 2024-02-19 o 16 54 14" src="https://github.com/IntersectMBO/govtool/assets/24510246/5ff8f3f4-0160-4c5d-afa3-9adc5bb18a30">

**Comment by pmbinapps** [comment]
OK NOW - Delegating enabled and status shown:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/a453d66e-178b-4ec2-8f32-4146c8ba6b2a)
