### ISSUE TITLE
🐛 GA showing empty title in preview.gov.tools

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2233]
### Area

Voting Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

Any wallet

### Context

I was trying to check details of the GAs on preview and I've realized there is one that has epoch boundaries set, but doesnt have a title nor an error.

### Steps to reproduce

1. Go to the list of Governance Actions

### Actual behavior

There is no title on a specific one

### Expected behavior

There should be error displayed in the case of invalid metadata (in this case its likely not CIP-0108 or CIP-119 compliant)

<img width="1116" alt="Screenshot 2024-10-25 at 09 38 13" src="https://github.com/user-attachments/assets/10ca34c5-95ec-4167-bdcb-902e135d0256">

**Comment by spannercode** [comment]
The one with empty title seems to have title and other governance action metadata.
Here is the link from preview.cardanoscan.io
https://preview.cardanoscan.io/govAction/gov_action19pq6tqg8v9n6qe30rd835w9uerhl8pheeezuxwhr8v07s2yauggqqx5sgly?tab=meta

Compared to other valid governance actions like this one:
https://preview.cardanoscan.io/govAction/gov_action1rarl8newf7gsn03wl6gc9jhqsvr72autml4zz58xjq7y3mw2pw8sqsymael?tab=meta
