### ISSUE TITLE
💡 Set up domain for the gov.tools status page

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2237]
### Area

Other

### Is there new design needed?

No

### What?

Status page for gov.tools is being set up, more checks to be added and there should be easily recognizable secure domain associated with it.

https://status.gov.tools

Currently available at - http://51.44.65.72:3001/status/gov-tools

### Why?

Improved monitoring, but also something that can be communicated to the community as the source of relevant status information.

### How?

Initially by Kuma.

**Comment by aaboyle878** [comment]
reverse proxy has been configured and ssl certificate installed, status monitor can be viewed at https://status.gov.tools/status/gov-tools
