### ISSUE TITLE
Markdown not rendered on Proposal List

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#2242]
I submitted a proposal for a GA using Markdown

Markdown was not rendered on the "proposals" home page, but it works on the detail page.

<img width="1308" alt="image" src="https://github.com/user-attachments/assets/ed28664c-550b-482d-ab89-94c1b3825374">

<img width="1310" alt="image" src="https://github.com/user-attachments/assets/078e2480-17fd-4c51-8e13-74ec190a5b23">

**Comment by nebojsajsimic** [comment]
@m-i-k-e  We can't use markdown here, it can easily destroy design of the card, so is correct solution to clean up text and just put plain text without markdown symbols?

**Comment by m-i-k-e** [comment]
The cards need the markdown stripped or sanitised. They should if possible swap markdown tags for our CSS Markup. So they will look like any card that we've generated.

The detail page is supposed to support Markdown as per the CIP, however, it will definitely break accessibility rules, and the page will possibly look odd.

**Comment by bosko-m** [comment]
Same issue is occurring of course on GA cards too.
Described in #2263 
So whatever you agree here, can be applied to GAs too.
