### ISSUE TITLE
🐛 Govtool Crashes on submitting GA. Console errors

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#2253]
### Area

Proposal Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

Latest Lace

### Context

Trying to submit a GA from the Proposal area, it crashed with errors

### Steps to reproduce

1. Create ga proposal
2. fill up fields
3. Download json
4. upload link
5. Crashes and locks browser

### Actual behavior

Crashes

### Expected behavior

Not crashing

**Comment by m-i-k-e** [comment]
Loom video: https://www.loom.com/share/6276dd13964e48bfa5af716cb372b184?sid=616eb0d9-075e-4866-89ee-ab0aaa4a98a7

**Comment by m-i-k-e** [comment]
<img width="564" alt="image" src="https://github.com/user-attachments/assets/e167c49a-b9ea-4751-bc85-ce977ee49ba2">

**Comment by bosko-m** [comment]
@m-i-k-e Please confirm if this is still happening, I couldnt reproduce it.
