### ISSUE TITLE
🐛 Submitted Governace Action Proposal goes missing upon sending to chain

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#2254]
### Area

Other

### Domain

preview.gov.tools

### Which wallet were you using?

Latest Lace

### Context

I successfully submitted a GA to chain via making a proposal first. 
When I returned to find it in the 'proposals' section, it was not there. However, there is a filter called "submitted for vote". Even when this is turned on, the GA cannot be found.

watch video from start, this error is after the 3:00 mark.

### Steps to reproduce

1. Create GA in Proposal view
2. submit to chain successfully
3. return to Proposals page
4. Look for your recent GA

### Actual behavior

Cannot find it at all, even with filter checked to 'submitted for vote'

### Expected behavior

Should be able to find it.

**Comment by bosko-m** [comment]
Duplicate of #2262
