### ISSUE TITLE
Update guides & documentation on all supported Governance Actions

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2256]
Guides & documentation should be updated along with adding support for all Governance Actions, be it by rendering only or allowing submission too.

**Comment by m-i-k-e** [comment]
There is currently no documentation pages on any Governance Actions. I am working on a new and better structure for the guides. Here is a tree view of where the new pages would live (the green branch)

![Image](https://github.com/user-attachments/assets/cd225689-757b-463f-840c-08eec29480a5)

**Comment by m-i-k-e** [comment]
This is currently blocked while I await a 'dev' copy of the guides to work on. I need this because of the major changes to the structure needed. I've asked @l-br1 on Slack to make available a temporary dev guides url so I can proceed without breaking anything.

**Comment by m-i-k-e** [comment]
Here is the existing and proposed navigation for GitBook:

![Image](https://github.com/user-attachments/assets/51cdfaeb-b8ca-4907-93ad-689fbab6cf7c)

**Comment by m-i-k-e** [comment]
This is done in guides release "#56 - Add all Gov Actions"

Cannot publish this yet, as the other changes to the structure - as outlined above - need to be added as well.

**Comment by m-i-k-e** [comment]
This is finished, but I am blocked as I don't have merge access anymore. I need the priviliges restored to publish this. This also blocks #2253

**Comment by m-i-k-e** [comment]
Done and awaiting review and publishing by @l-br1

**Comment by m-i-k-e** [comment]
Merged in to live Guides. There will be broken links. These will be in a new issue.
