### ISSUE TITLE
🐛 Governance Action can be submitted multiple times consecutively without leaving the page

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2264]
### Area

Proposal Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

Lace

### Context

Was exploring end 2 end user experience of a proposal evolving into the governance action.

Reference loom video - https://www.loom.com/share/b57d9f1ad28345e0b16415ca05549afa?sid=61f53e95-b96e-4cd3-bf7a-86d399d9dabd

### Steps to reproduce

1. Go to the specific proposal and submit it as governance action
2. Fill in the steps all the way to the last screen where you could submit it
3. Click submit
4. On the success message modal click x to close it
5. Click submit again

### Actual behavior

1. You are able to submit it

### Expected behavior

1. You shouldnt be able to submit it as upon success message you should be taken out of that screen to the list of governance actions or list of proposals where you can see your proposal you just submitted as governance action.

**Comment by kneerose** [comment]
![Screenshot from 2024-10-29 11-33-01](https://github.com/user-attachments/assets/17d63120-8628-4b43-9b95-ac5142068a7a)

Displaying this popup would be a better option when the user tries to re-submit a proposal, until the transaction is completed

**Comment by m-i-k-e** [comment]
@MSzalowski That will not fix the bug, as the user can dismiss this and re-submit. In UX you cannot depend on users to read instructions and follow them. The interface itself needs to be foolproof.

How do multiple GAs work? Do copies go on chain, or is there a different bug?

**Comment by nebojsact** [comment]
@bosko-m we need to clarify this bug, do we need to block user to submit one action based on one proposal? Or just redirect on some other page (Which one?), or just block pressing button again?

**Comment by bosko-m** [comment]
@nebojsact Disabling button seems like the right and simple thing to be done in that case.
Which means blocked until.you get the output of the submitted transaction, which can be successful or failed.
