### ISSUE TITLE
🐛 Error on becoming a DRep

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#2272]
### Video
https://www.loom.com/share/49b1794d81934d00b841e5a123bf0dce?sid=adb3a561-b275-4f6e-9c31-a7f1418de877

### Area

Delegation Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

Latest Lace

### Context

I was trying to be come a DRep and the following happened:

Got ParseIntError when I tried to submit metadata url

### Steps to reproduce

Try to become drep:
Fill out form with just name
download metadata
put metadata in Github
fetch url from GH
paste in GovTool
Hit return

### Actual behavior

Get ParseIntError
<img width="520" alt="image" src="https://github.com/user-attachments/assets/5d81c317-6d0d-4f50-a043-56115d0989bb">

### Expected behavior

Completes registration as a DRep

**Comment by m-i-k-e** [comment]
Metadata file

{
  "@context": {
    "@language": "en-us",
    "CIP100": "https://github.com/cardano-foundation/CIPs/blob/master/CIP-0100/README.md#",
    "CIP119": "https://github.com/cardano-foundation/CIPs/blob/master/CIP-0119/README.md#",
    "hashAlgorithm": "CIP100:hashAlgorithm",
    "body": {
      "@id": "CIP119:body",
      "@context": {
        "references": {
          "@id": "CIP119:references",
          "@container": "@set",
          "@context": {
            "GovernanceMetadata": "CIP100:GovernanceMetadataReference",
            "Identity": "CIP119:IdentityReference",
            "Link": "CIP119:LinkReference",
            "Other": "CIP100:OtherReference",
            "label": "CIP100:reference-label",
            "uri": "CIP100:reference-uri",
            "referenceHash": {
              "@id": "CIP119:referenceHash",
              "@context": {
                "hashDigest": "CIP119:hashDigest",
                "hashAlgorithm": "CIP100:hashAlgorithm"
              }
            }
          }
        },
        "paymentAddress": "CIP119:paymentAddress",
        "givenName": "CIP119:givenName",
        "image": "CIP119:image",
        "objectives": "CIP119:objectives",
        "motivations": "CIP119:motivations",
        "qualifications": "CIP119:qualifications",
        "doNotList": "CIP119:doNotList"
      }
    },
    "authors": {
      "@id": "CIP100:authors",
      "@container": "@set",
      "@context": {
        "name": "http://xmlns.com/foaf/0.1/name",
        "witness": {
          "@id": "CIP100:witness",
          "@context": {
            "witnessAlgorithm": "CIP100:witnessAlgorithm",
            "publicKey": "CIP100:publicKey",
            "signature": "CIP100:signature"
          }
        }
      }
    }
  },
  "authors": [],
  "hashAlgorithm": {
    "@value": "blake2b-256"
  },
  "body": {
    "doNotList": false,
    "givenName": {
      "@value": "I-AM-A-TEST-DREP-Man"
    },
    "motivations": {
      "@value": ""
    },
    "objectives": {
      "@value": ""
    },
    "paymentAddress": {
      "@value": ""
    },
    "qualifications": {
      "@value": ""
    },
    "references": []
  }
}

**Comment by m-i-k-e** [comment]
<img width="695" alt="image" src="https://github.com/user-attachments/assets/595b1ff5-6b85-466e-99d8-4fa1e3a0e52b">

**Comment by MSzalowski** [comment]
I need to investigate this issue, but most likely this is on the wallet side AND/OR wrong protocol params `drep_deposit` amount

**Comment by MSzalowski** [comment]
I tested yesterday on preview on GovTool-v1.0.25 and I was able to register

**Comment by bosko-m** [comment]
@spannercode Also verified it works.
I've also tested on preview and it works.
