### ISSUE TITLE
🐛 Supporting space on Given name

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#2276]
### Area

Delegation Pillar

### Domain

gov.tools

### Which wallet were you using?

N/A

### Context

As a DRep I should be able to set my Given Name with multiple words separated by space.

**givenName** [(link)](https://cips.cardano.org/cip/CIP-0119#:~:text=their%20payment%20address.-,givenName,that%20authors%20will%20use%20this%20field%20for%20their%20profile%20name/%20username.,-image)
```
- Compulsory
- This is a property inherited from [Person](https://schema.org/Person)
- It is the only compulsory property
- A very short freeform text field. Limited to 80 characters.
- This MUST NOT support markdown text styling.
- It is intended that authors will use this field for their profile name/ username.
```

There was a misunderstanding on the requirement here leading to not allowing the spaces:
https://github.com/IntersectMBO/govtool/issues/1873

### Steps to reproduce

While registering as DRep or editing DRep metadata, try to input given name with space.

### Actual behavior

Space and multiple words separated by space is not allowed

### Expected behavior

Space and multiple words should be supported.

**Comment by m-i-k-e** [comment]
There are lots of spaces in Unicode:
https://www.compart.com/en/unicode/category/Zs

Question: do we allow just one space, and what about consecutive spaces?

Could a user make a name up of just spaces? It would seem acceptable under the rules.

**Comment by bosko-m** [comment]
For the start we should just allow space character , ascii code 32.

**Comment by kneerose** [comment]
-  @bosko-m  Still reproducing on dev , preview env
### Allure report on preview 
- [3E_1. Should accept valid data in DRep form](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/113/#behaviors/f7eea6c55a554c79a959f2fe9524fccc/524369483ef1f622/)
- [3M_1. Should accept valid data in edit dRep form](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/113/#behaviors/f7eea6c55a554c79a959f2fe9524fccc/87b828f886b81fc6/)

**Comment by kneerose** [comment]
Additionally, users can submit multiple votes on the same proposal poll using the same user authentication
related ticket -> https://github.com/IntersectMBO/govtool/issues/2356

**Comment by bosko-m** [comment]
@kneerose Its not yet deployed on preview.

**Comment by kneerose** [comment]
@bosko-m  still reproducing on dev 
![image](https://github.com/user-attachments/assets/62ea3146-85cc-4827-9e93-168c99668194)

**Comment by MSzalowski** [comment]
![Zrzut ekranu z 2024-11-08 12-27-30](https://github.com/user-attachments/assets/14b84236-e5c2-41e9-8cd2-3a7d4a81af81)

Could you please recheck this? It seems to be working just fine now

**Comment by bosko-m** [comment]
Verified on Preview.
