### ISSUE TITLE
🐛 Add issue to project GH action is failing with authentication token issue

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#2277]
### Area

Other

### Domain

gov.tools

### Context

Issue:
<img width="1069" alt="Screenshot 2024-10-30 at 11 26 12" src="https://github.com/user-attachments/assets/92c0b7fb-5d0e-4ecf-b551-83c3f1c7dfd6">
Maybe the authentication token has expired (?)

Workflow file:
https://github.com/IntersectMBO/govtool/blob/develop/.github/workflows/add-issue-to-project.yml

Example Run:
https://github.com/IntersectMBO/govtool/actions/runs/11591218447/job/32270484606 (this link can expire)

### Steps to reproduce

- Create an issue
- Check the action 'add issue to project'
- You might receive an email about failing action run

### Actual behavior

The action execution fails with authentication error related to token

### Expected behavior

The action should execute without issues.

**Comment by Ryun1** [comment]
done!

**Comment by bosko-m** [comment]
Verified and confirmed it works.
