### ISSUE TITLE
[USERSNAP] The "HELP" link at the bottom of gov.tools leads to a Page not found web page: "The page you are looking for doesn't exist." 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2292]
**Taken at**: https://gov.tools/connected/governance_actions/51f495aa23f4b3b3aa90afde4a0e67823bb7ac4ac65f5ffbb138373b863f2f74#0
**Fields**:
- Add a comment: The &#34;HELP&#34; link at the bottom of gov.tools leads to a Page not found web page: &#34;The page you are looking for doesn&#39;t exist.&#34; 

**Browser**: Chrome 130 (Windows 10)
**Screen size**: 1712x943
**[Open #152 in Usersnap](https://app.usersnap.com/l/feedback/6403b32c-5c42-4264-8c57-bb1b4a122d47?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
Good catch.

**Comment by m-i-k-e** [comment]
We can temporarily link to this: https://docs.gov.tools/using-govtool/support#for-support-you-can-reach-the-team-on-the-intersect-discord-server-at
