### ISSUE TITLE
🐛 GovTool on mainnet showing connected to Preview instead of mainnet

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2295]
### Area

Wrapper

### Domain

gov.tools

### Which wallet were you using?

Eternl

### Context

I'm a dRep, and I've posted by dRep ID wallet address below. 
When I go to  1694.io it recognises me and I can view my dRep profile.
But when I go to gov.tools to try and view governance actions I get a blue spinning wheel for 20 seconds or so, then a green bar appears at the top of the screen saying it trying to load preview network and a button to click to go to mainnet. - but whether i press the button or not nothing changes from the sinny wheel. 
I've just used unfrak it, but it made no difference.
I'm using a 6 month old apple laptop, brave browser. 

### Steps to reproduce

1. Go to gov.tool
2. Pick any menu item on the left

### Actual behavior

I'm trying to use mainnet. But when I go to gov.tools to try and view governance actions I get a blue spinning wheel for 20 seconds or so, then a green bar appears at the top of the screen saying it trying to load preview network and a button to click to go to mainnet. - but whether i press the button or not nothing changes from the spinny wheel. 
This happens when selecting any options on the left-hand menu; Dashboard, dRep directory, Governance actions, I can't bring up anything for these, just endless spinny wheel. 

### Expected behavior

It should correctly show its connected to mainnet so no top blue header and there shouldnt be endless spinning upon clicking every item from the left menu.

**Comment by bosko-m** [comment]
@spannercode Could you take a look at this perhaps? 🤔

**Comment by spannercode** [comment]
@bosko-m As far as I understand the issue description, I'm not able to reproduce the issue. For me on Eternl wallet, it seems to work fine. Maybe I'm missing something.
<img width="1440" alt="Screenshot 2024-11-01 at 09 29 05" src="https://github.com/user-attachments/assets/ba6854ef-811b-47cc-8fec-70cbb6667bbe">

**Comment by bosko-m** [comment]
This is probably worth investigating @spannercode . Mentioned also in #2207 .
@MSzalowski @jdyczka I wonder how do we detect which network is user on?

**Comment by spannercode** [comment]
It is an interesting issue report.
> Actual behavior
I'm trying to use mainnet. But when I go to gov.tools to try and view governance actions I get a blue spinning wheel for 20 seconds or so, then a green bar appears at the top of the screen saying it trying to load preview network and a button to click to go to mainnet.

`... a green bar appears at the top of the screen saying it trying to load preview network and a button to click to go to mainnet.` --> This should not be present on the mainnet version (gov.tools) and is not reproducible at the moment on the current deployed version. From the description, it seems network mismatch between the GovTool and the wallet version but it is unclear which one.

**Comment by bosko-m** [comment]
Closing with the comment above.
