### ISSUE TITLE
🐛 DReps shouldn't be voting on Hard Fork Governance action in bootstrapping phase

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2304]
### Area

Voting Pillar

### Domain

preview.gov.tools

### Context

Reference GA - https://preview.gov.tools/governance_actions/049ae5d612b2fa825655809133b023d60c7f8cac683c278cf95de1622e4592f3#0

DReps shouldn't be voting on this. If govtool is getting those numbers from always abstain/no confidence, this should probably be fixed

### Steps to reproduce

1. Go to govtool
2. Go to the specific GA - https://preview.gov.tools/governance_actions/049ae5d612b2fa825655809133b023d60c7f8cac683c278cf95de1622e4592f3#0

### Actual behavior

1. There are voting numbers associated with DReps

### Expected behavior

2. There shouldnt be voting numbers associated with DReps

**Comment by bosko-m** [comment]
@Ryun1 Should these numbers be 0 or completely hidden DRep section?
CC @m-i-k-e

**Comment by Ryun1** [comment]
Probably best to ONLY show the group(s) that can vote on the action type within that protocol version

**Comment by bosko-m** [comment]
Better defined for all groups in #2316
