### ISSUE TITLE
Bump DBSync to 13.6.0.0 (for full governance)

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2310]
Expected to be running for the Chang #2 hard fork.

**Comment by MSzalowski** [comment]
Blocked as https://github.com/IntersectMBO/cardano-db-sync/releases/tag/13.6.0.0 is not released

**Comment by bosko-m** [comment]
@MSzalowski We have 13.6.0.1 officially
https://github.com/IntersectMBO/cardano-db-sync/releases/tag/13.6.0.1
