### ISSUE TITLE
[USERSNAP] Hello, I need some support with the jsonID file that I load into github.  I've completed all the fields, downloaded the created jsonId file, uploaded to github: https://github.com/peterhorsfallblockchain/DRep yet I still get an error (attache...

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2311]
**Taken at**: https://gov.tools/edit_drep
**Fields**:
- Add a comment: Hello, I need some support with the jsonID file that I load into github.  I&#39;ve completed all the fields, downloaded the created jsonId file, uploaded to github: https://github.com/peterhorsfallblockchain/DRep yet I still get an error (attached).  Please let me know how I can proceed - I&#39;ve tried it 6 times now.

Feel free to contact me via: peter.h.blockchain@gmail.com

Thank you!
Peter

**Browser**: Chrome 130 (Windows 10)
**Screen size**: 1428x1430
**[Open #155 in Usersnap](https://app.usersnap.com/l/feedback/220e77f1-af5e-4849-ad5c-3b856c754272?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
User contacted over the email.

**Comment by bosko-m** [comment]
It is the wrong link to metadata that was being used.

In essence, it needs to be changed from this https://github.com/peterhorsfallblockchain/DRep/blob/main/Peter_Horsfall.jsonld
to this https://raw.githubusercontent.com/peterhorsfallblockchain/DRep/refs/heads/main/Peter_Horsfall.jsonld

The link you were trying is the link to the file but with GH interface etc
The link below is the raw version and serves only the plain file
