### ISSUE TITLE
Hide vote totals for the groups that cant vote on a particular Governance Action type

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2316]
* Hide DRep totals for actions DReps cant vote on
* Hide SPO totals for actions they cant vote on
* Hide CC totals for actions CC cant vote on

### According to CIP-1694 for **bootstrapping phase**:

* Hard-Fork Initiation - hide vote totals for DReps
* Protocol Parameter Changes (non-security group) - hide vote totals for DReps and SPOs
* Protocol Parameter Changes (security group) - hide vote totals for SPOs
* Info - nothing to be hidden

### According to CIP-1694 for **full governance**:

* Motion of No-Confidence - hide vote totals for CC
* New Constitutional Committee and/or Threshold/Terms - hide vote totals for CC
* Update to the Constitution or Proposal Policy - hide vote totals for SPOs
* Hard-Fork Initiation - nothing to be hidden
* Protocol Parameter Changes (non-security group) - hide vote totals and SPOs
* Protocol Parameter Changes (security group) - nothing to be hidden
* Treasury Withdrawals - hide vote totals for SPOs
* Info - nothing to be hidden

**Comment by Ryun1** [comment]
@bosko-m I have edited slightly, to include changes to security group parameters
