### ISSUE TITLE
[USERSNAP] Hello, when I try to 'find a DRep' using the searchbar using this ID drep14pjm8ytt682wkp4jcegdj2yerkcy9a20xevvp7udlcd0ggjxdud nothing shows but it looks like the correct ID since it's working here: https://gov.tools/drep_directory/drep14pjm8y...

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2331]
**Taken at**: https://sanchogov.tools/connected/drep_directory
**Fields**:
- Add a comment: Hello, when I try to &#39;find a DRep&#39; using the searchbar using this ID drep14pjm8ytt682wkp4jcegdj2yerkcy9a20xevvp7udlcd0ggjxdud nothing shows but it looks like the correct ID since it&#39;s working here: https://gov.tools/drep_directory/drep14pjm8ytt682wkp4jcegdj2yerkcy9a20xevvp7udlcd0ggjxdud

**Browser**: Chrome 130 (macOS Catalina)
**Screen size**: 1901x954
**[Open #161 in Usersnap](https://app.usersnap.com/l/feedback/83a88dbd-5d81-4a9b-9d58-60d2df77d8ce?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
Not reproducible, tried several times, and it shows the results.

<img width="1131" alt="Screenshot 2024-11-06 at 09 58 29" src="https://github.com/user-attachments/assets/7647c0cd-9673-465e-add1-14a55df038d3">
