### ISSUE TITLE
Make govtool guides more unified

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#2353]
Here is a sitemap

General topics are pink, GovTool instructions are yellow, CC portal green.

The task for @m-i-k-e  is to get all the yellow ones together and make sense of the pink and green.

![Guides](https://github.com/user-attachments/assets/47c489e1-4ac0-424d-a525-6b83f1bc817e)

**Comment by bosko-m** [comment]
CC @Ryun1

**Comment by m-i-k-e** [comment]
Here is my proposed unification plan

![proposed nav for gitbook](https://github.com/user-attachments/assets/d58e78c2-3cf0-4834-bb99-642b167b733a)

**Comment by m-i-k-e** [comment]
And with the addition of new articles on Governance Actions: 
<img width="892" alt="image" src="https://github.com/user-attachments/assets/dbbb13fc-c1b9-4622-8fa5-2827066d161f">

**Comment by MSzalowski** [comment]
List of docs links used in GovTool:
```
Inside repository:
https://docs.gov.tools/
https://docs.gov.tools/how-to-use-the-govtool/getting-started/get-a-compatible-wallet

Inside the application:
https://docs.gov.tools
https://docs.gov.tools/faqs
https://docs.gov.tools/support
https://docs.gov.tools/using-govtool/govtool-functions/dreps/drep-error-conditions
https://docs.gov.tools/using-govtool/govtool-functions/delegating/abstain-from-every-vote
https://docs.gov.tools/using-govtool/govtool-functions/delegating/signal-no-confidence-on-every-vote
https://docs.gov.tools/using-govtool/govtool-functions/dreps/register-as-a-drep
https://docs.gov.tools/using-govtool/govtool-functions/governance-actions/governance-actions/propose-a-governance-action
https://docs.gov.tools/about/bootstrapping-phase
https://docs.gov.tools/using-govtool/govtool-functions/storing-information-offline
https://docs.gov.tools/how-to-use-the-govtool/using-govtool/delegating
https://docs.gov.tools/using-govtool/govtool-functions/direct-voting
https://docs.gov.tools/using-govtool/govtool-functions/dreps/retire-as-a-drep
https://docs.gov.tools/using-govtool/govtool-functions/governance-actions/view-governance-actions
https://docs.gov.tools/using-govtool/govtool-functions/governance-actions/propose-a-governance-action
https://docs.gov.tools/how-to-use-the-govtool/getting-started/get-a-compatible-wallet
https://docs.gov.tools/using-govtool/govtool-functions/dreps
```

**Comment by m-i-k-e** [comment]
Blocked because I can't publish the previous changes. I have lost the ability to merge the changes in. @l-br1 can you please restore them to me?

**Comment by m-i-k-e** [comment]
This is done. Awaiting review and publishing by @l-br1

**Comment by m-i-k-e** [comment]
Merged into live guides. There will be broken links, I will create a new issue to map the links.

**Comment by m-i-k-e** [comment]
@MSzalowski Can you please check the links in the list above and change them accordingly?

**Comment by m-i-k-e** [comment]
Closing, as @MSzalowski said he's updated the links.
