### ISSUE TITLE
🐛 Endless Poll Creation Loop Displays Multiple Results

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#2357]
### Area

Proposal Pillar

### Domain

dev-sanchogov.tools

### Context

While attempting to view the poll results for a proposal, I noticed that after closing a poll, the "Add Poll" button becomes visible. This allows a new poll to be added, which generates another set of results. Repeating this process results in an endless loop where multiple poll results are displayed.

### Steps to reproduce

1. Connect your wallet.
2. Create a new proposal or navigate to an existing one.
3. Add a poll.
4. Close the poll.
5. Notice that the "Add Poll" button reappears and allows a new poll to be added.
6. Repeat the process and observe that each cycle generates a new poll result.

### Actual behavior

The system allows multiple poll results to be generated as polls can be repeatedly added and closed.
https://dev-sanchonet.govtool.byron.network/proposal_discussion/2029
![image](https://github.com/user-attachments/assets/834005da-5443-43cf-bfe1-021f65f6d7ea)

### Expected behavior

The "Add Poll" action should be restricted by the API once the poll has been closed, preventing further additions. Alternatively, only the latest poll result should be visible, and multiple results should not be displayed.

**Comment by kneerose** [comment]
@nebojsajsimic any update on this ? I am still able to reproduce this issue 
https://dev-sanchonet.govtool.byron.network/proposal_discussion/2176
CC: @bosko-m

**Comment by bosko-m** [comment]
Can you test now @kneerose ?

**Comment by kneerose** [comment]
@bosko-m , I am still able to reproduce this 
https://dev-sanchonet.govtool.byron.network/proposal_discussion/2433

![image](https://github.com/user-attachments/assets/1656ee54-cd6e-4c2b-bf92-c38b0a7c7524)

**Comment by nebojsact** [comment]
I'll check this again, fix on alternative way so we will display only last created poll.

**Comment by kneerose** [comment]
@nebojsact I am still able to reproduce this issue:

- The "Add Poll" button is visible even after the poll has been closed.  
- Additionally, the API allows the creation of a new poll, regardless of whether the previous poll is closed or not.  

**Dev Environment**
https://dev-sanchonet.govtool.byron.network/proposal_discussion/2521
![image](https://github.com/user-attachments/assets/dc2611f6-7779-4e86-bf13-65acf8971c3c)



**Preview Environment**
https://preview.gov.tools/proposal_discussion/683
![image](https://github.com/user-attachments/assets/3c42e7aa-f1aa-4e35-8fd2-42e67c170528)

CC: @bosko-m

**Comment by nebojsact** [comment]
@kneexpected, so you can open and close polls, this is expected behavior,
change was that only the last closed pool is visible instead of a bunch of
opened and closed.
So yes, you can open new when you close the old one.

**Comment by kneerose** [comment]
@nebojsact , does this mean a user can vote on multiple polls for the same proposal? For instance, if a user has already voted on one poll and the poll owner closes it, then opens a new poll, can the same user vote again on the new poll for the same proposal?

Additionally, based on your comments, if the poll owner closes a poll with more responses and subsequently opens and closes a new poll, does this mean the results of the old poll will be discarded?

- The API currently allows the creation of a new poll even if the previous poll remains open. As a result, using the API to create multiple polls causes the "Close" button to appear multiple times for each poll created. The API should enforce a restriction to block the creation of a new poll for the same proposal if an existing poll is already open and not closed.

https://www.loom.com/share/19f879a3df854c879c1d9ff7277fb5de?sid=de71a437-ade5-4050-987e-8d3605cd223c

**Comment by nebojsact** [comment]
@kneerose as the logic for the poll was in place for opening and closing, I suppose that was made by request and description of functionality, yes if the user closes the poll, edit proposal and open new poll it is normal that old will be discarded. So @bosko-m can you help us with this logic? 
@kneerose also please open a new bug for new request and close this if everything from the initial request was resolved. Thanks!

**Comment by bosko-m** [comment]
@kneerose @nebojsact 
Here is the expected behavior:
* There can only be one poll active at the time (if thats not the case, please create the new ticket as it goes outside of the scope of this bug).
* The last closed poll should be shown
* Once the proposal has been submitted on chain, no new polls can be created and commenting should be off too.
Let me know if you have any questions.

**Comment by kneerose** [comment]
@nebojsact  ,
I have created a separate ticket for the backend poll creation issue [#2507](https://github.com/IntersectMBO/govtool/issues/2507).

**Current behaviour of proposal poll on frontend**
- When a proposal owner adds, edits, and closes a poll, and then adds a new poll, the UI renders as

![image](https://github.com/user-attachments/assets/b0ceaf46-d837-4463-9c94-4deab26afc3c)

- If the owner closes the new poll, the poll results are updated to reflect the new poll's results

![image](https://github.com/user-attachments/assets/ec95c189-a360-42f1-9299-98dca376e534)

**NOTE:** If this is the expected and intended behavior for the UI, this ticket can be considered closable.

CC: @bosko-m

**Comment by kneerose** [comment]
@bosko-m , after closing the new poll, the results are updated, and only the updated poll results are displayed.
 
![image](https://github.com/user-attachments/assets/ec95c189-a360-42f1-9299-98dca376e534)

**Comment by bosko-m** [comment]
All good, understood.
Thank you @kneerose
