### ISSUE TITLE
[USERSNAP] I am a DRep I cannot see the YES, NO and ABSTAIN vote buttons for the new governance action

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2358]
**Taken at**: https://gov.tools/connected/governance_actions/b2a591ac219ce6dcca5847e0248015209c7cb0436aa6bd6863d0c1f152a60bc5#0
**Fields**:
- Add a comment: I am a DRep I cannot see the YES, NO and ABSTAIN vote buttons for the new governance action

**Browser**: Chrome 130 (Windows 10)
**Screen size**: 2406x1200
**[Open #163 in Usersnap](https://app.usersnap.com/l/feedback/a013a1da-a80a-458c-a413-5814c7fd105d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by spannercode** [comment]
Likely because there are no votes on this governance action. Here is a link from cardanoscan.io.

https://cardanoscan.io/govAction/gov_action1k2jertppnnndejjcglszfqq4yzw8evzrd2nt66rr6rqlz54xp0zsq05ecsn?tab=votes
