### ISSUE TITLE
Set up notifications when db connection gets reset for Matomo analytics

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2371]
Set up the email notifications working or maybe a web hook so we know exactly if and when it gets reset so we don't end up having a gap in the future.
It would also be useful if we can understand why it was reset in the first place.

**Comment by aaboyle878** [comment]
Created a custom web hook running every 5 minutes that check the database availability and uptime, doing the same checks the Matomo API sending an alert if any state changes are detected
