### ISSUE TITLE
🐛 Unwanted truncation for governance action links

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#2391]
### Area

Voting Pillar

### Domain

sanchogov.tools

### Context

Reference links on proposals are truncated and broken in some cases
[see ab633bb08e0e9fe33eef865b7acc079c8b2f360fb851a97230d135bd4fd8fc07#0](https://sanchogov.tools/connected/governance_actions/ab633bb08e0e9fe33eef865b7acc079c8b2f360fb851a97230d135bd4fd8fc07#0)

(see full metadata [doc](https://github.com/IntersectMBO/governance-actions/blob/main/mainnet/2024-11-19-infohf/metadata.jsonld))

### Steps to reproduce

[see ab633bb08e0e9fe33eef865b7acc079c8b2f360fb851a97230d135bd4fd8fc07#0](https://sanchogov.tools/connected/governance_actions/ab633bb08e0e9fe33eef865b7acc079c8b2f360fb851a97230d135bd4fd8fc07#0)

### Actual behavior

The second reference link is completely truncated off of the screen
The reference URIs are also not rendered on the line below

![image](https://github.com/user-attachments/assets/fde5fb91-5507-448b-835e-64a521187743)

### Expected behavior

All reference links are shown correctly
Allowing the both the label and URI to be seen

**Comment by MSzalowski** [comment]
@m-i-k-e Wouldn't it be better to display label and url below label instead of both in one row?

**Comment by Crypto2099** [comment]
I don't see any functional benefit to treating the _Supporting Links_ section as a 2-wide grid anyway. Most URIs will always be long enough to cause undesirable truncation.

I would strongly advocate simply making this a vertically linear "list" of items when there is one or more reference links to display.

**Comment by bosko-m** [comment]
I agree with @MSzalowski and @Crypto2099 
You can proceed @MSzalowski

**Comment by m-i-k-e** [comment]
We have a new design for this, but it's not been implemented. It does use a 1 x 2 table, but the links are not truncated. In any case, we don't want truncation.
