### ISSUE TITLE
🐛 GovTool lets me put in link description without link urls

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#2403]
### Area

Delegation Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

Latest Lace

### Context

I was trying to register as a DREp and I put in a label for both my links and identity and no URL. The form didn't show an error. 

### Steps to reproduce

1. Try to register as a DRep
2. put in text in the description fields of both 'identity' and 'links'
3. Don't put in any url in the url fields
4. press "Continue" button

### Actual behavior

the form submits with no errors and you go to the data download screen

### Expected behavior

the form throws an error as the urls are missing.

**Comment by m-i-k-e** [comment]
Video:

https://www.loom.com/share/a73414d363084a17bdb79c912929c888?sid=f99a41f3-be17-49f8-9dc0-427ae179d1cf

**Comment by bosko-m** [comment]
@MSzalowski Do we already have the way to show this error message or it needs to be designed?
