### ISSUE TITLE
Bump DBSync to 13.6.0.4

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2411]
Bump DBSync to the latest released version **13.6.0.4**

https://github.com/IntersectMBO/cardano-db-sync/releases/tag/13.6.0.4

### There is no need to do a resync.

Assess and consider **[Postgres setup](https://github.com/IntersectMBO/cardano-db-sync/releases/tag/13.6.0.2)** suggestions

**Comment by bosko-m** [comment]
@MSzalowski Latest one is 13.6.0.4

**Comment by MSzalowski** [comment]
Bump on sancho is already in review

**Comment by MSzalowski** [comment]
Done on sancho

**Comment by aaboyle878** [comment]
updated on preview and mainnet
