### ISSUE TITLE
[USERSNAP] There seems to be no DRep "yes" votes on the plutus v3 cost model governance action

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2425]
**Taken at**: https://gov.tools/governance_actions/b2a591ac219ce6dcca5847e0248015209c7cb0436aa6bd6863d0c1f152a60bc5#0
**Fields**:
- Add a comment: There seems to be no DRep &#34;yes&#34; votes on the plutus v3 cost model governance action

![SCREENSHOT](https://resources.usersnap.com/company/127c73ca-bcdd-4a4a-89e5-a1faa2d0e4ca/datapoint_screenshot/7d3da3a0-1c05-43fe-b554-97da08feb900-annotated_38518659-c37e-4d59-bda9-b9fb0d162818.png?etag=274499e3760a83da81f04f177eb2be0f)
*[Download original image](https://resources.usersnap.com/company/127c73ca-bcdd-4a4a-89e5-a1faa2d0e4ca/datapoint_screenshot/7d3da3a0-1c05-43fe-b554-97da08feb900-annotated_38518659-c37e-4d59-bda9-b9fb0d162818.png?etag=274499e3760a83da81f04f177eb2be0f)*

**Browser**: Chrome 130 (Windows 10)
**Screen size**: 1368x912
**Browser size**: 1824x1047
**[Open #166 in Usersnap](https://app.usersnap.com/l/feedback/4ae7d800-cd37-4f79-8876-2be07fad6838?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
This looks like a bug to me.
