### ISSUE TITLE
[USERSNAP] Error occurred when I voted for a Governance Action using Typhon wallet.

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2436]
**Taken at**: https://gov.tools/governance_actions/b2a591ac219ce6dcca5847e0248015209c7cb0436aa6bd6863d0c1f152a60bc5#0
**Fields**:
- Add a comment: Error occurred when I voted for a Governance Action using Typhon wallet.

**Browser**: Chrome 131 (Windows 10)
**Screen size**: 1920x1080
**[Open #167 in Usersnap](https://app.usersnap.com/l/feedback/b01ba6e3-db78-4fe4-9b51-15dae6ac171c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
Closing as not enough information to replicate. 

- Not specified what the error was
- No version of Typhon wallet
- No operating system or platform info
