### ISSUE TITLE
🐛 Missing Stake Address and Amount  in Treasury Proposal Review Step and Draft

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#2438]
### Area

Proposal Pillar

### Domain

dev-sanchogov.tools

### Context

When creating a treasury proposal, after entering a valid receiving stake address and amount, and proceeding to the "Review Your Submission" step, the entered information disappears and is not displayed on the review card. Additionally, after saving the proposal as a draft, both the "Review Your Submission" section and the "Amount" field are missing. Users cannot add a new stake address or amount until toggling the governance action to "Info" and back to "Treasury."

### Steps to reproduce

1. Connect to the wallet.
2. Navigate to the treasury proposal creation form.
3. Enter a valid receiving stake address and amount.
4. Click the "Continue" button to proceed to the "Review Your Submission" step.
5. Observe that the entered stake address and amount are missing in the review section.
6. Save the proposal as a draft.
7. Check the draft proposal: observe that the "Review Your Submission" section and "Amount" field are missing.

### Actual behavior

- Entered stake address and amount (before clicking continue):
![image](https://github.com/user-attachments/assets/ed272bc9-7ac5-48c8-b583-f28ea0f2d2e2)

- Missing information in the "Review Your Submission" card:
![image](https://github.com/user-attachments/assets/9e7875f5-cc62-4f6b-a74b-46757b7e0ddf)

- Entered stake address and amount missing in draft proposal

![image](https://github.com/user-attachments/assets/766f6595-3481-4951-a5ee-271eeb3a6c6b)

### Expected behavior

- The entered receiving stake address and amount should persist and be visible in the "Review Your Submission" step and in the draft proposal.
![image](https://github.com/user-attachments/assets/69aa8064-5592-48f3-93cf-eb91055ee723)

**Comment by kneerose** [comment]
@nebojsact , I am able to see the stake address and amount in the 'Review Your Submission' section, but the entered stake address and amount are missing in the draft proposal. When the treasury proposal is saved as a draft and viewed later, the data is not retained.

![image](https://github.com/user-attachments/assets/a7b8861f-0c04-4158-b3ed-53ba54f07467)

Additionally, all the fields for the receiving address and amount currently have the same test IDs, leading to ambiguity.
![image](https://github.com/user-attachments/assets/aaaa0f5d-5942-4c1e-be59-91d56a49923b)

**Previous Test IDs** (used for a single stake address and amount):
- `receiving-address-content`
- `amount-content`

**Suggested Test IDs**:
- `receiving-address-${index}-content`
- `amount-${index}-content`

CC: @bosko-m

**Comment by kneerose** [comment]
@nebojsact ,
I noticed that the test IDs you added are still incorrect. Instead of adding the index as a number, you’ve added it as a string.

![image](https://github.com/user-attachments/assets/4e7fce0e-b404-4dfc-89e5-8726b5728d4a)

Additionally, the Receiving Address and Amount fields are still not visible on the draft.

![image](https://github.com/user-attachments/assets/6b726c61-76a4-4a2f-84a8-de6789cde79d)

Note: Please verify whether the issue is fixed properly before publishing a new version.

CC: @bosko-m

**Comment by kneerose** [comment]
@nebojsact  any updates on this ? I am still able to reproduce this on dev and preview env.

**Dev environment**
![image](https://github.com/user-attachments/assets/073823a7-ebd9-489b-8212-056c6a7f8cff)
![image](https://github.com/user-attachments/assets/11cc2d78-99aa-49a8-9ea7-fa5784f4b95c)

**Preview environment**
![image](https://github.com/user-attachments/assets/f36cc5d4-7529-4d3f-96bc-9be5e56d4c54)
![image](https://github.com/user-attachments/assets/eb2fda64-d465-4c2a-92f3-2545a7ee129d)

CC: @bosko-m

**Comment by nebojsact** [comment]
this is fixed in 0.5.5

[image: image.png]

**Comment by kneerose** [comment]
@MSzalowski , I am unable to test this as the new PDF version has not been updated in the dev environment. Could you please update it to the latest version?
CC: @bosko-m

**Comment by kneerose** [comment]
@nebojsact , I have updated the `pdfUI` version to `0.5.5` locally and tested it to ensure the correct application of the mentioned `TestIDs`. The following testId are correct now.

- **Receiving content:** `receiving-address-${index}-content`  
  Example: `receiving-address-0-content`

- **Amount content:** `amount-${index}-content`  
  Example: `amount-0-content`

![TestIDs example](https://github.com/user-attachments/assets/fb3e61b9-d406-4d61-8701-450adfb9d643)  

However, I noticed an issue: the **Receiving Address** and **Amount Title** are visible on the "Review Your Submission" card for **Info Proposal**.  

![Review Your Submission](https://github.com/user-attachments/assets/fa006e44-3421-4b2f-b244-eb84757bae3b)

To improve the UI/UX, it would be better to hide the **Receiving Address** and **Amount** Title for **Info Proposal**.

**Comment by nebojsact** [comment]
@kneerose please open new ticket for this bug thanks!
