### ISSUE TITLE
[USERSNAP] The search function doesn't work well. I mean what is it searching? If you enter a Drep name (or part of it), it does nothing. Ctrl F works but you need to load everything tediously using the "Show More" button. Also, the filter option seems ...

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2442]
**Taken at**: https://gov.tools/drep_directory
**Fields**:
- Add a comment: The search function doesn&#39;t work well. I mean what is it searching? If you enter a Drep name (or part of it), it does nothing. Ctrl F works but you need to load everything tediously using the &#34;Show More&#34; button.
Also, the filter option seems to be dysfunctional. When I sked to show all Active Dreps, it kept listing non-active ones.

**Browser**: Chrome 131 (Windows 10)
**Screen size**: 1920x1200
**[Open #168 in Usersnap](https://app.usersnap.com/l/feedback/05710f4b-e135-4571-9adf-06e732603d93?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
This is a known issue and we are working on it.
