### ISSUE TITLE
[USERSNAP] I dont understand why a Drep can have active status with 0 voting power, or when they dont have a name attached to their position (ex.:  data missing, or formatted incorrectly), or why 2 different Dreps can have the same name (ex.:  HD5000). ...

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2444]
**Taken at**: https://gov.tools/drep_directory
**Fields**:
- Add a comment: I dont understand why a Drep can have active status with 0 voting power, or when they dont have a name attached to their position (ex.:  data missing, or formatted incorrectly), or why 2 different Dreps can have the same name (ex.:  HD5000).
Some sort of clarity or a fix of what seems to be real problems would be good.
thank you

**Browser**: Chrome 131 (Android 10)
**Screen size**: 412x892
**[Open #169 in Usersnap](https://app.usersnap.com/l/feedback/b8b1eb9e-fb59-4d32-8192-ffc76fcda56c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
**The first question**  
(I don't understand why a Drep can have active status with 0 voting power, or when they dont have a name attached to their position (ex.: data missing, or formatted incorrectly) 
This behaviour is inherent in the way that DReps are defined. The only thing that's written to the chain is:

-  the DRep ID
- the hash of the metadata
- the URL of the metadata

Hence, there is no check on the name of the DRep, nor their balance.

I agree it's a confusing situation, but it would take some re-engineering of the Node to fix this.

**Comment by m-i-k-e** [comment]
Closing as we cannot fix this easily, or at all without re-writing the foundational CIP, and serious re-engineering of the Node itself.
