### ISSUE TITLE
GA Display: Users can click to visit the source of the metadata

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#245]
As any user

I want to be able to access the governance action metadata at its source

So that I can verify it

1. Given that I am on the page of a specific governance action

When I press the “view information at source”* button
Then a modal window opens up warning me that I am navigating off the site, and lists the url of the metadata

Given that I have pressed the “view information at source”* button on the page of a specific governance action

When I press the ok button on the modal warning window

Then the metadata anchor url will open in a separate tab

---

Include a button that links to the metadata. This is something that we have already built so it should not take up significant dev time.

**Comment by Ryun1** [comment]
very old, lets close
