### ISSUE TITLE
🐛 Preview is not operational at the moment

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#2469]
### Area

Other

### Domain

preview.gov.tools

### Which wallet were you using?

N/A

### Context

Preview is not operational at the moment.
DRep directory and Governance actions are not loading on the frontend. The Backend APIs seem to return the response.

Here is the console logs with stack trace:
```
TypeError: Cannot read properties of undefined (reading 'map')
    at X6e (index-87793cd3.js:244:12057)
    at async Promise.all (index 0)
    at async Object._ [as queryFn] (index-87793cd3.js:262:24427)
```

`![image](https://github.com/user-attachments/assets/fd2f5808-9499-4129-a216-6e552d3346b6)

### Steps to reproduce

1. Visit https://preview.gov.tools/drep_directory
2. OR, https://preview.gov.tools/governance_actions
3. Check console logs

### Actual behavior

The pages remains stuck on loading without any API results on the page.

### Expected behavior

The page should load the directory directory or the governance actions page correctly with all the results.

**Comment by mpavlovicbb** [comment]
Issue is fixed.
