### ISSUE TITLE
🐛 Submission of proposal as governance action asks for double signing of transaction and sometimes fails

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#2478]
### Area

Proposal Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

Eternl 1.12.19

### Context

When submitting a proposal (tested with both inform and treasury withdrawal proposals) as a governance action, the wallet displays the expected transaction signing pop-up. However, immediately after signing, a second transaction signing pop-up appears. Reviewing the wallet's transaction list reveals a pending transaction that is invalidated by this second transaction, which sometimes succeeds and other times fails.

The issue is that users are being prompted to sign two transactions when submitting a proposal as a governance action.

Note: This was tested on Eternl version 1.12.19, and it is possible that this is a wallet-related issue.

Here is the console log when it fails.
<img width="1166" alt="Screenshot 2024-12-05 at 18 23 52" src="https://github.com/user-attachments/assets/1104b055-5873-4e90-a9a8-0899cb67677c">

<img width="926" alt="Screenshot 2024-12-05 at 18 24 16" src="https://github.com/user-attachments/assets/33bc6b66-f080-450b-aba8-cd98f62a7d62">

### Steps to reproduce

1. Create any proposal
2. Try submitting the proposal as governance action. Fill the metadata URL and submit.
3. A wallet pop up to sign the transaction appears as expected. Sign the transaction and submit.
4. Immediately after signing the transaction, another wallet pops up, asking to sign again.
5. Before signing the second transaction, check on the wallet that there is already a pending transaction (100K Ada). You might need to refresh your wallet.
6. Sign the second transaction wallet pop up and submit
7. The submission of governance action **may** or **maynot** succeed. This is either indicated by seeing the transaction in progress on the submission form or nothing happens.
8. Check the wallet transactions, you'll see an invalid transaction in case of failure or success transaction.

### Actual behavior

GovTool asks twice to sign the governance action submission transaction and may or may not succeed at the end.

### Expected behavior

Governance action submission should ask for signing a single transaction and always succeed.

**Comment by spannercode** [comment]
I tested the issue on the Lace browser wallet and the Vespr mobile wallet:

- Lace Browser Wallet: I can confirm that the transaction signing prompt appears twice. However, the transaction successfully went through.
- Vespr Mobile Wallet: No double signing occurred, and the transaction completed smoothly.

**Comment by kneerose** [comment]
@MSzalowski @nebojsact ,
### Issues
**1. Failure on submitting the treasury proposal with stake address register**
 - Using Eternl wallet v1.12.19
 
      **Dev Environment**
      ![image](https://github.com/user-attachments/assets/5e535f4c-c2a7-4fda-a1a8-dfc747661276)
      
      **Preview Environment**
      
      ![image](https://github.com/user-attachments/assets/e3d99dd4-049d-4718-802b-120a1d130b38)
      
- Using lace wallet v1.17.6
      **Preview Environment**
      - The system logs indicate that the stake is not registered, despite the wallet stake being already registered.
      ![image](https://github.com/user-attachments/assets/0c503be1-6076-49f4-9839-999284eca995)
     -  [Transaction details](https://preview.cardanoscan.io/transaction/2fbfaab5abafc433ecd43af21cb5ceadc0787734372b7b2f7b32db3fe4e9e932?tab=utxo) of stake registered

**2. Missing Dialog for Unregistered Stake Wallets**
- When a stake is not registered, the system only logs a message instead of showing a dialog to inform the user. This impacts user interaction and awareness.
   - Lace Wallet: Stake not registered message appears in logs.

    ![image](https://github.com/user-attachments/assets/1b0b46a9-acc5-41c6-8d07-feedca1d3759)

   - Vespr Wallet

   ![image](https://github.com/user-attachments/assets/50ca95ad-b062-43f5-a66d-16e651bcf0da)

**Comment by MSzalowski** [comment]
@kneerose For the sake of clarity - based on your comment, I created separate issue as it seems to be a different error than duplicated signing of transactions

**Comment by MSzalowski** [comment]
Also @bosko-m it is not related to metadata validation. After looking into errors in console that @kneerose shared in images, it is related to submitting the transaction, so only on the wallet side.
