### ISSUE TITLE
[USERSNAP] Unable to vote on Governance Actions - options to select vote are not appearing even though wallet connected is a drep account

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2485]
**Taken at**: https://gov.tools/connected/governance_actions/fff0df644d328a5367212f45bab59060bde3c4091dc96c723062896fd6197314#0
**Fields**:
- Add a comment: Unable to vote on Governance Actions - options to select vote are not appearing even though wallet connected is a drep account

**Browser**: Chrome 131 (Windows 10)
**Screen size**: 2560x1440
**[Open #173 in Usersnap](https://app.usersnap.com/l/feedback/b24d6960-474f-4643-a87e-817473d17dfa?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
### According to CIP-1694 for **bootstrapping phase**:

* Hard-Fork Initiation - hide vote totals for DReps
* Protocol Parameter Changes (non-security group) - hide vote totals for DReps and SPOs
* Protocol Parameter Changes (security group) - hide vote totals for SPOs
* Info - nothing to be hidden

### According to CIP-1694 for **full governance**:

* Motion of No-Confidence - hide vote totals for CC
* New Constitutional Committee and/or Threshold/Terms - hide vote totals for CC
* Update to the Constitution or Proposal Policy - hide vote totals for SPOs
* Hard-Fork Initiation - nothing to be hidden
* Protocol Parameter Changes (non-security group) - hide vote totals and SPOs
* Protocol Parameter Changes (security group) - nothing to be hidden
* Treasury Withdrawals - hide vote totals for SPOs
* Info - nothing to be hidden

Explained in #2316
