### ISSUE TITLE
[USERSNAP] please ignore bug ticket in regards to voting options not being available - user error. Keep up the great work and apologies for the confusion!

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2486]
**Taken at**: https://gov.tools/dashboard
**Fields**:
- Add a comment: please ignore bug ticket in regards to voting options not being available - user error. Keep up the great work and apologies for the confusion!

**Browser**: Chrome 131 (Windows 10)
**Screen size**: 2560x1440
**[Open #174 in Usersnap](https://app.usersnap.com/l/feedback/81ca0847-e05a-456f-9533-4e0fe6c82838?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bosko-m** [comment]
Thank you 😁
