### ISSUE TITLE
Failure on submitting the proposals with unregistered or registered (but wrongly handled by govtool) stake keys

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#2490]
@MSzalowski @nebojsact ,
### Issues
**1. Failure on submitting the treasury proposal with stake address register**
 - Using Eternl wallet v1.12.19
 
      **Dev Environment**
      ![image](https://github.com/user-attachments/assets/5e535f4c-c2a7-4fda-a1a8-dfc747661276)
      
      **Preview Environment**
      
      ![image](https://github.com/user-attachments/assets/e3d99dd4-049d-4718-802b-120a1d130b38)
      
- Using lace wallet v1.17.6
      **Preview Environment**
      - The system logs indicate that the stake is not registered, despite the wallet stake being already registered.
      ![image](https://github.com/user-attachments/assets/0c503be1-6076-49f4-9839-999284eca995)
     -  [Transaction details](https://preview.cardanoscan.io/transaction/2fbfaab5abafc433ecd43af21cb5ceadc0787734372b7b2f7b32db3fe4e9e932?tab=utxo) of stake registered

**2. Missing Dialog for Unregistered Stake Wallets**
- When a stake is not registered, the system only logs a message instead of showing a dialog to inform the user. This impacts user interaction and awareness.
   - Lace Wallet: Stake not registered message appears in logs.

    ![image](https://github.com/user-attachments/assets/1b0b46a9-acc5-41c6-8d07-feedca1d3759)

   - Vespr Wallet

   ![image](https://github.com/user-attachments/assets/50ca95ad-b062-43f5-a66d-16e651bcf0da)

CC: @bosko-m

_Originally posted by @kneerose in https://github.com/IntersectMBO/govtool/issues/2478#issuecomment-2526933009_

**Comment by kneerose** [comment]
@MSzalowski  I am still able to reproduce this issue eventhough my stake is already registered

![image](https://github.com/user-attachments/assets/0c1786c2-c32b-406e-acde-37b420d5dfd9)

**Comment by kneerose** [comment]
@MSzalowski , the stake address registration certificate has been added for submitting the proposal as a governance action for unregistered stake wallet. However, the same error persists after submitting the proposal, even for wallets with/without a registered stake address.

**Eternl Wallet**
![image](https://github.com/user-attachments/assets/1eb874c8-a057-420f-91a2-3f307b448f54)

![image](https://github.com/user-attachments/assets/cf8f6c9a-1864-4fdc-87c5-967986e162c4)

**Lace Wallet**

![image](https://github.com/user-attachments/assets/6f649440-e213-4d3d-988a-0d6e5d55ecdb)


CC: @bosko-m

**Comment by MSzalowski** [comment]
@ Ryun1 Do you have any idea why that is not working?
I could submit the transaction with a stake key registration certificate on the preview. But using the same flow and wallet, but sancho is not working

**Comment by MSzalowski** [comment]
My CBOR of submitted transaction on preview:
```
84a700d9010281825820a55f536603680309d2c12dce777c084be00975af6619cf91cd2093bb6e0b0ea2000181825839007cf9cacd1f0454ea3bc8833bdc7ac4d6515d65f3462d4c3c1a8bcb2dd2565d8440f4865bf4d4cb4dc1d683c47327d6f7d7f70377e6d9486c1a02d7ae98021a0004bd6804d901028183078200581cd2565d8440f4865bf4d4cb4dc1d683c47327d6f7d7f70377e6d9486c1a001e84800b582058b297c776183cd8bbdaf60ab498a15081d9bd48d99168398e92f34ea1485e280dd9010281825820a55f536603680309d2c12dce777c084be00975af6619cf91cd2093bb6e0b0ea20014d9010281841b000000174876e800581de0d2565d8440f4865bf4d4cb4dc1d683c47327d6f7d7f70377e6d9486c8302a1581de0d2565d8440f4865bf4d4cb4dc1d683c47327d6f7d7f70377e6d9486c1a0001e0f3581cfa24fb305126805cf2164c161d852a0e7330cf988f1fe558cf7d4a6482785e68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4d537a616c6f77736b692f676f765f616374696f6e5f746573742f726566732f68656164732f6d61696e2f646174612532302832292e6a736f6e6c64582091c288e82efe3b8eb07bf2be28bcb94c4ae9ce2879837aa8d9a5756fa63b0a80a300d90102828258206ff178db73d1f16ef302436e68c59f7ab65356c3676267bd2ed835b408f4018858400776cdeda99a390ec90a8ab3b726f0a174d3fe7636ef71909688e3dc394f13348a2140e5522f24dbe9b06e90b28d63e7d63306fc23002523f36f812125064f0d825820f63b1cbb2b44334663082cb78ae7fc062c848eec7e0bd9fa257ff86209d1f7e95840938e6628bfd3107829a6f174bf1381e916d1c519cc4cede7f8f9fed7c5fa277b9fdc2b60c405069d03c74b92d929a70dcb45a475dd83a5d014174fbf16d1630007d90102815908545908510101003232323232323232323232323232323232323232323232323232323232323232323232323232323232259323255333573466e1d20000011180098111bab357426ae88d55cf00104554ccd5cd19b87480100044600422c6aae74004dd51aba1357446ae88d55cf1baa3255333573466e1d200a35573a002226ae84d5d11aab9e00111637546ae84d5d11aba235573c6ea800642b26006003149a2c8a4c301f801c0052000c00e0070018016006901e4070c00e003000c00d20d00fc000c0003003800a4005801c00e003002c00d20c09a0c80e1801c006001801a4101b5881380018000600700148013003801c006005801a410100078001801c006001801a4101001f8001800060070014801b0038018096007001800600690404002600060001801c0052008c00e006025801c006001801a41209d8001800060070014802b003801c006005801a410112f501c3003800c00300348202b7881300030000c00e00290066007003800c00b003482032ad7b806038403060070014803b00380180960003003800a4021801c00e003002c00d20f40380e1801c006001801a41403f800100a0c00e0029009600f0030078040c00e002900a600f003800c00b003301a483403e01a600700180060066034904801e00060001801c0052016c01e00600f801c006001801980c2402900e30000c00e002901060070030128060c00e00290116007003800c00b003483c0ba03860070018006006906432e00040283003800a40498003003800a404d802c00e00f003800c00b003301a480cb0003003800c003003301a4802b00030001801c01e0070018016006603490605c0160006007001800600660349048276000600030000c00e0029014600b003801c00c04b003800c00300348203a2489b00030001801c00e006025801c006001801a4101b11dc2df80018000c0003003800a4055802c00e007003012c00e003000c00d2080b8b872c000c0006007003801809600700180060069040607e4155016000600030000c00e00290166007003012c00e003000c00d2080c001c000c0003003800a405d801c00e003002c00d20c80180e1801c006001801a412007800100a0c00e00290186007003013c0006007001480cb005801801e006003801800e00600500403003800a4069802c00c00f003001c00c007003803c00e003002c00c05300333023480692028c0004014c00c00b003003c00c00f003003c00e00f003800c00b00301480590052008003003800a406d801c00e003002c00d2000c00d2006c00060070018006006900a600060001801c0052038c00e007001801600690006006901260003003800c003003483281300020141801c005203ac00e006027801c006001801a403d800180006007001480f3003801804e00700180060069040404af3c4e302600060001801c005203ec00e006013801c006001801a4101416f0fd20b80018000600700148103003801c006005801a403501c3003800c0030034812b00030000c00e0029021600f003800c00a01ac00e003000c00ccc08d20d00f4800b00030000c0000000000803c00c016008401e006009801c006001801807e0060298000c000401e006007801c0060018018074020c000400e00f003800c00b003010c000802180020070018006006019801805e0003000400600580180760060138000800c00b00330134805200c400e00300080330004006005801a4001801a410112f58000801c00600901260008019806a40118002007001800600690404a75ee01e00060008018046000801801e000300c4832004c025201430094800a0030028052003002c00d2002c000300648010c0092002300748028c0312000300b48018c0292012300948008c0212066801a40018000c0192008300a2233335573e00250002801994004d55ce800cd55cf0008d5d08014c00cd5d10011263009222532900389800a4d2219002912c80344c01526910c80148964cc04cdd68010034564cc03801400626601800e0071801226601800e01518010096400a3000910c008600444002600244004a664600200244246466004460044460040064600444600200646a660080080066a00600224446600644b20051800484ccc02600244666ae68cdc3801000c00200500a91199ab9a33710004003000801488ccd5cd19b89002001800400a44666ae68cdc4801000c00a00122333573466e20008006005000912a999ab9a3371200400222002220052255333573466e2400800444008440040026eb400a42660080026eb000a4264666015001229002914801c8954ccd5cd19b8700400211333573466e1c00c006001002118011229002914801c88cc044cdc100200099b82002003245200522900391199ab9a3371066e08010004cdc1001001c002004403245200522900391199ab9a3371266e08010004cdc1001001c00a00048a400a45200722333573466e20cdc100200099b820020038014000912c99807001000c40062004912c99807001000c400a2002001199919ab9a357466ae880048cc028dd69aba1003375a6ae84008d5d1000934000dd60010a40064666ae68d5d1800c0020052225933006003357420031330050023574400318010600a444aa666ae68cdc3a400000222c22aa666ae68cdc4000a4000226600666e05200000233702900000088994004cdc2001800ccdc20010008cc010008004c01088954ccd5cd19b87480000044400844cc00c004cdc300100091119803112c800c60012219002911919806912c800c4c02401a442b26600a004019130040018c008002590028c804c8888888800d1900991111111002a244b267201722222222008001000c600518000001112a999ab9a3370e004002230001155333573466e240080044600823002229002914801c88ccd5cd19b893370400800266e0800800e00100208c8c0040048c0088cc00800800505a182050082a0821a000624241a05557d98f5f6
```

**Comment by bosko-m** [comment]
@MSzalowski If its not working on Sancho and working on Preview, its good to go for the release on Preview.

**Comment by Ryun1** [comment]
@MSzalowski @bosko-m 

There was a check added to 10.X nodes, that prevents governance actions being submitted which attempt to return governance action deposits to stake addresses that dont exist.
That might be the issue, some wallets may not have upgraded to 10.x for their `submitTx()` endpoints.

**Comment by Ryun1** [comment]
When I am back from vacation next week, I will try to replicate myself

**Comment by bosko-m** [comment]
If thats the case its an external dependency 🤔

**Comment by kneerose** [comment]
@MSzalowski, I am now able to submit the treasury proposal on Sancho. The only issue or point of confusion for the user is detailed in [Issue #2536](https://github.com/IntersectMBO/govtool/issues/2536). 

Submitted proposal -> https://dev-sanchonet.govtool.byron.network/proposal_discussion/3016

Since the preview is currently down, I will check on it once `preview.gov.tools` is up.

CC: @bosko-m

**Comment by MSzalowski** [comment]
Let me know if it works as preview is back again

**Comment by kneerose** [comment]
@MSzalowski , I am now able to submit treasury proposal on `preview.gov.tools` as well

Submitted proposal -> https://preview.gov.tools/proposal_discussion/864
Governance action -> https://preview.gov.tools/governance_actions/bb6f400ec14dda55bc9c5b1700a5a22fd32ee46e5e82bd5679811f3e4c40f1b1#0
CC: @bosko-m
