### ISSUE TITLE
DRep can update metadata

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#261]
# Todo

Provide update functionality to DRep metadata

# User story

As someone who is registered to vote on behalf of myself and others (a DRep)

I want to update my DRep profile information.

So that I can keep it up to date, and make improvements.

---

Given that I am registered as a DRep:

When I have gone through the process of , updating I my metadata,

Then GovTool will create a transaction with a Registration Update Certificate to register this change on chain

---

DReps can update their metadata

**Comment by Ryun1** [comment]
very old, lets close
