### ISSUE TITLE
[DEV, TEST] Sentry error appears in consle.log

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#291]
![Image](https://github.com/IntersectMBO/govtool/assets/82152577/bb3f472d-b409-4c9c-aec9-dae1ca444f4f)

As a DevOps Engineer,

I want to adjust the Content Security Policy settings in the Traefik configuration within our Docker compose file,

so that Sentry can properly report errors without being blocked by the CSP.

### Summary:

1. Identify the incorrect CSP setting for the Sentry service in the dev, test, and staging environments.
2. Update the Traefik configuration in the Docker compose file to include the correct scripts locations for Sentry.
3. Ensure that the CSP settings allow Sentry to function correctly without compromising security.

This change enables Sentry to accurately report errors and issues, improving our ability to monitor and debug the application in development, testing, and staging phases.

### Acceptance Criteria

- [ ] The CSP setting in the Traefik configuration allows Sentry scripts to execute in the `dev`, `test`, and `staging` environments without being blocked.
- [ ] The updated CSP settings do not allow any scripts from unauthorized sources to execute, maintaining the security of the web application.
- [ ] Error reporting and logging through Sentry are verified to work correctly in all specified environments after the CSP adjustments.

**Comment by bosko-m** [comment]
@MSzalowski Is this still an issue?

**Comment by MSzalowski** [comment]
Not blocked anymore
