### ISSUE TITLE
GA Sorter needs better UX [BT- PO decision]

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#31]
To reproduce:

Go to Governance Actions on GovTool

click the ‘sort’ icon 

Issues:

The interface needs to tell the user what the sort order is. When a user clicks off this box (sorting the page) they cannot see what the order is without opening the box again.

Also, there is no indication of what the default sort order is at any stage in use, including when the user first sees the page. 

The choice of sorting options is not really clear or comprehensive

Is “Soon to expire” the inverse of “Newest first” - it would be if all Actions have exactly the same lifespan - but I’m not sure if this is true. If it is true, then this can be accomplished with one sort click. If not, then Newest and Oldest must be doable, and also “Expiry”

The sort options need to be ‘invertible’. In other words, “Highest amount of Yes votes” should be inverted to show “Lowest amount of Yes votes”

This UX pattern could be accomplished more efficiently and usably by using a data table as in the attachment. The table will need to be paginated (not shown). This is a very common UX pattern and works for data of this type. It also has the advantage of being very economical with space. The user can click on any row and go the the ‘detail’ page and see all the in-depth stuff on any GA.

Several users had problems with usability of the horizontal scrolling on this page. Another usability problem is having the “View All” hidden off-screen. This not only hides the option, but makes the user work hard for it.

![Image](https://github.com/IntersectMBO/govtool/assets/44342099/b72c8710-0839-4680-9974-ca985b8c5dd4)

![Image](https://github.com/IntersectMBO/govtool/assets/44342099/d62532e4-f036-4666-a07f-a69bf1f68c7e)

**Comment by bosko-m** [comment]
Changing this to the last known status before the migration to this project.

**Comment by m-i-k-e** [comment]
@bosko-m This is done in the design phase, but in the backlog for implementation. Is there a method that you know how we could keep track of things like this - which are feature improvements or UX improvements?

**Comment by bosko-m** [comment]
@m-i-k-e You closed the issue above. However, if this is still something to be done from engineering perspective, it needs to be prioritized. Can you please set up the priority? I've changed the status from `Done` to in `To Do`.

**Comment by m-i-k-e** [comment]
Yes, we did a redesign of the search experience a while back. It is still alive somewhere in Figma. It was put in the backlog. This is the issue: https://github.com/IntersectMBO/govtool/issues/759.

However, there are more improvements in the search functionality than are listed in the above issue.

**Comment by m-i-k-e** [comment]
@bosko-m I've written to @GypsyBinar and asked him to find the branch/part of Figma that these designs are in. Will update this issue with the Figma link.
