### ISSUE TITLE
Do not list DReps that set their donotlist to true

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#310]
### Why

As a DRep who has set their DRep Metadata to donotlist==true

I want to be invisible to the DRep Explorer

So that no one can find me in the DRep Explorer

### What

Do not display DReps with `donotlist` to `true`

### How

Filter DReps that set `donotlist` to true

**Comment by Ryun1** [comment]
@MSzalowski status on this? 🤔

**Comment by Ryun1** [comment]
this has been implemented now
