### ISSUE TITLE
Display DReps in DRep Explorer

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#319]
# Why
As someone who wants to delegate to a DRep

I want to see all the available DReps (i.e. not Single Voters)

So that I have a wide array of choice available to me.

# What
1. Given that I have just registered as a DRep
When I visit the DRep Explorer
My the on-chain aspects of my profile are listed

2. Given that I am on the DRep Explorer page
When I search for a DRep by DRep ID, or filter by active/inactive, or sort by voting power, or a combination of those things,
Then I can find all DReps that match these filters

3. Given that I am on the DRep Explorer page
When I look for predefined DReps
Then I can find them

4. Given that I am on the DRep Explorer page with my funded wallet connected
When I click the "delegate" button on a DRep
Then I can delegate to that DRep

**Can find DReps using the DRep Explorer**

**Comment by pmbinapps** [comment]
OK: NOTE: reg time differs depending on transactions processing 
  Given that I have just registered as a DRep
  When I visit the DRep Explorer
  My the on-chain aspects of my profile are listed


OK: - all designed features are working
Given that I am on the DRep Explorer page
When I search for a DRep by DRep ID, or filter by active/inactive, or sort by voting power, or a combination of those things,
Then I can find all DReps that match these filters

OK:
Given that I am on the DRep Explorer page
When I look for predefined DReps
Then I can find them

OK:
Given that I am on the DRep Explorer page with my funded wallet connected
When I click the "delegate" button on a DRep
Then I can delegate to that DRep

Some minor issues with Show more, and loaders tracked in separate issues.



Click over:
https://jam.dev/c/708603a5-f6ca-4c2a-b9a2-ca502552cc57
