### ISSUE TITLE
Vote Transaction link doesn't go to transaction

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#346]
## Context & versions
Sanchogov.tools current version

Loom Video: https://www.loom.com/share/a611944b1de84b84b730d34184d4c742?sid=94d4dfaa-f2cf-40c5-bb1b-9e52849bb5ad

## Steps to reproduce

  1. Go to GA explorer
  2. Click on "Voted"
  3. Choose any GA
  4. Click on "Vote Transaction"

  If not reproducible, describe the steps you took as you remember it.

## Actual behavior
Goes to the url 'https://adanordic.com/latest_transactions'

## Expected behavior
Should take you to the exact transaction

**Comment by pmbinapps** [comment]
Curretly cexplorer is shown with link to transaction. Actual transaction is usually not shown:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/cd294553-70ec-403a-9aa7-5b0b1135d0c6)

**Comment by m-i-k-e** [comment]
GovTool seems to generate the correct link now, but the Explorer is broken, so I can't finish the test.
