### ISSUE TITLE
[TEST] Registering as a DRep without metadata is making me a Sole Voter

### ISSUE THREAD

**Issue by SandraRodziewicz** [IntersectMBO/govtool#349]
## Steps to reproduce

  1. As a non DRep click Register as a DRep
  2. Skip on the Add information page
  3. Wait for the transaction to finish

## Actual behaviour
I become Sole Voter

## Expected behaviour
I should become DRep

**Comment by bosko-m** [comment]
Moving this one to the last known status before migration to this project.
