### ISSUE TITLE
Fix version fetching for backend and frontend on CI/CD pipeline

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#427]
As a DevOps Engineer,

I want to ensure the deployment scripts can fetch accurate versions for frontend and backend components,

so that we have a reliable versioning system of the application components.

### Acceptance Criteria:

- [x] The CI/CD pipeline's deployment scripts can access the entire git history.
- [x] The scripts can identify the last git commit that modified the frontend and backend subdirectories.
- [x] Docker image tags reflect the accurate version of the frontend and backend components based on the last modification.
- [x] The versioning system accurately represents the current state of the frontend and backend components.

**Comment by bosko-m** [comment]
@MSzalowski Not clear why this one is blocked

**Comment by MSzalowski** [comment]
Not blocked anymore, moving to staging
