### ISSUE TITLE
Implement new Git Workflow proposal in project

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#434]
As a project manager,

I want to implement a new Git workflow proposal in the project

to simplify the release candidate pull request process and minimize potential errors.

### Summary:
The current Git workflow in the project involves tedious steps to prepare a
release candidate pull request, which includes cherry-picking commits from the
feature. This process is time-consuming and prone to errors. A new workflow
proposal has been defined to simplify the process by reducing main branches to
two. Implementing this new workflow will require propagating requirements to the
team, organizing a workshop for knowledge-sharing, facilitating discussions and
Q&A sessions, and potentially creating a FAQ document.

### Acceptance criteria:
- [x] Share the new workflow proposal document (https://github.com/IntersectMBO/govtool/discussions/289) with the team.
- [ ] Organize a workshop to introduce the new workflow and provide know-how to team members.
- [ ] Facilitate discussions and Q&A sessions to address any questions or concerns related to the new workflow.
- [ ] Create a FAQ document based on the feedback and questions raised during the discussions.
- [ ] Ensure that team members understand and are comfortable with the new Git workflow before fully implementing it in the project.

**Comment by Ryun1** [comment]
I dont think we are pursuing this now
