### ISSUE TITLE
Resolve Grafana dashboard configuration datasource issue

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#442]
As a Grafana user,

I want to connect the panels on my dashboard with the correct datasource specified in the configuration

to avoid warnings about non-existing datasources.

### Summary:

The Grafana dashboard is displaying warnings about non-existing datasources because the UIDs of the datasources in the configuration do not match the expected values. To resolve this issue, the configuration needs to be corrected to connect the panels with the appropriate datasource.

### Acceptance criteria:

- [x] Identify the datasource with the correct UID in the configuration.
- [x] Update the datasource UID in the configuration to align with the expected value.
- [x] Test the dashboard to ensure that the warning about non-existing datasources is resolved.

**Comment by bosko-m** [comment]
@MSzalowski Is this really blocked or it should go to `In Staging` status?

**Comment by MSzalowski** [comment]
Not blocked anymore, moving to staging
