### ISSUE TITLE
Dashboard RWD fixes

### ISSUE THREAD

**Issue by SandraRodziewicz** [IntersectMBO/govtool#462]
Connected to: #351 
## Steps to reproduce

As a user with wallet connected

## Expected behaviour

1. 640

- card width: 608px

2. 1728

- three cards layout, card width: 444px

**Comment by bosko-m** [comment]
Changing this to the last known status before the migration to this project. (In QA)
@MSzalowski @SandraRodziewicz Did this one end up on staging env?

**Comment by MSzalowski** [comment]
Yes. Moved to staging column
