### ISSUE TITLE
Home page RWD fixes

### ISSUE THREAD

**Issue by SandraRodziewicz** [IntersectMBO/govtool#463]
Connected to #350 

## Steps to reproduce

As a user without a wallet connected

## Expected behavior

1. 375

- SanchoNet Governance Tool - font weight should be 700
- image and all the text on the cards besides the buttons should be aligned to the left
- Titles of the cards should be font-size: 28px, font-weight: 500, line-height: 36px (Delegate your voting power, Become a DRep etc.)
- Text under card title should be: font-size: 16px, line-height: 24px

2. 430

- SanchoNet Governance Tool - font-size: 57px; font-weight: 700; line-height: 64px;
- image and all the text on the cards besides the buttons should be aligned to the left
- Titles of the cards should be font-size: 28px, font-weight: 500, line-height: 36px (Delegate your voting power, Become a DRep etc.)
- Text under card title should be: font-size: 16px, line-height: 24px

3. 640

- SanchoNet Governance Tool - font-size: 57px; font-weight: 700; line-height: 64px;
- Titles of the cards should be font-size: 28px, font-weight: 500, line-height: 36px (Delegate your voting power, Become a DRep etc.)
- Text under card title should be: font-size: 16px, line-height: 24px

4. 768

- SanchoNet Governance Tool - font-size: 57px; font-weight: 700; line-height: 64px;

5. 1920

- Should still be single column of cards with width: 866px

6. 2560

- cards columns should be closer together (37px)

**Comment by bosko-m** [comment]
Changing this to the last known status before the migration to this project. (In QA)
@MSzalowski @SandraRodziewicz Did this one end up on staging env?

**Comment by MSzalowski** [comment]
Yes
