### ISSUE TITLE
Enhancing Docker Compose stack for proper frontend image tagging

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#466]
As a deployment manager,

I want to tag the frontend images with environment-specific flags

to ensure that the correct frontend build is used for the corresponding deployment environment.

### Summary:

The current deployment system utilizes Docker Compose stack to tag frontend
images based on the last commit SHA, which proves to be insufficient as frontend
images may vary based on build arguments and target deployment environments.
Therefore, to prevent using frontend images built for one environment in another
environment with different settings, an environment flag needs to be added to
the image tag for proper differentiation of frontend builds.

### Acceptance Criteria:
- [x] Identify the necessary build arguments specific to each target deployment environment.
- [x] Modify the Docker Compose stack configuration to include an environment flag in the frontend image tags.
- [x] Implement a mechanism to ensure that the correct environment flag is applied when building and tagging frontend images.
- [x] Test the deployment process using the enhanced tagging mechanism to verify that the correct frontend build is deployed to the corresponding environment.

![Image](https://github.com/IntersectMBO/govtool/assets/161099/85b86e21-119a-4d2d-9890-f7d6fe7a1e94)

**Comment by bosko-m** [comment]
@MSzalowski Any specific reason for this one to be blocked?

**Comment by MSzalowski** [comment]
Not blocked anymore
