### ISSUE TITLE
[sancho] Transactions - possible to try to vote on proposal in different tab causing error with msg 'Please try again later' [BT: decide on priority, assign]

### ISSUE THREAD

**Issue by l-br1** [IntersectMBO/govtool#5]
[from Pawel]

To reproduce. As DRep open 2 tabs with distinct GA to Vote. Initiate voting on one, and click vote 2nd tab. Compare with mov:

https://github.com/IntersectMBO/govtool/assets/134690345/af97a694-f42a-4cf5-beb4-5a7602cbc517

----

_Comment from Michal S. (22nd/11/23):_
BT

**Affected:** FE
**Reason:** It seems unlikely that a user would attempt to perform the same action on two separate tabs.
Other than that, normal use is not affected.
Proposed solution: Best: Implement a mechanism that does not allow the application to be used in multiple locations at the same time. Alternative: Provide a more contextual error message.
**Next action:** PO input needed.

**Comment by Ryun1** [comment]
very old, lets close
