### ISSUE TITLE
Proposal and network metrics endpoints break when network has no predefined DReps

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#501]
Bug spotted by @johnalotoski - great spot, thank you for raising 💪

## Context & versions
When GovTool is run on a network without any stake delegated to the predefined DReps (`no confidence` and `abstain`), then the proposal list and networks metrics backend endpoints break.

With GovTool [sancho-v1.0.1](https://github.com/IntersectMBO/govtool/releases/tag/sancho-v1.0.1).

### Fix
John has fixed the SQL queries causing this [here](https://github.com/IntersectMBO/govtool/commit/9920dcb53db35ee1196ebdd77af3090bbdc7c754).

## Steps to reproduce
Run GovTool on a network without any stake delegated to predefined DReps.

## Actual behavior
Proposal list and network metrics return error 500.

## Expected behavior
Proposal list and network metrics work.

**Comment by bosko-m** [comment]
Changing this to the last known status before the migration to this project. (In QA)
@MSzalowski Did this one end up on staging env?

**Comment by MSzalowski** [comment]
Seems like the fix is not working. I'll reopen this issue
