### ISSUE TITLE
[BT] GA Submit - where there is not enough founds - no info modal view is shown (INFO: DESING READY, TODO)

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#509]
During submition on Info GA - occurred that balance on account was below 1000 A, but no error dialog informing about this was show.

To reproduce, with balance lower than 1000 Ada try to submit a GA..

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b651192b-9d08-40b0-99f5-fa331b1095e7)

**Comment by pmbinapps** [comment]
OK NOW - handled with following message:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/3dbcd055-6dac-4a7b-9eca-ff9026b199c3)

**Comment by m-i-k-e** [comment]
The error in the screenshot above is not correct. This is the screen for this error: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=7079%3A81357&t=VewrRakbrZccwD9V-1

**Comment by pmbinapps** [comment]
Still NOT OK - previous modal was wrongly assumed as expected, below is expected one:

Figma [design](https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?node-id=10086-87741&t=QRB43UAH3HZx2vzX-4)


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/231bd665-19a0-4656-a9e4-09fa4f4d0c52)

Currently is shown:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/576cd344-34b8-4f45-b7ca-82ddd75f64b8)

**Comment by pmbinapps** [comment]
OK NOW on dev:

Recheck on test-sancho.



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/6318894d-b7fa-4818-b987-e6caa0ff6f39)
