### ISSUE TITLE
GA filter check boxes are backwards

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#51]
## Steps to reproduce
To reproduce:

1. go to Governance Actions on GovTool
2. click the ‘filter’ icon

## Actual behavior
Issue: When the checkboxes are unchecked, all the topics are visible. This is backwards. 

## Expected behavior
When the checkboxes are checked, the topics should be visible, and unchecked, not visible. See picture.

Further to make it easier to use, there should be a ‘master’ checkbox that turns them all on or off.

![image](https://github.com/IntersectMBO/govtool/assets/965789/600edcb1-f48c-4186-8ef9-33105cf8252b)

**Comment by Ryun1** [comment]
very old, lets close
