### ISSUE TITLE
Create shared Footer component

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#545]
### Why

Due to the latest design changes, we need to update the GovTool footer component.

### What

Update GovTool footer component.

Footer should include:
* Current copyright - © 2024 Intersect MBO
* Links to:
  * Privacy policy
  * Terms of service
* Help link - at this stage - link to https://docs.sanchogov.tools/support/get-help-in-discord
* Feedback - at this stage - link to https://docs.sanchogov.tools/bugs-or-features-suggestions/how-to-submit-a-bug

### How

* Should follow [this design](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=8016-30451&mode=design&t=D6BmaWlUjFm8EKFt-4)

* Should be responsive

* Current usersnap feedback should be hidden

# Important
We cannot deploy this task to beta without having the usersnap correctly opening on the feedback button click ❗ 
For the development, we can temporarily disable this in favor of handling the custom feedback button, but the beta deployment cannot be done without configured usersnap.

**Comment by pmbinapps** [comment]
One more issue to verify:

'OK Feedback' - recheck when this issue is in QA if new Feedback (transparent bgd) button is not overlapped by old (whole blue)
