### ISSUE TITLE
Handle action of opening usersnap feedback widget on the custom buttons

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#546]
### Why

To gather feedback from the users we need to propagate the feedback buttons around the app. To make it able we need to integrate the Usersnap via custom actions (custom feedback buttons).

### What

Create usersnap feedback service that would extract the API of opening the usersnap feedback widget.

That issue is not about the feedback button from the UI side.
That issue is only about handling the logic.

### How

Follow steps in [this guide](https://help.usersnap.com/docs/open-the-widget-with-your-own-feedback-button).

**Comment by pmbinapps** [comment]
OK - Feedback submitted and available in Usersnap service



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/120c5169-63ae-415d-86c1-9c0d21e6e922)
