### ISSUE TITLE
Deployment issue due to bug in Dockerfile

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#569]
As a developer,

I want to fix the bug in the Dockerfile for the backend module of the project

so that the deployment can be successful.

### Summary
The deployment of the project is failing due to a bug in the Dockerfile of the backend module, as highlighted in the failing deployment logs at https://github.com/IntersectMBO/govtool/actions/runs/8439354402/job/23113753291. The root cause of the issue is identified in the pull request (PR) at https://github.com/IntersectMBO/govtool/pull/564.

### Acceptance criteria:
- [x] Investigate the bug in the Dockerfile causing the build failure.
- [x] Identify the changes needed in the Dockerfile to resolve the issue.
- [x] Make necessary modifications to the Dockerfile.
- [x] Test the new Dockerfile to ensure successful building of the backend module.
- [ ] Push the changes to the repository and trigger a deployment to verify the fix.

**Comment by MSzalowski** [comment]
It is on staging, not blocked. Moved to appropriate column
