### ISSUE TITLE
Fix backend test GitHub Action

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#620]
## Context & versions
workflow: test_backend.yml
language: python

## Steps to reproduce
Dispatch workflow locally using act,
Or push any commit as the workflow is configured to dispatch on push

## Actual behavior
Every test fails due to the wrong configuration.

## Expected behavior
Workflow might fail if something indeed is wrong, but they should run and execute tests.

**Comment by pmbinapps** [comment]
@pmbinapps comment with status after test-sancho PR&deploy

**Comment by pmbinapps** [comment]
Skip as dev->test process is under discussion yet.
