### ISSUE TITLE
Add vote txHash into get DRep votes

### ISSUE THREAD

**Issue by Sworzen1** [IntersectMBO/govtool#626]
TODO:
- Add txHash into votes for this endpoint - https://dev-sanchonet.govtool.byron.network/api/swagger-ui/#/default/get_drep_getVotes__drepId_

FIGMA REFERENCE:
https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=8332-63338&mode=design&t=0yr8R5XPI3FeEFaP-4

**Comment by pmbinapps** [comment]
OK added:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/84c57e78-6bcf-4bff-9a99-994342876d36)
