### ISSUE TITLE
Add txHash into get DRep info

### ISSUE THREAD

**Issue by Sworzen1** [IntersectMBO/govtool#627]
TODO:
**Add last txHash in this [endpoint](https://dev-sanchonet.govtool.byron.network/api/swagger-ui/#/default/get_drep_info__drepId_)**
DRep:
-  drep is registered - drep registration txHash - link1
- drep is retired - drep reitrement txHash - link2
Sole Voter:
- sole voter is registered - sole voter registration txHash - link3
- sole voter is retired - sole voter retirement txHash - link4

FIGMA REFERENCES:
- [link1](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7838-145859&mode=design&t=0yr8R5XPI3FeEFaP-4)
- [link2](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7838-149791&mode=design&t=0yr8R5XPI3FeEFaP-4)
- [link3](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7672-80521&mode=design&t=0yr8R5XPI3FeEFaP-4)
- [link4](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7837-96895&mode=design&t=0yr8R5XPI3FeEFaP-4)

**Comment by pmbinapps** [comment]
Works as intended:
drep is registered - drep registration txHash - link1
drep is retired - drep reitrement txHash - link2
Sole Voter:
sole voter is registered - sole voter registration txHash - link3
sole voter is retired - sole voter retirement txHash - link4
