### ISSUE TITLE
Implement a loading modal for the validation of the metadata

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#646]
### Why

To inform the user that their metadata is being checked.

### What

Provide the modal with the loader that informs the user that their metadata is being checked.

[Figma design](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=9640-87470&mode=design&t=BG7lNZM0vUSYSdwI-0)

### How

Extend existing modals

**Comment by pmbinapps** [comment]
OK 



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/cb2614f5-e177-47cc-b618-4171fca1a3be)
