### ISSUE TITLE
[BT] Search doesn't find Governance Action by ID (TBC: works on test now, check invalid GA actions search)

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#650]
## Context & versions
staging.sanchonet

## Steps to reproduce

See Video: https://www.loom.com/share/6ad99e1b324141a6837318cc90ffdffb?sid=393484be-43c1-4e7c-812e-6711f3a2a4d7

  1. Go to GA list page
  2. Copy any GA Id
  3. Paste it into search box

## Actual behavior
Nothing is found on the search

## Expected behavior
Search should find any GA by ID

**Comment by MSzalowski** [comment]
Might be resolved after:
https://github.com/IntersectMBO/cardano-db-sync/issues/1716

**Comment by bosko-m** [comment]
@MSzalowski @pmbinapps This is working on dev environment. Can we assume it will work on staging once its up and running?

**Comment by m-i-k-e** [comment]
@MSzalowski @pmbinapps Titles are missing on dev Governance Actions, but they were showing on staging, as you can see in the video.

**Comment by m-i-k-e** [comment]
Works now, that is, the GA is found by searching for ID. Not tested for other text strings. Closing
