### ISSUE TITLE
Text correction (GA View - card - Remove 's' from - Withdrawals -> Withdrawal)

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#651]
## Context & versions
staging.sanchonet

## Steps to reproduce
Look at GA display

See Loom Video: https://www.loom.com/share/06396b8c5ae74ae5b0fa771be156b86f?sid=5e5b078f-8fee-40df-9a94-babea45d78b4

"Withdrawals" should be singular, i.e. "Withdrawal"

**Comment by pmbinapps** [comment]
OK on dev-sancho


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/cecd9a3a-dab2-44a2-88ce-b7584e749d8c)
