### ISSUE TITLE
[BT] Extra link on Info Storage screen (remove Read full guide extra link)

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#652]
## Context & versions
staging.sanchonet

## Steps to reproduce
Go to Info storage page

See Video: https://www.loom.com/share/c2e631fcb57d49c58fd819f9aadc960c?sid=b8c86619-3c8e-46a8-ade8-dce7b339089b

**Comment by pmbinapps** [comment]
OK NOW:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/fd153d84-fcb2-4071-b5f0-1256d11f1be2)

**Comment by m-i-k-e** [comment]
17 May. This is good:
<img width="869" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/0b9cba97-71ea-4837-9f81-61b3abe1f398">
