### ISSUE TITLE
[BT] Voting power display not correct (TBC: text to shown- related to showing Voting power component)

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#653]
## Context & versions
staging.sanchonet

## Steps to reproduce
See loom video https://www.loom.com/share/e5b37153717c4c25aec7f069935fead5?sid=08859958-8fae-4420-8adb-698bee4352fb

**Comment by MSzalowski** [comment]
Seems like the designs are appropriate to the screen you provided @pmbinapps is anything else wrong with that issue?

**Comment by MSzalowski** [comment]
On current implementation:
Missing `Show transaction` button as the transactions are not working properly currently

**Comment by MSzalowski** [comment]
DB-sync is updated but the transaction still fails due to the wrong drep registration status.
@jankun4 needs to correct the data fetching from db-sync

**Comment by MSzalowski** [comment]
Not blocked anymore

**Comment by MSzalowski** [comment]
TODO: To refine all the voting-power related issues

**Comment by m-i-k-e** [comment]
Voting power is only for any role that is registered as a voter: Dreps and Direct Voters. It's been agreed that VP is calculated at epoch boundaries.

The voting power 'chip' does not show if a user is not in a role that can vote, it displays and says 0 if a user can vote, but has no power in their 'account' because an epoch has not elapsed yet.

**Comment by MSzalowski** [comment]
So that, it seems like the voting power chip issue has been fixed.
@pmbinapps could you please reverify the issue?

**Comment by pmbinapps** [comment]
OK - Voting power chip on shown any more for Retired Direct Voter.

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/daec2d1b-c47b-424b-b2f3-deac1d4ff366)

**Comment by m-i-k-e** [comment]
Closing this as it now works
