### ISSUE TITLE
[BT] DRep registration doesn't finish. (80 chars long title not cut, not submittitng)

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#655]
## Context & versions
staging.sanchonet; Demos 1.7 

## Video
https://www.loom.com/share/efffe5bdceb14f4c920f4f569030b0db?sid=92b94338-7560-41ea-a943-0f0fd5281d78

## Steps to reproduce
  1. Try to become a DRep
  2. Go to end of flow and click "Submit"

## Actual behavior
nothing happens

## Expected behavior
Registration is complete

## Other Issues

1. Url field needs to return over in download button
2. Error messages need to be more friendlier

**Comment by pmbinapps** [comment]
OK NOW:
used json file:
https://raw.githubusercontent.com/mpawel79/testrepo/master/test_test_test_t.jsonld
