### ISSUE TITLE
[BT] Sole voter card needs highlight (SET PRIO)

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#657]
## Context & versions
staging.sanchonet

## Steps to reproduce
Register as Sole Voter
Go to Dashboard

## Video
https://www.loom.com/share/7bc58f5eef4846b4882c6874684a08a5?sid=6b522737-1afb-42ca-a420-d27846451397

**Comment by pmbinapps** [comment]
Transaction needed to register.

**Comment by pmbinapps** [comment]
OK NOW
Cards highlighted


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b27acbcc-2fa9-4072-8a0f-40670194c558)

**Comment by m-i-k-e** [comment]
Blocked, I can't test this due to to SanchNet respin. The problem is that I can't fund a new wallet (Demos) for now. Don't know how long this will persist.

**Comment by m-i-k-e** [comment]
This has been fixed. Closing
