### ISSUE TITLE
StoryBook Testing

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#660]
### Why

This test ensures that storybook components are working well and nothing is broken.

### What

Review existing Story book test review and fix any configuration and deployment issues.

### How

Execution
- On workflow file changed
- On frontend files changed
- Deployment: https://storybook-govtool.cardanoapi.io

**Comment by Ryun1** [comment]
This ready to be closed now @spannercode ?

**Comment by Ryun1** [comment]
The https://storybook.govtool.cardanoapi.io/ link does not work

**Comment by spannercode** [comment]
@Ryun1 as soon as the base repository for the storybook is decided, we can complete this. The link will be live again after the deployment.

**Comment by NabinKawan** [comment]
[PR](https://github.com/IntersectMBO/govtool/pull/1240) for updated storybook tests.

**Comment by NabinKawan** [comment]
[PR](https://github.com/IntersectMBO/govtool/pull/1241) for update workflow

**Comment by mesudip** [comment]
Storybook is deployed to link 
https://storybook-govtool.cardanoapi.io/

**Comment by spannercode** [comment]
The related PRs are merged and the deployment complete with a publicly accessible URL (in previous comment by Sudip) so closing this ticket as completed.
CC: @Ryun1
