### ISSUE TITLE
Lighthouse Tests

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#662]
### Why

The goal is to automate the process of testing our frontend codebase using Lighthouse to catch regressions and maintain high standards of quality across the user experience.

### What

Import the existing Lighthouse tests and update them to fit the testing strategy.

### How

- Install Lighthouse CI and integrate it with our existing CI/CD pipeline.
- Configure Lighthouse to run tests automatically on each push to the main branch and on pull requests.
- Set up basic configuration files for Lighthouse to specify which audits to run and establish performance budgets.
- Run initial Lighthouse audits to set a baseline for acceptable performance metrics.

**Comment by mesudip** [comment]
This is unblocked and In progress

**Comment by mesudip** [comment]
PR has been created for this issue. 
https://github.com/IntersectMBO/govtool/pull/997

**Comment by spannercode** [comment]
Lighthouse for GovTool is available here:
https://lighthouse-govtool.cardanoapi.io/app/projects/govtool/dashboard

**Comment by Ryun1** [comment]
This ready to be closed now @spannercode ?
