### ISSUE TITLE
Static Code Analysis

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#663]
### Why

The goal is to automate code quality checks, streamline code reviews, and prevent quality regressions by incorporating SonarQube into our CI/CD process.

### What

To improve code quality and ensure coding standards are met, we propose integrating SonarQube into our development pipeline. SonarQube will provide comprehensive static code analysis to detect bugs, vulnerabilities, and code smells in our codebase.

### How

- [x] Install and configure a SonarQube server or set up a SonarCloud account.
- [x] Integrate SonarQube with our existing CI/CD pipeline (GitHub Actions).
- [x] Create a sonar-project.properties file to specify project settings, source directories, and exclusion parameters.
- [x] Run an initial scan to establish a baseline for current code quality and identify critical areas for immediate improvement.
- [x] Configure the pipeline to run static code analysis on each commit to the main branch and on all pull requests.

**Comment by Ryun1** [comment]
GovTool repo now public, so we should be unblocked

**Comment by spannercode** [comment]
SonarCloud status is visible here:
https://sonarcloud.io/summary/overall?id=intersect-govtool
