### ISSUE TITLE
Reporting Dashboard using Allure Reports

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#664]
### Why

To facilitate better test result management and enhance the debugging process by providing a visual and detailed report of test executions, which will include trends, graphs, and historical data.

### What

To improve visibility and understanding of our automated test outcomes, we propose the integration of Allure Reports into our CI/CD pipeline. Allure Reports will provide a rich and insightful dashboard to display detailed test results, making it easier for developers and QA to analyze test executions and identify issues quickly.

### How

- [x] Install Allure Report generation tools in our test environment.
- [x] Ensure compatibility and integration with our existing test frameworks (frontend/backend)
- [x] Modify test scripts or CI/CD pipeline configurations to generate Allure result files during test runs.
- [x] Set up a server to host Allure dashboards
- [x] Customize the Allure dashboard to reflect our specific reporting needs, such as test severity, categories, and tags.
- [x] Integrate Allure reporting into the CI/CD pipeline to automatically update reports with each build or on a scheduled basis.

**Comment by Ryun1** [comment]
I think we can probably close this one, the dashboard looks good.

**Comment by NabinKawan** [comment]
@Ryun1 is this [PR](https://github.com/IntersectMBO/govtool/pull/814) configured?

**Comment by Ryun1** [comment]
I have granted both @mesudip + @NabinKawan admin, please feel free to add the secrets

**Comment by pmbinapps** [comment]
Reports accessible, under current break down. Works smooth.

**Comment by spannercode** [comment]
Waiting to have all tests included in the dashboard, then we plan to close this ticket.

**Comment by NabinKawan** [comment]
Here is the link for dashboard: [allure-report](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/4/#behaviors)

**Comment by Ryun1** [comment]
Can this be closed out @spannercode ?

**Comment by spannercode** [comment]
@Ryun1 Yes, it can be closed.

Here is the final link for the dashboard which includes frontend, backend and web-app-boilerplate test reports.
https://intersectmbo.github.io/govtool-test-reports/
