### ISSUE TITLE
Extended Test Cases - Chang H/F - PR to `cardano-test-plans`

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#666]
### Why

To cover the additional test cases

### What

New test cases are added on the existing user stories.
A document is attached with this ticket.

### How

- The additional test cases are covered as Playwright tests and added to the test suite.

[Extended Test Cases - Chang H_F.pdf](https://github.com/IntersectMBO/govtool/files/14903222/Extended.Test.Cases.-.Chang.H_F.pdf)

**Comment by Ryun1** [comment]
Can you make a pull request to the [cardano-test-plans](https://github.com/IntersectMBO/cardano-test-plans) repository, to add in these cases please

**Comment by spannercode** [comment]
Pull Request is submitted here: 
- https://github.com/IntersectMBO/cardano-test-plans/pull/37

**Comment by Ryun1** [comment]
Pull request merged 

- https://github.com/IntersectMBO/cardano-test-plans/pull/37
