### ISSUE TITLE
GA Search - Voted on - Add search functionality

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#674]
### Why

Voted on tab uses data from `GET /drep/getVotes/{drepId}` which should include the search parameters.
That task should provide integration with such params to allow searching for the voted on actions.

### What

Integrate the search params of `/drep/getVotes/{drepId}` endpoint.

### How

Use the same logic as for [`/proposal/list`](https://dev-sanchonet.govtool.byron.network/api/swagger-ui/#/default/get_proposal_list) endpoint.

**Comment by pmbinapps** [comment]
OK: checked [here](https://github.com/IntersectMBO/govtool/issues/640#issuecomment-2083165266)
