### ISSUE TITLE
Setting CORS policy for metadata validation service in dev environment

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#678]
As a developer,

I want to open a metadata validation service on the dev environment

so that I can access it from localhost only.

### Summary:
The task at hand involves configuring Cross-Origin Resource Sharing (CORS) policies for a metadata validation service in a development environment. This configuration will ensure that the service can only be accessed by developers from the localhost, limiting access to the dev server exclusively.

### Acceptance Criteria: 
- [x] Implement CORS settings on the metadata validation service to allow access only from localhost in the dev environment.
- [x] Verify that only developers from the localhost can access the metadata validation service.
- [x] Ensure that the CORS configuration does not impact any other functionalities of the service.
- [x] Document the steps taken to configure the CORS policy for future reference.

**Comment by pmbinapps** [comment]
That to be synced with current Haskel backend.
