### ISSUE TITLE
Add loaders to the lists and pending transactions on DRep explorer

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#681]
## Context & versions
Recent test-env.

## Steps to reproduce
1. Go to https://test-sanchonet.govtool.byron.network/ and enter the DRep directory page.

## Actual behavior

No loader is displayed on fetching the DReps.

## Expected behavior

The user should be informed via loader that some data is being fetched.

**Comment by pmbinapps** [comment]
OK NOW
