### ISSUE TITLE
Troubleshooting loading resources from Google Tag Manager due to CSP issue

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#693]
As a system administrator,

I want to configure Content Security Policy (CSP) settings in Traefik to allow images from Google Tag Manager

to resolve resource loading issues.

### Summary:
Currently, there is an issue with loading resources from Google Tag Manager due to CSP restrictions. It was mistakenly assumed that Google Tag Manager would not provide images, thus resulting in a lack of corresponding CSP settings in Traefik. To rectify this, the CSP settings in Traefik need to be adjusted to properly allow images from Google Tag Manager.

### Acceptance Criteria:
- [x] Review the current CSP settings in Traefik to identify the missing configuration.
- [x] Modify the CSP settings to explicitly allow images from Google Tag Manager.
- [x] Test the changes by loading resources from Google Tag Manager to ensure that the issue has been resolved.
- [x] Document the updated CSP configurations in Traefik for future reference.

**Comment by pmbinapps** [comment]
Moving to Stage as already resolved:
https://github.com/IntersectMBO/govtool/issues/707
