### ISSUE TITLE
Fix displaying modals to not block signing transactions with metadata

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#710]
## Context & versions

* dev-env
* test-env
## Steps to reproduce

Navigate to the flow that requires metadata:
* Creating gov action.
* DRep registration

## Actual behavior

* When validation ends no modal is displayed which causes either misunderstanding of what happens or completely blocks building the transaction.

## Expected behavior

Modals are displayed correctly

**Comment by pmbinapps** [comment]
OK NOW
