### ISSUE TITLE
GAs fails validation due to fetching the resource blocked by CSP

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#712]
Integrate displaying GAs and validation of their metadata with validation service to not be blocked by CSP.

## Current version

Every displayed action fails validation
![Image](https://github.com/IntersectMBO/govtool/assets/24510246/74250e2f-8be8-4bce-9fde-e0b9e75510d3)

## Expected version
Data missing or any other validation on GAs should be displayed only when the validation indeed fails (not being blocked by CSP)

**Comment by pmbinapps** [comment]
OK NOW


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/f7b55010-d298-400a-b604-6f18654ee1b8)
