### ISSUE TITLE
Updating and restarting Cardano infrastructure on SanchoNet

### ISSUE THREAD

**Issue by placek** [IntersectMBO/govtool#714]
As a system administrator of SanchoNet,

I want to update the Cardano infrastructure elements to the New Node 8.10.0-pre version and the New DB-Sync tag,

so that the network can be restarted and resynchronized properly.

### Summary:
SanchoNet, running on the Cardano network, requires an update of its infrastructure elements. Following the update, the network needs to be restarted and resynchronized. The update includes transitioning to the new Node 8.10.0-pre version and adopting the new DB-Sync tag. These actions are crucial to ensure that the network maintains its optimal performance and reliability.

### Acceptance Criteria:
- [x] Install the new Node 8.10.0-pre version from https://github.com/IntersectMBO/cardano-node/releases/tag/8.10.0-pre,
- [x] Install the new DB-Sync,
- [x] Restart the Cardano stack on SanchoNet on dev to apply and verify the updates,
- [x] Resynchronize the Cardano network on SanchoNet on dev to apply and verify the updates.

**Comment by pmbinapps** [comment]
No problems related to this item
