### ISSUE TITLE
DRep explorer - Main page - click on View DRep Directory - doesn't show DRep list, instead invokes connect and dashboard is shown

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#719]
Button:
![Image](https://github.com/IntersectMBO/govtool/assets/82152577/67c95201-5095-4f74-a604-a0da6effe353)

Shows:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/4572b7d7-b387-409e-9ea7-9d12b6c1cc0c)

Instead - DRep exploler view.

Jam [recording](https://jam.dev/c/15e1d2b5-8ce9-4c20-82a3-ca088ada53bc) here

**Comment by pmbinapps** [comment]
OK NOW - DRep directory is shown.

**Comment by m-i-k-e** [comment]
Looks good Closing
