### ISSUE TITLE
Extend /drep/list endpoint to apply search and filter functionality

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#722]
### Why

To allow searching and filtering DReps.

### What

extend /drep/list endpoint to include:
* filter - multi choice, based on DRep status (active, inactive, retired)
* sorting - based on date of registration, voting power, status (active > inactive > retired)
* Allow searching for DRepID.

### How

Api should be simillar to GET /proposal/list for gov actions.
Describe in a comment final form that should be treated as acceptance criteria.

**Comment by pmbinapps** [comment]
DRep list is empty. Registration as DRep not possible due to problems with wallet.

**Comment by pmbinapps** [comment]
Checked [here](https://github.com/IntersectMBO/govtool/issues/221#issuecomment-2078889275)
