### ISSUE TITLE
Apply business logic (backend) to drep list

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#723]
### Why

To allow user search, filter and sort dreps on a DRep list

### What

Apply business logic provided via #722 in drep list page.

### How

Should have similar logic to proposal list.

# Acceptance criteria.
1. I should be able to search via drep id
2. I should be able to filter out dreps for active, inactive, retired
3. I should be able to pass sorting (for a status, voting power, registration dat) to my drep list.

**Comment by pmbinapps** [comment]
Checked here https://github.com/IntersectMBO/govtool/issues/221#issuecomment-2078889275
