### ISSUE TITLE
DRep explorer - Dashboard - DRep card - delegating - wrong text and button label

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#724]
'Use Your Voting power' instead 'Delegate you voting power'
'Delegate' label on button instead 'View DRep directory'

Delegate button leads to previous delegation wizard.

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/3ef2bbbf-6c90-4cf5-90f0-592dfd0abb75)

**Comment by pmbinapps** [comment]
OK NOW:
![image](https://github.com/IntersectMBO/govtool/assets/82152577/7a525809-4360-4bfb-8ffc-b9f0d0bbb3b1)

**Comment by m-i-k-e** [comment]
Looks good. Closing
