### ISSUE TITLE
Bump CSL to v12.0.0-alpha.29

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#725]
### Why

To make it compatible with the new [Cardano node release](https://github.com/IntersectMBO/cardano-node/releases/tag/8.10.0-pre).

### What

Bump CSL to [v12.0.0-alpha.29](https://www.npmjs.com/package/@emurgo/cardano-serialization-lib-browser/v/12.0.0-alpha.29).

**Comment by pmbinapps** [comment]
Requiered updated - moving to Staging.
