### ISSUE TITLE
Strange Governance Actions Appear

### ISSUE THREAD

**Issue by Thomas-Upfield** [IntersectMBO/govtool#73]
Summary: Governance Actions Appear when they shouldn't be there.

To replicate: 
1. go to GovTool Governance Actions page
2. find a governance action type that has more than 6 governance actions (so you can see the view all option when you scroll all the way to the right).
3. vote on enough governance actions so that there are fewer than 6 governance actions and you can see all governance actions without using "view all".
4. Keep voting on these governance actions and strange things will happen, like different amounts of governance actions being found each time you go to the governance actions page. 

Please see more here: https://discordapp.com/channels/826816523368005654/1178799499381063751/1199026524179939410 

This issue was reported by a community member but I also verified.

**Comment by bosko-m** [comment]
Moving this to the last known status, as it seems the status was lost while moving to the new project.
