### ISSUE TITLE
Update transaction composition library

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/govtool#732]
We need to be able to submit transactions during playwright test.

This is broken with current node release.

### ToDo:
- [x] Update kuber dependency to use  lastest version of cardano-api `8.44`

**Comment by mesudip** [comment]
The Changes required in transaction composition library is incorporated in the infrastructure.
Furthermore, the governance action loader is live and functional on fresh sanchonet.
https://vva-governance.cardanoapi.io/

**Comment by Ryun1** [comment]
should we close this then?
