### ISSUE TITLE
Integrate Proposal discussion flow into Voting flow

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#736]
On the Proposal Discussion Forum Figma, the proposal part of Governance Actions is not integrated with the flow on the GovTool Figma (which is being built). A Governance Action (or it could be called a Governance Proposal) is a single thing with multiple stages. 

1. Enter proposal in a form, which can be saved as a Draft
2. The proposal can be made 'live' on GovTool and discussed
3. The proposal can be abandoned before going on chain
4. It can go on-chain for a vote (requires a large deposit)
5. It can be enacted
6. It can be not-enacted (expire or get voted down)
7. It can be viewed in perpetuity after the vote has closed.

All of these stages must be supported by the design and navigation of each proposal.

Furthermore, the Governance Action section currently on govtool must support aggregated searching of all the above, with a clear indicator of what stage any proposal is in, and also with properly-structured filtering to help users find the proposals they are interested in.

**Comment by Ryun1** [comment]
this is implemented I believe
if not, discussion can move to newer issues

**Comment by m-i-k-e** [comment]
A comprehensive critique of what is up with this flow, and some ideas on how to fix it.
https://www.loom.com/share/5c1f0710628646708cd7cb77189d1bf0?sid=1f798d8d-e4ec-43f3-b9c2-0aa876a15039
