### ISSUE TITLE
DRep directory - Drep list - Load more button not shown after 10 items

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#740]
Issue in feature https://github.com/IntersectMBO/govtool/issues/220

NOT OK Show more - NOT SHOWN AFTER TEN ITEMS

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/41946728-4925-4ac5-9e9d-1224af11847d)

Design:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/2bb48751-3151-41fc-80a4-e06179a9622a)

**Comment by Sworzen1** [comment]
blocked by [issue 756](https://github.com/IntersectMBO/govtool/issues/756)

**Comment by pmbinapps** [comment]
OK NOW

**Comment by m-i-k-e** [comment]
@l-br1 Are you assigning this for me to test? This should be assigned to a tester, as they should do regression testing on all fixed bugs. @MSzalowski can you please verify the workflow for fixed bugs?

**Comment by m-i-k-e** [comment]
"Show more" button works 17 May

<img width="1305" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/a06f7124-4dee-4b0d-8d9f-4369847c7e3a">

**Comment by MSzalowski** [comment]
>  @MSzalowski can you please verify the workflow for fixed bugs?

Yes, you should verify only what is delivered on staging which at this stage should be tested by QA

**Comment by spannercode** [comment]
Adding this to list of automated tests. Assigned to @NabinKawan

**Comment by spannercode** [comment]
This is covered as 
`2O. Should load more DReps on show more`


![Image](https://github.com/IntersectMBO/govtool/assets/45617712/b9de1993-8bd7-4596-bb3c-89c49b297f6e)
