### ISSUE TITLE
Integrate Proposal Discussion Forum Figma files into GovTool

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#744]
The Proposal Discussion Forum is not a separate app but simply a part of GovTool. Having someone work on it in an external file makes it difficult or even impossible to see how it fits in with GovTool from a user perspective. 

Moving the designs into GovTool makes a lot of sense.

**Comment by m-i-k-e** [comment]
This has not been done

**Comment by bosko-m** [comment]
Its already covered for work elsewhere.
