### ISSUE TITLE
add copy to maintenance page

### ISSUE THREAD

**Issue by l-br1** [IntersectMBO/govtool#753]
please update body copy to:

_The SanchoNet GovTool Beta is currently down for maintenance. 
SanchoNet Govtool is connected to SanchoNet testnet, which means that if the network gtes upgraded with new features Govtool needs to be updated too.

Please try again later._

**Comment by bosko-m** [comment]
@MSzalowski I suppose we can close this one?

**Comment by MSzalowski** [comment]
yes, I'll do that
