### ISSUE TITLE
DRep directory - DRep list - missing loader

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#767]
Seems like the loader element is missing just before appearing list of DReps. It is used when some other elements on site are being loaded or prepared.

Compare with Jam [recording](https://jam.dev/c/e13265ba-f4dc-4aa9-89f8-2a1a1ac26ae2)

**Comment by MSzalowski** [comment]
That is already done on dev

**Comment by pmbinapps** [comment]
OK NOW;
https://test-sanchonet.govtool.byron.network/drep_directory



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/690895d5-fcf7-4b24-96d9-b3e997b05775)
