### ISSUE TITLE
GovTool Maintenance page - change tab title 'Error page' to 'Maintenance page'

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#776]
![image](https://github.com/IntersectMBO/govtool/assets/82152577/e6a5c624-d059-4db6-88db-2c3a1c48523d)

Occurred in [thread](https://binarapps.slack.com/archives/C06M3FZ4L4U/p1713445967782449)

**Comment by bosko-m** [comment]
@MSzalowski I suppose we can close this one?

**Comment by MSzalowski** [comment]
Yes, I'll do that
