### ISSUE TITLE
[Usersnap] Different Voting Power display on top of screen and in card

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#788]
- Add a comment: Maybe my interpretation/lack of understanding, but confused as to why voting power is different in the top right wallet balance style field, vs the balance available for delegation in the bottom left. Apologies if I am not understanding (highly likely)
- Screen size: 1576 x 1268
- Browser: Chrome 122 (Linux)
- Referer: [SanchoNet Govtool](https://sanchogov.tools/dashboard)
- [Open #37 in Usersnap](https://app.usersnap.com/l/feedback/c8d07400-ac34-42c5-a3bb-2087b57bdedb?utm_medium=integration&utm_campaign=integration&utm_content=open)

![Image](https://github.com/IntersectMBO/govtool/assets/965789/efcb271f-ec82-40fe-b90e-baff65e1383e)

**Comment by m-i-k-e** [comment]
This is still pertinent as a user issue. It's very confusing to see two different 'voting power' displays. Which one is correct?

I think we need to re-think how we display Voting Power, i.e. we should display the 'as-it-is-now' figure, possibly along with the figure at epoch boundaries. It doesn't make sense to say delegate 100k ADA to yourself, and have a zero voting power showing at the top of the screen. Especially if when you vote for something, you ostensibly apply the entire 100k to the Vote.

**Comment by bosko-m** [comment]
@m-i-k-e On which environment do you observe and experience this? Looking at dev and staging envs, the top right button is not displayed anymore at all. What am I missing?
