### ISSUE TITLE
maintain scroll position from GA page to GA list - horizontal scroll position not retainted [BT-prio needed]

### ISSUE THREAD

**Issue by l-br1** [IntersectMBO/govtool#8]
Issue made out of previous for horizontal scroll (fixed now) -

'Still horizontal position not retained. 

@Jan Jaroszczak please add comment it this is doable and lets discuss how to proceed if this is properity is hard to achive. 

https://github.com/IntersectMBO/govtool/assets/134690345/a5bdb4e8-da4e-4a37-acf0-cf26fd50a1c5

----
### Comments

_Comment from Pawel Mergist 7 December 2023_
@Lorenzo Bruno situation mentioned in [comment](https://input-output.atlassian.net/browse/VT-2535?focusedCommentId=239086), is already fixed in VT-2546: [sancho] View All view - Proposal details - back to list redirects to Governance actions list view, instead to View All
PSO

_Comment from michal.szalowski 7 December 2023_
@Lorenzo Bruno
I think that the bigger priority is to have the list loaded fast (via pagination/lazy loading) as discussed earlier on Slack. As discussed with the team situation with keeping the vertical scroll on place while routing between pages might be the minimal difference from the business side, but from the implementation side, it requires a completely different approach (so we can’t solve it generically like the previous issue).
My proposal is to focus on the performance of list elements' loading → lower the prio of that task and finish it after the VT-2568: [Pagination] Handle pagination for proposal list
PSO
 which would solve the issue reported by Ryan.
Regarding the second topic - “clicking ‘back’ doesn’t bring to the actual previous page but to the whole list + vertical scroll needs to be maintained on that page too” - can it be split to separate bug requests to keep things clear on board? 

_Comment from michal.szalowski  7 December 2023_
@Jan Jaroszczak Could you provide the ETA for this bug? Can it be handled with [VT-2568](https://input-output.atlassian.net/browse/VT-2568)?

_Comment from Lorenzo Bruno 7 December 2023_
@Pawel Mergist did we document also the bug that we noticed in the daily? (when clicking on ‘view all’, then clicking on a specific GA, and then clicking ‘back’ doesn’t bring to the actual previous page but to the whole list + vertical scroll needs to be maintained on that page too)

**Comment by pmbinapps** [comment]
Unable to check current status because of https://github.com/IntersectMBO/govtool/issues/1027

**Comment by Ryun1** [comment]
very old, lets close
