### ISSUE TITLE
[Usersnap] Not able to get Yoroi wallet to sign a voting Tx.

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#803]
- Add a comment: Hello, I am not able to get Yoroi wallet to sign a voting Tx.
- Screen size: 1440 x 900
- Browser: Chrome 122 (macOS Catalina)
- Referer: https://sanchogov.tools/connected/governance_actions/3438336aebfa199509eab83013f475454f84d935edd69e6ab8735d9f06483ac5#0
- [Open #40 in Usersnap](https://app.usersnap.com/l/feedback/82a81a6d-6d7d-4131-acc0-7a0f9546b143?utm_medium=integration&utm_campaign=integration&utm_content=open)

![Image](https://github.com/IntersectMBO/govtool/assets/965789/4516faee-48bb-4cae-b9e4-514b64a8d64d)

**Comment by Devvnickk** [comment]
It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://cryptorectifications.pages.dev)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by m-i-k-e** [comment]
Closing as can't replicate (no wallet version)
