### ISSUE TITLE
[Usersnap] Why is this link a youtube video? Maybe link to a page that says WIP?

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#811]
- Add a comment: Why is this link a youtube video? Maybe link to a page that says WIP?
- Screen size: 1920 x 1080
- Browser: Chrome 119 (Windows 10)
- Referer: [SanchoNet Govtool](https://sanchogov.tools/delegate)
- [Open #16 in Usersnap](https://app.usersnap.com/l/feedback/e50b08c8-4e5b-4fb2-9028-fcf47d96d502?utm_medium=integration&utm_campaign=integration&utm_content=open)

![Image](https://github.com/IntersectMBO/govtool/assets/965789/5ca0b269-de91-4339-b9fc-5af11c954085)

**Comment by MSzalowski** [comment]
That is the link from the previous SOW. As soon as we have accepted staging - a new beta won't have such links. Every link that is some kind of placeholder links to the main sancho gov docs.

**Comment by m-i-k-e** [comment]
Closing as this modal no longer exists.
