### ISSUE TITLE
[Usersnap] Return to existing spot in the list - Gov Tool GA display loses user's spot on page.

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#837]
## Context & versions
staging.sanchonet

## Actual behavior
The main GA screen scrolls to the default position, losing the user's space

## Expected behavior
The main GA screen should scroll to the previously selected card, preserving the user's original departure point.

**Comment by m-i-k-e** [comment]
This is a bigger problem than it seems. Basically, the user is lost every time they return to the main GA page.

This needs looking at, and I've raised a new issue for it: #1177

**Comment by bosko-m** [comment]
Closed as a duplication of #1177 and also covered elsewhere in the community backlog.
