### ISSUE TITLE
Configure sanchogov.tools sub-domain for the analytics service

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#849]
### Why

To provide access to the analytics under one domain tree.

### What

Configure sanchogov.tools sub-domain called `participation`  - `participation.sanchogov.tools`

Setup infra (on the current govtool infrastructure) for the https://github.com/intersectMBO/govtool-analytics-dashboard

**Comment by MSzalowski** [comment]
@placek Please note below the requirements for setting the infra such as secrets, details regarding the environment, and so on.

**Comment by placek** [comment]
Requirements:
* [Secrets](https://github.com/IntersectMBO/govtool-analytics-dashboard/settings/secrets/actions) set for each required [ENV](https://github.com/IntersectMBO/govtool-analytics-dashboard/blob/main/.env.example);
* The address of a registry where you want to push [docker images](https://github.com/IntersectMBO/govtool-analytics-dashboard/blob/main/Dockerfile) to (if such registry is present);
* Extensive information on what are the services required to fully support that dashboard: what is externaly required, what internal services it depends on…
* Who and how should be able to access that dashboard.
