### ISSUE TITLE
Dashboard - As DRep - Voting power element shows wrongly 0 ADA

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#850]
Occurred on [test-sancho](https://test-sanchonet.govtool.byron.network/):
With, Eterln (beta) wallet.

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/81d5a088-7dbd-48bc-9e27-9664ea9d23d5)

**Comment by pmbinapps** [comment]
This issue depends on db-settings. 
Settings as Ready for Stage.

**Comment by m-i-k-e** [comment]
Nothing that I can see that I'm able to do here.
