### ISSUE TITLE
GA - Submit - potentially fee for submit is to high

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#851]
On test-sancho, having nearly 50k of ADA it is still not enough:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/fbb57b45-1e0f-4743-8d64-820dec9ec245)

Jam [recording](https://jam.dev/c/ac55c455-74d1-4b12-b38a-a15944232780).

**Comment by pmbinapps** [comment]
This issue depends on db-sync settings.
Setting as Ready for Stage.

**Comment by m-i-k-e** [comment]
@l-br1 Why have you assigned this to me?

**Comment by m-i-k-e** [comment]
Nothing that I can see that I'm able to do here.
