### ISSUE TITLE
GA - View - just submitted GA that passed validation is shown with 'Data missing' title

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#854]
To reproduce on test-sancho:

1. Submit new Info GA: with following data:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/05c14b92-77a6-4c9d-936d-6a9248e001af)

2. Provide Info.json from url: https://raw.githubusercontent.com/mpawel79/testrepo/master/Info.jsonld

3. New GA Info proposal should pass validation.
4. Go to GA to see the Newest Info action
5. Find the last one - 'Data missing' is shown in title eg like for [this](https://test-sanchonet.govtool.byron.network/connected/governance_actions/e938a478983b3a632c589b1aab297d23da23e4fc906b1ae0e83d37927b3b2496#0)

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/9a0c5817-8934-4d23-b986-54ec66bbde83)

**Comment by m-i-k-e** [comment]
@l-br1 Did you assign this to me for testing?

**Comment by m-i-k-e** [comment]
There is nothing I can do here. It seems that there is a bug in the validation code.
