### ISSUE TITLE
DRep explorer - /drep/list API - list of DReps is empty after an hour after registration as DRep

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#856]
After registration as DRep - its id is not showing on /drep/list and thus is not visible in DRep directory.

To reproduce on test-sancho

1. Register as DRep
2. Wait an 1 hour
3. Check in DRrep explorer if an entry appeared.
4. Check check /drep/list https://test-sanchonet.govtool.byron.network/api/drep/list

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b4020e2b-3853-4387-8a30-ceb520b5607a)

The DRep which must appear is:
CIP-95 🤠
.cip95.getPubDRepKey(): 3028de6a65c5584cf8f8138b44d14fbe2c58e878b40d705753dbf3f2262a6a8c

Hex DRep ID (Pub DRep Key hash): fc790f12e3ef3f58db42355b15559c288ed2d4338ff078600ef2b7c3

Bech32 DRep ID (Pub DRep Key hash): drep1l3us7yhraul43k6zx4d324vu9z8d94pn3lc8scqw72muxxumyg6

.cip95.getRegisteredPubStakeKeys():

No registered public stake keys returned.
First registered Stake Key Hash (hex):

.cip95.getUnregisteredPubStakeKeys():

fb09e094f454235d41bf573eae511ec2f576a9ab87ebb80a49ac5d6456965254
First unregistered Stake Key Hash (hex): 3f2cbef7b5340739aa99ffcd76ca6a7334487dc65dc21b4f77ea0ea2

**Comment by pmbinapps** [comment]
Depends from db-sync. Retest after today PR and resync.

**Comment by m-i-k-e** [comment]
Cannot test this as I cannot become DRep

**Comment by MSzalowski** [comment]
https://github.com/IntersectMBO/govtool/pull/1247 Unblocks this issue

**Comment by m-i-k-e** [comment]
Working now.
