### ISSUE TITLE
Snapshot testing

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#86]
### Why

To easily track changes in conditionally rendered layouts (with a hard to track conditions that are going on), changes that involve variables and variable scoped pieces of layouts to render, etc.

[This PR](https://github.com/IntersectMBO/govtool/pull/84) is a perfect example of a need of snapshot tests. With such functionality it would be much easier to check whether i18n provided via that pr works (translations are placed where they should be placed, there are no typos in translations and so).

### What

Unit testing is already on [this pr](https://github.com/IntersectMBO/govtool/pull/58). As it uses Vitest, we should also use part of vitest that includes [snapshot testing](https://vitest.dev/guide/snapshot).

### How

Following [this](https://vitest.dev/guide/snapshot) guide.

**Comment by Ryun1** [comment]
very old, lets close
