### ISSUE TITLE
Dashboard - DRrep card - opening DRep details with button > shows endlessly loader

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#866]
To reproduce on test-sancho:
1. Delegate to a DRep
2. Go to Dashboard
3. Click on DRep card > button.

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/032eaba9-ce32-4c92-8719-d80b815fa011)

Compare with Jam [recording](https://jam.dev/c/a1d30e64-726a-4037-97e1-61aedd3ea4c5)

**Comment by Sworzen1** [comment]
It should be fixed

**Comment by pmbinapps** [comment]
Ok now
