### ISSUE TITLE
[USERSNAP] I have not had any success getting my wallet to connect and show proper balance.  I have registered multiple times as a Drep and it never holds.  Today I cannot reregister because it shows UTXO balance insufficient 

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#867]
**Sender**: None
**Taken at**: https://sanchogov.tools/dashboard
**Fields**:
- Add a comment: I have not had any success getting my wallet to connect and show proper balance.  I have registered multiple times as a Drep and it never holds.  Today I cannot reregister because it shows UTXO balance insufficient 

**Browser**: Chrome 122 (macOS Catalina)
**Screen size**: 1440x900
**[Open #44 in Usersnap](https://app.usersnap.com/l/feedback/64a2bcd2-2352-4d7c-bdc1-bee06c79112c?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
@kickloop I can do nothing here. Why is this assigned to me?
