### ISSUE TITLE
Dashboard - as DRep - Voting power chip is showing zero

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#872]
To reproduce, on test-sancho:
 1. Register as Drep
 

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/f95e2960-b51e-47a6-b93a-22f753c87125)

 3. Register as Sole Voter
 

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/63fa96d3-b625-43f0-ae41-7b27123358fc)

**Comment by MSzalowski** [comment]
Voting power is not equal to the ADA that ADA holder has on their wallet. Also - these values are taken directly from the DB-sync meaning that we can do little or nothing with that.
Moving to the next iteration and lowered a prio.

**Comment by MSzalowski** [comment]
Closing as it's not an issue
