### ISSUE TITLE
DRep explorer - delegation to a DRep seems to fail but there is info that 'You have delegated A... to:  with card and DRep id

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#875]
Occurred on test-sancho with demos 1.8 wallet.

To reproduce:
1. Go to DRep exploler
1. Delegate to a DRep, observe card will move to the top.
2. Reload page after 3 minutes - walltet will connect
3. Watch - after while the delegation transactions is reported to be failed (4:02 min. Jam [record](https://jam.dev/c/20f8956e-4e81-42e8-80d1-fc51f3cd0115)). - but in fact it seems to be OK delegation is retained.

Jam recording here, error - delegation failed occurs in 4:02 min.

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/6cfede5d-a634-41e2-b050-15d600085275)

https://jam.dev/c/20f8956e-4e81-42e8-80d1-fc51f3cd0115

**Comment by pmbinapps** [comment]
Duplicated [here](https://github.com/IntersectMBO/govtool/issues/920)

**Comment by JanJaroszczak** [comment]
Fixed in this PR: https://github.com/IntersectMBO/govtool/pull/947

**Comment by pmbinapps** [comment]
Above PR #947 - not merged yet to test. Issue still occurs - last recording before [merge](https://jam.dev/c/6795c366-5f05-42f9-b8ba-0ade2d2c7a97).

**Comment by pmbinapps** [comment]
OK NOW

NOTE: not checked - self delegation, [issue](https://github.com/IntersectMBO/govtool/issues/904) blocked

**Comment by m-i-k-e** [comment]
Tested this and can't replicate bug. Looks OK
