### ISSUE TITLE
Padding on 'chips' on DRep list too large 

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#877]
## Context & versions

staging.sanchonet
## Actual behavior
Padding doesn't match Figma

## Expected behavior
Padding matches Figma

**Comment by pmbinapps** [comment]
@m-i-k-e hi Mike, could mark, or paste what chips from below (or other) do you think of?


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/c6ac5ce0-b1a7-4d54-a465-489d8e1a317d)
