### ISSUE TITLE
padding on buttons too small on DRep list

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#878]
## Context & versions

staging.sanchnoet
## Steps to reproduce

  1. Go to Drep List
  2. Look at buttons

## Loom Video
https://www.loom.com/share/29143157de9946108b88e44f9b43a279?sid=bf6f9deb-72ff-4924-87ce-478230e01130
  If not reproducible, describe the steps you took as you remember it.

## Actual behavior
Buttons' padding does not match Figma

## Expected behavior
Buttons' padding should match figma

**Comment by pmbinapps** [comment]
![Image](https://github.com/IntersectMBO/govtool/assets/82152577/f3cd65b1-7d7d-49df-a66b-db0f3ce4851e)



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/69380dfe-6f1b-4c50-8729-18a6823e1716)

**Comment by pmbinapps** [comment]
OK padding on buttons
NOT OK - small misalignment on Active and View details, Delegate buttons

Additional:

View details button background should be white



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b2cb1005-3d58-4a5f-8a34-94af1f1cad43)

**Comment by MSzalowski** [comment]
@pmbinapps Please reopen issues that are going back after QAs verification

**Comment by pmbinapps** [comment]
OK NOW - slight difference, but most of columns of data synced with Figma


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/a80a456a-a8b8-41d7-8ed2-72dd9e343bff)
