### ISSUE TITLE
Drep listing alignment and numbers

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#879]
## Context & versions

staging. sanchonet
## Steps to reproduce

  1. Go to Drep list
  2. Look at list elements

## Explained in Loom Video
https://www.loom.com/share/d218ec980a2d4377b0c7d31aebf24b2f?sid=36d8280e-9d55-47d3-914f-61dcdb2ddfe1

## Actual behavior
Don't match Figma

## Expected behavior
Should match Figma

**Comment by pmbinapps** [comment]
OK NOW:

[FIGMA](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7079-81357&mode=design):
![image](https://github.com/IntersectMBO/govtool/assets/82152577/a19944a8-7590-454b-a8f2-e38e719df5b1)


Test-sancho DRep list:

![image](https://github.com/IntersectMBO/govtool/assets/82152577/38a60635-5f87-4a13-b42f-d277438a3161)
