### ISSUE TITLE
Change terminology of "sole voter" to "direct voter"

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#880]
### Why

After comms review, sole voter was determined to be a bad name.

### What

Replacing all user facing copy of "sole voter" to be "direct voter"

### How

by using ctrl-f

**Comment by pmbinapps** [comment]
OK on Dashboard

NOT OK for retired Sole Voter(Direct Voter)



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/c9633f4b-b085-4089-b53c-cff01bf60b60)

**Comment by pmbinapps** [comment]
NOT OK - 'DRep' text used now instead Direct Voter



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/9f2d6a01-af14-41e6-b9aa-4abb5809e47e)

**Comment by MSzalowski** [comment]
That is already done with #957

**Comment by pmbinapps** [comment]
OK when user is Direct Voter

**Comment by m-i-k-e** [comment]
@pmbinapps Correct: "Direct Voters" don't have any metadata to edit.

**Comment by m-i-k-e** [comment]
OK, I have changed the main Figma file to say "Direct Voter" instead of "Sole Voter"

**Comment by m-i-k-e** [comment]
@pmbinapps @MSzalowski To recap: 'Direct Voter's' listings _don't_ show up in the DRep directory. However, if a user knows the drep ID of a Direct Voter, and they search for it, it should show and there should be a detail page for it. This will not have any metadata on it. I'm not sure what happens now, as this is not able to be tested.

Whatever state of affairs that happens now should be ok, as long as the Direct Voter is not listed in the DRep directory. In the future, we will build Voting Histories for every voter, and therefore in the future the Direct Voter's page could have value to them. But we are not there today.

**Comment by m-i-k-e** [comment]
A similar text issue to changing this text is #911. I've made both of these changes in Figma, and they are ready for devving.

**Comment by pmbinapps** [comment]
@m-i-k-e issue mentioned [here](https://github.com/IntersectMBO/govtool/issues/880#issuecomment-2115942865) is tracked [here](https://github.com/IntersectMBO/govtool/issues/960#issuecomment-2100935922)

**Comment by MSzalowski** [comment]
Issue no longer exists. Could you please retest it @pmbinapps?

**Comment by pmbinapps** [comment]
OK - Sole Voter text is not occurring anywhere
