### ISSUE TITLE
Delegate connected dashboard card - buttons are not scaling properly

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#883]
## Context & versions

dev, test, staging sanchonet

## Steps to reproduce
1. Connect your wallet.
2. Display dashboard on a mobile view.

## Actual behavior

<img width="563" alt="image" src="https://github.com/IntersectMBO/govtool/assets/24510246/613979ea-031b-4372-87c4-173a95ac67b2">

View DRep Directory button takes all the free space.

## Expected behavior

Buttons should be equally sized in a row.

**Comment by Sworzen1** [comment]
<img width="1440" alt="Zrzut ekranu 2024-04-29 o 23 28 21" src="https://github.com/IntersectMBO/govtool/assets/50292667/acbe66d4-1891-478b-aa7b-2125bcd7cd7e">
@pmbinapps can you check this case ? on my device it works correctly

**Comment by pmbinapps** [comment]
OK NOW
https://jam.dev/c/a4178a95-3777-4dc1-96f8-f41a4a803f88
