### ISSUE TITLE
DRep explorer - DRep list - Sole voter is shown on list, when not searched

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#886]
Sole Voter should only be shown when he/she is explictly searched with Search input box:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/3b17cf00-c488-46aa-85a3-4b339954b869)

Sole Voter should be excluded from DRep list.

Occurred when checking this [issue](https://github.com/IntersectMBO/govtool/issues/318#issuecomment-2083211094)

**Comment by MSzalowski** [comment]
To extract conditions on which direct voter is treated as a direct voter

**Comment by MSzalowski** [comment]
Not blocked anymore, but this issue is not crucial and being done in next iteration won't have an impact on the core system functionalities..
