### ISSUE TITLE
Setup another testing environment

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#891]
# Why
To allow the automated testing in separation, prepare duplicate of the staging environment for the DQuadrant team.

# What
* Prepare duplicate of the staging environment for the DQuadrant team.

**Comment by MSzalowski** [comment]
@mesudip 
Q:
* Whether what is pushed by DQuadrant is to be run on the environment (meaning the tools)?
* Is the subdomain needed? If so - nginx setup is needed.
* Number of resources needed?
* Are the ssh accesses needed?

**Comment by Ryun1** [comment]
- Access via ssh?
  - sudo access needed if basic installs not done, like docker
- subdomain -> would be best to have subdomain
  - Decision; use dQuads cardanoapi.io domain for now, migrate later on
- what do we want?
  - replication of other existing environments
  - some resource limitations may occur, although enough for Node+DBSync
- how is resource provisioning done
  -  fixed is probably fine, but can be extended as needed
- timeline
  - 2 MD -> likely monday
  - but this is priority 1

**Comment by Ryun1** [comment]
No longer needed, closing for now.
