### ISSUE TITLE
Write Metadata hosting service for Tests

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#894]
When registering dreps or creating proposals for tests, Metadata json must be publicly hosted.
We need a service to host those data.

### Why
Using a metadata host service for testing instead of mock will make sure that the metadata-fetching, indexing  or validating components of govtool are functioning properly.

Here is a deployed service URL:
https://metadata.cardanoapi.io/docs/

**Comment by mesudip** [comment]
PR is ready with the changes: https://github.com/IntersectMBO/govtool/pull/930
