### ISSUE TITLE
[BUG] Slow delegation issue

### ISSUE THREAD

**Issue by NabinKawan** [IntersectMBO/govtool#897]
## Slow delegation

**Description:**
The delegation transaction has been successfully added in dbsync, but there is a significant delay in confirmation of the delegation transaction on the frontend.

**Comment by pmbinapps** [comment]
OK NOW- the same as [DRep explorer - delegation to a DRep seems to fail but there is info that 'You have delegated A... to: with card and DRep id](https://github.com/IntersectMBO/govtool/issues/875)

**Comment by kneerose** [comment]
### Related test reports
- [2A. Should show delegated DRep Id (on Dashboard, and DRep Directory) after delegation](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/41/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/e2a33ab5fc2c219e/)
- [2F. Should change delegated DRep](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/41/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/addcb262be0b6fe4/)
- [2U. Should show delegated voting power to Abstain](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/41/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/dc256f79bbeb00b/)
- [2V. Should show delegated voting power to No confidence](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/41/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/ea1d6c9ecfb7443c/)

**Comment by NabinKawan** [comment]
Hi, @pmbinapps, Slow delegation has been improved, but sometimes slow delegation confirmation in UI is still causing our tests to be flaky.

What actually happened?
1. Delegation tx send
2. Delegation tx polling
3. Transaction has been confirmed and added into dbsync
4. Waited for 20 secs, but the frontend failed to confirm it

**Comment by MSzalowski** [comment]
That should be fixed after https://github.com/IntersectMBO/govtool/issues/1235
