### ISSUE TITLE
Search bugs (case insensitive search, phrase highlight, not found msg)

### ISSUE THREAD

**Issue by l-br1** [IntersectMBO/govtool#9]
https://www.loom.com/share/eb0e4f2810ce4b7daddddd0dc9bba7ef

----
### Comments 

_Comment from Thomas Upfield 26 October 2023 at 12:17_

Assigning to @Lorenzo Bruno so he can work out how this should work.

_Comment from Pawel Mergist 25 October 2023 at 13:19_
View Voted:
OK: insensitive search

NOT OK: Filtering when a search phrase is given, compare with scr:

![Image](https://github.com/IntersectMBO/govtool/assets/134690345/cc2883f4-e4d2-4ad0-bcef-dca15ecb3f1c)

_Comment from Lorenzo Bruno 25 October 2023 at 12:11_

Search, filter and sorting should work across both tabs as desgined by @Bartłomiej Łuczak . However, there might be a mistake in the structure of this page for how it works, because sorting and filtering might only make sense within the tab and I am not sure @Bartłomiej Łuczak has designed voted on and to vote on cards to live together

_Comment from Agnieszka Zytka 25 October 2023 at 11:17_

@Pawel Mergist , there was a fix for search merged yesterday. Please check if it’s case insensitive and works for new gov actions ID. 

_Comment from Agnieszka Zytka 25 October 2023 at 11:15_

@Lorenzo Bruno , search as desribed in this task is now working. The issue has been detected with foltering and sorting on “Voted”. Is it aslo a priority for beta-testing? If yes, I suggest this ticket can be closed and new one with filtering and sorting for “voted” should be created. Then it will be a work for BE: FYI @Michał Jankun 

_Comment from Jan Jaroszczak 24 October 2023 at 17:36_

@Pawel Mergist, I’ve talked it through with Bartek and the endpoint responsible for “Voted” tab is not prepared for filtering and sorting. Let’s discuss possible solutions on tomorrow’s call

_Comment from Pawel Mergist 24 October 2023 at 15:57_

NOT OK on Voted on: when a filter is cutting some category, previously selected cards are still visible. To reproduce type eg 4 and select category that found items are not beloging.

![Image](https://github.com/IntersectMBO/govtool/assets/134690345/7e0f881e-1860-4c2b-987d-a727266d1242)

_Comment from Pawel Mergist 24 October 2023 at 12:20_

TODO: check on some more items when env is working again

_Comment from Pawel Mergist 24 October 2023 at 12:19_

OK FOR:

- case insensitive search within proposal ids

- highlighting found phrase in proposal id

![Image](https://github.com/IntersectMBO/govtool/assets/134690345/2b7aee6e-e281-4d8f-b369-67c684039afd)

- invalid text when there are no results

![Image](https://github.com/IntersectMBO/govtool/assets/134690345/46db39ae-0474-4bd1-a31c-27be73e75730)

_Comment from Pawel Mergist 13 October 2023 at 10:51_
@Bartłomiej Sworzeń prioritise this or assign to @Jan Jaroszczak 

_Comment from Lorenzo Bruno 13 October 2023 at 10:33_
@Pawel Mergist I understand @Agnieszka Zytka is off until next week. 
Personally I would not consider them features, case sensitive search is a bug (no search should ever be case sensitive), the copy when no search results are found is simply wrong as it is related to something else (@Bartłomiej Łuczak @Katarzyna Grzonka missed to map that in figma, but it’s a small fix) and highlighting is how @Bartłomiej Łuczak did design the search function since the beginning (now, I don’t think it’s an issue if we don’t have it right now, however it’s still a missing element).

For the two bugs (copy for now results and case sensitivity) I do consider them as high priority for the completion of the last milestone (as without those fixes search feature doesn’t work)

_Comment from Pawel Mergist 13 October 2023 at 10:09_
This issue depicts 3 features:

- case insensitive search within proposal ids

- highlighting found phrase in proposal id

- invalid text when there are no results

**Comment by pmbinapps** [comment]
OK search ok
OK case insensitive 
NOT OK - phrase highlight



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/fd6e7cd1-b8b8-4987-8b80-5a71dd6f7911)

**Comment by Ryun1** [comment]
very old, lets close
