### ISSUE TITLE
Either DRep delegation fails, or the "this is your DRep" is not being displayed in the Drep list and delegation page

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#903]
## Context & versions
staging.sanchonet

## Loom video
https://www.loom.com/share/0b9ec6bb1a6e4a529338652a9fafe245?sid=daaee709-f963-49cc-86ab-b6d656e9b15c

## Steps to reproduce

  1. Delegate all ADA-power to Abstain
  2. Register as DREP
  3. Delegate to yourself

## Actual behavior
You cannot find 'your DRep' in the list
Delegation transaction fails

## Expected behavior
To be easily able to find 'you' if you're a DREP - there is a figma screen for this
To be able to delegate to yourself, and the interface will indicate as such

**Comment by pmbinapps** [comment]
@m-i-k-e  Regarding this 'You cannot find 'your DRep' in the list' when you paste in search drepid it should be found. In loom it looks like you are pasting a web address.

This 'Delegation transaction fails- tracked [here](https://github.com/IntersectMBO/govtool/issues/875)

**Comment by m-i-k-e** [comment]
@pmbinapps Yes, good spot, I pasted a URL. So it would of course fail. Thanks

**Comment by pmbinapps** [comment]
Overall experience of delegation is improved now @m-i-k-e please take look on [test-sancho](https://test-sanchonet.govtool.byron.network/connected/drep_directory).

You can also watch - Jam recording [here](https://jam.dev/c/3b6b8292-0b93-4444-ae4f-b5e370eb8ba8)
