### ISSUE TITLE
No option to delegate to myself as a drep after delegating to Abstain

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#904]
## Context & versions
staging.sanchonoe

## 
https://www.loom.com/share/2fbab1772d424095b0de8833c029b559?sid=7f22a55c-2a29-441a-977a-a5ddbb7cf313

## Steps to reproduce

  1. Delegate to abstain
  2. try to delegate to yourself

## Actual behavior
There is no delegate button on the 'your' dRep list 'card' or detail page, hence, not possible to self-delegate

## Expected behavior
Able to self-delegate

**Comment by m-i-k-e** [comment]
The missing delegation buttons on the 'self' drep appear probably all the time: https://www.loom.com/share/310530ffd4a040a795520cff3e45563d?sid=32d30642-f48d-48ca-9cd8-c129d18afe46

**Comment by pmbinapps** [comment]
'Yourself' label wrong place mentioned in  Loom comment (https://github.com/IntersectMBO/govtool/issues/904#issuecomment-2085656950) tracked [here](https://github.com/IntersectMBO/govtool/issues/913)

**Comment by pmbinapps** [comment]
@m-i-k-e is it the concept of 'Delegating to Myself' replaced by being 'Sole Voter'? 

DW: @MSzalowski

**Comment by m-i-k-e** [comment]
@pmbinapps @MSzalowski. The concept of sole voter and delegating to oneself are similar, but different. So someone might be a sole voter for a while, and then decide to become a Drep. In current govtool, they would have to become drep first, and then do a second action to delegate to themselves. Yes, this should be improved on the UX design side. But this is our current state.

To answer your question "is it the concept of 'Delegating to Myself' replaced by being 'Sole Voter'?" : No. However, if we make some User Experience tweaks, we can either mandatorily or optionally get the user to transfer their Voting Power when they become a Drep.

To add to the confusion, if I am a DREP, and then become a Sole Voter, my own voting power is automatically transferred to my Sole Voter account.

**Comment by pmbinapps** [comment]
To check showing Voting power value.

**Comment by JanJaroszczak** [comment]
for now, blocked by:
https://github.com/IntersectMBO/govtool/issues/957

**Comment by pmbinapps** [comment]
Original Issue - with US with this feature [here](https://github.com/IntersectMBO/govtool/issues/220)

**Comment by pmbinapps** [comment]
First attempt to see the button on DRep list was fine - Delegate button was shown - but transaction somehow failed with msg not enough founds - this is to be explored.
Recording [here](https://jam.dev/c/19f1ff8e-ce8f-4030-901a-72c3eaebebcf) - first sec Button is visible:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/ed1d85e8-4613-4f02-972e-5c7a34154597)



Next, button was not visible any more:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/9eb08926-ebbb-4196-b834-fecec7dd4a6b)

To reproduce:
1. Register as DRep
2. Observe if transaction was successful.
3. Copy you Drepid from card or Demo DApp
4. Go to DRep Explorer - Drep list and search for you DRep id - you should be Active with Delegate button

**Comment by m-i-k-e** [comment]
@pmbinapps Can you say why this is blocked?

**Comment by pmbinapps** [comment]
@m-i-k-e a deployment is not effective, fix is not visible on test, and dev envs, in the moment.

**Comment by m-i-k-e** [comment]
@pmbinapps I don't understand. If this is closed, then does that mean it won't be fixed?

**Comment by pmbinapps** [comment]
@m-i-k-e from event logs looks like it was auto-closed when a PR was made, from my perspective is in QA and is not finished yet.

@MSzalowski it could be that an Github action is Closing issues whey they are merged

**Comment by pmbinapps** [comment]
dev-sanchnet:
OK Now 


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/c51e6c26-f54f-433f-81f0-c9a2beb26100)

**Comment by pmbinapps** [comment]
OK ON test-sancho:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/78ad4197-49d4-4197-be90-c1d77b72a83e)

**Comment by MSzalowski** [comment]
> @MSzalowski it could be that an Github action is Closing issues whey they are merged

Yes, we should have the config that doesn't move issues to done once they are merged. But this is not as important as the integration parts that we have currently in scope

**Comment by MSzalowski** [comment]
@pmbinapps should that still be assigned to you?
