### ISSUE TITLE
When you are a DRep, your listing in the explorer needs to be noticeable, and pinned to the top of the DRep list. There is a design for this in Figma

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#907]
## Context & versions
staging.sanchnet

## Loom video:
https://www.loom.com/share/aef14c1241a145dbb8668d7c9e2872f2?sid=3374ad55-091c-419a-9a9b-7f6345a5c99b

## Steps to reproduce

  1. Become a Drep
  2. Look for yourself in the Drep directory

## Actual behavior
You can't find yourself other than by searching for your exact Drep ID

## Expected behavior
You can find yourself as per the design in Figma: https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=9342%3A242707&mode=design&t=YS0TICiCourCfGTj-1

**Comment by pmbinapps** [comment]
Looks like omitted in latest iterations:

Should be like this Figma [design](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=9342-242707&mode=design&t=JeAnBO1ZgqVvtAQd-0):

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/e6eb6690-aaf2-4af7-a34e-7ba52bc2779b)

**Comment by pmbinapps** [comment]
This seems not to be working as expected:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/fe358b11-6318-43ad-a16c-6d71f66dc103)

**Comment by m-i-k-e** [comment]
@pmbinapps are you going to reopen this issue?

**Comment by pmbinapps** [comment]
@m-i-k-e Close - is related to part of work made in this entry '[JanJaroszczak](https://github.com/JanJaroszczak)
closed this as [completed](https://github.com/IntersectMBO/govtool/issues?q=is%3Aissue%20state%3Aclosed%20archived%3Afalse%20reason%3A%22completed%22) in [#961](https://github.com/IntersectMBO/govtool/pull/961)[5 days ago](https://github.com/IntersectMBO/govtool/issues/907#event-12755270944)'. 

I'm not able to modify this.

Status of issue is In QA now, it will be finished, when its Status is set to Done

**Comment by pmbinapps** [comment]
OK NOW - on dev-sancho

* Current - 'Yourself' Drep pinned to top of DRep list

NOTE: Drep list is pinned for all Filter selections. 'Yourself' filter not implemented yet



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/1d5d36fd-6078-40ce-9a74-4b776e89c944)

**Comment by pmbinapps** [comment]
OK on test-sancho - DRep item pinned to top of list in every case (any filter on)
NOTE: New option Yourself not delivered/handled yet


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/0aaf419b-9b62-4820-8491-a13fb7e61e30)


Compare with recording.
https://jam.dev/c/0b0fb3a7-6437-43b3-9c3c-52a102b56b73
