### ISSUE TITLE
Registed as a DRep, but dashboard says "Vote on Governance Actions as a Sole Voter"

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#911]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Become Drep
  2. Look at dashboard
  3. Look at Sole Voter Card

## Actual behavior
Card says: "Vote on Governance Actions using..."

## Expected behavior
Card should say:" **Register** to Vote on Governance Actions using..."

The wording is confusing, but this change will fix it.

**Comment by kgrzonka** [comment]
@m-i-k-e 
I changed the text on Sole Voter Card in view with Drep registration in Progress card and after. 
Should I change the copy everywhere (I can change this in design system) or only here? 

https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/branch/c1Yn6bSFqualsfyvnmJ906/Voltaire---GOV-TOOL?type=design&node-id=7838%3A264475&mode=design&t=Tmsv9MOUQO4Ntqzb-1

**Comment by m-i-k-e** [comment]
Yes, perfect. Thanks

**Comment by m-i-k-e** [comment]
Ready to merge in Figma

**Comment by m-i-k-e** [comment]
@kgrzonka Can you check the branch again re: my Slack message?

**Comment by m-i-k-e** [comment]
I have done this, no need to work on it @kgrzonka

**Comment by m-i-k-e** [comment]
@MSzalowski please make this text change.

**Comment by MSzalowski** [comment]
Assigned to current iteration

**Comment by Sworzen1** [comment]
I've fixed it but on design it doesnt exist in Direct Voter [figma reference](https://www.figma.com/design/c1Yn6bSFqualsfyvnmJ906/%23911?node-id=7672-80163&t=G56Le1g6v6CIx5pZ-4)

**Comment by pmbinapps** [comment]
This should be in IN QA after deployment.

**Comment by pmbinapps** [comment]
OK vs [design](https://www.figma.com/design/c1Yn6bSFqualsfyvnmJ906/%23911?node-id=7672-80163&t=G56Le1g6v6CIx5pZ-4):



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b5a95bf3-8b22-4591-9e9f-d3989ff7b45d)
