### ISSUE TITLE
DRep explorer - DRep list - label 'Yourself' should be placed next to the status

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#913]
Noticed by @m-i-k-e in this [issue](https://github.com/IntersectMBO/govtool/issues/904#issuecomment-2085656950).

When user is registered as DRep in DRep list - label "Yourself" is placed like below:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/2dda742f-35e6-4047-b88f-b62150bf8762)

Should be like below:

Figma design [here](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=9342-304646&mode=design&t=x7KSTDYFq0kEsc8X-0).

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/34b75476-f8c1-466a-8090-7fdf9052fd58)

**Comment by pmbinapps** [comment]
OK NOW


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/f2cbd814-0c3b-48cc-9def-b06f1f2ec08b)

**Comment by m-i-k-e** [comment]
This works ok
