### ISSUE TITLE
Error on closing DRep submission modal, and then clicking submit again, in DRep reg flow

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#915]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Go through Drep registration to the point where you have an external url for your metadata, paste it in, and click submit
  2. Dismiss the Modal
  3. Click "Submit" again

## Actual behavior
You get this modal
<img width="235" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/cf1f1a88-749b-407e-ae70-2ed4ff97b816">

## Expected behavior

1. Either the submit button would be disabled
2. or the modal should show 'in progress'
3. or the screen should show 'in progress' and submit button disabled

## Loom video
https://www.loom.com/share/041fce3245dd4854b2fbb5b39f01442f?sid=4babe0e6-938c-4917-8417-61a7a6bc24d6

**Comment by kgrzonka** [comment]
@m-i-k-e 

Hmm I don't know if I understood correctly but in our flow used should go to view with dashboard with popup (https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7145%3A39402&mode=design&t=x1LGQmLXUFLTgRRi-1) and then closing the popup and see dashboard with DRep registration In Progress card and then finished screen with green toast and finished state card (https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7838%3A145859&mode=design&t=x1LGQmLXUFLTgRRi-1). This is the flow when everything went well. 

In case with problem, for example "Your External Data Does Not Match the Original File" and clicking "Go to data edit screen" user should go to https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=12550%3A88915&mode=design&t=x1LGQmLXUFLTgRRi-1 .

**Comment by m-i-k-e** [comment]
@l-br1 I think that this is a real bug. @kgrzonka The problem arises when the user closes the modal with the "X". When they do, GT acts like the user hasn't registered, and I can fill out the form and submit it again. I should be locked out of the form until the transaction has gone through. If I have already registered (i.e. if I've waited at this page so long that the transaction has gone through), I need to see a message (this is be a separate issue) that tells me that I've already registered.

The reason I asked you to look at it is because I thought that you could look at the flow and see if:

1. There was already a path for a user clicking the "X", but the devs just didn't see it in Figma - so you could point this out
2. If no design in Figma, create a solution for this situation.

PS: I have just tried to retest this, and I have got another bug, or issue. I've slacked Michal and Adrian so they should be looking at it. Here is the loom video in case you're curious: https://www.loom.com/share/de772e5b85d549618ada4aca4e80153b?sid=480db51a-9498-4315-8d7d-0d0713ffc279

**Comment by m-i-k-e** [comment]
PS Again. @kgrzonka please wait to work on this until after Adrian/Michal get back. So this is on hold for today. I will revisit and comment when they have cleared up the bug.

**Comment by m-i-k-e** [comment]
Actually, I will ask them here:

@MSzalowski Can you please look at this video: https://www.loom.com/share/de772e5b85d549618ada4aca4e80153b?sid=480db51a-9498-4315-8d7d-0d0713ffc279

It seems another issue is blocking me from looking at this.

**Comment by pmbinapps** [comment]
@m-i-k-e DRep registration works fine in the moment, just recharge your wallet, or better create fresh one as cardano node was bumped up.



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b207228e-2f70-47b1-9e92-ebde144c79e0)
