### ISSUE TITLE
No Confidence needs Voting Power and Info button when delegated to - same goes for Abstain

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#917]
## Context & versions
staging.sanchonet & GovTool Figma designs

## Steps to reproduce

  1. Delegate to Vote no
  2. Look at Vote No row on drep explorer

## Actual behavior
The voting power and buttons are missing

## Expected behavior
The Automated voting options need to show both the info buttons and the 'accumulated' voting power as in other drep listings.

## Loom video https://www.loom.com/share/0c3a71e0336f4c1988f2b50a387eb44b?sid=6c209272-407d-4859-9a6c-e6a23a65d4ba

**Comment by kgrzonka** [comment]
Fixed:
https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=12181%3A91756&mode=design&t=ACqzr7VudFd51p5r-1
https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=12181%3A93328&mode=design&t=ACqzr7VudFd51p5r-1

Question - "Info" button should disappear too ?
@m-i-k-e

**Comment by kgrzonka** [comment]
@m-i-k-e 

https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/branch/7cPRUfanIc1vF9GOv5cOFf/Voltaire---GOV-TOOL?type=design&node-id=10029%3A93137&mode=design&t=l6Usq7ZDAmRPVKiX-1

**Comment by m-i-k-e** [comment]
@m-i-k-e Please check for merge

**Comment by m-i-k-e** [comment]
@kgrzonka I merged this change and I can't see it in Figma. Could you please check and find it? If it's not done, could you please create a new branch, make the change, and ping me so I can check it and merge it?

**Comment by kgrzonka** [comment]
@m-i-k-e 
I created new branch and I made all the changes. These views only appear in flow from the side:
https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/branch/OEOot4ypU9xEMTGhgRVpLM/Voltaire---GOV-TOOL?m=auto&node-id=10029%3A93137&t=dTZ6isTqjr8MAzvX-1

**Comment by m-i-k-e** [comment]
@MSzalowski Ready for Dev, and merged into main Figma file https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=13156%3A89243&t=2SZ66T2eZnuLZyWR-1
