### ISSUE TITLE
Items on Abstain and No Confidence dropdown implemented different than the design in Figma

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#918]
## Context & versions
staging.sanchonet

## Steps to reproduce
  1. Delegate to No Confidence
  2. Go to Dashboard

## Actual behavior
The design is different than the one in Figma in several ways

1. It is not expanded automatically, it should be
2. It has a 'pill' on the closed Combi box that says "no confidence" - there is no design for this
3. It has a 'selected' pill on the expanded combi box, again this is not in the designs

## Expected behavior
Combo box should be expanded like in Figma.

## Loom video
https://www.loom.com/share/ce2603435b5a4147a320de9a86c316a3?sid=d0f7e4f8-2108-4040-82dd-68e2519a08ec

**Comment by pmbinapps** [comment]
Issues mentioned in loop:
- 'Wallet connected' msg - as a bug - it occurs just after reload of page - this is normal behaviour after Wallet connect if need to be removed in this case, decision is needed (@MSzalowski @Sworzen1 )


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/e42824dd-01eb-4e2c-9106-a9d51c8b995d)

- 'NO CONFIDANCE' - label - should not be used - no such design. There is also no other design in( DRep explorer [section](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7079-30954&mode=design&t=wySJeXjRZaiJE8v9-4) ) screen how it should be presented. @m-i-k-e please add a link or screenshow how it should be shown


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/a2a4cf8e-c85d-4dea-a0ed-39ab2e0990aa)

- 'Selected' label usage the same as above - not on design. Could find how this should be shown in DRep explorer section

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/67edc7ff-3257-4874-b214-aba99780215b)

**Comment by m-i-k-e** [comment]
@pmbinapps @MSzalowski Here is the figma design: https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=12181%3A93328&mode=design&t=ALxcq4IdeSpWx8J0-1

Please note: it is missing the "Voting Power and buttons. This is an omission in Figma. Could you add it, or do you need a design to reference?

**Comment by m-i-k-e** [comment]
The missing info on this has been raised as a bug already.

**Comment by m-i-k-e** [comment]
@pmbinapps Why is this blocked?

**Comment by pmbinapps** [comment]
OK for Abstain


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/961208d0-9e87-4c09-a52d-0b593829d668)


OK for No confidance




![Image](https://github.com/IntersectMBO/govtool/assets/82152577/1ce91212-5149-4264-92f2-b4dfeb6dcbe0)





Jam [recording](https://jam.dev/c/9bd989b7-84f0-474a-bab8-c149e8fa954e)

**Comment by pmbinapps** [comment]
OK on test-sancho - item is expanding itself when state of transaction is updated:

https://jam.dev/c/5c663751-869f-4b4a-b43c-64c8c485d28c

**Comment by MSzalowski** [comment]
@pmbinapps Should this still be assigned to you?
