### ISSUE TITLE
Delegating to No confidence still shows DRep delegation for a while, Automated Voting options 'accordion' is closed, should be open.

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#919]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Delegate to a Drep
  2. Delegate to No Confidence

## Actual behavior vs expected behaviour

1. Delegation starts and
2. The interface still shows (while delegation is in progress) that you are delegated to a Drep. This should disappear as soon as the user presses the delegate button
3. When a user is delegated to Abstain or No confidence, the 'combo' box that contains these options should be open. This also should apply when the delegation is in progress.

## Expected behavior
As above, also see loom video.

## Loom video
https://www.loom.com/share/c652a0543a534c4dafcf2396cc918500?sid=4981ff20-9f4b-4dd3-a837-26b6766347cb

**Comment by pmbinapps** [comment]
Two visual aspect mentioned in loop:
- Automated Voting option card should stay unfolded after delegation
- If  You have delegate do a DRep and change to No or Abstain this card should be updated earlier - please refer to loom for [details](https://www.loom.com/share/c652a0543a534c4dafcf2396cc918500?sid=4981ff20-9f4b-4dd3-a837-26b6766347cb)


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/8938c103-71df-4079-a5d6-32a3503c2978)

**Comment by MSzalowski** [comment]
@m-i-k-e In that case could you please clarify a bit states of this badges (when they should be displayed and why)
Based on the issue and [figma design](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7825-90067&mode=design&t=WTIJhg5K1YA2Zvai-4).

**Comment by pmbinapps** [comment]
The interface still shows (while delegation is in progress) that you are delegated to a Drep. 
**OK NOW** :This should disappear as soon as the user presses the delegate button


**TODO**: When a user is delegated to Abstain or No confidence, the 'combo' box that contains these options should be open. 
This also should apply when the delegation is in progress.

**Comment by JanJaroszczak** [comment]
Fully fixed with this PR: https://github.com/IntersectMBO/govtool/pull/1013

**Comment by pmbinapps** [comment]
OK NOW:

-  Delegation card disappears when Abstain, No confidance chosen
- Abstain - No confidance is unfolded when a delegation is in progress or activated

Jam [recording](https://jam.dev/c/260d0088-245f-4d8d-8732-6c919b10e2d3)

**Comment by m-i-k-e** [comment]
This works fine now: https://www.loom.com/share/fabf24eeeac74a479bd3a404fede8069?sid=8329fe5c-840e-4dbd-bce0-24162494ced3
