### ISSUE TITLE
Multiple bugs on Delegation flow

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#920]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Have ada in wallet, and not be delegated to any Drep
  2. Pick a Drep and delegate

## Actual behavior
Toast immediately says "Your voting power has been successfully delegated" - but this is not true

## Expected behavior
Toast is showing up in the wrong order. I expect that this message should say something like "Delegation in progress"

<img width="666" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/ace2e1c1-1e61-4365-b4b8-3b84a57ad4cd">

## Steps to reproduce

  1. After delegation above has initiated, and while it's in progress, click "Dashboard" in the menu.
  2. Go to the dashboard
  3. Click the arrow next to the 'Drep_name" in the "Delegation in Progress" card
  4. You will go to the DRep detail page of the Drep to whom you are currently delegating
  5. Click the "Back to the List" link in the upper right corner of the screen
  6. You will go back to the DRep list

## Actual behavior
User is sent to the Drep list, however, they didn't come from there. While the page is called 'the list' the user can't go 'back' to it, as they have not come from it.

## Expected behavior
Links will have the proper context for users, and will 'know' where they came from. A possible solution would be just to have the links say "Back", and then GovTool would be able to take the users back to where they came from.

## Steps to reproduce

  1. Go to Dashboard, refresh the screen a few times

## Actual behavior
Repeated showing of 'toasts', including 'wallet connected', Transaction Pending, etc. These look strange, and there is no need to remind users that their wallet is connected. This is a bug

## Expected behavior
Users will see the "Wallet Connected" toast only when appropriate" i.e. just after the wallet has successfully connected to GovTool

## Steps to reproduce

  1. Go to Dashboard, refresh the screen a few times

## Actual behavior
Toast shows that the delegation transaction has failed

## Expected behavior
Transaction has gone through ok, and error messages are correct. What I mean is at this time, I can't tell if:

1. The error is that the transaction has failed
2. or the system is showing me an incorrect toast - as there were several incorrect toasts already shown

## Steps to reproduce

  1. STay on dashboard, wait until you see the 'transaction failed' toast
  2. look at Drep ID in Delegated card
  3. It is not the same as the one delegated to
  4. It is truncated and is not a proper DRep ID
  5. When you click on it, you go to a page where nothing happens (this is a seperate bug due to no '404' page)

## Actual behavior
Drep ID has changed from one that has been delegated to
Link does not take you to the Drep that you've delegated to 
Link does not take you to an existing page

## Expected behavior
Link has the correct DRep ID
Link, when clicked, takes you to the correct page, which is the DRep you delegated to.

## Steps to reproduce

  1. Click link to DRep on dashboard

## Actual behavior
The page changes to Drep Directory, and a spinner spins endlessly

## Expected behavior
There should be a page not found error - as there is no DREp with this ID. This happens if any bad url is passed to this page

**Comment by pmbinapps** [comment]
* Other issue: 'Back to list issue' - 
Delegation error tracked [here](https://github.com/IntersectMBO/govtool/issues/875)

**Comment by pmbinapps** [comment]
'Wallet connected' info - rather should stay:
```
Bug 3 - on Video from 2:12 to 3:13
Steps to reproduce
Go to Dashboard, refresh the screen a few times
```

**Comment by JanJaroszczak** [comment]
- Bug 1 and 4 done in in this PR: https://github.com/IntersectMBO/govtool/pull/947
- Bug 2 done in PR: https://github.com/IntersectMBO/govtool/pull/952
- Bug 5 and 6 done earlier by someone else
- Bug 3 was decided not te be treated as a bug

**Comment by pmbinapps** [comment]
Transaction related errors and corresponding updates on Drep explorer and Dashboard are fixed by:

https://github.com/IntersectMBO/govtool/issues/865
https://github.com/IntersectMBO/govtool/issues/875
https://github.com/IntersectMBO/govtool/issues/897

No showing 'Wallet connected' was decided to keep on [review](https://github.com/IntersectMBO/govtool/issues/920#issuecomment-2098479210) meeting - THIS TO DECIDE

**Comment by pmbinapps** [comment]
Duplicate of some symptoms mentioned here https://github.com/IntersectMBO/govtool/issues/920
