### ISSUE TITLE
DRep delegation incorrect DRep card

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#925]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Delegate to a Drep on the Drep list page
  2. When the action starts, the Drep you are delegating to you is supposed to show up at the top of the screen. Look at the top of the screen, and compare the Drep Id to the one you delegated to.

## Video:
https://www.loom.com/share/5809a62bd658421d8c314f7be710e64c?sid=5dcae875-e665-4713-afaa-c97413027ec0

## Actual behavior
The incorrect DRep shows up at the top of the screen, then after a while, the correct one shows up

## Expected behavior
The Drep you are delegating to should show up at the top of the screen

**Comment by pmbinapps** [comment]
Related to handling of transaction status and presenting transitions of states:
- tracked [here](https://github.com/IntersectMBO/govtool/issues/865), [here](https://github.com/IntersectMBO/govtool/issues/875)

**Comment by pmbinapps** [comment]
This is seems to work now when delegating and nothing (no reload, lag) occurs - [recording](https://jam.dev/c/821d4303-35ed-4bc4-ab62-a5ac24a3ff98)

But when a reload is made in the middle of processing of transaction card with current delegation is updated before delegation transaction ends - compare with [recording](https://jam.dev/c/a4b67c86-82cc-4858-99b9-8f89832d3719) 0:57 sec

**Comment by pmbinapps** [comment]
@m-i-k-e make the card move from bottom to top - expand this visual aspect

**Comment by l-br1** [comment]
- replace the old DRep card with the in progress card. If the transaction fails revert to old DRep 

This solves the problem of the bug and it improves the usability (avoiding leaving the card randomly in the list)

**Comment by pmbinapps** [comment]
OK on test sancho:

Jam [recording](https://jam.dev/c/c57483da-fa26-48e9-b711-1026fba2586d)
