### ISSUE TITLE
DRep panel needs to be clickable, not just arrow, DRep link to page doesn't work.

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#926]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Delegate to a drep
  2. Go to dashboard
  3. click on the drep part of the delegation card

  
## Video:
https://www.loom.com/share/036544d88d474b95900ba43584b51883?sid=a44192d0-f2b1-4b6f-a079-ae9f800a5172
## Actual behavior
Nothing happens

## Expected behavior
You will go to the DRep detail page

## Steps to reproduce

  1. Delegate to a drep
  2. Go to dashboard
  3. click on arrow on the drep part of the delegation card

## Actual behavior
You go to the DRep area, but no page is shown, just a spinner

## Expected behavior
You will go to the DRep detail page

## Note:
This looks like two bugs: One is that the DRep Id is wrong (you can see it's too short), and the other is that there is no '404' page, and therefore the spinner just keeps going.

**Comment by pmbinapps** [comment]
1. New feature - white are with Drep_name should be clickable:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/d653bcae-d560-473d-bab6-3e9ee06a3bc1)

2. Endless Loader when clicked on > - tracked [here](https://github.com/IntersectMBO/govtool/issues/866)

**Comment by pmbinapps** [comment]
OK NOW

https://jam.dev/c/5b95e536-fe00-4cb4-ab46-609195c52d94
