### ISSUE TITLE
no 404 page in drep directory

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#928]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Go to a Drep detail page
  2. Add any character to the end of the url
  3. hit return
## Loom video
https://www.loom.com/share/709bf5a3f1ca44a997938f05ea93c90c?sid=8ae0da24-5e01-4048-87f0-18a5962a6cc4

## Actual behavior
You go to a page with an endless spinner

## Expected behavior
You should have a page not found or Drep not found error

**Comment by pmbinapps** [comment]
Valid bug - page not found is not shown, instead endless loader is shown.

**Comment by pmbinapps** [comment]
Now loader is shown:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/f27116b6-5807-4856-8798-f822586b64d3)

Request should return similary like GA not found.

**Comment by m-i-k-e** [comment]
@pmbinapps @MSzalowski We will get a design made for this.

**Comment by pmbinapps** [comment]
OK - Drep - not found shown instead:



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/a9f56e4e-b390-4f9d-85bd-83410a69126d)
