### ISSUE TITLE
DRep links are appended to govtool url

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#929]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Go to a Drep detail page
  2. Click a link

## Video
https://www.loom.com/share/7959bb5dfd97489fab44db9dbb108538?sid=7ea7902c-a3da-4e74-853a-4884d4cebf02
## Actual behavior
Link tries to find url within govtool, i.e. the external link is being appended to the govtool url. No page is found

## Expected behavior
User should see external page

**Comment by pmbinapps** [comment]
OK External link is opened

TBC : @m-i-k-e Should be in this case there any modal view to confirm if to visit external page?

**Comment by pmbinapps** [comment]
OK  on test-sancho
