### ISSUE TITLE
Re-delegate to same DRep, should not be possible

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#931]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Delegate to a DRep
  2. When transaction is finished
  3. Delegate to the same DRep

## Actual behavior
It seems that you can delegate again to the same DRep

## Expected behavior
GovTool should not permit this, and tell the user that they have already delegated to this DRep

**Comment by pmbinapps** [comment]
Decision needed how to handle such case (@MSzalowski ) - user delegated to a DRep and still sees Delegate button on its Details page, which he/she could press and delegate again:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/4340c36e-7a7a-4152-b720-bb6df1aa9fb2)

**Comment by m-i-k-e** [comment]
@MSzalowski @pmbinapps what should happen is that GovTool needs to say that this has already been delegated to. This should be assigned to design for the requisite screens. You can assign it to me.

**Comment by JanJaroszczak** [comment]
I've fixed it already in this PR: https://github.com/IntersectMBO/govtool/pull/985

**Comment by pmbinapps** [comment]
OK NOW - button not visible on Drep details after delegation

https://jam.dev/c/3bdb0104-00a0-4468-b2db-e14dee43696d

**Comment by MSzalowski** [comment]
@pmbinapps Should it still be assigned to you?

**Comment by m-i-k-e** [comment]
This is fixed now
