### ISSUE TITLE
Padding on 'chips' on DRep list too large 

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#933]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Look at Drep Directory

## Actual behavior
Padding on buttons doesn't match Figma design

**Comment by Sworzen1** [comment]
double https://github.com/IntersectMBO/govtool/issues/877

**Comment by pmbinapps** [comment]
Retest [here](https://github.com/IntersectMBO/govtool/issues/877)

**Comment by m-i-k-e** [comment]
Closing, as duplicate of #877
