### ISSUE TITLE
padding on buttons too small on DRep list

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#934]
## Steps to reproduce

  1. Look at DRep directory

## Actual behavior
Padding doesn't match Figma

## Expected behavior
Padding should match Figma

**Comment by pmbinapps** [comment]
Padding to correct on DRep list:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/63288575-163c-4339-b102-d5b887fd0e7c)

**Comment by Sworzen1** [comment]
double https://github.com/IntersectMBO/govtool/issues/878

**Comment by pmbinapps** [comment]
OK NOW, checked [here](https://github.com/IntersectMBO/govtool/issues/878#issuecomment-2103358053)

**Comment by m-i-k-e** [comment]
Closing, duplicate of #878
