### ISSUE TITLE
Drep listing alignment and numbers don't line up

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#935]
## Context & versions
staging.sanchonoet

## Steps to reproduce

  1. Go to DRep directory list

## Actual behavior
Voting Power amounts don't line up, and six decimal places are shown

## Expected behavior
Voting power should line up, and no numbers past the decimal should be shown.

**Comment by pmbinapps** [comment]
Alignment errors for DRep id, Voting power on DRep list (to find issue related to this @pmbinapps )


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/99504e4f-438a-4458-abe8-355f9540ab68)

**Comment by Sworzen1** [comment]
double https://github.com/IntersectMBO/govtool/issues/879

**Comment by pmbinapps** [comment]
Fixed [here](https://github.com/IntersectMBO/govtool/issues/879#issuecomment-2101291584)

**Comment by m-i-k-e** [comment]
Closing as a duplicate of #879
