### ISSUE TITLE
Can't become sole voter

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#936]
## Context & versions
staging.sanchonet Demos Wallet 1.8.1

## Steps to reproduce
  1. Already registered as a DRep, and delegated to a different Drep (Don't know if these are essential pre-requsites)
  2. Try to become sole voter by clicking "register" button
## Actual behavior
Strange dialog comes up: 
<img width="263" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/5a44f3ac-548e-4a0d-a5a2-b34e16334c61">

## Expected behavior
Be able to become sole voter

**Comment by MSzalowski** [comment]
Then I'll move it to In QA for you to retest it

**Comment by pmbinapps** [comment]
dev-sancho:

Delegation to Direct voter worked fine recently.



https://jam.dev/c/43a6afd8-e2d1-4019-a455-d813e91790fd

**Comment by m-i-k-e** [comment]
Blocked from retesting by #1160

**Comment by m-i-k-e** [comment]
Note: I can become a Direct Voter, just not one _after_ becoming a DRep
