### ISSUE TITLE
[BUG]  Missing Test IDs

### ISSUE THREAD

**Issue by NabinKawan** [IntersectMBO/govtool#937]
**Description:**
Several components across various pages lack proper test IDs, impeding effective testing and automation.

### DRep Registration Page:
- **Page URL:** /register_drep
![Registration Page](https://github.com/IntersectMBO/govtool/assets/43606623/88be6fc4-147c-4769-8744-497167a7b14a)

  - The `testId` for the "Continue" button is incorrectly set as `retire-button`; it should be `continue-button`.

  - Test IDs for form fields in the DRep registration form are missing:
    - `add-link-button` for the "Add Link" button.
    - `name-input` for the name input field.
    - `email-input` for the email input field.
    - `bio-input` for the bio input field.
    - `link-input` for the link input field.

![DRep Form Fields](https://github.com/IntersectMBO/govtool/assets/43606623/69c2f464-31b9-4820-95cd-6a3e75bd92d8)

  - The test ID for the "Register" button is incorrectly set as `retire-button`; it should be `register-button`.

![Register Button](https://github.com/IntersectMBO/govtool/assets/43606623/532af7f5-a831-4342-95f6-b29e373ab5ae)

### Delegation Page:
- **Page URL:** [Provide URL]
![image](https://github.com/IntersectMBO/govtool/assets/43606623/9c91e4c0-9114-4f62-a4b9-261ba1dcc3f3)
  - Test IDs are missing for:
    - `delegation-options-dropdown`.
    - `signal-no-confidence-card`.
    - `abstain-delegation-card`.

### Governance Action Details Page:
![image](https://github.com/IntersectMBO/govtool/assets/43606623/9341c98e-7798-444c-8b46-c33258d2ffb6)
![image](https://github.com/IntersectMBO/govtool/assets/43606623/db3caf67-4ceb-47dc-95c3-f1d42dc4974d)
- Test ID for the "Provide Context" button is missing.
- Test ID for the "Provide Context" input is missing

### Retirement Page:
![image](https://github.com/IntersectMBO/govtool/assets/43606623/7b1410d9-26f9-4962-b869-220e1b29513b)
- The test ID for the "Continue" button is incorrect; it should be `continue-retirement-button`.

### Dashboard:

![Image](https://github.com/IntersectMBO/govtool/assets/43606623/29713038-16bd-4b26-b484-37590b00be11)

- Incorrect test ID for "View DRep Directory".
- Inside the `dRep-card`, the `dRep-id-display-card` test ID is conflicting with the sidebar's `dRep-id-display-card`. Suggest creating distinct test IDs, such as `dRep-id-display-card-dashboard` for the dashboard.
![image](https://github.com/IntersectMBO/govtool/assets/43606623/a06d7d43-903a-48bf-a254-02369e0242b1)

### Mobile

![Image](https://github.com/IntersectMBO/govtool/assets/43606623/41125ee5-95be-4ae3-a50b-d2b0ac71b957)

- test ID missing for `open-drawer-button` for logged out state 

**Important:** Please ensure to add proper test IDs for all interactive elements to facilitate testing and automation.

**Comment by pmbinapps** [comment]
For page:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/125909b8-4b7a-4e0f-9526-5a9b4afbc7b6)



data-testid="Back-to-dashboard-link"
data-testid="ArrowBackIosIcon"
data-testid="name-input"
data-testid="this-is-name-that-will-be-shown-on-your-drep-profile-error"
data-testid="email-input"
data-testid="bio-input"
data-testid="some-sentence-about-yourself-error"
data-testid="link-input"
data-testid="add-link-button"
data-testid="back-button"
data-testid="continue-button"
data-testid="privacy-policy-footer-link"
data-testid="term-of-service-footer-link"
data-testid="help-footer-button"
data-testid="feedback-footer-button"


Drep explorer page with delegation part:

data-testid="logo-button"
data-testid="dashboard-link"
data-testid="drep-directory-link"
data-testid="governance-actions-link"
data-testid="guides-link"
data-testid="faqs-link"
data-testid="disconnect-button"
data-testid="InfoOutlinedIcon"
data-testid="drep1063u9e7ukcdw3lp4ssgxrufg9ds8wvyq3xmlhruwlw305grfrf0-copy-id-button"
data-testid="automated-voting-options-accordion"

Dashboard:

data-testid="logo-button"
data-testid="dashboard-link"
data-testid="drep-directory-link"
data-testid="governance-actions-link"
data-testid="guides-link"
data-testid="faqs-link"
data-testid="disconnect-button"
data-testid="InfoOutlinedIcon"
data-testid="voting-power-delegation-status"
data-testid="ArrowForwardIosIcon"
data-testid="delegate-learn-more-button"
data-testid="delegate-to-another-drep-button"
data-testid="voting-power-delegation-status"
data-testid="register-button"
data-testid="register-learn-more-button"
data-testid="voting-power-delegation-status"
data-testid="retire-as-sole-voter-button"
data-testid="learn-more-button"
data-testid="voting-power-delegation-status"
data-testid="view-governance-actions-button"
data-testid="learn-more-governance-actions-button"
data-testid="voting-power-delegation-status"
data-testid="propose-governance-actions-button"
data-testid="learn-more-button"
data-testid="privacy-policy-footer-link"
data-testid="term-of-service-footer-link"
data-testid="help-footer-button"
data-testid="feedback-footer-button"
data-testid="delegation-options-dropdown"
data-testid="abstain-from-every-vote-info-button"
data-testid="abstain-from-every-vote-delegate-button"
data-testid="signal-no-confidence-on-every-vote-info-button"
data-testid="signal-no-confidence-on-every-vote-delegate-button"
data-testid="SearchIcon"
data-testid="search-input"
data-testid="filters-button"
data-testid="sort-button"
data-testid="drep1qzw234c0ly8csamxf8hrhfahvzwpllh2ckuzzvl38d22wwxxquu-copy-id-button"
data-testid="drep1qzw234c0ly8csamxf8hrhfahvzwpllh2ckuzzvl38d22wwxxquu-view-details-button"
data-testid="drep1qzw234c0ly8csamxf8hrhfahvzwpllh2ckuzzvl38d22wwxxquu-delegate-button"
data-testid="drep1qy6m9ntcsmq9qex6raha0x904fknajstsy7d3wpquwe67lmmnvh-copy-id-button"
data-testid="drep1qy6m9ntcsmq9qex6raha0x904fknajstsy7d3wpquwe67lmmnvh-view-details-button"
data-testid="drep1qy6m9ntcsmq9qex6raha0x904fknajstsy7d3wpquwe67lmmnvh-delegate-button"
data-testid="drep1q9rg69aquphsns4tl2n75m8n2vemxgjrnrw435cgsh8lu6fyps8-copy-id-button"
data-testid="drep1q9rg69aquphsns4tl2n75m8n2vemxgjrnrw435cgsh8lu6fyps8-view-details-button"
data-testid="drep1q9rg69aquphsns4tl2n75m8n2vemxgjrnrw435cgsh8lu6fyps8-delegate-button"
data-testid="drep1qdmu50p35u8aupu89c00v7fzkplj54yk2m7uzhes2sgmvxdqzsy-copy-id-button"
data-testid="drep1qdmu50p35u8aupu89c00v7fzkplj54yk2m7uzhes2sgmvxdqzsy-view-details-button"
data-testid="drep1qdmu50p35u8aupu89c00v7fzkplj54yk2m7uzhes2sgmvxdqzsy-delegate-button"
data-testid="drep1qjxfjlftmt7gyr50mtmk4mw6d4rl3zrdrfdt964cgvz3gphes2n-copy-id-button"
data-testid="drep1qjxfjlftmt7gyr50mtmk4mw6d4rl3zrdrfdt964cgvz3gphes2n-view-details-button"
data-testid="drep1qjxfjlftmt7gyr50mtmk4mw6d4rl3zrdrfdt964cgvz3gphes2n-delegate-button"
data-testid="drep1qnfx6nqvadycrvcl43xdrlre85npfts7llj0z8nn2ytx2h8nwv2-copy-id-button"
data-testid="drep1qnfx6nqvadycrvcl43xdrlre85npfts7llj0z8nn2ytx2h8nwv2-view-details-button"
data-testid="drep1q4kevzwntlr7724zz5m9t8tnfn35msqauwn8sfrc89rduqmkplx-copy-id-button"
data-testid="drep1q4kevzwntlr7724zz5m9t8tnfn35msqauwn8sfrc89rduqmkplx-view-details-button"
data-testid="drep1q4kevzwntlr7724zz5m9t8tnfn35msqauwn8sfrc89rduqmkplx-delegate-button"
data-testid="drep1qkszl23wfw6kxxuzvsucs07c5ycx40q24r2nl2qmf84k7re5muj-copy-id-button"
data-testid="drep1qkszl23wfw6kxxuzvsucs07c5ycx40q24r2nl2qmf84k7re5muj-view-details-button"
data-testid="drep1qc76sc0stectv3krel2xphk3pw3hdzuc59p639mz4mme6wwudjp-copy-id-button"
data-testid="drep1qc76sc0stectv3krel2xphk3pw3hdzuc59p639mz4mme6wwudjp-view-details-button"
data-testid="drep1qmehvg7vxh9tgwy6rgxenauc3j6hql6nkjrthvcjm457kktpj9k-copy-id-button"
data-testid="drep1qmehvg7vxh9tgwy6rgxenauc3j6hql6nkjrthvcjm457kktpj9k-view-details-button"
data-testid="drep1qmehvg7vxh9tgwy6rgxenauc3j6hql6nkjrthvcjm457kktpj9k-delegate-button"
data-testid="show-more-button"
data-testid="privacy-policy-footer-link"
data-testid="term-of-service-footer-link"
data-testid="help-footer-button"
data-testid="feedback-footer-button"


Gov Actions - details page:
data-testid="logo-button"
data-testid="dashboard-link"
data-testid="drep-directory-link"
data-testid="governance-actions-link"
data-testid="guides-link"
data-testid="faqs-link"
data-testid="disconnect-button"
data-testid="InfoOutlinedIcon"
data-testid="back-to-list-link"
data-testid="governance-action-details-card"
data-testid="governance-action-details-card-header"
data-testid="share-button"
data-testid="NoConfidence-type"
data-testid="submission-date"
data-testid="InfoOutlinedIcon"
data-testid="expiry-date"
data-testid="InfoOutlinedIcon"
data-testid="external-modal-button"
data-testid="d2f4bea73f954f5f9104d0aedeafc180336f63fcb19671646b9bbc0639fb906d#0-id"
data-testid="copy-button"
data-testid="yes-radio"
data-testid="no-radio"
data-testid="abstain-radio"
data-testid="show-votes-button"
data-testid="provide-context-button"
data-testid="vote-button"
data-testid="privacy-policy-footer-link"
data-testid="term-of-service-footer-link"
data-testid="help-footer-button"
data-testid="feedback-footer-button"

Retirement:

data-testid="Back-to-dashboard-link"
data-testid="ArrowBackIosIcon"
data-testid="back-button"
data-testid="continue-retirement-button"
data-testid="privacy-policy-footer-link"
data-testid="term-of-service-footer-link"
data-testid="help-footer-button"
data-testid="feedback-footer-button"

**Comment by SandraRodziewicz** [comment]
Most of the test Ids are there, the few missing are delegated to separate task to be fixed later https://github.com/IntersectMBO/govtool/issues/1038

Ready for staging

**Comment by NabinKawan** [comment]
**Reopening this ticket again**

Test-ids are not consistent. They are changing [link](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/20/#behaviors/f7eea6c55a554c79a959f2fe9524fccc/fcb8eca0f1c45314/)

Please adjust test-ids acc. to the test.

**Comment by pmbinapps** [comment]
OK Registration page ids are:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/a24a0951-6fa3-4d9b-a008-882b6cf955c4)



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/fd72425c-7976-437f-b368-f267b15903c9)

OK on Storage page Submit is as register-button



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/abab00dc-3433-44a2-afde-9c4accae519f)

OK Delegation page



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/8ffcce1a-3202-425b-89f0-560a3860561d)

**Comment by pmbinapps** [comment]
Regarding [comment](https://github.com/IntersectMBO/govtool/issues/937#issuecomment-2134739859), these current ids that set on DRep registration, update should enable automation:

 

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/255c217d-4c7d-4a66-805e-ca0c38fba026)

**Comment by kneerose** [comment]
I have listed the remaining missing test IDs on another [ticket](https://github.com/IntersectMBO/govtool/issues/1050). This can be closed now. CC: @bosko-m

**Comment by bosko-m** [comment]
Closing as per the comment above.
