### ISSUE TITLE
Create govtool metadata submission service

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#942]
# What
In order to integrate with the new services architecture extract metadata creation functionality into the separate package.

# How
Metadata creation service should work in both ways:
Provider:
```js
<MetadataProvider>{children}</MetadataProvider>
```
and usage with hooks
```js
const { validate, initialize } = useMetadata();
```
And service:
```js
const metadataService = new MetadataService(...config)
```

* Metadata service should follow [CIP-108](https://github.com/Ryun1/CIPs/tree/governance-metadata-actions/CIP-0108) standard.
* Metadata service should provide fields validation described in the above standard.
* Metadata service should build jsonld as an output.
* Metadata service should not use CSL in v1 hence, no on-chain data are to be applicable on first delivery.

**Comment by MSzalowski** [comment]
@pmbinapps Why is that being blocked?

**Comment by MSzalowski** [comment]
The issue has been blocked due to failed test-env deployment.

**Comment by pmbinapps** [comment]
Unable to verify Registration as Drep and Submitting new GA due to:

[DRep registration - Registration hang up after providing json file and confirming](https://github.com/IntersectMBO/govtool/issues/1011)

https://github.com/IntersectMBO/govtool/issues/1015

**Comment by pmbinapps** [comment]
Adding meta data:
OK for dRep
OK for Info GA

**Comment by MSzalowski** [comment]
That is to be moved to the https://github.com/IntersectMBO/govtool-assembly

This package is not testable at the moment.

**Comment by MSzalowski** [comment]
Migrate to govtool-assembly under [this PR](https://github.com/IntersectMBO/govtool-assembly/pull/4)

**Comment by MSzalowski** [comment]
Not required for the working govtool-assembly
