### ISSUE TITLE
Dashboard - Delegation card - after delegation to a DRep - drepid seems to be wrong as such drep is not findable in DRep explorer

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#945]
DRep card on Dashboard show drep id that does not exist in DRep explorer:

Dashboard - with for Delegation to drepid: drep1p58qr3cxcquyqare

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/062b671c-2aed-4c32-a71b-be2c3ca9abcf)

DRep explorer - drepid not found, and actual drep that is delegation is made is different:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/f87da416-67f2-41c8-a117-f2d98d93a0f3)

Compare with [jam](https://jam.dev/c/5b36a08b-c558-480b-b01f-baa47d3be37c) recording.

**Comment by MSzalowski** [comment]
We are using the same cards for the DReps and Delegation (which is just a DRep where the delegation is set to). Which means, that searched DRep is on the list (on the Delegation section).

@m-i-k-e Is that correct approach? Or should we duplicate that card and display that DRep in both the list below the search bar and on the delegation section if someone have active delegation on such DRep?
