### ISSUE TITLE
Test infrastructure and services setup

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/govtool#948]
A AWS service has been created under IntersectMBO's account. 

### Tasks
 - Update setup scripts and compose files for postgres, node and db-sync
 - Add build commands for required services including the commands to deploy.
    - govtool-frontend
    - govtool-backend
    - govaction-loader-frontend
    - govaction-loader-backend
    - metadata-api-server
 -  Configure CI/CD to automatically deploy to the environment when pushed to test branch.

**Comment by spannercode** [comment]
Deployment configured in following domains

Govtool Test Env : https://govtool.cardanoapi.io/
Lighthouse https://lighthouse-govtool.cardanoapi.io/
Metadata host service: https://metadata-govtool.cardanoapi.io/
Kuber server: https://kuber-govtool.cardanoapi.io/
Gov Action Loader : https://governance-govtool.cardanoapi.io/
