### ISSUE TITLE
GA - Proposal submitting - After 1st correction of metadata with 'Go to data Edit', continuation of submitting ends with blank screen

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#949]
To reproduce on test-sancho
1. Start adding new proposal
2. Fill all metadata
3. Proceed with wizard until view where the link to json file is to be provided.
4. Enter wrong path to file
5. When modal with options what to do appears choose 'Go to Edit Screen'

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/cc8c00c3-d061-4753-9836-9407fbc4447e)

6. Do not change anything - just proceed to modal with option to enter json file location again.
7. Provide wrong link again, and click Continue -  Blank screen appears 

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/c6b8e707-1b05-4c55-b415-b6c1e6927855)

Compare with [recording](https://jam.dev/c/5e95f327-324c-4d5a-8e8c-f55109d4000c)

**Comment by MSzalowski** [comment]
@pmbinapps Please revalidate that ticket as on my side it seems to be working now
