### ISSUE TITLE
Transactions - Retiring as Sole (Direct Voter) last long until page reload, finishes as expected but with error message

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#951]
To reproduce on test-sancho:
1. Be registered or - Register as Direct Voter
2. Retire - wait couple minutest if needed.
3. If status is not changing - Reload page
4. Wait until transaction finishes observe transaction update and card related to Direct (Sole voter) text change
5. Transaction is reported as invalid but result of Retirement is as desired

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/72629ffb-d300-4dcd-b710-f191f3c1dc9a)

Compare with jam [recording](https://jam.dev/c/ca26c589-20ec-431e-a9fe-b489b650fb22) 3:39s

**Comment by MSzalowski** [comment]
@pmbinapps Please revalidate that bug if it is still occurring after recent respins and wallet updates
