### ISSUE TITLE
Wrong DRep type returned after change from DRep to Direct Voter

### ISSUE THREAD

**Issue by JanJaroszczak** [IntersectMBO/govtool#957]
When a user, so far registered as DRep, registers as Direct Voter:

- `ada-holder/get-current-delegation/{stakekey}` returns:
![Image](https://github.com/IntersectMBO/govtool/assets/78307999/40c25346-d69b-4e64-b892-5d2672d07983)

- `drep/info/{drepId}` returns (`isRegisteredAsSoleVoter: true`):
![Image](https://github.com/IntersectMBO/govtool/assets/78307999/b903fb8f-9e9d-4613-9242-331cfbb9f03c)

- but `drep/list?page=0&pageSize=10&search={dRepView of myself}` still returns `type: "DRep"`:
![Image](https://github.com/IntersectMBO/govtool/assets/78307999/b188f687-8e0b-4563-a51d-ecef094cf366)

**Comment by pmbinapps** [comment]
OK when user is Retired as Direct Voter and Registered as DRep:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/c576c501-a825-413b-939a-720aa9863c03)

NOT OK when user Retired as DRep and Registred as Direct Voter - his DRep id is not retrived by /drep/list endpoing



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/7a7851fd-0fab-4e85-9e88-ad1cea17ce31)
