### ISSUE TITLE
DRep explorer - DRep list - DRep id and (Direct Voter) on who a delegation is already made is not found on in Find Drep

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#960]
To reproduce:

1. Delegate to a DRep 
2. Use his/her Drep id in Find DRep search - nothing is shown

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/da12bc39-83a7-4a5a-9271-5e6ded467407)

Jam [Recording](https://jam.dev/c/2e126d0b-9dc3-49f7-bd27-9818146c9f3c)

**Comment by pmbinapps** [comment]
The same occurs for Direct Voter - he/she should be fould but is not:

User story with requirement [here](https://github.com/IntersectMBO/govtool/issues/318#issuecomment-2083211094)

![image](https://github.com/IntersectMBO/govtool/assets/82152577/05a09069-fa78-43ec-9cd2-3ba28a50c359)

**Comment by MSzalowski** [comment]
@m-i-k-e that is because we display the DRep/Direct voter card on the delegation panel. Should we display that delegated card also on the list below the search box, or should we display the label "No results" or something else

**Comment by MSzalowski** [comment]
That issue is no longer existing. Could you please retest it @pmbinapps

**Comment by pmbinapps** [comment]
OK works as intended user not shown to on Drep list after registration as DRep
