### ISSUE TITLE
Extended User Stories

### ISSUE THREAD

**Issue by NabinKawan** [IntersectMBO/govtool#964]
**1. Wallet connect**
- [x] 1E. Should hide incompatible wallets when connecting.

**3. DRep registration**
- [x] 3K. Should display “In Progress” status on dashboard until the blockchain confirms Drep registration

**4. Proposal Visibility**
- [x] 4E. Should display DRep’s voting power on governance actions page
- [x] 4F.  Should Disable DRep functionality upon wallet disconnection on governance page
- [x] 4G. Should display correct vote counts on governance details page for DRep
- [x] 4H. Should verify none of the displayed governance actions have expired, been ratified, or enacted on the governance action page.
- [x] ~4I. Should count the most recent vote submitted by a DRep for the same transaction.~
- [x] 4J. Should include metadata anchor in the vote transaction.

**5. Proposal Functionality**
- [x] 5J. Should hide retirement option for non-registered DRep
- [x] 5K.  Should return deposit on DRep retirement

**Comment by NabinKawan** [comment]
These are extended user stories for [playwright-tests](https://github.com/IntersectMBO/govtool/issues/733#issue-2245089941)

**Comment by spannercode** [comment]
Part of the tests included in this ticket are blocked because of the delegation issue:
- https://github.com/IntersectMBO/govtool/issues/967

**Comment by spannercode** [comment]
The delegation bug is fixed so this issue is unblocked now.

**Comment by NabinKawan** [comment]
This has been completed. https://github.com/IntersectMBO/govtool/pull/1033
