### ISSUE TITLE
Integrate CSL with the wrapper

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#968]
# What 
Integrate CSL library into wrapper

# How
To make the already defined actions used across govtool pillars wrap up some commonly used CSL services into one Provider & Service (including eg.: cert builders, transaction builders and so on).

* Such service should be stateless to make it able to use on the server-side frameworks.

Logic might be reused from the current govtool implementation (having in mind that copy&paste is rather not intended as current solution requires refactor)

* Should be part of GovTool wrapper based on [this issue](https://github.com/IntersectMBO/govtool/issues/680).

* Wallet connection should be separate (as it is already done with the wallet-connector package)

**Comment by pmbinapps** [comment]
No negative impact on functionality was noticed.
