### ISSUE TITLE
Extend wallet connector package to include some minimal to connect the wallet UI

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#969]
# What
In order to select the wallet and handle the wallet connection errors - create minimal React UI components inside the `govtool-wallet-connector` package.

# How
Using the UI should be optional - meaning that `govtool-wallet-connector` should be working on its own without the need of using the implemented UI to perform the connection.

Components should follow the Intersect/Govtool design system.
Components should not include any hard-coded or predefined labels making them adjustable via prop by the components consumers.
Components should be stateless to make them able to use in th SSR solution.

**Comment by MSzalowski** [comment]
Moving issue to TODO after review

**Comment by MSzalowski** [comment]
Moved changes introduced with this issue to proper wrapper on govtool-assembly - link to Pull Request: https://github.com/IntersectMBO/govtool-assembly/pull/1

**Comment by MSzalowski** [comment]
@bosko-m It would be great to have someone from Proposal discussion pillar to review this pull request. Who in your opinion should it be assigned to?

**Comment by bosko-m** [comment]
@MSzalowski Os this still relevant considering the discussion about the wrapper yesterday? CC @teske00 @vpaunovic
