### ISSUE TITLE
[USERSNAP] teste

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#980]
**Sender**: pawel.mergist@binarapps.com
**Taken at**: https://test-sanchonet.govtool.byron.network/dashboard
**Fields**:
- Add a comment: teste

**Browser**: Chrome 123 (Android 6.0)
**Screen size**: 1846x708
**[Open #46 in Usersnap](https://app.usersnap.com/l/feedback/fec688e7-d44d-47e6-a5e6-8efba683b016?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by m-i-k-e** [comment]
@kickloop I can see no information on this bug. When I open it in usersnap, nothing.
