### ISSUE TITLE
"My Drep" detail page with delegation details needed

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#987]
## Context & versions
Voltaire GovTool

## What's the issue?
There needs to be some indication on the DRep detail page that the connected user has delegated ADA and how much to them

## How to fix:
Make a branch and alter this page: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=7747%3A58655&t=7rsYaYcuCkBafa4l-1

It needs to indicate how much the user has delegated to the DRep on the detail page as it does on the listing page.

Listing page: 
<img width="702" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/127c9bda-12a8-441e-9e2c-86ef8f85d5f9">

**Comment by kgrzonka** [comment]
@m-i-k-e 

I've just wondering about place for this information. In first version its similar to the Listing page (its god cause user know that from other screens but we have a lot of space in Badge with "This is your DRep profile" so maybe we should put this copy there (version below) ? One minus ot this solution is mobile version but then we can designed larger badge and the informations will be highlighted.
https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/branch/ZH880OE06GBfLR3Vbyt1jn/Voltaire---GOV-TOOL?type=design&node-id=13156%3A89243&mode=design&t=EutxeybQvrMH9aR0-1

**Comment by m-i-k-e** [comment]
The bottom one looks good.

<img width="959" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/a109193e-1729-441a-9281-3c2582e19b78">

**Comment by m-i-k-e** [comment]
Need to merge this in Figma and assign to Byron @mike

**Comment by m-i-k-e** [comment]
New design here: 

https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=13156%3A89243&t=x09dBYj7HyHzBIBz-1

**Comment by m-i-k-e** [comment]
Marked as Ready for Dev

**Comment by m-i-k-e** [comment]
@MSzalowski This is done in Figma and 'ready to dev'

**Comment by m-i-k-e** [comment]
https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=13156%3A89243&t=2SZ66T2eZnuLZyWR-1

**Comment by pmbinapps** [comment]
OK NOW:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/e6d3ecc3-1579-4529-b8db-64e3765ad9f8)

**Comment by m-i-k-e** [comment]
Closing as this is done
