### ISSUE TITLE
DRep Explorer

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#99]
# Development Phase
**Deliver by 30th March, 2024**

# Supporting documents
* https://github.com/cardano-foundation/CIPs/tree/master/CIP-0095/README.md
* https://github.com/cardano-foundation/CIPs/blob/master/CIP-1694/README.md

# Overview
_What is the DRep Explorer_
The DRep Explorer is a feature within GovTool that allows an Ada Holder to find the DRep that they wish to delegate to and then delegate to them (delegation is already a feature of GovTool).

_Who is the DRep Explorer for?_
The DRep Explorer is for:
1. DReps who wish to promote themselves to Ada Holders (so that they can increase their voting power)
2. Ada Holders who wish to read the profile of a specific DRep
3. Ada Holders who wish to search for DReps based on the searchable characteristics of the DRep

# Designs
⚠️ - waiting for confirmation if ready for development
* [Become DRep](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7079-46858&mode=design&t=XuWdBL3VixCwdtb6-0)
* [DRep Explorer](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7079-29609&mode=design&t=XuWdBL3VixCwdtb6-0)

**Comment by Ryun1** [comment]
very old, lets close
