### ISSUE TITLE
DRep Explorer covered user stories

### ISSUE THREAD

**Issue by spannercode** [IntersectMBO/govtool#999]
To cover the acceptance criteria for DRep explorer user stories.

The following is the list of user stories extended to cover DRep Explorer:
- [x] 2J . Should search by DRepId
- [x] 2K Should filter DReps
- [x] 2L.   Should allow users to copy dRepId.
- [x] 2M. Should sort DReps
- [x] 2N. Should show dRep information in details page
- [x] 20 Should load more DReps on show more
- [x] 2P Should enable sharing of dRep details.
- [x] 2Q Should include dRep status and voting power on the dRep info card.
- [x] 2R Should display a modal indicating waiting for a previous transaction when delegating if the previous transaction is not complete.
- [x] 2S Should retire you as a direct voter if you delegate to another dRep
- [x] 2T. Should show warning message on delegation when funds are insufficient.
- [x] 2U. Should delegate only own voting power to Abstain as registered DRep already has delegated voting power
- [x] 2V. Should delegate only own voting power to 'No Confidence' as registered DRep already has delegated voting power
- [x] 2W. Should display voting power of DRep

**Comment by NabinKawan** [comment]
This is completed [PR](https://github.com/IntersectMBO/govtool/pull/1068).
